### ISSUE TITLE
MM Finance Polygon

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1007]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/mm-finance-polygon&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.2  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1hO31pPj8qBlfO4R9Wt8-xR5RbOX-VqbC/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Daily Volume

Daily volume data shows a high discrepancy of around 20% with official website data in the past five days.

| Subgraph | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 13,881,951.44| 17,520,000.00 | -3,638,049| -20.77%|

### Total Pool Count

Dexscreener and the official website only show 34 and 20 pools respectively as compared to subgraph's 142 pools.

### Pool Overview TVL  & Rewards

- 11 out of 15 pools' TVL are in line with official website data and the four other pools that have large discrepancies. 

|12th pool - DSF, MMF |Official Website| % Difference |
| :---- | :--- | :---  | 
| 506,442 | 1,000,000 | -49.36% |

|13th pool - MMF, MMO |Official Website| % Difference |
| :---- | :--- | :---  |
| 354,739 | 728,850 | -51.33% |

|14th pool - stMATIC, LDO |Official Website| % Difference |
| :---- | :--- | :---  | 
| 292,604 | 594,630 | -50.79% |

|15th pool - MMF, SOLAR |Official Website| % Difference |
| :---- | :--- | :---  | 
| 123,284 | 266,750 | -53.78% |

- Four pools are displaying zero numbers for its base yield data. 

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| MLP/MMF Pair Base Yield| 0% | 22.11%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| DSF/MMF Pair Base Yield| 0% | 47.09%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| MMF/MMO Pair Base Yield| 0% | 11.60%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| MMF/SOLAR Pair Base Yield| 0% | 153.25%|

- The percentages under 'REWARD TOKENS' column should not be zero as liquidity providers are actively incentivized with rewards in the form of MMF tokens

- See 'Pool_Overview' sheet for details

Please refer to the attached worksheet for more details.

**Comment by ishraq8** [comment]
Again i suspect there is something wrong with MMF pricing. it seems MMF pools are showing half TVL of what it should be. 

Similar to: https://github.com/messari/subgraphs/issues/997#issuecomment-1249957287

**Comment by ishraq8** [comment]
Pricing resolved here @steegecs this can be depoloyed.
