### ISSUE TITLE
Notional V2 Mainnet QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1038]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=fortysevenlabs/notional-ethereum&tab=protocol
| Schema Version  |  2.0.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1JBeUtwnVzlv7zFk1QVMr_q4noyTm076m/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

## General Note
We understand this version of the subgraph separates the Notional Finance protocol into lending and DEX; and this subgraph tracks the lending data according to the Messari lending schema. In the public info, most sources do not differentiate lending and DEX for Notional, thus making the protocol's information not comparable to any other lending protocol. Having said this, it would also mean that the data from this subgraph would differ from info of Notional in the public domain, as they are defined differently (lending only vs. lending + DEX). In the course of our review, we have applied sanity checking to a large extent. More accurate verification of the subgraph data is possible, when the DEX part of the Notional subgraph is ready.

###  Supply Side and Protocol Side Revenue

For the lending of Notional, protocol side revenue data should be  zero. The protocol do not receive any share from interest fees paid to lenders, but only charges a fee when users trade in their DEX. When a borrower makes a borrowing action with Notional, he incurs two fees: the implied interests and the transaction fee. Implied interest goes to the lending business of Notional and 100% to the supply-side. Transaction fee goes to the DEX business. 

### Revenue and volume in general

There's no public source for lending only revenue of Notional. We have done the below checks:

1. The cumulative borrowing balance of 6m USDC pool seems to be smaller than the official website data. 
2. For the 6m USDC pool, the implied yield (subgraph total revenue / subgraph cumulative borrow / average duration of 3m, annualised) is 3.2%. This is in line with the current yield of 3.5% or the last month average of 3% borrowing rate. 

Therefore, the revenue calculation is likely to be correct but some borrowing actions might not be fully tracked.

### Pool Overview TVL  & Rewards
We note that the pool overview TVLs of each pool do not add up to the total TVL.

### Others
There are some differences we have noticed and are not necessarily data errors.

#### Total Value Locked (TVL)
TVL data is lower and shows a discrepancy around 16% to 27% with Defi Llama and official website data. This might be due to the reason that Defi Llama and the official website also track the liquidity of DEX business side of the protocol. This can be checked again when the dex subgraph of Notional is ready.

#### Events
- Eight of the 10 deposit transactions are verifiable in the official website and Etherscan. The other two have questionable data. See the screenshots above. Refer to the screenshots in the 'Events' sheet.
- Nine out of 10 borrow transactions can be confirmed in the official website and Etherscan. The other one transaction may not be a borrow transaction. Refer to the screenshots in the 'Events' sheet.
- Some of the transactions in the official website are missing in the subgraph. Refer to the screenshots in the 'Events' sheet.
- See 'Events' sheet for details

**Comment by fortysevenlabs** [comment]
Shared my response for each of these with @SerenityFund over discord. Will post a summary of final findings here after the discussion is complete.

**Comment by ishraq8** [comment]
@fortysevenlabs Was there a new version of this that corrected the errors? I am happy to QA the endpoints and we can close notional V2

**Comment by ishraq8** [comment]
Current PR: https://github.com/messari/subgraphs/pull/941

**Comment by fortysevenlabs** [comment]
Posting summary from some of the discussions previously with @SerenityFund / @ishraq8 .

> Pool Overview TVL & Rewards
> We note that the pool overview TVLs of each pool do not add up to the total TVL.

Tarun - The total TVL is being calculated by checking erc20 balance of cTokens. This would mean the proxy contract would include cTokens deposited as part of lend trades plus the cTokens deposited to the liquidity pools. On the other hand, the pool TVLs would only include cTokens currently deposited in the market.

Kane -  ok in line with my understanding as well. i will note in the methodology that the protocol level TVL is sum of pool tvl + collaterals.

**Comment by fortysevenlabs** [comment]
> Total Value Locked (TVL)
> TVL data is lower and shows a discrepancy around 16% to 27% with Defi Llama and official website data. This might be due to the reason that Defi Llama and the official website also track the liquidity of DEX business side of the protocol. This can be checked again when the dex subgraph of Notional is ready.

The price returned for cWBTC is 0 per messari’s price lib and hence TVL is off by 15-20%. This along with not having DEX related info is the cause for TVL mismatch between subgraph and token terminal.

I'm exploring an alternative for obtaining cWBTC price (use notional function to go from cWBTC -> WBTC and then use messari price lib to go from WBTC to USD).

**Comment by fortysevenlabs** [comment]
> Events - Deposits
> Eight of the 10 deposit transactions are verifiable in the official website and Etherscan. The other two have questionable data. See the screenshots above. Refer to the screenshots in the 'Events' sheet.
* This 0xb8bd07602075084756e0224311d01de68ab5981c19953ace2c17389d5108429f does seem to be a deposit (lend). See https://info.notional.finance/accounts/details?accountId=0xb538cd918e66bc89f2cce1b8b1569fb9ce88fb6e
* This 0x0591d85e03795f5c758a56e54693bbb28c834056420847f6db4a51c17f1ab1eb does seem to be a deposit (lend). See https://info.notional.finance/accounts/details?accountId=0x871061661c9afe93307d956cbb6250813cdfecf9

> Events - Borrows
> Nine out of 10 borrow transactions can be confirmed in the official website and Etherscan. The other one transaction may not be a borrow transaction. Refer to the screenshots in the 'Events' sheet.
* This 0x75633850b6acdefa82e05ac90f750b3c31094d22141c81bd8e86b651c97aa468 does seem to be a borrow. See https://info.notional.finance/accounts/details?accountId=0x6aa6316c1a1d78a14899f45d39a45c5fd92be9a3

**Comment by fortysevenlabs** [comment]
> Events - Missing Transactions
> Some of the transactions in the official website are missing in the subgraph. Refer to the screenshots in the 'Events' sheet.
These transactions do seem to be missing. INVESTIGATING.

**Comment by fortysevenlabs** [comment]
Pending Items
- [ ] Supply / Protocol Revenue: For the lending of Notional, protocol-side revenue data should be zero.
- [ ] Revenue and volume in general: Some borrowing actions missing in 6M USDC Pool
- [ ] Events: Missing transactions in events sheet

**Comment by fortysevenlabs** [comment]
> Supply / Protocol Revenue: For the lending of Notional, protocol-side revenue data should be zero.
Updated procotol side revenue to 0 in https://github.com/messari/subgraphs/pull/941/commits/e9e6be76b91f3eaf5c446d60ec3057f6d4b4f879

**Comment by fortysevenlabs** [comment]
> Revenue and volume in general: Some borrowing actions missing in 6M USDC Pool
This could have been a result of the missing transactions mentioned as a separate item. The missing transactions are now resolved.
