### ISSUE TITLE
Schema 1.2.0. Issue with usage metrics derivation in Protocol interface

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#105]
In the protocol interface, `usageMetrics` should be `dailyUsageMetrics`. Otherwise the DexAmmProtocol will not fit the interface.
<img width="658" alt="Screen Shot 2022-04-23 at 1 56 19 AM" src="https://user-images.githubusercontent.com/56660047/164881283-93461158-1846-4f32-a4b3-1c705987e880.png">

**Comment by this-username-is-taken** [comment]
Fixed here https://github.com/messari/subgraphs/pull/106
