### ISSUE TITLE
subgraphs.xyz improvements

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1050]
- Merge hosted service and decentralized network
- Use `deployment.json` in Github as data source
- Show curation signal for subgraphs in decentralized network

**Comment by bye43** [comment]
@this-username-is-taken going to leave this open for visibility on what @MichaelC1999 and I are working on, but might become a long thread, so will explore other options.

Subgraph Dashboard
1. Make aave naming the same on deployment status table as on deployed subgraphs tab
2.  Change coloring
    * Green = 100% indexed
    * Orange = <100% indexed
    * Red = Error / Not indexing 
3. Old schema are in orange font
    *  Would be nice to have hover with message “Not the current schema version
4. Change Decentralized symbol to white or purple (for the graph?)
    *  I think so people who do not hover do not get the impression it is better
5. I like the idea of color coding deployments in the collapsed view
    * The polygon symbol would be outlined in orange 
    * The rest in green
6. Pull curation signal for decentralized protocols and notify when there is no curation for the subgraph 
    * Maybe something similar to the decentralized symbol (a red circle with an exclamation point)
    * When you hover the message is “No curation for subgraph”
    
Subgraph Bot
1. Make indexing error rows closer together 
2. Add okgraph hyperlink to the names of the protocols for indexing errors
