### ISSUE TITLE
How do we build these subgraphs?

### ISSUE THREAD

**Issue by paymog** [messari/subgraphs#1052]
I've looked through the docs and haven't been able to find clear documentation on how to build the subgraphs in this repository. I've tried running `npm run build --id=uniswap-v2-ethereum` from [`deployments/package.json`](https://github.com/messari/subgraphs/blob/master/deployment/package.json#L8) but got the following error

```
Error: Cannot find module '/Users/paymahn/code/goldsky/deployment/deployment.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

which suggests to me that the script is incorrectly configured (it's searching too high up the folder higherarchy). Is this the script that should be used for building subgraphs? If not, how should I generate builds of the various subgraphs in this repository?

**Comment by paymog** [comment]
Here's what I found:

```
$ cd subgraphs/aave-governance
$ yarn
$ npm_config_protocol=aave-governance npm_config_id=aave-governance-ethereum npm_config_template=aave-governance.template.yaml yarn prepare:yaml
$ npx graph codegen
$ npx graph build
```

this will generate a `build` directory which can then be deployed to a hosting service.

**Comment by dmelotik** [comment]
hi @paymog maybe we need to be more explicit on where to call these commands. For the purpose of what you are doing, you would make these calls from https://github.com/messari/subgraphs/tree/master/subgraphs/aave-governance

**Comment by steegecs** [comment]
Hey @paymog! Sorry this is not very clear in the documentation, I'll improve the documentation. 

Where are you running this command from?

**Comment by paymog** [comment]
I ran that command from the aave-governance subgraph directory

**Comment by this-username-is-taken** [comment]
hey @paymog, just checking, do you still need help on this?

**Comment by paymog** [comment]
Hey! Nope, I figured out how the build and deploy system works. We can close this out!
