### ISSUE TITLE
Fix Uniswap v3 pool TVL

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1071]
See https://twitter.com/DefiIgnas/status/1572126274340163584

**Comment by steegecs** [comment]
Indexing here: https://thegraph.com/hosted-service/subgraph/steegecs/uniswap-v3-ethereum-test1?version=pending

Added a new collect Entity and update usage metrics to include a count for Collect in addition to fixes on TVL by accounting for swap fee collections. See PR here: #1092

**Comment by steegecs** [comment]
Subgraph indexing and in process of QA - ran into some pricing issue, but I found a potential cause.

**Comment by steegecs** [comment]
https://github.com/messari/subgraphs/pull/1255

Needed another fix. Subgraphs are now indexing again.

**Comment by bye43** [comment]
@steegecs I check both ARB and ETH deployments and they look good. I am assuming MATIC and OP will be as well, but will close the issue after I give them a quick scan
