### ISSUE TITLE
Create CLI deployment tool

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1080]
This tool will make it easier and more efficient for us to deploy a subgraph from the command line.

This should be lightweight and composable on any subgraph in our repo to deploy to any service (hosted service, decentralized network, studio, and cronos portal).

The cli tool flow I have in mind is as follows:
1) user types in the protocol they want to deploy
2) The networks available come up and you can select any combination of them
3) you say what service you want to deploy to and where that lives (ie, messari's or your own)
4) Optional: you enter an access token if necessary
5) you confirm you are deploying the subgraphs you want
6) The cli tool then utilizes our deployment commands to deploy the correct subraphs

Question(s):
- Where does this live? Does it get it's own directory, or should it live in `./deployment`?

**Comment by this-username-is-taken** [comment]
Doesn't our current deployment script already do this?

**Comment by dmelotik** [comment]
What I am describing here would basically make it easier to run the commands that trigger deployments. For example instead of copy/pasting and changing the inputs you would just type compound and it would bring up the deployments and you just select them.

Def low priority, but thought it would make deployments more efficient from the cli.

**Comment by this-username-is-taken** [comment]
oh right, i remember you mentioned this. Yes, that'll be very helpful!

**Comment by steegecs** [comment]
CLI tool is ready for review here! 
https://github.com/messari/subgraphs/pull/1124
