### ISSUE TITLE
Aave Forks underscore added fields in schema

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1084]
Additional fields in the schema should be marked with an underscore. This keeps is consistent across the entire project. Do this after #976 is merged

**Comment by dmelotik** [comment]
#1220

**Comment by bye43** [comment]
Have to redeploy all AAVE deployments / forks for this

**Comment by dmelotik** [comment]
Closing, as described here: https://github.com/messari/subgraphs/pull/1220#issuecomment-1409419206
