### ISSUE TITLE
Work through Beefy Finance issues and QA results

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1085]
Beefy Finance has been punted quite a bit, and we have some tangible things to fix from the QA #561 

I have gone through beefy and marked things to fix and what can be done about them: https://www.notion.so/messari/Beefy-Finance-Refactor-QA-fix-d7c77f7fb1b24480ab04f938e2bc8d32

*Note, I am still unsure if we will be able to get price 100% of the time, but we will try our best

**Comment by dmelotik** [comment]
Avalanche 1.2.1: https://okgraph.xyz/?q=dmelotik%2Fbeefy-finance-avalanche

Arbitrum 1.2.1:  https://okgraph.xyz/?q=dmelotik%2Fbeefy-finance-arbitrum

**Comment by ishraq8** [comment]
Thanks @dmelotik ill take a look at the ones you deployed.

**Comment by dmelotik** [comment]
Note: use this https://thegraph.com/docs/en/developing/creating-a-subgraph/#transaction-receipts-in-event-handlers to try and accurately get revenue!

**Comment by ishraq8** [comment]
Current status:
Fantom- data matches but 86% synced
Arbitrum is ok should be good for front end.
Polygon- syncing still 24%
BSC- shows zero across the board
Optimism not synced
The following fails: Avalanche, cronos, moonbeam, moonriver, fuse, aurora, harmony, celo

Strategy:
1) Use TVL across the board for protocol metrics. Mention in docs that Beefy has a large number of bespoke vaults, making it difficult to create accurate subgraphs. Leave subgraphs that are in development as is for potential future reference.
2) Use Arbitrum and Fantom in protocol metrics. Update other subgraphs to the current version (there is a version control issue). Return to remaining subgraphs in a month to see how accurate they are. The ones that are accurate can be displayed on protocol metrics. Document in docs about the limitations.


I have some ideas for our longer discussion on how not to repeat similar issues on bespoke protocols. I will work on the docs and we can decide which strategy to use.

**Comment by dmelotik** [comment]
@ishraq8 it sounds like rn we can only show Arbitrum? Because we don't have a way to pick and choose metrics to surface on PM atm

These were my thoughts on 2:

There are 2 ways (not exclusive) where protocols are difficult to build subgraphs for:

1. The protocol does not fit into one of our schemas very well OR a schema is not properly defined to the best of our ability. This makes the data difficult to define on the buildor-side. Can be remedied by making a new schema that makes more sense (if there is sufficient need. ie LSDs)
 
2. The data becomes increasingly difficult to properly attain making the effort the effort high, and the data may still not be 100% accurate. This can happen for multiple reasons to different degrees (ie, NEAR has limitations without contract calls, beefy contracts were improved poorly, protocol has poor documentation, contracts are not verified or public, developers are difficult to work with, etc.). This is where it makes sense to do an honest cost-benefit analysis.

**Comment by dmelotik** [comment]
Thanks for looking into this @ishraq8
