### ISSUE TITLE
Using `rewards.ts` to dynamically get blocks/day on arbitrum does not work

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1087]
Trying to dynamically get blocks/day on arbitrum does not work due to the way block numbers are returned from the arbitrum one RPC: https://github.com/OffchainLabs/arbitrum/blob/master/docs/Time_in_Arbitrum.md

In order to find a working solution we could just hard code the block interval for arbitrum. Although, in the past it has been variable based on (https://arbiscan.io/chart/blocktime). The other option is to see if we can still figure out a way to get this dynamically using what we found above. 

Outcomes:
- However we choose to address this, all arbitrum subgraphs that used dynamic blocks/day calculation will need to be switched

**Comment by tnkrxyz** [comment]
This affects dforce-arbitrum (to be fixed in PR #1049) and cream-finance-arbitrum (no fix yet).

**Comment by dmelotik** [comment]
Looks like #1049 fixes some of them. It won't fix cream finance arbitrum, since it uses `rewards.ts` to get blocks/year. I reckon we should look across all of messari/subgraphs to fix any of this. I think rari fuse arb is another affected one.

**Comment by tnkrxyz** [comment]
cream finance can be fixed in a similar way - by setting ARBITRUM_BLOCKS_PER_YEAR = ETHEREUM_BLOCKS_PER_YEAR in compound-forks/src/constants.ts. The fix in #1049 only fixed it for dforce because the change was made in compound-forks/protocols/dforce/src/constants.ts . Not sure about rari etc

**Comment by dmelotik** [comment]
We still need to go through and ensure all the compound forks deployed to arbitrum are not affected. ie, I know rari fuse arbitrum needs to get off using reward.ts

**Comment by steegecs** [comment]
Hows this coming along? Did you find a fix? Do you need help?

**Comment by tnkrxyz** [comment]
@dmelotik , lmk if I can help with this.

**Comment by dmelotik** [comment]
I think I will get it done rq this week since I know exactly what needs to happen. I will assign you to review @tnkrxyz, thanks
