### ISSUE TITLE
Subgraph Development Standard Library

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#1096]
Many of the functions we use in subgraph development are common, however, they are not necessarily a standard. We have often come up with our own variations to suit the needs of our subgraphs. This has led to us calling many function that are similar in some ways but different in others and have different names. Because many of the functions we use to index subgraphs are unique to a particular subgraph, we are more prone to bugs, it is harder to read across subgraphs, and time consuming to write new functions rather than having common functions in a standard library. 

I think it would be a good idea to consider building out a standard library for subgraph development soon to increase consistency, reduce our susceptibility to data quality issues, and improve the speed of subgraph development. The idea would be to make common functions for generating and updating entities from the store, as well as common utility functions. Ideally, all updating of entities could be done with our common functions. This would ensure as long as we can generate the correct inputs for passing to functions in our standard library, we have stronger assurance the the data is being generated and transformed as we would like.

**Comment by this-username-is-taken** [comment]
tracking here: https://github.com/messari/subgraphs/issues/1386
