### ISSUE TITLE
Subgraph logging infra

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1098]
### Problem

1. The Graph’s official subgraph logging is broken. It only saves logs for the past hour (and indeterministically), which makes debugging subgraphs incredibly difficult. I’ve escalated this issue to them a couple times but it’s not being prioritized.
2. The Graph doesn’t provide an easy way for people to find out the indexing speed of a subgraph, which makes it difficult to estimate its indexing time. This is important for large subgraphs that take potentially weeks or months to index.

### Solution

1. Since there is a public API that allows anyone to query log data (for the past hour or so), we can scrape them on a regular basis, save them on our infra, and allow people to query ANY historical log, search/sort/filter them easily. This will make debugging SIGNIFICANTLY easier.
2. Similar to the logs, we can also scrape the indexing status of subgraphs on a regular basis, thus getting a historical record of how fast the subgraphs have been indexing, and can provide estimates on when it’ll fully indexed.

### Query Endpoint

[https://api.thegraph.com/explorer/graphql](https://api.thegraph.com/explorer/graphql)

**Comment by steegecs** [comment]
Can we count this as closed?
