### ISSUE TITLE
Build The Graph subgraph

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1100]
https://github.com/messari/subgraphs/pull/845

**Comment by this-username-is-taken** [comment]
@ishraq8 this is ready to QA. It's pretty different from the regular defi protocols, so I think maybe easier if you work with @steegecs to get it QAed

**Comment by ishraq8** [comment]
Sounds good. @steegecs talked to me about it before.

**Comment by ishraq8** [comment]
Subgraph looks good!

QA: https://docs.google.com/spreadsheets/d/1lO5IIvrmpMiC3BQIqmasCjbTAYi3YKI2/edit#gid=1958176400

comments:
1. @steegecs Just want to double check that you are considering these metrics for revenue (under indexing rewards) 
<img width="1305" alt="Screen Shot 2022-10-06 at 12 03 49 PM" src="https://user-images.githubusercontent.com/47088402/194377579-ba42a0d0-000f-483c-ba79-f2b2d78232b4.png">

2. There are no pool data. would it be worthwhile creating a curating and indexing pool? not a big deal if it is a lot of work.

Other than that looks great.

**Comment by steegecs** [comment]
1. Yes these are all being considered! I'm pretty sure the `Allocated Stake` is just `Indexers Stake + Delegators Stake`, right? 
2. @this-username-is-taken and I discussed this when planning out this subgraph. We decided not to track these pools, but we can consider it in a further iteration of this subgraph.

**Comment by ishraq8** [comment]
Thanks @steegecs, good to know the pools were discussed. the subgraph is accurately reporting the data, so this subgraph is good to go.

**Comment by steegecs** [comment]
Boom! Sweet. Thanks for reviewing this!
