### ISSUE TITLE
Compound Forks Total Borrow Accuracy

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1111]
We can improve the accuracy and reliability of `market.totalBorrowBalanceUSD` through using other events to get this data.

In compound forks the `AccrueInterest` event is emitted and ingested before an event for `RepayBorrow` or `Borrow`. This doesn't accurately represent the actual borrow amount afterwards, since we only update borrows on accrue interest, but it can change after.

The transaction events also include the new `totalBorrows`, so we can utilize that to get more accurate data!

**Comment by tnkrxyz** [comment]
closed with #1136 merged
