### ISSUE TITLE
Euler missing revenue for a couple days around end of Aug 2022

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1115]
![image](https://user-images.githubusercontent.com/2354636/193165883-9558b0d2-615e-4ce8-9946-c1eb8b7d8178.png)

**Comment by tnkrxyz** [comment]
Still looking, as this unlikely the direct cause of missing revenues for 8/18-20, but the [methodology](https://github.com/messari/subgraphs/tree/master/subgraphs/euler-finance#cumulative-protocol-side-revenue-usd) for computing protocolSideRevenue seems wrong to me: `Cumulative protocol-side revenue = Cumulative protocol-side revenue + Market Deposits Balance * ((Market Supply APY / (1 - Market Reserve Fee)) - Market Supply APY)`. From euler's code, the reserve fee applies to total borrow, not total deposit: https://github.com/euler-xyz/euler-contracts/blob/dfe600640e5e7a2eae1c26b768bbc1141bb4c9b9/contracts/BaseLogic.sol#L220 . 

The method seems to be based on the assumption that `supply APY=borrow APY * (1 - reserve ratio)`. From what I see, there is no such relationship between supply APY, borrow APY, and reserve fee. For example, as of 10/1 for the wstETH pool, the supply APY = 0.75%, borrow APY = 2.86%, while reserve fee ratio = 0.10 (400000000 on a scale of 4000000000). https://app.euler.finance/

**Comment by ishraq8** [comment]
@tnkrxyz this is a good catch. Let me double check to see what is probably best for Euler.

I am also looking into the total revenue disruption.

**Comment by tnkrxyz** [comment]
It is strange that I now get correct (? at least non-zero) totalRevenue for 8/18-20 without changing the code (I added logs, but haven't change any functional lines). Still puzzled what is going on.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/97625120/193475087-7ed0c991-2a1e-4a50-994f-f81eb5e343b6.png">

**Comment by ishraq8** [comment]
@tnkrxyz do you have link to your redeployment? Ill do another round of QA

I looked into the protocol side revenue issue. So what that is calculating is the reserve factor, set at 23% of what borrowers pay back, so you are correct.

I am thinking:  `Market Borrow Balance * (Market Borrow APY *Market Reserve Fee)`
But this assumes the reserve fee is part of the protocol revenue. Let me know what you think before we make changes to code and docs.

https://docs.euler.finance/euler-protocol/eulers-default-parameters#reserve-factor

**Comment by tnkrxyz** [comment]
I deployed to my own account: https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler?selected=logs

The default reserveFee is 23%, but it can varies by market/pool, for example it is 10% for wstETH.

According to their document, reserveFee is certainly the protocol side revenue (https://docs.euler.finance/developers/getting-started/architecture#reserves), similar to other lending protocols such as aave and compound. What is not clear to me at this point is whether the difference between borrowAPY and lendingAPY after reserveFee is protocolSide revenue too.

If I am not mistaken, the wstETH reserveFee ratio is 10%, the current borrowAPY is 2.85% and lendingAPY is 0.75%, so even after reserve fee, there is still 0.0285 * (1 - 0.10) - 0.0075 = 1.815% that is not accounted for. Even at 23%, there is a difference of 1.44% unaccounted.

**Comment by tnkrxyz** [comment]
The issues had been fixed in the code in the master branch: https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.studio.thegraph.com%2Fquery%2F29379%2Feuler%2Fv0.1.0&tab=protocol&view=financialsDailySnapshots-dailyProtocolSideRevenueUSD (deployed using the euler code in the master branch)

Re-deploying subgraph should fix the missing revenue in the official subgraph.

**Comment by this-username-is-taken** [comment]
Great!

**Comment by tnkrxyz** [comment]
> According to their document, reserveFee is certainly the protocol side revenue (https://docs.euler.finance/developers/getting-started/architecture#reserves), similar to other lending protocols such as aave and compound. What is not clear to me at this point is whether the difference between borrowAPY and lendingAPY after reserveFee is protocolSide revenue too.

> If I am not mistaken, the wstETH reserveFee ratio is 10%, the borrowAPY is 2.85% and lendingAPY is 0.75% as of 10/1 (https://app.euler.finance/), so even after reserve fee, there is still 0.0285 * (1 - 0.10) - 0.0075 = 1.815% that is not accounted for. Even at 23%, there is a difference of 1.44% unaccounted.

Realized I am not comparing apple-to-apple here: at any time, the collateral asset amount > borrow amount. If taking into account the difference, they should be equal: borrow amount * borrow APY * (1 - reserve fee ratio) = collateral asset * lending APY.

@ishraq8 let me know if this makes sense and/or consistent with your reading. thx!

**Comment by tnkrxyz** [comment]
This issue is fixed after redeploying. Copied possible (minor) improvement to simplifying protocol side revenue calculation to #1139

**Comment by ishraq8** [comment]
Thanks @tnkrxyz, and yes, the methodology is a bit more complex than needed. thanks for catching that!
