### ISSUE TITLE
add tvl ranking from defillama to subgraphs.xyz

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1130]
A new feature request for Subgraphs.xyz: We have a new page with a list of the highest tvl protocols that we have not currently started development on.

Why do this?
- It is a manual process to prioritize new subgraphs to make based on TVL.
- New protocols may come onto the scene and we will spot them quicker with an automated tool

As an additional, it would also be nice to see the TVL (from Defillama) ranked on subgraphs that are not prod ready. This way we can aide in prioritizing subgraph dev.

**Comment by bye43** [comment]
Closing this since we added it! Thanks @MichaelC1999! Sorting by protocol is in the works too
