### ISSUE TITLE
dForce QA all chains

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1138]
I'll do a QA on all chains that have a dForce subgraph and pass on to @dmelotik & @tnkrxyz when complete. 

Use this issue for QA reports, updates and  discussion/improvements to the subgraph. 

Ethereum-https://docs.google.com/spreadsheets/d/1kh2aQDSmtjDc4j3KnepaBI0-C9WDMSnK/edit#gid=507208116
BSC- https://docs.google.com/spreadsheets/d/1x0FQe7KVtL1New0-OcDturalpw42x6kM/edit#gid=844206217
Arbitrum-https://docs.google.com/spreadsheets/d/1aasjJpHoomR1GmO0PV45q1ByY2isophn/edit#gid=1294817563
Avalanche- Subgraph not supported.
Optimism-https://docs.google.com/spreadsheets/d/1XE9zZMf_vyIHH35NAY7JDEdnjUFji4ay/edit#gid=1294817563
Polygon-https://docs.google.com/spreadsheets/d/1ni2OuVB8kqMSX_6oeg8MLzM1F9V4r5_N/edit#gid=1294817563

**Comment by this-username-is-taken** [comment]
Here are some related threads:
https://github.com/messari/subgraphs/issues/1106
https://github.com/messari/subgraphs/issues/868

Note that dForce is pretty difficult as most sources have issues. Would good to sync up with @tnkrxyz on this.

**Comment by ishraq8** [comment]
I am working on the QA for all chains, but did want to raise the issue of the CDP/synth market they have. I personally think it may need it's own subgraph as this component functions more like Synthetix (not entirely) than a traditional CDP (maker). The purpose of dForce's CDP (USX & EUX) seems primarily in their synthetics market and not as a stablecoin (dai, LUSD ect).  Feel free to share thoughts. I don't think we have a subgraph for synthetix. 

<img width="1126" alt="Screen Shot 2022-10-05 at 10 55 08 PM" src="https://user-images.githubusercontent.com/47088402/194203852-aafc4631-64f3-416b-bf3b-742d475af270.png">

**Comment by this-username-is-taken** [comment]
Gotcha, @nemani is working on a subgraph for Synthetix. Should probably discuss how to handle synthetic tokens in the general case then. Maybe we can bring this to Discord?

**Comment by ishraq8** [comment]
@tnkrxyz Finally got a chance to go through all of subgraphs. Overall our schemas  are good there are only two issues:

1) TVL and pool level TVL is off for BSC (almost double) and Ethereum (about 5% higher on the front end). Both of these schemas are older version and the newer versions on 1.1.4 and dont have this issue. Alternatively it could be a pricing issue, but i doubt it, because it is all the pools
2) Rewards are off on all the pools and minting is showing zero on all subgraphs. See if you can fix it. It is not a high priority for Protocol Metrics, but it would be nice to have accurate rewards.
3) I have excluded the synthetic market data for this. Likely we will need an independent subgraph for that similar to synthetix (that will be similar to the CDP schema).
4) Avalanche has not been deployed and should not be ingested.

notes: publicly available data for this is kind of a mess. Token terminal is wrong across the board and Defillama amalgamates the synthetics market and lending platform. Front end and on chain data generally conform with our subgraph. 

Let me know if you have questions or concerns. I think if these issues are addressed we can finally ingest dforce!

**Comment by tnkrxyz** [comment]
@ishraq8 , I just realized that there is a discrepancy in the deployed version (1.1.4) & the current code version (1.2.2). And the ethereum and bsc deployment failed at ~95%. Would you mind verifying when the new deployment is done? Also, it seems I don't have access to the google sheets listed above (tnkrxyz@gmail.com).

**Comment by tnkrxyz** [comment]
@ishraq8 , were you not able to see these reward emission data/charts? they load all right for me - you indicate there was "Reward Token output error on subgraph (Code Error)" in the speadsheet. The example below are for USDC on polygon:

https://subgraphs.messari.io/subgraph?endpoint=messari%2Fdforce-polygon&tab=pool&poolId=0x5268b3c4afb0860d365a093c184985fcfcb65234&view=marketDailySnapshots-rewardTokenEmissionsAmount%2520%5B0%5D

![image](https://user-images.githubusercontent.com/97625120/199362823-f71134c7-2fb3-4600-aeb0-f30c52bfbb15.png)
![image](https://user-images.githubusercontent.com/97625120/199362869-090b562b-770a-43a0-9f7e-b1f2735f0323.png)

**Comment by ishraq8** [comment]
> @ishraq8 , were you not able to see these reward emission data/charts? they load all right for me - you indicate there was "Reward Token output error on subgraph (Code Error)" in the speadsheet. The example below are for USDC on polygon:

Thanks for this, wasn't showing before but is correct now

**Comment by dmelotik** [comment]
Hey @ishraq8 the rewards were fixed for Optimism and Polygon by @tnkrxyz ! They are still slightly off from their FE, but I will let you decide what our room for error is and if it is acceptable.

Here are the deployments:
- Optimism: https://okgraph.xyz/?q=tnkrxyz%2Fdforce-optimism
- Polygon: https://okgraph.xyz/?q=tnkrxyz%2Fdforce-polygon

**Comment by ishraq8** [comment]
@tnkrxyz @dmelotik Dforce looks great!We are finally ready for prod with this!
