### ISSUE TITLE
euler subgraph improvements

### ISSUE THREAD

**Issue by tnkrxyz** [messari/subgraphs#1139]
Besides the possible method problem with protocolSideRevenue (#1115), a few improvements to the euler subgraph implementation:

1. The implementation relies on calling `EulerGeneralView.doQuery()` on ~100 markets on every major events. It is so inefficient  that the current implenetation has to skip 119 blocks between calling it again. Call doQuery on the market emitted the event is an easy improvement; It is also possible to access individual value from relevant events/contract(s) for even better efficiency.
2. The subgraph uses the address of underlying token as the id of the corresponding market and it is different than the specification in the schema. For example, the id for the wstETH market is [0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0](https://etherscan.io/address/0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0), and it is the address for the wstETH contract. It should be the euler eTokenAddr (asset) [0xbd1bd5C956684f7EB79DA40f582cbE1373A1D593](https://etherscan.io/address/0xbd1bd5C956684f7EB79DA40f582cbE1373A1D593) or dTokenAddr (debt) [0x436548baAb5Ec4D79F669D1b9506D67e98927aF7](https://etherscan.io/address/0x436548baAb5Ec4D79F669D1b9506D67e98927aF7)

**Comment by tnkrxyz** [comment]
3. Possible simplifying protocolSideRevenue calculation (from #1115):

> Realized I am not comparing apple-to-apple here: at any time, the collateral asset amount > borrow amount. If taking into account the difference, they should be equal: borrow amount * borrow APY * (1 - reserve fee ratio) = collateral asset * lending APY.

> This means the current method for calculating protocol side revenue is correct, but more complex than needed
> `Market Deposits Balance * ((Market Supply APY / (1 - Market Reserve Fee)) - Market Supply APY)`

> =

> `Borrow Balance * Borrow APY * Reserve Fee`

**Comment by dmelotik** [comment]
@tnkrxyz I wonder if there is a clean way to get revenue from euler. For example in compound we have `AccrueInterest()`. When looking at this a while back I couldn't find anything, but maybe it is more convoluted.

**Comment by dmelotik** [comment]
This might be out event to watch https://github.com/euler-xyz/euler-contracts/blob/master/contracts/Events.sol#L32

And then every time it is emitted we take the difference from the last to the current value of `interestAccumulator` then multiply by the spot price of the asset. lmk what you think

**Comment by tnkrxyz** [comment]
Haven't looked into the euler contracts to know much about this, but what you propose makes sense to me.

**Comment by tnkrxyz** [comment]
Dug into the contract a bit more. I agree AssetStatus is a better way to get interest/revenues. It seems to me the interestAccumulator is an index, instead of actual interest ([L215](https://github.com/euler-xyz/euler-contracts/blob/master/contracts/BaseLogic.sol#L215). 

My reading of the contract (https://github.com/euler-xyz/euler-contracts/blob/master/contracts/BaseLogic.sol#L213-L228) is that total Revenue = `newTotalBorrows - totalBorrows` and the reserve / protocol side revenue = `newReserveBalance - reserveBalance` , and the difference is supply side revenue = total revenue - protocol side revenue. Because the event only gives the current `totalBorrows` and `reserveBalance`, we need an entity to keep track of their previous values (per market).

@dmelotik , can you help me see if there are holes in my logic?

**Comment by dmelotik** [comment]
Hey @tnkrxyz for some clarity on how I am thinking about this (some of this may already be implemented):

`AssetStatus` is emitted at every transaction. And if you look this occurs after the deposit, withdraw, borrow, etc. So prices of the relevant token should be updated before or during the creation of a transaction. This way we get a proper USD price in the transaction.

Then in the `AssetStatus` handler we can update the market input tokens, Tvl, protocol tvl, borrows, rates, revenues, outputtokensupply, revenues, outputtoken price, etc. (everything but price). This can all be done for just the market that is being emitted on.

Now for the actual revenue calculation: To me it looks like it is either totalRevenue = totalBorrows * (currInterestAccum / prevInterestAccum) OR totalRevenue = totalBorrows * (currInterestAccum - prevInterestAccum). It would be ideal to do it this way to avoid any new contract calls.

Then protocol side revenue = total revenue * [reserveFee](https://docs.euler.finance/developers/getting-started/contract-reference#reservefee)

suppy side = total * (1 - reserveFee)

> Note; make sure to update the readme with notes and make good comments about how you are deriving the revenue. This is the most difficult metric to calculate in euler and we want to be as transparent as possible.


Euler's subgraph: https://thegraph.com/hosted-service/subgraph/euler-xyz/euler-mainnet

**Comment by tnkrxyz** [comment]
Thanks for the response! One minor issue with the method you propose is that totalBorrows already included interestRate accrued for the period (https://github.com/euler-xyz/euler-contracts/blob/1ad10e95f2991f13e32e601d791b2c3fa9c1bd45/contracts/BaseLogic.sol#L233), so multiplying it with `(currInterestAccum / prevInterestAccum)` double count the interest (total revenue). Of course it may be possible to reverse the process & calculate the totalBorrows before interest and apply interestAccumulator on top of it.

A simpler approach I found is to track the reserveBalance, and `protocol side revenue = reserveBalance - previous reserveBalance`, and because `protocol side revenue = total revenue * reserve fee/Reserve Fee Scale`,  `total Revenue = protocol side revenue * Reseve Fee Scale / reserve fee`. And finally, `supply side revenue = total Revenue - protocol side revenue`. 

Do you know, is the code for Euler's subgraph available? I checked their github and could not find it.

**Comment by dmelotik** [comment]
> Do you know, is the code for Euler's subgraph available?
Unfortunately I think it is private now

I think the issue with using reserve balance is that it can be subtracted from https://github.com/euler-xyz/euler-contracts/blob/master/contracts/modules/Governance.sol#L95. How do you account for this?

I see what you are saying about over estimating though. I think it would be spot on to find `totalRev` = `newTotalBorrows` - `newTotalBorrows * oldInterestAccum / newInterestAccum` then using `reserveFee` for protocol / supply side. I am just deconstructing this line: https://github.com/euler-xyz/euler-contracts/blob/1ad10e95f2991f13e32e601d791b2c3fa9c1bd45/contracts/BaseLogic.sol#L215

What do you think?

**Comment by tnkrxyz** [comment]
> @tnkrxyz I think the issue with using reserve balance is that it can be subtracted from https://github.com/euler-xyz/euler-contracts/blob/master/contracts/modules/Governance.sol#L95. How do you account for this?

Yes, I am. I can add a handler for `GovConvertReserves` that emits when reserve is removed.

> I see what you are saying about over estimating though. I think it would be spot on to find `totalRev` = `newTotalBorrows` - `newTotalBorrows * oldInterestAccum / newInterestAccum` then using `reserveFee` for protocol / supply side. I am just deconstructing this line: https://github.com/euler-xyz/euler-contracts/blob/1ad10e95f2991f13e32e601d791b2c3fa9c1bd45/contracts/BaseLogic.sol#L215

This can work, but likely more complex than tracking reserveBalance. For example, in [DToken.borrow()](https://github.com/euler-xyz/euler-contracts/blob/c426d7665f0b93437296ff29077e3dfe57e87286/contracts/modules/DToken.sol#L105-L120), the interest rate is calculate before adding the new borrow amount, and then logAssetStatus is emitted with the new borrow amount. In this case, `event.params.totalBorrows` will include the new borrow amount and is different than the value used in calculating interest. To get the correct borrow amount for interest accounting, we will need to track the new borrow amount and deduct from the `event.params.totalBorrows`.

**Comment by tnkrxyz** [comment]
BTW, @dmelotik, I checked with Vincent, and he approves that I will work on refactoring the euler finance subgraph in the next few days.

**Comment by dmelotik** [comment]
@tnkrxyz I see what you are saying there, the other place I could imagine special logic would be liquidations. Is this true?

**Comment by tnkrxyz** [comment]
> @tnkrxyz I see what you are saying there, the other place I could imagine special logic would be liquidations. Is this true?

That's correct - I will have to think about how best to handle liquidation.

This will fix the issue that the current implementation does not included in the protocol side revenue the % of liquidation is credited to the reserve (2%).  But I need a special handle that the protocol side revenue from the liquidation  is not shared with the supplier.

**Comment by tnkrxyz** [comment]
@dmelotik I figured out a way to rollback revenue from liquidation fees in helper.ts/rollbackRevenue(). Implemented in #1242

**Comment by tnkrxyz** [comment]
closed with #1242 merged
