### ISSUE TITLE
Uniswap-V2 Ethereum - Outlier in Uniswap v2 subgraph

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1191]
https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/uniswap-v2-ethereum&tab=protocol

<img width="899" alt="Screen Shot 2022-10-11 at 11 14 57 PM" src="https://user-images.githubusercontent.com/2354636/195248587-bdd3bb46-7e7f-4c76-98d0-4e1761622b62.png">

**Comment by steegecs** [comment]
#1237 
Being addressed and grafting from this PR.

**Comment by steegecs** [comment]
Related to issue #1391

**Comment by bye43** [comment]
Closing this, will be addressed in substreams
