### ISSUE TITLE
UwU Lend fix rewards

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1206]
UwU lend needs rewards to be added. Didn't do this right now because it is not necessary for protocol metrics and there are other things with higher priority at the moment.

**Comment by dmelotik** [comment]
Rewards are being calculated; however, it is unclear how to differentiate between rewards for borrowers / depositers.

**Comment by dmelotik** [comment]
Made a message in their discord to see if I can get some clarity: https://discord.com/channels/978102149420560414/978261473996447744/1031654534965112842

**Comment by dmelotik** [comment]
Depost rewards are good most of the time, still unclear about how much to allocate to borrowers!

**Comment by ishraq8** [comment]
Rewards looked fixed. match front end this is good to go @dmelotik
