### ISSUE TITLE
Ellipsis Finance BSC QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1209]
| Item| Info| 
| :----| :---| 
| Subgraph Review | https://subgraphs.messari.io/subgraph?endpoint=shashwats22/ellipsis-finance-v2&tab=protocol |
| Date Reviewed  | 12-Oct-22 |
| Schema Version  | 1.3.0 |
| Subgraph Version  | 1.0.1 |
| Methodology Version  | 1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1jus0r1up-5mU5GEqfhaVYzIXFSpZUhI7/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL pool and rewards

 - Sum of all pool TVL is not in line with the subgraph. Out of 84 pools 43 pools are considered inactive while 3 pools have a different input token. Out of the 41 active pools 22 pools have a percentage difference of more than 10% with differences ranging to as much as 6456.14% this contributes to the big discrepancy of numbers. 
- Reward APYs are accurate.
- Please refer to the sheet "Pool_Overview (Active only)" for more info.

| Protocol TVL Subgraph | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 697,392,59.35 | 74,872,873.30 | -5,133,614 | -7.36% |

| Pool 7 BNBx, WBNB | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 2,038,290.68| 3,619,037.27 | -1,580,746.59| -77.55%|

| Pool 34 aETHb, ETH| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 1,619.33| 106,165.55 | -104,546.22| -6456.14%|

###  Cumulative and Daily Volume
We note large discrepancy in daily volume data, for instance, based on the latest checking on 15th Oct (UTC+0 3am) for the top three pools by TVL.

| Pool  | Subgraph | Official Website | 
| :---- | :--- | :---  |
| val3EPS | 0 | 480.468 | 
| 2pool | 5,928 | 8,460 | 
| valDAI-val3EPS | 0 | 917 |

- Volume and revenue data of the largest pool val3EPS is not correctly recorded, showing zero for a few days.

In addition, the cumulative protocol volume was distorted due to the higher cumulative volume in pool 3EPS:

| Pool  | Subgraph | Official Website | 
| :---- | :--- | :---  |
| 3EPS | 47.7m | 25.8m | 

### Revenue
 - We calculated daily total revenue by multiplying Daily Volume and the Fee percentage from the website (assuming 0.0.4% for stablecoins pools and 0.4% for non-stablecoin pools). The results show a large discrepancy.  Please refer to the sheet 'Revenue' for details of calculation.
 - The reasons are due to the volume data discrepancy above. In addition, some of the pools may have the pool fee set incorrectly. For instance, pool 3EPS has LP fee set to be 0.04% instead of 0.02% (50% of the pool fee rate 0.04%).
 
Please refer to the attached worksheet for more details.

**Comment by shashwatS22** [comment]
> @shashwatS22 - Can you bump here when fixes are synced? Thanks!

Sure, it's around 65% synced, I'll let you know. 
I have deployed it again with significantly less price caching.
Here is the link: 
https://thegraph.com/hosted-service/subgraph/shashwats22/ellipsis-finance-5-day

**Comment by pietydespises** [comment]
@shashwatS22 most of the fixes look good now, any update on getting proper pricing from the price lib?

**Comment by shashwatS22** [comment]
@pietydespises I am working with @harsh9200 to solve this, he is busy with other projects right now, he is saying he needs some time to work on a custom price lib module for this, because many of the tokens don't follow the generic pricing methods.

**Comment by pietydespises** [comment]
hey @shashwatS22 @harsh9200 , any update on the pricing library fix here? otherwise this is good to ship

**Comment by harsh9200** [comment]
Hi, @pietydespises I tried fixing the price of high-priority tokens impacting most of the metrics of the subgraph, but some of the token prices still need to be fixed. So till then we can close this issue as completed and open a separate issue for tracking price-related issues on the ellipsis subgraph.

**Comment by pietydespises** [comment]
ok sounds good! thanks for doing that
