### ISSUE TITLE
Difference between uniswaps own subgraphs

### ISSUE THREAD

**Issue by paymog** [messari/subgraphs#1225]
What are the major differences between the [Messari Uniswap-v3 subgraph](https://github.com/messari/subgraphs/tree/master/subgraphs/uniswap-v3) and the [uniswa-v3 subgraph published by uniswap](https://github.com/Uniswap/v3-subgraph)? These subgraphs are fairly complex and there doesn't seem to be a simple diff I can run against them. Has Messari added or removed any major components relative to the uniswap authored subgraph?

**Comment by this-username-is-taken** [comment]
I'd say start with diffing the schema. That'll give you a high-level understanding of the differences without going into the code.

**Comment by dmelotik** [comment]
Closing this issue, as it has become stale.

@paymog feel free to open another issue if you have additional questions or clarifications! Thanks
