### ISSUE TITLE
Pangolin Avalanche QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1230]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=robinbernon/pangolin
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1e52e4S1j7lXa9D4CoHTe5uC-6Mxy0MNQ/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

#### Daily Volume Data
This is not necessarily a data error, but in the past seven days, the volume data from October 11 and 13 have discrepancies of more than 10%. 

|Subgraph's Daily Volume data for Oct. 13 |Official Website| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|1,522,883.40 | 4,342,366 |-2,819,483|-64.93%|

|Subgraph's Daily Volume data for Oct. 11 |Official Website| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|1,533,777.39 | 1,928,922 |-395,145|-20.49%|

- Refer to the sheet 'Protocol' 

#### Total Pool Count

- As compared to subgraph's 3,214 pools, official website and Dexscreener only show 100 and 234 pools respectively. 

### Editorials  

There are some errors we have noticed and are not necessarily data errors.

#### Pool Overview

- The pool overview section cannot be accessed and it is displaying some issues as it says 'Failed to fetch'
- Refer to the sheet 'Pool_Overview'   

#### Pool

- The subgraph query is not working no matter how many times the page is being refreshed.
- Refer to the sheet 'Pool_vault_schema' and 'Pool_snapshots'  

#### Events

- The subgraph is not showing any data and only shows black screen.
- Refer to the sheet 'Events'   

 Please refer to the attached worksheet for details.

**Comment by pietydespises** [comment]
Working on getting the Pool Overview and Pool pages working on the validation dashboard and will then QA them myself

**Comment by pietydespises** [comment]
this is good to go
