### ISSUE TITLE
Spiritswap Fantom QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1234]
#Review Info
| Item| Info | 
| :----| :---| 
| Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=messari/spiritswap-fantom |
| Date Reviewed  |	18-Oct-22 |
| Schema Version  |	1.3.0 |
| Subgraph Version  |	1.1.3 |
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1OVJL1sO2PxMZ-jA8bqSJLh7eBOWOCAPl/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Pool TVL

 - Sum of all pool TVL is in line with the subgraph. There is a total of 2,202 pools and after checking a small sample size of the top 100 pools 12 are not seen in the subgraph although the TVL is still in line with website data. The 11th pool has a significant discrepancy namely USDC,FRAX.
- Refer to the sheet "Pool_Overview (Active only)" for more info

| #11 USDC, FRAX | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 247,842.76| 1,038,861.04 | -791,018.28| -319.16%|

Please refer to the attached worksheet for more details.

**Comment by steegecs** [comment]
Being addressed in this PR #1259. It should fix any reduced TVLs. I went ahead and deployed, but it will probably take a week at least to sync. I am not sure what the speed is on this one. What do you think about putting this one in production, and then cleaning up the last data issue(s) with pool TVL? Or do you think we should wait for it to sync again fully before doing so?

**Comment by pietydespises** [comment]
Moving ahead to production before last pool TVL issue is fixed sounds good to me but I'd want @this-username-is-taken's opinion before confirming.

**Comment by this-username-is-taken** [comment]
> Moving ahead to production before last pool TVL issue is fixed sounds good to me but I'd want @this-username-is-taken's opinion before confirming.

sounds good to me! I'd still leave this open to track so we don't forget. IIRC this one takes a very long time to index

**Comment by steegecs** [comment]
Still has about 500,000 blocks left. A while to go.

**Comment by steegecs** [comment]
@pietydespises, this is ready for validation again for that pool you have mentioned. We are synced to head, and from my looks, it seems we are clear to backfill this.  
https://thegraph.com/hosted-service/subgraph/messari/spiritswap-fantom

**Comment by pietydespises** [comment]
yep looks good!
