### ISSUE TITLE
Uniswap v3 missing account that swap the tokens

### ISSUE THREAD

**Issue by sydneyhenrard** [messari/subgraphs#1253]
The Swap event for some transactions have the same from and to which is `0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45` (Uniswap V3: Router 2)

For instance 
```
{
  swaps(
where: {hash: "0x6d1788ab192dc6e55e57d345816aea8831d27d4c4bd829daca496e252d2f2b5a"}    
  ) {
    id
    from
    to
  }
}
```
returns
```
{
  "data": {
    "swaps": [
      {
        "id": "0x6d1788ab192dc6e55e57d345816aea8831d27d4c4bd829daca496e252d2f2b5a-3",
        "from": "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45",
        "to": "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"
      }
    ]
  }
}
```
So there is no way to know what is the actual account that swaps the token. One way to do it is to index the originator of the transaction which is `0x000000000000d34c44564053af35e4fe271d0caa`. My guess is that it would be the msg.sender.

https://arbiscan.io/tx/0x6d1788ab192dc6e55e57d345816aea8831d27d4c4bd829daca496e252d2f2b5a

**Comment by steegecs** [comment]
Thanks for bringing this up! Looking into it.

**Comment by steegecs** [comment]
![Screen Shot 2022-10-23 at 3 00 51 PM](https://user-images.githubusercontent.com/56660047/197415475-b0af037f-abfd-491f-8015-f5d66ff6a846.png)

@sydneyhenrard So our schema defines the `to` and `from` fields as the one that sent and receives the token. This should often be the same address. If you want to know the pool that the swap is occurring through, you can look at the `pool` entity. There is no single account doing the swapping, as the swap occurs using the collected reserves in a liquidity pool with a token pair.

**Comment by sydneyhenrard** [comment]
The address `0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45` corresponds to the Uniswap V3 - Router 2. If you look at the transaction the actual address that receives the token is `0x000000000000d34c44564053af35e4fe271d0caa`. This address swaps GMX for AETH but this is the Uniswap Router that does the swap.

By using the subgraph from Uniswap https://thegraph.com/hosted-service/subgraph/ianlapham/arbitrum-minimal with the query:
```
{
  swaps(
where: {transaction_contains: "0x6d1788ab192dc6e55e57d345816aea8831d27d4c4bd829daca496e252d2f2b5a"}    
  ) {
    sender
    recipient
    origin
  }
}
```
You can see that the initiator of the transaction is not lost
```
{
  "data": {
    "swaps": [
      {
        "sender": "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45",
        "recipient": "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45",
        "origin": "0x000000000000d34c44564053af35e4fe271d0caa"
      }
    ]
  }
}
```
What I don't understand is that the code seems correct, the sender (event.transaction.from) is the initiator of the transaction.
https://github.com/messari/subgraphs/blob/master/subgraphs/uniswap-v3/src/mappings/core.ts#L70
https://github.com/messari/subgraphs/blob/master/subgraphs/uniswap-v3/src/common/creators.ts#L406

**Comment by steegecs** [comment]
Hmm. Yeah this is strange to me too. I'll run some tests on follow up on this! Thank you for laying this out for me.

**Comment by steegecs** [comment]
Okay - I believe this is taken care of here. This version, as well as others like it will soon be grafted to production and backfilled. 

https://thegraph.com/hosted-service/subgraph/steegecs/uniswap-v3-arbitrum?version=pending
