### ISSUE TITLE
Detailed Revenue Metrics

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1268]
Suggestion on future schema for revenue - instead of doing all the math on the backend and having one revenue number on the schema, can we have an array of each different rev type?

Example
TotalRevenue: [
    {name: FeeRevenue,
     AmountUSD: 10000},
     {name: LiquidationRevenue,
     AmountUSD: 1000}
]
This way the consuming app/users more clearly knows what’s in the rev number and can have more flexibility in displaying rev (example being us generating financial statements for quarterlies where you would want to show the breakout of revenues across product lines and types like swap fees, withdraw fees, liquidation etc)

**Comment by dmelotik** [comment]
@bye43 what protocols have liquidation revenue?

**Comment by bye43** [comment]
@dmelotik From my quick methodology scan: 
* AAVE V3
* Abracadabra 
* MakerDAO
* Liquity 
* QiDAO
* Synthetix
* trueFI
* Vesta
* Moola Market

Couple notes here though. The methodology for Compound and its associated forks says that liquidations are currently note included, so potentially may want to take a look at that being included if its relevant. Also, we should consider flashloan revenue too.

**Comment by dmelotik** [comment]
Maybe we can keep the revenue as is, but create a new field for revenue by type and have an array with `revenue` types. Going to see what people say, but something we could include in the 3.0.0 schema

**Comment by dmelotik** [comment]
Being fixed in new schema

**Comment by bye43** [comment]
Being addressed here: https://github.com/messari/subgraphs/issues/1081
