### ISSUE TITLE
Rocketpool Mainnet QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1277]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/benreilly19/rocketpool&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.1  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1G_N0W8q1UaOt0YqgZVTrOyKeObEM9S7o/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### TVL
- Subgraph's TVL data shows a seven-day average discrepancy of 9.30% with Defi Llama data. Furthermore, we have computed the implied TVL using the official website data and the results are in line with Defi Llama data. This implies that Defi Llama data is more accurate than the TVL data of the subgraph.
- See 'Protocol' and 'Support-Implied-TVL' sheets for more information.

|Subgraph TVL 7-day average |Defi Llama 7-day average | Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|349,138,759 | 385,051,231 |-35,912,472|-9.30%|

|Recent Subgraph TVL |Implied TVL | Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|351,798,821 | 392,741,941 |-40,943,120.11|-10.42%|

### Revenue

- Daily revenue data must not be zero. Our computations for the implied revenue show that the total revenue for the recent data must be around $17.7 million. The protocol side revenue should also be larger than the supply side revenue as the node operators take commissions from LPs by reducing their staking rewards. 
- Refer to 'Protocol' and 'Support-Implied-Revenue' sheets

|Subgraph Daily Supply Side Revenue |Implied Revenue| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|0| 6,209,738.96 | -6,209,738.96|-100%

|Subgraph Daily Protocol Side Revenue |Implied Revenue| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|0| 11,532,372.35 | -11,532,372.35|-100%

|Subgraph Total Daily Revenue |Implied Revenue| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
| 0 | 17,742,111.31 | -17,742,111.31 |-100%

### Pool Overview 

 - TVL has a discrepancy of about 10% against Defi Llama and implied TVL data. See the analysis under TVL section.
 - Input tokens must only be in ETH.
 - Base Yield should not be zero as there is supply side revenue. See 'Support-Implied-Revenue' sheet for more information.

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@zdql - Bumping this QA for Rocket Pool

**Comment by zdql** [comment]
@bye43 Daily revenue being 0 is due to my methodology of only tracking revenue when beacon chain rewards are updated. This is flawed, but I'm not sure of a better methodology. Any suggestions for other ways to track this more regularly?

**Comment by dmelotik** [comment]
@bye43 tagging you to get a review of the the QA changes on this? https://okgraph.xyz/?q=benreilly19%2Frocketpool

If there are things to change @zdql will address in a separate PR, but we will merge #1427 this week

**Comment by dmelotik** [comment]
All good now @bye43 ?

**Comment by bye43** [comment]
@dmelotik Can you close this whenever it gets backfilled?

**Comment by dmelotik** [comment]
Yes I will @bye43

**Comment by dmelotik** [comment]
all done @bye43
