### ISSUE TITLE
Decimal issue with ChainLinkFeed of Price lib

### ISSUE THREAD

**Issue by AP-Atul** [messari/subgraphs#128]
# Token
Address: `0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b`
Etherscan: [Convex Token(CVX)](https://etherscan.io/address/0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b)
Original Price: `approx $26.8241`
Reported Price from Price Lib: `$2853.700013` at block `14594214`

## Debug Details
Latest Round Data from `Chainlink Feed` with address `0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf`
![Screenshot 2022-04-29 at 11 07 16 AM](https://user-images.githubusercontent.com/35269424/165890079-b2775ca5-c1f9-46a0-abfb-c4b6b04a09f7.png)

Getting decimals
![Screenshot 2022-04-29 at 11 09 20 AM](https://user-images.githubusercontent.com/35269424/165890227-cc7cd0ae-6035-4bf3-b451-f8b14acb8d0b.png)

Calculations
```
Reported price = 2695000000
Decimals = 8

Final price = 2695000000 / 100000000 = $26.95
```

## Possible Solution
If the Chainlink Feed is able to fetch the price for input token then it will also be effective to fetch the decimals for the token.

**Comment by harsh9200** [comment]
Hello, this bug is already fixed in PR #120
