### ISSUE TITLE
Alpaca Finance BSC QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1282]
## Review Info
| Item| Info| 
| :----| :---| 
| Subgraph Review | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/corerouter/alpaca&tab=protocol |
| Date Reviewed  |	24-Oct-22 |
| Schema Version  |	2.0.1 |
| Subgraph Version  |	1.0.0 |
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1mO-5eY5lm7E2baYMq8sjLw1BmfYw7VZN/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL pool

 - Sum of pool TVL is in line with the subgraph although out of all pools ETH pool shows a big discrepancy.
- Refer to the sheet "Pool_Overview" for more info

| Subgraph| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 386,446,683.54| 394,189,695.50 | -7,743,011.96| -2.00%|

| #08 ETH| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 2,218,065.16| 10,801,768 | -8,583,702.84| -386.99%|

### Revenue

- Daily revenue is correct although cumulative revenue is not in line with protocol and supply percentages from the website. Difference in percentage is mainly due to the ALPACA and TUSD pool. See "Total Revenue" sheet for more info. 

### Borrow
- Total borrow balance USD is negative which should not be the case.

### Usage metrics
- Daily Users and transaction count are not in line with hourly data and dune analytics. In addition total pool count should be 9 compared to 14 in the subgraph. 

### Events
- Liquidates page may have incorrectly placed its decimal places in reference with BSCscan. Refer to the screenshots in the "Events" sheet.

Please refer to the attached worksheet for more details.

**Comment by this-username-is-taken** [comment]
@corerouter

**Comment by corerouter** [comment]
Gotcha. I am going to take a look and fix the problems. Thanks!

**Comment by ishraq8** [comment]
@corerouter Took a look at the QA and it was done well. Let me know if you need any help and I can QA the fixes. Thank you for taking a look at this.

**Comment by corerouter** [comment]
@ishraq8 Sure. I will let you know once they are fixed. As the subgraph needs about 3 days to sync, it may take some time to fix them. Thanks!

**Comment by corerouter** [comment]
The fix has been deployed and verified. Please take a look when you have time. Thanks!

**Comment by ishraq8** [comment]
@corerouter This is great! all issues resolved. Alpaca is now ready for prod.
