### ISSUE TITLE
Add Aave V3 into aave-v2-forks

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1295]
There are a few issues with Aave V3 data. These will largely be fixed when we add aave v3 into the aave-v2-forks directory ad rename to `aave-forks`.

Linking the issues here, and closing them:
- #966 
- #1285

**Comment by dmelotik** [comment]
I believe transfers also create a withdraw entity therefore double counting deposits and withdraws. Will be fixed when added to aave forks, and can benefit from the new 3.0 lending schema

**Comment by bye43** [comment]
PR: https://github.com/messari/subgraphs/pull/1549

**Comment by ishraq8** [comment]
took a look data is accurate.
