### ISSUE TITLE
AAVE fork positional QA 

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1364]
End Points
https://api.thegraph.com/subgraphs/name/dmelotik/aave-v2-ethereum
https://api.thegraph.com/subgraphs/name/dmelotik/aave-v2-avalanche

https://api.thegraph.com/subgraphs/name/dmelotik/aave-v2-ethereum-amm

https://api.thegraph.com/subgraphs/name/dmelotik/aave-v2-arc

https://api.thegraph.com/subgraphs/name/dmelotik/aave-v2-rwa

https://api.thegraph.com/subgraphs/name/dmelotik/geist-fantom

https://api.thegraph.com/subgraphs/name/dmelotik/uwu-lend-ethereum

https://api.thegraph.com/subgraphs/name/dmelotik/radiant-capital-arbitrum

**Comment by ishraq8** [comment]
@dmelotik Great work on AAVE V2 forks.
I compared these to top wallet holders on debank and they matched.
Comments:
1) I will need to double check once integrated into the lending whales data apps. Only checked a few wallets per deployment so don't want odd outliers.
2) Proxy apps, like instadapp, the proxy wallet appears on the subgraph. Will need to do an instadapp overlay on the front end to match the initiating wallet to the proxy one. 

This is ready to deploy on the the graph

**Comment by dmelotik** [comment]
Deploying all of these to messari hosted service now. No changes will affect protocol metrics
