### ISSUE TITLE
Venus BSC - Need to add rewards

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1370]
Still need to add rewards to the Venus subgraph

**Comment by bye43** [comment]
@dmelotik is there a link for this deployment

**Comment by dmelotik** [comment]
Yep, forgot to update: https://okgraph.xyz/?q=messari%2Fvenus-protocol-bsc

**Comment by bye43** [comment]
@ishraq8 can you do a quick check on these rewards?

**Comment by ishraq8** [comment]
Rewards are good on this @dmelotik, matches front end. once deployed i can backfill

**Comment by dmelotik** [comment]
I have already backfilled
