### ISSUE TITLE
Multichain Subgraph QA

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1384]

**Comment by this-username-is-taken** [comment]
Assigned to @dhruv-chauhan

**Comment by bye43** [comment]
@pietydespises For the first bridge (multichain) on ETH/FTM, do you mind doing a full QA in case there is anything in the schema or methodologies that seem wrong to you, so we can update or fix them in future bridges? 

Deployments/methodology here: https://github.com/messari/subgraphs/pull/1457#issue-1466045180

**Comment by pietydespises** [comment]
Looks great! Why is the cumulativeUniqueTransferReceivers metric so low (on the order of 10s) when the cumulativeUniqueTransferSenders is so high (on the order of thousands) for both networks? @dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
@pietydespises my bad; fixed it in PR #1578

**Comment by pietydespises** [comment]
Looks good! Receivers metric on Fantom looking quite wonky, can you double check that one? Also, noticing all the message metrics are zero. I guess we do not consider asset transfers as messages and that is the only type of activity that goes on on multichain?

**Comment by dhruv-chauhan** [comment]
@pietydespises 
- only deployed transfer receivers changes for mainnet, also deployed for fantom now (`QmSX2tUcHneUwHgEaAbX8Bcf7eYsMkFgZyt5WwC8WvjoPJ`)
- yes, asset transfers and messages are separate activities. For multichain, the cross-chain messaging (they call it anyCall) is not live yet, so we only track transfers as of now.

**Comment by pietydespises** [comment]
Awesome, thanks @dhruv-chauhan . Also is there a particular reason that you know of revenue is near zero for recent dates?

**Comment by dhruv-chauhan** [comment]
good catch @pietydespises! Silly typo, fixed in the same PR #1578 , updated deployments IDs in PR description.

**Comment by pietydespises** [comment]
great, thank you

**Comment by bye43** [comment]
@pietydespises going to move this to `syncing` while we wait to backfill and show it on PM

**Comment by pietydespises** [comment]
ty sir
