### ISSUE TITLE
Balancer 2.0.0 Schema Upgrade Account and Position Data QA

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#1392]
| Item | Info |
| :---- | :--- | 
| Subgraph Reviewed (Eth) | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmWgtTvAwn6rPLWYQuNy5F4s8Ct1LZV4p5X4PesNUigxkA&tab=protocol |
| Subgraph Reviewed (Arbitrum) | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/Qmc47H3j5KKCuN8Sfw9RpUK7sg9CKx9e2krJbrS8QboW8E&tab=protocol |
| Subgraph Reviewed (Matic) | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmXV5Bgs56BLHXXpGWoV8gAv8ev6tkwN7sT4BPoBosLb66&tab=protocol |
| Date Reviewed  | 08-Nov-22 |
| Schema Version  | 2.0.0 |
| Subgraph Version  | 1.2.0 |
| Methodology Version  | 1.0.0 |

###  All Financial Metrics on Arbitrum

All financial metrics on Arbitrum are displaying abnormally large values 

## Notes/Comments

Polygon data looks reasonable, and account/position data across all three chains looks accurate.

**Comment by this-username-is-taken** [comment]
@nemani

**Comment by nemani** [comment]
Redeployment without any grafts seems to have fixed the issue for arbi. 
waiting for it to sync to confirm, but you can see them here: Blue is new deployment and Red is old with large values. 


https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmZ1taQzXd3vPjmbRmexZqo9eqswWvJUJfBsTz1xpWWQo1&tab=protocol&overlay=https://api.thegraph.com/subgraphs/id/Qmc47H3j5KKCuN8Sfw9RpUK7sg9CKx9e2krJbrS8QboW8E

**Comment by pietydespises** [comment]
hell yea, this looks good to ship then.
