### ISSUE TITLE
schema-dex-amm-extended.graphql LiquidityPoolDailySnapshot Stat properties need to be lists

### ISSUE THREAD

**Issue by smith-phil** [messari/subgraphs#1407]
The Stat properties for LiquidityPoolDailySnapshot in the extended dex amm schema (schema v2.0.0) need to be lists as there needs to be a stat entity for each of the deposit tokens in the liquidity pool. This change will match the existing pattern for inputToken on the LiquidityPool entity. LiquidityPoolDailySnapshot properties to be updated:

- swapStats
- depositStats
- withdrawStats

This means the Stat entity id needs to be updated to differentiate between the deposit tokens. Something like
`{ protocol/pool }-{ [Optional] Pool ID }-{[Optional] Token ID}-{ deposit/withdraw/swap }-{ Days/hours since Unix epoch }`

See [this](https://discord.com/channels/953684103012683796/961658223444787220/1038822273097936896) discussion for clarification.

**Comment by dmelotik** [comment]
@steegecs related to #801

**Comment by steegecs** [comment]
No longer including stat properties on entities.
