### ISSUE TITLE
QiDao rewards missing

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1422]

**Comment by bye43** [comment]
@dmelotik Does MAI have rewards for their CDP option? I don't know if the actual lending portion emits `QI` could be wrong though

**Comment by dmelotik** [comment]
@bye43 looks like there are borrow rewards on vaults for borrowing MAI so I think yes: https://docs.mai.finance/borrowing-incentives

**Comment by dmelotik** [comment]
donezo

**Comment by bye43** [comment]
Note: Not tracking because rewards are calculated off chain
