### ISSUE TITLE
Vesta-Finance Arbitrum - Add Rewards

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1424]

**Comment by bye43** [comment]
PR: https://github.com/messari/subgraphs/pull/1470

**Comment by bye43** [comment]
@ishraq8 Can you QA these rewards when you get the chance? https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/vesta-finance-arbitrum&tab=poolOverview

**Comment by ishraq8** [comment]
Rewards for stability pool are accurate. this should get merged.
