### ISSUE TITLE
QiDao Missing Ethereum / Harmony / Moonbeam deployments

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1431]
QiDao is on harmony and ethereum, but we do not have the deployments for them setup at all.

**Comment by bye43** [comment]
@jaimehgb Should we move this to backlog for now and bump it to p0 after rewards are finished. We are going to have to support rewards on it in protocol metrics, so I think it makes sense to do the rewards for all of the lending protocols on display, and then add these in after opposed to moving bandwidth to support these deployments w/out rewards

**Comment by jaimehgb** [comment]
> @jaimehgb Should we move this to backlog for now and bump it to p0 after rewards are finished. We are going to have to support rewards on it in protocol metrics, so I think it makes sense to do the rewards for all of the lending protocols on display, and then add these in after opposed to moving bandwidth to support these deployments w/out rewards

Yep, I agree. No need to add rewards if it is not even showing. Will just become a requirement to finish it and backfill after rewards are complete. 

Let's move to backlog

**Comment by bye43** [comment]
PR: https://github.com/messari/subgraphs/pull/1661

**Comment by ishraq8** [comment]
completed

**Comment by bye43** [comment]
@ishraq8 Going to move this to syncing. Can you move it to `Done` after they are all backfilled?

**Comment by ishraq8** [comment]
Yeah no prob, sorry I hit done

**Comment by ishraq8** [comment]
backfilled and in PM
