### ISSUE TITLE
How to query the Uniswap v3 HEX/USDC pool based on token0 and token1 ?

### ISSUE THREAD

**Issue by firstprimecrypto** [messari/subgraphs#1432]
Hi,
Since inputTokens[] is an array, how can I query the liquidiy pool providing HEX and USDC as symbol names for token0 and token1 ?
The query below seems not to work....
Subgraph ID: ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7

Thank you for replying!

```
{
   liquidityPools(first: 1, where: { inputTokens_: { symbol: { in: ["HEX","USDC"] }  } } ) {
    id
    name
    symbol
    totalValueLockedUSD
    fees {
      id
      feePercentage
      feeType
    }
    inputTokens {
      name
      symbol
    }
    
  }
}
```

**Comment by jaimehgb** [comment]
Hey @firstprimecrypto !

Try the query like this instead:
```
liquidityPools(first: 1, where: { inputTokens_: { symbol_in: ["HEX", "USDC"]} } ) {
```

Should be `symbol_in` instead of `symbol: { in: …`

**Comment by firstprimecrypto** [comment]
Thank you! I've tried it but unfortunately it doesn't work. It just comes back with the first hit on "HEX" or "USDC", but not as a tokenpair. I think that's beause the inputTokens is an array.

Imo, below is basically what I need. But the query is not well-formed (using array offsets), so it doesn't work.

[https://thegraph.com/explorer/subgraphs/ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7?view=Playground](https://thegraph.com/explorer/subgraphs/ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7?view=Playground)

```
{
   liquidityPools(first: 1, where: { 
       AND: [
           { inputTokens_.0: { symbol: "HEX"} }
           { inputTokens_.1: { symbol: "USDC"} }
       ]
    })
    id
    name
    symbol
    totalValueLockedUSD
    fees {
      id
      feePercentage
      feeType
    }
    inputTokens {
      name
      symbol
    }
}
```

Maybe you have another idea?

**Comment by jaimehgb** [comment]
Yeah … I think the [graphQL API for subgraphs](https://thegraph.com/docs/en/querying/graphql-api/) is not that much flexible. As a matter of fact, support for nested queries [was added very recently](https://twitter.com/graphprotocol/status/1561796155301937155?lang=en).

There is a hack I can think of, I hope it works for your use case, which is querying by both token symbol and token address. Like, `give me all pools which include a token with symbol HEX and a token with address 0x…..`:

```
{
   liquidityPools(
    first: 1, 
    where: {
      inputTokens_: {
        symbol: "HEX"
      },
      inputTokens_contains: ["0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"]
    } 
  ) {}
}
```

Although if you know the addresses and don’t mind querying that way instead of by symbol, you can do:

```
liquidityPools(
    first: 5
    where: {
      inputTokens_contains: [
        "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48”,
        "0x2b591e99afe9f32eaa6214f7b7629768c40eeb39"
      ]
    } 
  )
```

**Comment by firstprimecrypto** [comment]
Thank you! The combination of a symbol name as token0 and the tokenaddress as token1 is a clever solution!
With this it's possible to find the proper pooladdress based on 2 tokens without having to provide the 3rd fee parameter.
This is exactly what I was looking for.
