### ISSUE TITLE
Subgraph "Uniswap v3 Ethereum" gives quite a lot network timeouts and false positives errors

### ISSUE THREAD

**Issue by firstprimecrypto** [messari/subgraphs#1439]
Hi,

The subgraph "Uniswap v3 Ethereum" gives quite a lot network timeouts and false positives errors. I am considering to use this in a project but it's not stable enough atm.
Is this a known issue? And/or is there something to do about it?

Subgraph ID: ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7

Example errors:
* CombinedError: [Network]
* CombinedError: [GraphQL] Invalid value provided for argument `where`: Object({"inputTokens_": Object({"id": String("0x2b591e99afe9f32eaa6214f7b7629768c40eeb39")})})

Please repeat the query multiple times and you see it will hit an error or a proper execution.

The valid query I used is:

https://thegraph.com/explorer/subgraphs/ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7?view=Playground
```
{
   liquidityPools(first: 1, orderBy: totalValueLockedUSD, orderDirection: desc, where: { 
          inputTokens_: { id: "0x2b591e99afe9f32eaa6214f7b7629768c40eeb39"} }) {
    id
    name
    symbol
    totalValueLockedUSD
    fees {
      id
      feePercentage
      feeType
    }
    inputTokens {
      id
      name
      symbol
    }
  }
}

```

**Comment by this-username-is-taken** [comment]
Appreciate the feedback. Unfortunately this is an issue with `graph-node` so it'd be best if you reported in https://github.com/graphprotocol/graph-node.

As an alternative, you can use the same subgraph on Hosted Service which has been pruned to improve query performance: https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-ethereum. Note that the caveat is it won't support time-travel queries

**Comment by firstprimecrypto** [comment]
Thank you, the hosted service works fine! I will report the issue the graph-node.
