### ISSUE TITLE
Liquidity in Uniswap V3 Pools

### ISSUE THREAD

**Issue by roama3** [messari/subgraphs#1441]
#1255 exchanged the use of the "Burn" event for the "Collect" event in order to address a bug in tracking TVL. However, it is no longer possible to determine the liquidity currently deployed in the pool as a position may be burnt, meaning it is no longer providing liquidity, without being collected. 

Would it be desirable to re-introduce tracking of the Burn event in order to determine current liquidity available in the pool?

**Comment by steegecs** [comment]
Hi @roama3. Thank you for addressing this with us! I am working on including this in an upcoming update to the Uniswap V3 subgraph. I will keep you updated.

**Comment by roama3** [comment]
Hi @steegecs, that's great news, thank you! Is there a PR in progress I could refer to?

**Comment by steegecs** [comment]
I'll push soon and ping you.

**Comment by steegecs** [comment]
@roama3 

Here is the PR! Still in progress.

**Comment by roama3** [comment]
Thank you! 😄 I await with anticipation

**Comment by steegecs** [comment]
Hi @roama3! At last we have merged in the PR for Uni V3. Currently we are working on validating the data.

**Comment by roama3** [comment]
Amazing, thanks!
