### ISSUE TITLE
Iron-Bank Optimism: Add deployment and rewards

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1445]
This is being done by @tnkrxyz in #1433 ,but wanted to track it here as well since we will need to do some additional things to add it to PM.

**Comment by dmelotik** [comment]
Creating new hosted service subgraph: https://thegraph.com/hosted-service/subgraph/messari/iron-bank-optimism

**Comment by tnkrxyz** [comment]
closed with #1433

**Comment by bye43** [comment]
@ishraq8 Do you mind doing a quick scan on this and the rewards?

**Comment by ishraq8** [comment]
@tnkrxyz There is something off with the rewards on optimism compared to what IB is reporting. Could you double check? All the other chains don't have rewards. 
![Screen Shot 2022-12-14 at 1 10 47 PM](https://user-images.githubusercontent.com/47088402/207676139-fca0e824-f709-46a0-abd9-87cfa49d58af.png)


![Screen Shot 2022-12-14 at 1 10 38 PM](https://user-images.githubusercontent.com/47088402/207676167-b345c4a3-5b7b-4099-a54d-e2157114f52e.png)
