### ISSUE TITLE
Vesta-Finance Arbitrum subgraph issues

### ISSUE THREAD

**Issue by tnkrxyz** [messari/subgraphs#1461]
I'm using this issue to list likely issues the vesta-finance subgraph I came across as I work on [the rewards](https://github.com/messari/subgraphs/issues/1424):

Deployed subgraph: https://subgraphs.messari.io/subgraph?endpoint=messari/vesta-finance-arbitrum&tab=protocol
- subgraph version: 1.0.0
- schema version: 2.0.1
- methodology version: 1.0.0

## Issues
- protocol.totalPoolCount = 1
- protocol.mintedTokenSupplies = 805.005
- market id is the address of underlying token, not the contract address of the market, e.g https://arbiscan.io/address/0x8d9ba570d6cb60c7e3e0f31343efe75ab8e65fb1#readContract
- stabilityPool were not included

**Comment by bye43** [comment]
@tnkrxyz Was this resolved?

**Comment by ishraq8** [comment]
Rewards look accurate on the subgraph. Stability pools were added. This should be good to merge.

**Comment by dmelotik** [comment]
merged! @ishraq8
