### ISSUE TITLE
Build Derivatives Schema

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1474]

**Comment by ishraq8** [comment]
Research: https://www.notion.so/messari/Protocol-Type-Research-Derivatives-8ae0bef9e49b416c88b9077786f340b1

Metrics: https://www.notion.so/messari/Protocol-Type-Metrics-List-Derivatives-c7f18d1eea3e4a8c84a2d8822670b5b0

**Comment by bye43** [comment]
Next steps here:

@ishraq8 going to draft either options or perps schema

**Comment by bye43** [comment]
Open PR here: https://github.com/messari/subgraphs/pull/1596
