### ISSUE TITLE
Experiment on time it takes to index raw events

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1479]
The goal is to understand how much time (and how much faster) it takes to index just the raw input data without any transformations.

I think we can use Uniswap v2 and Uniswap v3 as an example, and try the following:
- a subgraph for 1 single event (e.g. `Swap`, `PairCreated`)
- a subgraph for 1 single call
- a subgraph for all events needed

**Comment by steegecs** [comment]
In progress!

**Comment by steegecs** [comment]
Uniswap V2 Experiment
- All Events (PairCreate + Swap + Mint + Burn + Initialize + Sync)
  - 14.8 Days to fully Index
- 1 Event (PairCreated + Swap)
- 7.64 Days to fully Index
- 1 Call (PairCreate + SetFeeTo (Factory))
  - 3.11 Days to fully index
