### ISSUE TITLE
CI / Lint additions

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1484]
- Add check for folder/file naming to stay standard file name scheme being https://google.github.io/styleguide/tsguide.html#identifiers-imports
- ~~Add a new GH action to check for formatting separate of the other actions~~ Done by @jaimehgb 
- Add lint check so we have no string literals

**Comment by jaimehgb** [comment]
> Add lint check for literals 

This one refers to the addresses? @dmelotik

**Comment by dmelotik** [comment]
@jaimehgb I mean no string literals

**Comment by dmelotik** [comment]
TODO:
- https://eslint.org/docs/latest/rules/camelcase ignore globals, and ensure that it doesn't break any graph imports
- https://eslint.org/docs/latest/rules/max-lines-per-function add max lines AND max indents to make functions easier to read
- https://eslint.org/docs/latest/rules/no-magic-numbers helping with literals

There are no "out of the box" eslint rules to prevent string literals. We would either have to make our own or use a third party. Lowest priority given the work req'd.

**Comment by tnkrxyz** [comment]
@dmelotik , I started to work on this task, draft PR in #1955.

> - [X] Add check for folder/file naming to stay standard file name scheme being https://google.github.io/styleguide/tsguide.html#identifiers-imports

done.

> - Add lint check so we have no string literals

I need a bit clarification what is allowed, what is not:
- allowed:
   - template literal: `${var1}-${var2}`
   - log.error("[error] variable value: {}", [])

- disallowed:
   - string concatenation: var1 + "-" + var2
 
What else?

> * https://eslint.org/docs/latest/rules/camelcase ignore globals, and ensure that it doesn't break any graph imports

[camelcase is deprecated](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/camelcase.md). it is suggested to use naming-convention. I suppose we will exclude imported names. What about single word variable name, like `vault`? leading "_" ok?

> * https://eslint.org/docs/latest/rules/max-lines-per-function add max lines AND max indents to make functions easier to read

I could not find this rule in the aslant-plugin installation: https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin/src/rules . Maybe also deprecated?

> * https://eslint.org/docs/latest/rules/no-magic-numbers helping with literals

done.

> 
> There are no "out of the box" eslint rules to prevent string literals. We would either have to make our own or use a third party. Lowest priority given the work req'd.

**Comment by tnkrxyz** [comment]
> * I agree with the allowed, but I don't think we should disallow string concats. This is mainly to make sure we don't have "daily" not being used as a constant, etc.

@dmelotik , Can you give me a few examples of not allowed? 

Like `const snapshotId = "daily-" + market.id + "-" + days`? 

How about `const entityId = "GAUGE-FACTORY"` used in some subgraphs to save/read a single entry entity?

> * naming conventions: _ appended is OK i'd say. But variables should be camelcase if not global and all caps snake case if global.

> * That is okay for the functions. I think this is a best effort type of issue

Should we make them error or warning?

**Comment by dmelotik** [comment]
Yes! 

Allowed:
- `const ENTITY_ID = "GUAGE-FACTORY";`
- Any namespaces with constants

Disallowed:
- `const snapshotId = "daily-" + market.id + "-" + days;`
- `const prefix = "daily";`

Basically, the only file a string should created from a literal is the constants.ts

The tough part, is that no one notices warnings (almost like a silent fail). Maybe we can try making them errors and if it gets crazy we can just make it a warning?

**Comment by jaimehgb** [comment]
+1 to errors over warnings :)

**Comment by tnkrxyz** [comment]
ok, I pushed my my addition in #1955 . pls take a look when you get a chance.

@dmelotik , I didn't add the max-lines-per-function rule, because I couldn't find it in https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin/src/rules and I haven't found a good replacement. Let me know if this is something we want to implement ourselves if no ready rule is available.
