### ISSUE TITLE
Euler-Finance Ethereum - Reflect reward emission change (April 1st)

### ISSUE THREAD

**Issue by tnkrxyz** [messari/subgraphs#1488]
euler changes it reward distribution from epoch 18 (with a 3-month trial period) with the passing of eIP 24: https://snapshot.org/#/eulerdao.eth/proposal/0x7e65ffa930507d9116ebc83663000ade6ff93fc452f437a3e95d755ccc324f93 . Refactor the euler reward emission implementation to reflect this change.

**Comment by tnkrxyz** [comment]
Another eIP relevant is eIP 28 that exclude FTT from eligibility of rewards: https://snapshot.org/#/eulerdao.eth/proposal/0x40874e40bc18ff33a9504a770d5aadfa4ea8241a64bf24a36777cb5acc3b59a7 (effective from epoch 16).

**Comment by dmelotik** [comment]
@tnkrxyz is this something that will need to be updated every x weeks?

**Comment by bye43** [comment]
@jaimehgb

**Comment by tnkrxyz** [comment]
> @tnkrxyz is this something that will need to be updated every x weeks?

Depending on what Euler decides to do after the current trial period. If they keep the current rewards scheme, then no change is needed. If they decide to change again, then we will need to change the subgraph too. Will have to check again in March.

**Comment by dmelotik** [comment]
ACTION: follow up on this, and fix if the data in the subgraph is wrong.
