### ISSUE TITLE
Goldfinch Ethereum: Membership vault and reward & more

### ISSUE THREAD

**Issue by tnkrxyz** [messari/subgraphs#1499]
Goldfinch recently deployed their membership vault that allows users to stake their output token (from senior pool and tranched pools) and GFI token to earn rewards: https://docs.goldfinch.finance/goldfinch/protocol-mechanics/membership

The subgraph in #1298 not yet include this. Will come back to implement this once merged.

**Comment by tnkrxyz** [comment]
Another [open comment from @dmelotik](https://github.com/messari/subgraphs/pull/1298#discussion_r1018210259) re: `updatePosotion()` in helper.ts

https://github.com/tnkrxyz/subgraphs/blob/847f33e3f09faadedaa797734612007f414bcfb3/subgraphs/goldfinch/src/common/helpers.ts#L501-L503

```
  let openPosition = getOpenPosition(account.id, market.id, side);
  if (!openPosition) {
    openPosition = getNewPosition(account.id, market.id, side, event);
```

> Can a user not add onto an existing position? If that is the case this looks good, otherwise there is double counting

**Comment by tnkrxyz** [comment]
More comments/TODOs [from Dylan](https://discord.com/channels/@me/984342328510652416/1050462217012785175):

> openPositionCount = cumulativePositionCount, this is likely not true
> And is there any other identifier we could append to the Market names?

**Comment by dmelotik** [comment]
And Senior Pool rates ✅

**Comment by ishraq8** [comment]
This is resolved here: https://github.com/messari/subgraphs/pull/1536
