### ISSUE TITLE
Burrow QA NEAR

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1510]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=chainscore/burrow&tab=protocol
| Schema Version  |  2.0.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1fbgqf5EWBTlLGkRUTM3U1nHFve3oMn1F/edit?usp=share_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  Revenue

- We have computed the revenue using data from official website and the results show a large discrepancy.
- We only used rewards from Base APY (excluding net liquidity rewards). 
- See 'Support-Implied-Revenue' sheet for more info

| Subgraph - Supply Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 189.66| 353.90 | -164.25| -46.41%| 

| Subgraph - Protocol Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 63.22| 307.10 | -243.88| -79.41%| 

| Subgraph - Daily Total Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 252.88| 661.00 | -408.12| -61.74%| 

- Refer to the sheet 'Protocol'   

### Total Pool Count
- The official website shows only 13 pools as compared to subgraph's data of 14. 

### Pool Overview - TVL and Rewards

- Out of the 14 pools in the subgraph data, only one pool is not shown in the official website. And the pool's name is Meta Token.
- Five out of those 14 pools' TVL data show over a 10% discrepancy with official website data. The pools' names are USD Coin, Tether USD, DAI Stablecoin, Aurora, and USN Stablecoin.
- The BRRR (WNEAR for Burrow's pool)  reward tokens data of the pools are not supposed to be zero as shown in the official website. 
- Refer to the sheet "Pool_Overview" for details

#### USD Coin pool
- Interest percentages are not in line with official website data
- TVL data has a large discrepancy with official website data of about 17%
- Reward APRs and Token Emissions data must not be zero as it is an active pool
- Refer to the sheet "Pool_vault schema" for details

#### Staked Near pool
- Interest percentages are also not in line with official website data
- Reward APRs and Token Emissions data must not be zero as it is an active pool too.
- Refer to the sheet "Pool_vault schema" for details

### Positions
- The data from 'account' column directs you to Ether explorer instead of Near explorer
- The ranking in balance column is not sorted by value. 
- The data from 'hashOpened' and 'borrows' columns directs you to Ether explorer as well and also says error. 
- The hash transaction cannot be found at the account's address Near explorer site, making the data not verifiable.
- Refer to the sheet "Positions" for details

### Editorials  

There are some differences we have noticed and are not necessarily data errors.

#### Events
- There is no data for 'date' column at liquidate transactions section.
- It shows this text 'Invalid date'
- Refer to the sheet "Events" for details

Please refer to the attached worksheet for more details.

**Comment by ishraq8** [comment]
@prasad-kumkar ill take a look at the newer subgraph and compare it to the QA. Thank you.

**Comment by ishraq8** [comment]
@prasad-kumkar Thanks for the updated subgraph, there are a few issues that would be worth taking a second look at from the initial QA:

1) Revenue seems still to be off based on the raw calculations. I am unsure if it is because the front end on Burrow has incorrect TVL, but take a look if possible.
2) Rewards seem to be 0 on the subgraph while Burrow says there are rewards in BRR and wburrow
3) Having 14 pools is not an issue, ignore that comment from the original QA. One of those pools was deprecated.
4) The issues with events and positional data may be a front end issue. This is the first subgraph for NEAR so it may be defaulting to ethereum based subgraphs. Just double check if any of those issues can be resolved on the subgraph level, otherwise I will bring this up with the subgraphs.xyz team.

Let me know if you have any questions or concerns. This was great work and thank you for doing this.

**Comment by ishraq8** [comment]
Double checked, burrow is fine based on data available. I am making a note in the docs that Near subgraphs don't support view function calls so rewards cannot be calculated.

**Comment by dmelotik** [comment]
Thanks @ishraq8, I updated the docs to reflect the no rewards and made notes of no contract calls on near subgraphs. I fixed the things I wanted to resolve and am waiting for it to sync: https://okgraph.xyz/?q=messari%2Fburrow-near

**Comment by ishraq8** [comment]
Perfect, thank you @dmelotik. Appreciate you updating the docs :)

**Comment by dmelotik** [comment]
Merged and synced @ishraq8 / also set off the backfill and hopefully it is up on PM tomorrow

**Comment by ishraq8** [comment]
thank you @dmelotik
