### ISSUE TITLE
Build Morpho Subgraph

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1511]
Morpho: https://www.morpho.xyz/

Notes:
- We want to use the 3.0.1 lending schema. We have a lending sdk [here](https://github.com/messari/subgraphs/tree/master/subgraphs/_reference_/src/sdk/protocols/lending) to help do all of the tedious actions. The developer only needs to make the protocol specific mappings, then they can use the logic hidden in the SDK.
- Compound V3 is an [example](https://github.com/messari/subgraphs/tree/master/subgraphs/compound-v3) of this in action.
- Since Morpho has liquidity in both Morpho and Aave or Compound we want to make sure we capture that nuance. To do that `protocol/market.totalValueLockedUSD` should be the total liquidity in aave/morpho. But then we should have helper fields called `protocol._morphoTotalValueLockedUSD` and `market._morphoTotalValueLockedUSD` to know the difference.
- In addition we probably want positions to have an extra field along the lines of `position._isMorpho`. This should tell someone that the position is in morpho P2P lending or aave.
- Since Morpho separates the protocol into morpho-compound and morpho-aave we should do the same with our subgraphs. This does not require more code, just setting up a new [configuration folder](https://github.com/messari/subgraphs/tree/master/subgraphs/abracadabra/protocols/abracadabra/config/deployments) watching the other contracts.
- Since morpho has aave rates/P2P rates I think we should focus on surfacing the P2P rates. I am even okay with leaving out the rates from aave pools. It actually seems out of the scope of the Morpho subgraph.
- Generally revenue in a lending protocol is going to be the interest borrowers pay. I think revenue in the Morpho subgraph should be the amount of an asset the borrow pays when P2P lending is happening. And if morpho takes a cut that is protocol side revenue.
- A README.md should be added like other protocols that outlines some of the unique things about morpho that are described here.

```[tasklist]
### Deployment QA Status
- [ ] https://github.com/messari/subgraphs/issues/2114
- [ ] https://github.com/messari/subgraphs/issues/2113
```

**Comment by bhor123** [comment]
Hello @bye43 .This is Bhor Sharma, I wanted to contribute for developing the morpho subgraph. Can you please guide me , I was thinking of using the existing aave subgraph but if you have already made some progress please shed some light

**Comment by bye43** [comment]
Hey @bhor123! Thanks for reaching out. I recommend you start by looking at our docs, and the subgraph docs in general. Morpho might be a tricky one to build based on our schemas and the way it works, and we are currently a bit constrained on our end in terms of QA and code review. Thus, at this point in time, we are only accepting contributions from people with extensive experience building subgraphs.

**Comment by bhor123** [comment]
Ok sure @bye43 ,thanks for replying. I am looking at the docs and the schemas in general. It would also be great if I can find a way to communicate with you apart from Github. My email id is bhorshrm@gmail.com.Can you please send a mail so that I can communicate with you later, it would be really helpful :)

**Comment by bhor123** [comment]
Also, it would be great if you can suggest a subgraph that you think might be less trickier to poke around?

**Comment by bhor123** [comment]
can you also suggest a subgraph which you feel might be less trickier. It would be of great help!!

**Comment by bhor123** [comment]
Sure @bye43 ,i have already started looking and am developing some test
subgraphs,will reach out once i have validated that the output data is
correct and subgraph is working fine

**Comment by bye43** [comment]
@julien-devatom Do you have deployment links for morpho-compound and morpho-aave-v2 that you could share here? We will take a look our [dashboard](subgraphs.xyz) to QA the data

**Comment by julien-devatom** [comment]
> @julien-devatom Do you have deployment links for morpho-compound and morpho-aave-v2 that you could share here? We will take a look on our [dashboard](https://subgraphs.messari.io/) to QA the data

Of the contracts or the subgraphs?

**Comment by bye43** [comment]
That should be fine! Just need any deployment link, an example being this [Compound V3 ](https://thegraph.com/hosted-service/subgraph/messari/compound-v2-ethereum). No worries if its just on your own hosted service. We can still start looking at the data if the subgraphs are synced to head.

**Comment by julien-devatom** [comment]
We cannot deploy anymore on the hosted service and we are not exposing our indexer to internet :/ I think that I'll deploy the subgraph to the decentralized network soon

**Comment by jaimehgb** [comment]
Got it deployed here: https://thegraph.com/hosted-service/subgraph/jaimehgb/morpho

Hope you don't mind @julien-devatom :)

**Comment by julien-devatom** [comment]
@jaimehgb ty ser!
