### ISSUE TITLE
Create PR / Issue templates

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1513]
Create templates.

For PRs we also probably want to include a first-time builder checklist:
- subgraph is in deployment.json
- subgraph builds with messari-cli
- actions pass?
- subgraph.yaml is generated via template
- etc.

**Comment by dmelotik** [comment]
The graph has a nice interface here: https://github.com/graphprotocol/graph-cli/issues/new/choose

**Comment by jaimehgb** [comment]
That’s pretty cool actually
