### ISSUE TITLE
Honeyswap Gnosis: TVL and fee issues

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1514]
Honeyswap gave the following feedback:
```
Solarmkd, [Dec 12, 2022 at 2:05:48 AM]:
Fees are 0.3% and not like it says 3% on Messari.
Maybe you can check and report that to your team.
Tvl is also higher , for reference you can check https://info.honeyswap.org/
```

**Comment by bye43** [comment]
@ishraq8 will let you take over here, but @steegecs looks like the difference in TVL is from mispricing or token blacklisting for certain pools. Example - `0xeba7cc57e6f745b8d5cab829e07346c65393d78e` on [honeyswap UI ](https://info.honeyswap.org/#/pair/0xeba7cc57e6f745b8d5cab829e07346c65393d78e) is 204k and [subgraph i](https://api.thegraph.com/subgraphs/name/messari/honeyswap-gnosis/graphql?query=%7B%0A++liquidityPool+%28id%3A+%220xeba7cc57e6f745b8d5cab829e07346c65393d78e%22%29+%7B%0A++++totalValueLockedUSD%0A++%7D%0A%7D) is reporting 102K.

**Comment by steegecs** [comment]
Working on this now!

**Comment by steegecs** [comment]
Backfilled.

**Comment by ishraq8** [comment]
Thank you @steegecs

**Comment by bye43** [comment]
@steegecs if updating fee %

**Comment by ishraq8** [comment]
PR:  https://github.com/messari/subgraphs/pull/1589
