### ISSUE TITLE
How to deploy subgraphs to a particular service using Messari CLI

### ISSUE THREAD

**Issue by Genesis3800** [messari/subgraphs#1518]
Hey guys,
I don't have a particular issue to propose, but this seems to be the best place to post this question. 
I really like what you guys have built. The Messari CLI is especially great. I have figured out how to build my own subgraphs using this repo and the corresponding CLI, but I was wondering if it is possible to deploy my subgraphs to a particular subgraph hosting service from within the CLI?

**Comment by steegecs** [comment]
Hi @Genesis3800, My apologies for taking so long to get back on this. Yes, you can do this. You must add an entry for your subgraph into the deployment.json, and then add the `-d` flag at the end of your build command to deploy. It will then walk you through the service selection, and ask for your target (the service account - e.g. `messari`). Have you been able to figure this out yet?

**Comment by dmelotik** [comment]
@Genesis3800 please take a look at these docs for more in depth information on this!

https://github.com/messari/subgraphs/blob/master/docs/TOOLING.md#messari-subgraph-cli

Closing this, but if you have additional questions please feel free to create a new issue! Thanks
