### ISSUE TITLE
Build Maple 2.0 Subgraph 

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1531]
Launched Dec. 14: https://maple.finance/news/maple-2-0-new-smart-contracts-products-and-our-2023-strategy/

**Comment by bye43** [comment]
@jaimehgb

**Comment by ishraq8** [comment]
@dmelotik QA for maple 2.0 passed.

TLDR: Hard to find accurate visual data. Compared deposits and withdrwals from the contract addresses and they match the subgraph.

Great work!
