### ISSUE TITLE
Build Hop Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1555]
```[tasklist]
### Deployment Status
- [ ] https://github.com/messari/subgraphs/issues/1807
- [x] Polygon : https://okgraph.xyz/?q=QmQhux3MYTgebT8HpxJeW9VtvpytByGujQ4umNVm2K5sDY
- [x] Optimism : https://okgraph.xyz/?q=QmWrmex74onLzwk8cK6625jqNW4QUJoC25CL9QfZmxntyW
- [x] Arbitrum : https://okgraph.xyz/?q=QmRkuASsskvysrucvDViRQHEbycKbk89r26BYfEufe7wgr
- [x] Ethereum : https://okgraph.xyz/?q=QmTBvXdRdsUVa257KgnpUTn6qBEYet9KdnNT24CcKv7GV8
```

**Comment by bye43** [comment]
QA for xDAI here: https://github.com/messari/subgraphs/issues/1807

**Comment by itsjerryokolo** [comment]
I messed up the initial PR trying to upgrade messari cli. 
I wasn't sure how to recover it so I created a new one here. Sorry for the inconvenience. 
https://github.com/messari/subgraphs/pull/2127

**Comment by bye43** [comment]
@pietydespises Can you give ETH deployment a quick scan here? Looks like it is fully indexed and check it off if it looks good thanks!

**Comment by pietydespises** [comment]
Hop bridge has an LP component to it no? So why is there zero TVL?

**Comment by itsjerryokolo** [comment]
@pietydespises The pools live on L2.

**Comment by bye43** [comment]
@pietydespises Can you check out the optimism deployment here? I already gave the TVL a quick look and I have some comments below for @itsjerryokolo, but not exactly sure how to compare or what the other metrics sanity looks like:

- [ ] Looks the [deployment ](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmSMrTSSjkY2ZaoXaaaAQEa4EWdWgYKvYMPoJHSEYYWvkF&tab=poolOverview)is missing `sUSD` and `rETH` pools compared to the [HOP UI](https://app.hop.exchange/#/pools?token=ETH)
![Image](https://github.com/messari/subgraphs/assets/107651107/55c7fc15-3fa1-4381-b53a-8803502c43fa)
![Image](https://github.com/messari/subgraphs/assets/107651107/b0fa36aa-b458-4a40-854d-b0b1dd4694ad)

**Comment by itsjerryokolo** [comment]
@pietydespises Those pools were probably added while it was syncing. 
I can add those in a new deployment.

**Comment by pietydespises** [comment]
why does TVE & TVI look the way they do? And yes please add those in a new deployment. Otherwise looks good.

**Comment by itsjerryokolo** [comment]
@pietydespises  Optimism had a regenesis which meant that Pool had millions in liquidity from the first block.

**Comment by bye43** [comment]
@itsjerryokolo OP looks good then once the new deployment syncs w/ the new pools! Thanks

**Comment by bye43** [comment]
@pietydespises could you take a quick look at this - https://okgraph.xyz/?q=QmQhux3MYTgebT8HpxJeW9VtvpytByGujQ4umNVm2K5sDY and check it off on the checklist above or leave comments for jerry below?

**Comment by pietydespises** [comment]
@itsjerryokolo why is TVE zero after 12/08/2021?

**Comment by itsjerryokolo** [comment]
@pietydespises Jamie explained here: https://github.com/messari/subgraphs/issues/1807#issuecomment-1507126409

**Comment by bye43** [comment]
@pietydespises Can you take a look at arbitrum (https://okgraph.xyz/?q=QmRkuASsskvysrucvDViRQHEbycKbk89r26BYfEufe7wgr) when you have the chance?

**Comment by pietydespises** [comment]
looks good!

**Comment by itsjerryokolo** [comment]
@pietydespises @bye43 Is the mainnet one good as well?

**Comment by bye43** [comment]
@pietydespises Ethereum : https://okgraph.xyz/?q=QmTBvXdRdsUVa257KgnpUTn6qBEYet9KdnNT24CcKv7GV8

**Comment by pietydespises** [comment]
Yes looks good as well
