### ISSUE TITLE
Build GMX Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1584]

**Comment by bye43** [comment]
@corerouter

**Comment by bye43** [comment]
@ishraq8 @corerouter has completed GMX on the generic schema. Do you think you could give the metrics a quick scan and when the derivatives schema is merged into master we can move forward with it? PR w/ deployments here: https://github.com/messari/subgraphs/pull/1640

**Comment by ishraq8** [comment]
TY, will wait for sync.

**Comment by corerouter** [comment]
> TY, will wait for sync.

Thanks! The subgraph for GMX avalanche has finished syncing while the subgraph for GMX arbitrum is likely to finish syncing in 2 days.

**Comment by ishraq8** [comment]
Perfect, will check back on monday

**Comment by ishraq8** [comment]
Updated QA passed for both Avalanche and Arbitrum

**Comment by ishraq8** [comment]
on hosted
