### ISSUE TITLE
Generic Schema SDK

### ISSUE THREAD

**Issue by jaimehgb** [messari/subgraphs#1585]
Since we are going to be using the generic schema a bit more often, it will be useful to have a library for it. To make subgraphs made with it easier to review and less prone to reimplementation errors for snapshots and things alike.

Also, to make it easier to add new functionality to the schema and all subgraphs built with it at once.

**Comment by bye43** [comment]
Done w/ PR: https://github.com/messari/subgraphs/pull/1595
