### ISSUE TITLE
#bug; incorrect Pangolin V2 Avalanche fees

### ISSUE THREAD

**Issue by TKYAngus** [messari/subgraphs#1598]
Link to subgraph: https://api.thegraph.com/subgraphs/name/messari/pangolin-avalanche
Example with the liqudityPool id=0xbd918ed441767fe7924e99f6a0e0b568ac1970d9
```json
        "fees": [
          {
            "id": "0xbd918ed441767fe7924e99f6a0e0b568ac1970d9-lp-fee",
            "feePercentage": "0.3",
            "feeType": "FIXED_LP_FEE"
          },
          {
            "id": "0xbd918ed441767fe7924e99f6a0e0b568ac1970d9-protocol-fee",
            "feePercentage": "0",
            "feeType": "FIXED_PROTOCOL_FEE"
          },
          {
            "id": "0xbd918ed441767fe7924e99f6a0e0b568ac1970d9-trading-fee",
            "feePercentage": "0.3",
            "feeType": "FIXED_TRADING_FEE"
          }
        ]
```

However from the doc (https://docs.pangolin.exchange/multichain/avalanche-network/png-token/litepaper#protocol-fees-and-token-buybacks), on Avalanche trader pays a 0.3% fee that is paid out to 
- Liquidity Pools: 0.25% (in accordance with their share in the particular pool)
- PNG staking Pool: 0.0425%
- Pangolin DAO’s treasury: 0.0075%

**Comment by bye43** [comment]
Addressing here on PR: https://github.com/messari/subgraphs/pull/1632
