### ISSUE TITLE
Stargate Finance FANTOM QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1603]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=dhruv-chauhan/stargate-fantom&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1QsFsPossp_8IyoaUjsgg5J1753hWRSJC/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL

- The subgraph TVL data is mathematically in line with Defi Llama from Jan. 6 -9, 2023 (four days). However, in the recent data (Jan. 10, 2023), there is a large discrepancy of -12.93% and 24.10% with Defi Llama data and the official website data respectively.

January 10, 2023:

| Subgraph - TVL | Defi Llama - TVL | Absolute difference | Difference % |
| :---- | :--- | :---  | :---  | 
| 15,675,875.73| 18,003,807.27 | -2,327,931.54| -12.93%| 

| Subgraph - TVL | Official Website - TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 15,675,875.73| 12,631,345.30 | 3,044,530| 24.10%| 

- Refer to the sheet 'Protocol'   

### Pool Overview - TVL and Rewards

- There is only one pool which is USD Coin-LP, and its TVL data has a discrepancy of 19.64% with the official website data.
- The pool's $STG reward percentage data on 'Reward Tokens' column shows a discrepancy with Defi Llama data (0.50% vs 3.16%).
- Refer to the sheet "Pool_Overview" for details

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
@SerenityFund @bye43 
- TVL has been fixed and now matches the official website data. 
- The subgraph tracks emission amounts, not reward APR which is a calculated metric. Reward emissions in our subgraph is correct.
- Reward APR on the QA dashboard is calculated as [`(daily reward emissions)/(TVL) * 356 * 100`]. There is however one caveat. 
  - Reward APR on the website and Defilama are calculated on the `pool's liquidity locked in farming contract` and not the `total liquidity of pool (=TVL)`.
  - Another thing, specific to fantom, that I noticed is that our estmation of #blocks per day is much more acurate to the [actual number](https://ftmscan.com/chart/blocks). Stargate and Defilama however assume a constant [block rate](https://github.com/DefiLlama/yield-server/blob/9ede1b911c76e40faf60467915f47aa54126614c/src/adaptors/stargate/index.js#L131-L148).

The math,
```
poolID = [0](https://ftmscan.com/address/0x12edeA9cd262006cC3C4E77c90d2CD2DD4b1eb97)
allocPoint = 10000
totalAllocPoint = 10000
stargatePerBlock = 14000000000000000 (18 decimals)

stargatePerBlockForPool = stargatePerBlock.mul(allocPoint).div(totalAllocPoint);
    = 14000000000000000

TVL = [12669298](https://ftmscan.com/address/0x12edeA9cd262006cC3C4E77c90d2CD2DD4b1eb97#readContract#F33)
liquidityInFarm = [5510740](https://ftmscan.com/address/0x224D8Fd7aB6AD4c6eb4611Ce56EF35Dec2277F03#readContract#F4)
```
On subgraph QA dashboard,
```
blocksPerDayActual = [55000](https://ftmscan.com/chart/blocks)
stargatePerBlockForPoolPerDayActual = stargatePerBlockForPool.mul(blocksPerDayActual)
    = 770 x 10^18 [1209]

APY% = ((stargatePerBlockForPoolPerDayActual.mul(365).mul(priceSTG)).div(TVL)).mul(100)
    = ((770 * 365 * 0.46) / 12669298) * 100
    = ~1
```
Actual APY,
```
blocksPerDayActual = [55000](https://ftmscan.com/chart/blocks)
stargatePerBlockForPoolPerDayActual = stargatePerBlockForPool.mul(blocksPerDayActual)
    = 770 x 10^18 [1209]

APYActual% = ((stargatePerBlockForPoolPerDayActual.mul(365).mul(priceSTG)).div(liquidityInFarm)).mul(100)
    = ((770 * 365 * 0.46) / 5510740) * 100
    = ~2.35
```
Assumed APY (on website and defilama),
```
blocksPerDayAssumed = [86400](https://github.com/DefiLlama/yield-server/blob/9ede1b911c76e40faf60467915f47aa54126614c/src/adaptors/stargate/index.js#L131-L148)
stargatePerBlockForPoolPerDayAssumed = stargatePerBlockForPool.mul(blocksPerDayAssumed)
    = 1209 x 10^18

APYAssumed% = ((stargatePerBlockForPoolPerDayAssumed.mul(365).mul(priceSTG)).div(liquidityInFarm)).mul(100)
    = ((1209 * 365 * 0.46) / 5510740) * 100
    = ~3.68
```

**Comment by pietydespises** [comment]
looks good to go! great work!
