### ISSUE TITLE
Stargate Finance MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1604]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=dhruv-chauhan/stargate-mainnet-2&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1XvJL4h7U0TPx7K3LqdX1Qo8-SO8aiZXR/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL

- Although the subgraph TVL data is in line with Defi Llama data in the five recent days, the data from official website of Stargate protocol shows otherwise. There is a high discrepancy of 16.32% with the implied TVL data from the official website.

January 9, 2023:

| Subgraph - TVL | Defi Llama - TVL | Absolute difference | Difference % |
| :---- | :--- | :---  | :---  | 
| 94,869,746.99| 94,938,590.84 | -68,843.85| -0.07%| 

| Subgraph - TVL | Official Website - TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 94,869,746.99| 129,211,073.16 | -21,085,507| -26.58%| 

- Refer to the sheet 'Protocol'   

### Pool Overview - TVL and Rewards

- The TVL data of all pools have discrepancies of ranging from 12% to 203% with the official website data.
- The percentage data on 'Reward Tokens' column have discrepancy with data from the Defi Llama's official website.
- Refer to the sheet "Pool_Overview" for details

#### USD Coin-LP
- TVL data shows a big discrepancy of -35.83% with official website data
- - The reward APR data of the pool is 3.36% which is smaller than the data of Defi Llama which is 2.27%

#### Tether USD-LP
- TVL data shows a massive discrepancy of -23.47% with data from the official website 
- The reward APR data is 4.44% which is lower than Defi Llama's 3.63%

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
@SerenityFund @bye43 
- TVL has been fixed and now matches the official website data. 
- Reward emissions are inline with actual numbers.
- Reward APR on the QA dashboard is calculated field, more detail here:#1603 
Since, for ethereum pools, the total liquidity of bridged asset pools is around the same as their liquidity in farm contract, Reward APR on the QA dashboard is similar to what is reported on the website/defilama. However for more accurate number, `liquidity in farm` shall be used instead of `TVL` while calculating the reward APR.

**Comment by bye43** [comment]
@pietydespises Could you give this a quick scan when you get the chance?

**Comment by bye43** [comment]
@pietydespises Could you give this a quick scan when you get the chance?

**Comment by pietydespises** [comment]
also looks good to go.
