### ISSUE TITLE
#feature; add alpaca fantom

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1625]
**What do you think is missing?**
Alpaca finance fantom deployment

**Describe the solution you'd like**
new subgraph

**Additional context**
Find contract links here: https://docs.alpacafinance.org/our-protocol-1/transparency#relevant-contract-addresses

If there is no additional logic required this should only take a few hours of eng time

**Comment by bye43** [comment]
@ishraq8 can you take a quick look at this too when it merges / is synced to head

**Comment by ishraq8** [comment]
@tnkrxyz This is well done. 1 comment and 1 issue
Comment: The TVL is different from DefiLama and front end of alpaca, but if you calculate the deposits to value, the subgraph is actually accurate. Good work

Issue: The interest rates seem to be very high in the 4 pools could you double check. attached are images of the front end and ALPACA as an example. 

<img width="487" alt="Screen Shot 2023-01-24 at 10 37 17 AM" src="https://user-images.githubusercontent.com/47088402/214338771-1ffc21d8-167b-4c23-a37f-d9caeffcdd33.png">

<img width="1160" alt="Screen Shot 2023-01-24 at 10 37 45 AM" src="https://user-images.githubusercontent.com/47088402/214338801-6b59ce36-cd87-4c37-9942-f2944f6dc95b.png">

**Comment by tnkrxyz** [comment]
@ishraq8 , thanks for the QA! The interest rates are probably due to number of blocks disrepancy we ran into before. Looking into it.
