### ISSUE TITLE
UniswapV2 Indexing failed

### ISSUE THREAD

**Issue by astr0cyph3r** [messari/subgraphs#1655]
Indexing failed

https://okgraph.xyz/?q=messari%2Funiswap-v2-ethereum

![image](https://user-images.githubusercontent.com/91176571/215507489-093ede1a-4fde-4b8d-869e-53faec459a4c.png)
.

**Comment by bye43** [comment]
Going to redeploy from the beginning. @jaimehgb to redeploy

**Comment by jaimehgb** [comment]
Done!
