### ISSUE TITLE
#bug; introduction of block param to price getters in prices-lib breaks subgraph sdk

### ISSUE THREAD

**Issue by fortysevenlabs** [messari/subgraphs#1694]
**Describe the bug**
The addition of `block` param breaks (in this https://github.com/messari/subgraphs/commit/9b4b172cd2ea3990f2247e54a23734f504303d41) breaks `Pricer`, `TokenPricer` in the sdk.

**Reproduction**
Run `messari build` in any of the protocols that use the `sdk`.

**Expected behavior**
Update the `TokenPricer` interface and add documentation for how to use `Pricer` for bridge sdk.

**Comment by fortysevenlabs** [comment]
@harsh9200 @jaimehgb fyi

**Comment by bye43** [comment]
Issue related: https://github.com/messari/subgraphs/issues/1696

**Comment by jaimehgb** [comment]
@harsh9200 is it possible to make the block optional so it doesn’t break old subgraphs when upgrading the price lib version?

**Comment by harsh9200** [comment]
@jaimehgb yeah, that is feasible. I will do that.
