### ISSUE TITLE
MakerDao Ethereum: ETH-A and ETH-B TVLs are wrong

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1695]
**Describe the bug**
Eth-A and Eth-B TVL are off, looks like `inputtokenbalances` are off.

**Reproduction**

Following Vaults are the issue:
ETH-A: 0x2f0b23f53734252bda2277357e97e1517d6b042a
ETH-B: 0x08638ef1a205be6762a8b935f5da9b700cf7322c
![Screen Shot 2023-02-06 at 11 18 46 AM](https://user-images.githubusercontent.com/47088402/217025977-e01b0c2b-9bf4-4de2-90c2-be09f4f9f494.png)

![Screen Shot 2023-02-06 at 11 20 59 AM](https://user-images.githubusercontent.com/47088402/217026632-6400079c-4558-49d2-8d9e-42617e41b94f.png)

![Screen Shot 2023-02-06 at 11 21 56 AM](https://user-images.githubusercontent.com/47088402/217026644-65e1ecb5-f70f-44ac-bae6-d66f502be033.png)

**Expected behavior**
This may be a input balance issue or pricing issue on weth. double check. Doesn't match onchain.

**Additional context**
Everything in MakerDAO is accurate except this.

**Comment by bye43** [comment]
@tnkrxyz This is weird. [Looks](https://api.thegraph.com/subgraphs/name/messari/makerdao-ethereum/graphql?query=%7B%0A++markets+%28where%3A+%7Bid_in%3A+%5B%220x2f0b23f53734252bda2277357e97e1517d6b042a%22%2C%220x08638ef1a205be6762a8b935f5da9b700cf7322c%22%5D%7D%29+%7B%0A++++name%0A++++id%0A++++inputTokenBalance%0A++++inputTokenPriceUSD%0A++%7D%0A%7D) like the `inputTokenBalance` is off for both ETH A and B.[ ETH A etherscan](https://etherscan.io/address/0x2f0b23f53734252bda2277357e97e1517d6b042a) and [ETH B etherscan](https://etherscan.io/address/0x08638ef1a205be6762a8b935f5da9b700cf7322c)

**Comment by tnkrxyz** [comment]
that's odd. looking into this.

**Comment by tnkrxyz** [comment]
@bye43 , @ishraq8 , sorry this take a long while to figure out/fix. I believe I figured out the issue and have a fix #1717 if verified working.

**Comment by ishraq8** [comment]
Fix is working, will close once merged and backfilled
