### ISSUE TITLE
Optimism Gateaway - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1700]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmayRkPM3wyaTJEzJXNRb5E8Pt53m4Ytk8dSAeBPsgmQhg&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1lyrlXGcY9_MXgHYjCA8yunNJ21sMm3SN/edit?usp=share_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL

- The TVL subgraph data is not mathematically aligned with Dune Analytics data as it shows a 5-day average discrepancy of -45.45%. This is probably due to some large pools missing in the subgraph. For example, the OP token pool which currently has a TVL of about $693 million, is missing from the subgraph data.

February 6, 2023:

| Subgraph - 5-day average TVL | Dune Analytics - 5-day average TVL | Absolute difference | Difference % |
| :---- | :--- | :---  | :---  | 
| 1,246,131,990.32| 2,284,425,000.00 | -1,038,293,009.68| -45.45%| 

- Refer to the sheet 'Protocol'   

### Total Pool Count and Total Supported Token Count

- The official website only shows 100 pools/supported tokens, while the subgraph data has 124 pools.
- Refer to the sheet 'Protocol'   

### Pool Overview - TVL 

- Out of the subgraph's top 10 pools by TVL, only three have shown large discrepancies with the Dune Analytics data, and these pool tokens are DAI, sUSD, and SNX.
- Three of the top 10 pools in the Dune Analytics dashboard by TVL are not shown in the subgraph data. It includes OP, KWENTA, and VELO which have TVL USD amounts of 692.87m, 86.35m, and 61.82m.
- This explains why there is a large discrepancy in the overall TVL of subgraph data compared to Dune Analytics data.
- Refer to the sheet "Pool_Overview" for detail

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@spitko QA for OP gateway here!

**Comment by spitko** [comment]
Thanks for the QA, a few comments below:

> ### TVL
> * The TVL subgraph data is not mathematically aligned with Dune Analytics data as it shows a 5-day average discrepancy of -45.45%. This is probably due to some large pools missing in the subgraph. For example, the OP token pool which currently has a TVL of about $693 million, is missing from the subgraph data.
> 
> February 6, 2023:
> 
> Subgraph - 5-day average TVL	Dune Analytics - 5-day average TVL	Absolute difference	Difference %
> 1,246,131,990.32	2,284,425,000.00	-1,038,293,009.68	-45.45%
> * Refer to the sheet 'Protocol'

The Dune Analytics chart is for total Optimism on-chain value while the subgraph TVL only counts the value of tokens locked in escrow on Ethereum mainnet.

There is no OP token pool, because OP is a native L2 token and does not exist on mainnet.

> ### Total Pool Count and Total Supported Token Count
> * The official website only shows 100 pools/supported tokens, while the subgraph data has 124 pools.
> * Refer to the sheet 'Protocol'

The official website is just a convenience, tokens can be bridged also without using the website. The subgraph counts all unique tokens bridged as separate pools.

> ### Pool Overview - TVL
> * Out of the subgraph's top 10 pools by TVL, only three have shown large discrepancies with the Dune Analytics data, and these pool tokens are DAI, sUSD, and SNX.
> * Three of the top 10 pools in the Dune Analytics dashboard by TVL are not shown in the subgraph data. It includes OP, KWENTA, and VELO which have TVL USD amounts of 692.87m, 86.35m, and 61.82m.
> * This explains why there is a large discrepancy in the overall TVL of subgraph data compared to Dune Analytics data.
> * Refer to the sheet "Pool_Overview" for detail

OP, KWENTA and VELO are all native Optimism tokens and cannot be bridged through Optimism Gateway.

**Comment by bye43** [comment]
@pietydespises Could you take a look at this when you get the chance?

**Comment by bye43** [comment]
@pietydespises Also if the above is fine, can you give the [OP deployment](https://okgraph.xyz/?q=spitko%2Foptimism-gateway-optimism) a quick one over and then we can mark this as `prod`?

**Comment by pietydespises** [comment]
Agreeing with @spitko here, this looks good to go.
