### ISSUE TITLE
UniSwap TVL

### ISSUE THREAD

**Issue by CedricVo91** [messari/subgraphs#1709]
hey guy, 

I tried to get the tvl for uniswap but using the query below I get a way too large number i.e. "totalValueLockedUSD": "3416999981000001023430901.940636953". 

What is the reason for that?
Thanks a lot

`
{
  protocol(id: "0x1f98431c8ad98523631ae4a59f267346ea31f984") {
    cumulativeProtocolSideRevenueUSD
    cumulativeSupplySideRevenueUSD
    cumulativeTotalRevenueUSD
    cumulativeUniqueUsers
    subgraphVersion
    totalPoolCount
    name
    totalValueLockedUSD
  }
}

`

**Comment by bye43** [comment]
Hey @CedricVo91! Are you querying the decentralized network deployment? There was a bug in that subgraph and we have to re-deploy it to the decentralized network still. If you query the[ hosted service deployment ](https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-ethereum), you should get the right TVL. Here's the query - https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-ethereum/graphql?query=%7B%0A%09protocol%28id%3A+%220x1f98431c8ad98523631ae4a59f267346ea31f984%22%29+%7B%0A%09%09cumulativeProtocolSideRevenueUSD%0A%09%09cumulativeSupplySideRevenueUSD%0A%09%09cumulativeTotalRevenueUSD%0A%09%09cumulativeUniqueUsers%0A%09%09subgraphVersion%0A%09%09totalPoolCount%0A%09%09name%0A%09%09totalValueLockedUSD%0A%09%7D%0A%7D%0A%0A
