### ISSUE TITLE
Build Across V2 Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1711]
```[tasklist]
### Deployments QA Status
- [ ] https://github.com/messari/subgraphs/issues/2165
- [x] Arb: https://thegraph.com/hosted-service/subgraph/fortysevenlabs/across-v2-arbitrum
- [x] OP: https://thegraph.com/hosted-service/subgraph/fortysevenlabs/across-v2-optimism
- [x] Polygon: https://thegraph.com/hosted-service/subgraph/fortysevenlabs/across-v2-polygon
- [x] Boba: https://thegraph.com/hosted-service/subgraph/fortysevenlabs/across-v2-boba
```

**Comment by bye43** [comment]
@fortysevenlabs

**Comment by bhor123** [comment]
Hello @fortysevenlabs,This is Bhor, I am a web3 enthusiast and Dapp developer and i wanted to work with you for developing Across V2 subgraph. I have prior experience developing some test subgraphs and would love to contribute and learn with the amazing team at Messari. Please feel free to reach out to me , I have already studied the schema and would like to be as much help as possible. My email is bhorsharma560@gmail.com and discord is Bhor sharma#7534.

**Comment by pietydespises** [comment]
@fortysevenlabs how is this going?

**Comment by pietydespises** [comment]
Arbitrum: good
Optimism: good
Matic: good
Boba: probably correct, but looks weird due to extremely low use. I suggest we hide this.
