### ISSUE TITLE
Uniswap-V3 Arbitrum, Polygon: TVL spiking

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1712]
### Polygon
![uniswap-v3-polygon-020823](https://user-images.githubusercontent.com/107651107/217642722-e41a9deb-710e-456e-8603-bdc6abb88534.jpeg)

### Arbitrum
![uniswap-v3-arbitrum-020823](https://user-images.githubusercontent.com/107651107/217642730-e9d8260a-4971-4438-b066-a5ebd983e286.jpeg)

**Comment by bye43** [comment]
@steegecs Same here, is this still an issue?

**Comment by steegecs** [comment]
Have a fix that is currently indexing for both of these: 

https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/id/Qmcb9BcWwzGwqCWAdjF81DgR2Gspuc88UMYuf3sZtau7gi&tab=protocol&version=pending&name=steegecs/uniswap-v3-arbitrum

https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/id/QmTqLYAWWUKhgv4cR9fCtp2MTLFe1AynpiXr9CCWcRMTfS&tab=protocol&version=pending&name=steegecs/uniswap-v3-polygon

**Comment by steegecs** [comment]
These have been fixed!
