### ISSUE TITLE
Ribbon Finance - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1727]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/shashwats22/ribbon-finance-generic
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1Vzwda42SjpB5oEUt39qhGBZli8R1U3NH/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview - TVL

- The TVL data of the three out of the 13 pools show large discrepancies of more than 20% with the official website data. 
- These pools are the top 7, 11, and 12 pools, namely Ribbon Aave Theta Vault, Ribbon ETH Theta Vault (V1), and Ribbon BTC Theta Vault (V1).
- Ribbon ETH Theta Vault (V1), and Ribbon BTC Theta Vault (V1) pools are inactive pools.

| Subgraph - Ribbon Aave Theta Vault TVL |Ribbon Aave Theta Vault - Official Website TVL| Absolute Difference |% Difference | Vault Address (Etherscan)
| :---- | :--- | :---  | :---  | :---  |
|$3,030,448.69| $2,432,846 | -1,410.10|24.56% | 0xe63151a0ed4e5fafdc951d877102cf0977abd365

| Subgraph - Ribbon ETH Theta Vault (V1 & Inactive) |Ribbon ETH Theta Vault (V1 & Inactive) - Official Website TVL| Absolute Difference |% Difference | Vault Address (Etherscan)
| :---- | :--- | :---  | :---  | :---  |
|$194,018| $256,286.99 | -604.33|-24.30% | 0x0fabaf48bbf864a3947bdd0ba9d764791a60467a

| Subgraph - Ribbon BTC Theta Vault (V1 & Inactive) |Ribbon BTC Theta Vault (V1 & Inactive) - Official Website TVL| Absolute Difference |% Difference | Vault Address (Etherscan)
| :---- | :--- | :---  | :---  | :---  | 
| $55,385.57 | $76,328.88 | -2,006.46 |-27.44% | 0x8b5876f5b0bf64056a89aa7e97511644758c3e8c

- Refer to the 'Pool Overview' sheet

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@shashwatS22 Here is the QA for ribbon. The pricing looks slightly off for the vaults above, which is probably why the TVL is slightly off. Here is my query - https://api.thegraph.com/subgraphs/name/shashwats22/ribbon-finance-generic/graphql?query=%7B%0A++vaults+%28where%3A%7Bid_in%3A+%5B%220x8b5876f5b0bf64056a89aa7e97511644758c3e8c%22%2C+%220x0fabaf48bbf864a3947bdd0ba9d764791a60467a%22%2C+%220xe63151a0ed4e5fafdc951d877102cf0977abd365%22%5D%7D%29+%7B%0A++++name%0A++++id%0A++++inputToken+%7B%0A++++++name%0A++++++id%0A++++++lastPriceUSD%0A++++%7D%0A++%7D%0A%7D

**Comment by bye43** [comment]
@dmelotik Just checked the latest version of this and it is good to go. Can we deploy Mainnet and Avax to the Messari hosted?
