### ISSUE TITLE
Deposits on the UniSwap v3 Messari Subgraph (https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-ethereum) 

### ISSUE THREAD

**Issue by CedricVo91** [messari/subgraphs#1734]
Hey guys,

I tried to query the 1000 latest mint transactions on Uniswap using the query below.
Using "deposits", I did not get the full picture of the mint transactions. 
For example: using the following transaction 0x69cd4a4d56e20385de9cde7e9f9a262d274855657e20b5971ecd2c701b4e8bd0 I get the following results: 
- From: 0xc36442b4a4522e871399cd717abdd847ab11fe88
- To: 0xcbcdf9626bc03e24f779434178a73a0b4bad62ed

However, both seem to be liquidity pools (correct me if I'm wrong here) when inspecting the transaction, and it misses the id of the address who deposited the liquidity (e.g. LPs.)
How can I get all the mint transactions and possibly some more information regarding the liquidity tokens that these LPs received?

Thanks a lot!
``````{
  deposits(first: 1000, orderBy: timestamp, orderDirection: desc) {
    amountUSD
    blockNumber
    from
    to
    hash
    inputTokenAmounts
    inputTokens {
      decimals
      lastPriceUSD
      name
      symbol
    }
    timestamp
    pool {
      inputTokenBalances
      name
      symbol
      createdTimestamp
      id
    }
  }}
``````

**Comment by bye43** [comment]
@CedricVo91 This is because we used the owner parameter, which was laid out as the owner of the position in the docs, but it turns out it is the NFT manager every time. There is a fix for this in a new subgraph that is indexing. Will let you know when this is up!

**Comment by steegecs** [comment]
Hi @CedricVo91, thank you again for addressing this issue with us. Our subgraph at this endpoint (messari/uniswap-v3-etheruem) now has this issue fixed, and soon the rest as well!
