### ISSUE TITLE
#bug; Incorrect Iron Bank borrow/supply interest rate APY on Avalanche chain and Optimism chain

### ISSUE THREAD

**Issue by TKYAngus** [messari/subgraphs#1746]
### Background
In current mapping we calculate borrow interest rate using `convertRatePerUnitToAPY()`, in which:
- ratePerUnit: cTokenContract.borrowRatePerBlock()
- unitPerYear: NetworkSpecificConstant.unitPerYear, i.e. SECONDS_PER_YEAR / 2 = 15,768,000 for Avalanche

At the first glance the calculation looks correct as in `CToken.accrueInterest()` Iron Bank accrues interest according to delta in block number (`blockDelta`).

Take cToken 0xb3c68d69E95B095ab4b33B4cB67dBc0fbF3Edf56 (iWAVAX) [accrueInterest()](https://snowtrace.io/address/0xb3c68d69E95B095ab4b33B4cB67dBc0fbF3Edf56#code#F1#L323) as example:
```solidity
    function accrueInterest() public returns (uint256) {
        /* Remember the initial block number */
        uint256 currentBlockNumber = getBlockNumber();
        uint256 accrualBlockNumberPrior = accrualBlockNumber;
      
       ...

        /* Calculate the number of blocks elapsed since the last accrual */
        uint256 blockDelta = sub_(currentBlockNumber, accrualBlockNumberPrior);

        /*
         * Calculate the interest accumulated into borrows and reserves and the new index:
         *  simpleInterestFactor = borrowRate * blockDelta
         *  interestAccumulated = simpleInterestFactor * totalBorrows
         *  totalBorrowsNew = interestAccumulated + totalBorrows
         *  totalReservesNew = interestAccumulated * reserveFactor + totalReserves
         *  borrowIndexNew = simpleInterestFactor * borrowIndex + borrowIndex
         */

        Exp memory simpleInterestFactor = mul_(Exp({mantissa: borrowRateMantissa}), blockDelta);
        uint256 interestAccumulated = mul_ScalarTruncate(simpleInterestFactor, borrowsPrior);
        uint256 totalBorrowsNew = add_(interestAccumulated, borrowsPrior);
        uint256 totalReservesNew = mul_ScalarTruncateAddUInt(
            Exp({mantissa: reserveFactorMantissa}),
            interestAccumulated,
            reservesPrior
        );
        uint256 borrowIndexNew = mul_ScalarTruncateAddUInt(simpleInterestFactor, borrowIndexPrior, borrowIndexPrior);
      
       ...

    }
```
### Issue
However if we look into details of [getBlockNumber()](https://snowtrace.io/address/0xb3c68d69E95B095ab4b33B4cB67dBc0fbF3Edf56#code#F1#L158), surprisingly it returns `block.timestamp` instead of `block.number`:
```solidity
    function getBlockNumber() internal view returns (uint256) {
        return block.timestamp;
    }
```

That means Iron Bank actually accrues interest **by second** instead of by block on Avalanche chain, i.e. the projected borrow/supply rate APY shown in subgraph is half of the actual value.

### Fix Suggestion
To fix this we should use SECONDS_PER_YEAR as unitPerYear for Avalanche chain in calculating borrow/supply rate APY.

### Other Notes
On Fantom and Optimism chain the implementation of `getBlockNumber()` also returns `block.timestamp`. Optimism chain is also impacted but not Fantom (as Fantom is set with 1 block per second)

On Ethereum chain the implementation returns `block.number` instead. As long as ETHEREUM_BLOCKS_PER_YEAR (13 seconds per block) is correct the estimation should be fine.

### Relevant Link
IronBank cToken list on Avalanche: https://docs.ib.xyz/v/avalanche/lending-market/itoken
IronBank cToken list on Optimism: https://docs.ib.xyz/v/optimism/lending-market/itoken-address

**Comment by bye43** [comment]
@TKYAngus Good catch! @tnkrxyz Harsh and I just found a similar error for Curve OP seems like its because blocks on OP are not at a specific time - https://community.optimism.io/docs/developers/build/differences/#block-production-is-not-constant

**Comment by tnkrxyz** [comment]
Indeed, good catch & thanks for the thorough issue! We ran into this similar issue with other subgraphs, but haven't got to fix it for Iron Bank yet. Will push a fix soon.

**Comment by ishraq8** [comment]
resolved pulled and backfilled.
