### ISSUE TITLE
Monitor Detected Issue rocket-pool (TEST)

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1752]
Posting an issue through the Github API to test for implementation. Please ignore Indexing errors on rocket-pool

ethereum: https://okgraph.xyz/?q=messari%2Frocket-pool-ethereum

**Comment by bye43** [comment]
Indexing Error Description:
Indexing errors on rocket-pool
ethereum: https://okgraph.xyz/?q=messari%2Frocket-pool-ethereum

Protocol Error Description:
Protocol Errors on notional-finance
ethereum: https://subgraphs.messari.io/subgraph?endpoint=messari/notional-finance-ethereum&tab=protocol

Field: cumulativeTotalRevenueUSD
Value: $1,668,275.64 != $0.00 + $1,334,620.51
Description: lendingProtocol entity has a cumulativeTotalRevenueUSD that is not within $1000 of the value of cumulativeProtocolSideRevenueUSD + cumulativeSupplySideRevenueUSD
