### ISSUE TITLE
Optimism Gateway - OPTIMISIM QA

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#1753]
Can you take a look at the Optimism side for the Optimism Gateway? TVL looks broken (showing 0 values everywhere) @spitko https://okgraph.xyz/?q=spitko%2Foptimism-gateway-optimism

**Comment by spitko** [comment]
> Can you take a look at the Optimism side for the Optimism Gateway? TVL looks broken (showing 0 values everywhere) @spitko https://okgraph.xyz/?q=spitko%2Foptimism-gateway-optimism
> 
> 

I left the TVL as 0 on purpose as the Optimism side contract does not hold any funds, tokens are locked on Ethereum side.
