### ISSUE TITLE
[notional-finance-ethereum]: Protocol Error [cumulativeTotalRevenueUSD] (MONITOR)

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1755]
Field: cumulativeTotalRevenueUSD
Value: $1,670,084.69 != $0.00 + $1,336,067.75
Description: lendingProtocol entity has a cumulativeTotalRevenueUSD that is not within $1000 of the value of cumulativeProtocolSideRevenueUSD + cumulativeSupplySideRevenueUSD

**Comment by bye43** [comment]
Existing issue alr out. This was used for monitor bot testing
