### ISSUE TITLE
[alpaca-finance-lending-fantom]: Protocol Error [totalBorrowBalanceUSD] (MONITOR)

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1756]
Field: totalBorrowBalanceUSD
Value: $21,113,652.47
Description: lendingProtocol entity has a lower totalDepositBalanceUSD than totalBorrowBalanceUSD.

**Comment by bye43** [comment]
Existing issue alr out. This was used for monitor bot testing
