### ISSUE TITLE
#bug; Uniswap v3 liquidity pools missing input tokens

### ISSUE THREAD

**Issue by daniel-finnan** [messari/subgraphs#1763]
**Describe the bug**
The following liquidity pools only have one input token symbol:

```
Uniswap V3 /Wrapped Ether 0.3%
0xe8c6c9227491c0a8156a0106a0204d881bb7e531
Uniswap V3  (Wormhole)/USD Coin 0.01%
0x537a0a5654045c52ec45c4c86ed0c1ffe893809d
Uniswap V3 /Wrapped Ether 0.3%
0xcdff6ddfc9e4807c9927fd58708c2ef3484cc305
Uniswap V3 /Wrapped Ether 1%
0x3afdc5e6dfc0b0a507a8e023c9dce2cafc310316
Uniswap V3 /Wrapped Ether 0.05%
0x886072a44bdd944495eff38ace8ce75c1eacdaf6
Uniswap V3  (Wormhole)/Tether USD 0.01%
0xe1d74c16203f87644584a1ad3ac34c4f1e8f7e1e
Uniswap V3 /Tribe 0.05%
0xe83bad50c0b3f58ded74ecd67f001337e319075f
Uniswap V3 /USD Coin 1%
0xc486ad2764d55c7dc033487d634195d6e4a6917e
Uniswap V3  (Wormhole)/Dai Stablecoin 0.01%
0x76138d5acbb1edd2c39989775107b0ec9866fa3c
Uniswap V3 /Wrapped Ether 0.3%
0x75a63a58bcd7ddf799462fb50264974c5c6239cb
Uniswap V3 /Tether USD 0.3%
0x628e2d0a150779b649810056e931d2eadcd4db5b
Uniswap V3 /Wrapped Ether 0.3%
0xc75ba9831e713666e2ba1d11952c95011c961573
Uniswap V3 /Wrapped Ether 1%
0x64f701f93cfbe2cc5d4886f1a514eb1ac02543eb
Uniswap V3 /USD Coin 0.3%
0x0f9d9d1cce530c91f075455efef2d9386375df3d
Uniswap V3  (Wormhole)/USD Coin 0.3%
0xd73b43c9271d0c02a6bbda814017685448ff36e5
Uniswap V3 /Tether USD 1%
0xb5f8d230523c4bdcd00603ee354921441fde39b4
Uniswap V3 /Tether USD 0.3%
0x5cccad2332292cd5882365bb3584424241ab2210
Uniswap V3 /Tether USD 1%
0xf74a97cc57f1691b4df364264df742e81b4c7754
Uniswap V3 /Wrapped Ether 0.05%
0xeb2423fbeb5d94cd83136a74341a39a2487fb3cb
Uniswap V3 /Wrapped Ether 1%
0x3d3a645a4edd9cce81ff15941042d6f08f9b053f
Uniswap V3 /Tether USD 0.3%
0x2afeeadc34dc95b194f3d8d22b912a983640e082
Uniswap V3  (Wormhole)/Tether USD 0.3%
0x1f6423a6ed9e9cbaa34e924d34d9fbd952f9de16
Uniswap V3 /Wrapped Ether 0.3%
0x11c633c532cedd178ba09708b8e377cd6e58d767
Uniswap V3 /Tether USD 0.05%
0x0cbe2f86e2fd90040ebb557b99f83400bf8f3717
Uniswap V3  (Wormhole)/Tether USD 1%
0x9963536672d5037b986a4cbe00780b1937f79e91
Uniswap V3 /Wrapped Ether 1%
0x98f8b8968612463e011beb3127a0980aa3e2b0a7
Uniswap V3 /USD Coin 0.05%
0x936198fcac6d8cdec3815f24ba250041f593f6c3
Uniswap V3 /Wrapped Ether 0.05%
0x919d9fb4f00089bda65dff6c90cb78552ee4c19d
Uniswap V3 /Wrapped Ether 0.3%
0x8f9a0935b26097a1fc15d4919e0b9e466edc1c57
Uniswap V3 /Wrapped Ether 0.3%
0x8ca580042454ddea4f09fe99dcd189cc3464fa63
Uniswap V3 NFT/NFT 0.05%
0xacabefc959a714b6d2061112a4e3f4fcad00d52f
Uniswap V3 /Universe Finance Token 1%
0xaaba8a92687bfdba363a3ccb29991599d84fed8f
```
Here is the raw json from my query:
```
            {
                "__typename": "LiquidityPool",
                "id": "0xcdff6ddfc9e4807c9927fd58708c2ef3484cc305",
                "name": "Uniswap V3 /Wrapped Ether 0.3%",
                "cumulativeVolumeUSD": "39012620.92336277826566512764821941",
                "cumulativeProtocolSideRevenueUSD": "0",
                "cumulativeSupplySideRevenueUSD": "117037.8627700883347969953829446602",
                "cumulativeTotalRevenueUSD": "117037.8627700883347969953829446602",
                "inputTokens": [
                    {
                        "__typename": "Token",
                        "symbol": ""
                    },
                    {
                        "__typename": "Token",
                        "symbol": "WETH"
                    }
                ]
            },
```
Some of these indeed seem to be pools with two different tokens, such as:
```
Uniswap V3 /Wrapped Ether 0.3%
0xcdff6ddfc9e4807c9927fd58708c2ef3484cc305
```
which appears to be [AVT/ETH](https://info.uniswap.org/#/pools/0xcdff6ddfc9e4807c9927fd58708c2ef3484cc305), or this one:
```
Uniswap V3 /Wrapped Ether 0.3%
0xe8c6c9227491c0a8156a0106a0204d881bb7e531
```
which appears to be [MKR/ETH](https://info.uniswap.org/#/pools/0xe8c6c9227491c0a8156a0106a0204d881bb7e531).

Others appear to be a `(Wormhole)` swapping the same tokens, such as:
```
Uniswap V3  (Wormhole)/USD Coin 0.01%
0x537a0a5654045c52ec45c4c86ed0c1ffe893809d
```
which corresponds to [USDC/USDC](https://info.uniswap.org/#/pools/0x537a0a5654045c52ec45c4c86ed0c1ffe893809d).

**Reproduction**
Using the following query:
```
    {
        liquidityPools(
          first: 1000
          orderBy: cumulativeVolumeUSD
          orderDirection: desc
          skip: 10000
        ) {
          id
          name
          cumulativeVolumeUSD
          cumulativeProtocolSideRevenueUSD
          cumulativeSupplySideRevenueUSD
          cumulativeTotalRevenueUSD
          inputTokens {
            symbol
          }
        }
      }
```

[Link to subgraph](https://thegraph.com/explorer/subgraphs/ELUcwgpm14LKPLrBRuVvPvNKHQ9HvwmtKgKSH6123cr7)

**Expected behavior**
Maybe I'm missing something, but I would have expected each liquidity pool to have two input tokens, especially as they do indeed display this via the Uniswap app. Plus, the `(Wormhole)` pools don't make sense to me. What are they, am I missing something about my understanding of Uniswap? Why are some of these pools missing input token symbols?

**Additional context**
I'm trying to query total cumulative volumes of all tokens on Uniswap so these liquidity pools appear rather mysterious! Any help appreciated, many thanks.

**Comment by bye43** [comment]
@daniel-finnan Thanks for the thorough issue. Will let @steegecs speak on this more, since he built the Uniswap subgraphs, but in the mean time you can [query ](https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-ethereum/graphql?query=+%7B%0A++liquidityPools%28where%3A+%7Bid_in%3A+%5B%220xcdff6ddfc9e4807c9927fd58708c2ef3484cc305%22%2C%220xe8c6c9227491c0a8156a0106a0204d881bb7e531%22%2C+%220x537a0a5654045c52ec45c4c86ed0c1ffe893809d%22%5D%7D%29+%7B%0A++++%09id%0A++++++name%0A++++totalValueLockedUSD%0A++++++cumulativeVolumeUSD%0A++++++cumulativeProtocolSideRevenueUSD%0A++++++cumulativeSupplySideRevenueUSD%0A++++++cumulativeTotalRevenueUSD%0A++++++inputTokens+%7B%0A++++++++symbol%0A++++++++id%0A++++++++lastPriceUSD%0A++++%7D%0A++++inputTokenBalances%0A++%7D%0A%7D) the `id` of the `inputTokens` which looks like it is returning for some of the examples you listed above and maps to the token on etherscan. Seems like some of the tokens in the subgraph are just not returning the `symbol` field.

**Comment by daniel-finnan** [comment]
On the `(Wormhole)` part of my issue, cleared up my understanding of what was going on here, e.g.
Token (origin) USDC
Token (target) USDCso(Wormhole)
But the lack of two input tokens on the query result is a little confusing I think.
