### ISSUE TITLE
MakerDAO Ethereum: `protocolSideRevenueUSD` spike into the billions

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1785]
@tnkrxyz Looks like the [MakerDAO deployment ](https://subgraphs.messari.io/subgraph?endpoint=messari/makerdao-ethereum&tab=protocol)with the `inputTokenBalance` fix has `protocolSideRevenueUSD` spiking into the billions on 06/28/2020. [Query](https://api.thegraph.com/subgraphs/name/messari/makerdao-ethereum/graphql?query=%7B%0A++marketDailySnapshots+%28orderBy%3A+dailyProtocolSideRevenueUSD%2C+orderDirection%3A+desc%2C+where%3A+%7Btimestamp_gt%3A+1593302400%2C+timestamp_lt%3A+1593388799%7D%29+%7B%0A++++market+%7B%0A++++++name%0A++++++id%0A++++%7D%0A++++dailyProtocolSideRevenueUSD%0A++%7D%0A%7D) is showing very high revenue for these three vaults: ETH-A, ZRX-A , KNC-A. 
![download-41](https://user-images.githubusercontent.com/107651107/220495073-75ac383b-b90c-47c9-8a64-deacf17beff0.jpg)

**Comment by tnkrxyz** [comment]
Oops, looking into this.
