### ISSUE TITLE
Portal - Wormhole - FANTOM

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1791]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=dhruv-chauhan/portal-fantom-2&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1eKg4WXYHHbiD1GjxO3rMb1HJL23vUpXI/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Total Pool Count and Total Supported Token Count

Portal Bridge website only shows 5 tokens/pools instead of Subgraph's 221.

### Pool Overview - TVL

- Only five tokens/pools are shown in the Portal Bridge website. 
- These five tokens are WFTM, USDC, BTC, ETH, and DAI.
- WFTM pool has a discrepancy of -19.27% with the Portal Bridge website. However, this maybe due to the unavailability of wormhole-wrapped token prices.

| Subgraph - Wrapped Fantom TVL | Portal Bridge Website - Wrapped Fantom TVL | Difference % 
| :---- | :--- | :---  | 
| $1,614,618.98| $2,000,000.00 | -19.27%| 

- USDC pool shows a large discrepancy of -79.76% with the Portal Bridge website. USDC's price usually ranges from $0.99 - $1.01, so the discrepancy should not be this much.

| Subgraph - USD Coin TVL | Portal Bridge Website - USD Coin TVL | Difference % 
| :---- | :--- | :---  | 
| $156,676.18| $774,000.00 | -79.76%| 

- Refer to the sheet "Pool_Overview" for details

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@dhruv-chauhan QA for portal FTM. Looks like another pricing issue, but can you quickly check out? This will be the last in depth QA for portal, and will have @pietydespises give the rest of the deployments a quick look over before moving everything to prod.
