### ISSUE TITLE
Build Gains Network Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1793]
```[tasklist]
### Deployment Status
- [ ] Polygon: https://okgraph.xyz/?q=dhruv-chauhan%2Fgains-trade-polygon-121
- [ ] https://github.com/messari/subgraphs/issues/2005

**Comment by bye43** [comment]
@dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
PR #1972 ready for review! @bye43

**Comment by ishraq8** [comment]
approved QA in other issue

**Comment by ishraq8** [comment]
upgrade needs to be added to hosted: https://github.com/messari/subgraphs/pull/2104

**Comment by dmelotik** [comment]
Both versions are fully synced, I am not sure if the polygon deployment has passed QA

**Comment by ishraq8** [comment]
Double checking polygon

**Comment by ishraq8** [comment]
@dhruv-chauhan For Gains, is there a reason swaps are zero?
