### ISSUE TITLE
HOP-XDAI-BRIDGE - XDAI

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1807]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmYoKNXFLVdXsvR8hGxStsAZfW4CT1cX5wjePqAciqVj5Q&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/11pJ1n_qDGwCf7zPo2tu7X3bxAq5SM1fk/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Revenue

- We have computed the recent daily total revenue using data from official website and the results show that there is a large discrepancy of 286.11% with the subgraph data.
- See the sheet 'Support-Implied-Revenue-&-TVL'  for the computations

February 25, 2023:

| Subgraph - Daily Total Revenue | Official Website - Daily Total Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 94.04| 24.36 | 69.68| 286.11%| 

- Refer to the sheet 'Protocol'   

### Total Pool Count and Total Supported Token Count
- The official website only shows 5 pools/tokens instead of the subgraph data of 7.

### Pool Overview 

- Two pools in the subgraph data are inactive and not shown in the official website, and these are hWBTC/WBTC and HOP pools.
- The reward tokens of the pools must be on $HOP or $GNO token instead of $DAI token as shown in the official website.
- Refer to the sheet "Pool_Overview" for details

#### hUSDC/USDC pool
- The input token balance data on hUSDC/USDC pool may be incorrect as it is supposed have two data, one for USDC with about 500k token balance, and another one for hUSDC with about 600k token balance according to Gnosis scan.

#### hETH/ETH pool
- The input token balance data on hETH/ETH pool may be wrong too as it should not be just a decimal number. There must be two data, one for ETH with about 180 token balance, and another one for hETH with about 180 token balance as well according to Gnosis scan.

As mentioned above, the token rewards of the pools should be $HOP or $GNO tokens instead of $DAI token. As a result, the reward token emissions data of both pools must be inaccurate as well.

- Refer to the sheet "Pool_vault schema" for details

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@itsjerryokolo QA for Hop xDAI

**Comment by bye43** [comment]
@pietydespises Could you take a look at this new deployment? The issues identified above should have been addressed. 
- https://thegraph.com/hosted-service/subgraph/itsjerryokolo/hop-protocol-xdai

**Comment by pietydespises** [comment]
looks good!

**Comment by itsjerryokolo** [comment]
@pietydespises I asked @jaimehgb about this. He said TVE can be 0. This value is calculated internally.
I'm not sure if this is an issue.

**Comment by jaimehgb** [comment]
TVE refers to the value of assets native to the chain where the subgraph is running, that have been bridged away. For example, if I send 10 native ETH from mainnet to BSC, TVE from mainnet will be those 10 ETH. If I bridge those ETH back to mainnet, TVE from BSC **won't change**, because that value wasn't native to bsc.

So, in layer 2's, it is possible for TVE to be 0 or very low, if all the value bridged away initially came from other chains.

It would still be worth investigating those spikes @itsjerryokolo . It might be some token deployed in XDAI that was bridged somewhere and then stopped being used, or price from that token went to 0, or something. If you could take a look to see what is the reason? Other than that, 0 is fine

**Comment by itsjerryokolo** [comment]
Okay, I'll investigate.

**Comment by itsjerryokolo** [comment]
Hi @jaimehgb,
I looked at the early transfers and I'm not sure what to make of it. 
Within the time period it shows the first TVE on the dashboard as $3912, 
$4602 was transferred in from L1, and only $4 was transferred out to other chains. 
The only pool at that time was the USDC pool and the price is hardcoded as $1. 
Only $404 liquidity was added to the pool. 
<img width="363" alt="Screenshot 2023-04-17 at 1 06 54 PM" src="https://user-images.githubusercontent.com/73024324/232496723-b2eb1839-cf38-4a48-8a95-3a24f94bb439.png">

**Comment by bye43** [comment]
@pietydespises Could you give this one more scan the TVI and TVE values should be fixed - https://okgraph.xyz/?q=QmWMvGmrpp3KQiCeiPfhh76AugNm6N2bN3d2pkZf27W9ZH

**Comment by pietydespises** [comment]
looks good @bye43

**Comment by bye43** [comment]
cc: @dmelotik This is good to be deployed on hosted

**Comment by dmelotik** [comment]
@itsjerryokolo is this the source of the deployments? https://github.com/messari/subgraphs/pull/2127

If so, can you fix the merge conflicts and fix the failed workflows (For now, you can ignore the lint errors)

**Comment by itsjerryokolo** [comment]
@dmelotik Yes. I just did that.
