### ISSUE TITLE
Moonwell Moonbeam: Indexing Errors

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1819]
https://okgraph.xyz/?q=messari/moonwell-moonbeam
```A determinstic fatal error occured at block 3060190: Failed to call 'asc_type_id' with 'ArrayBuffer' wasm backtrace: 0: 0x309a - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall 1: 0xd47a - <unknown>!generated/templates/CToken/SolarBeamLPToken/SolarBeamLPToken#try_getReserves 2: 0xd830 - <unknown>!protocols/moonwell/src/mapping/setMarketRewards 3: 0xe204 - <unknown>!protocols/moonwell/src/mapping/handleAccrueInterest : wasm trap: interrupt wasm backtrace: 0: 0xffffffff - <unknown>!node_modules/@graphprotocol/graph-ts/global/global/id_of_type 1: 0x309a - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall 2: 0xd47a - <unknown>!generated/templates/CToken/SolarBeamLPToken/SolarBeamLPToken#try_getReserves 3: 0xd830 - <unknown>!protocols/moonwell/src/mapping/setMarketRewards 4: 0xe204 - <unknown>!protocols/moonwell/src/mapping/handleAccrueInterest in handler `handleAccrueInterest` at block #3060190 (19651dc82a366431b72acec4bc4cac761718af070864e943f2998977a55b2fb4)```

**Comment by bye43** [comment]
@dhruv-chauhan Could you take a look at this when you get the chance? Thanks!

**Comment by dhruv-chauhan** [comment]
The code looks good to me, [test deployment](https://thegraph.com/hosted-service/subgraph/dhruv-chauhan/moonwell-moonbeam) has successfully synched ahead.

I reckon [it's a timeout, wrongly reported as a deterministic error](https://github.com/graphprotocol/graph-node/issues/3576) and redeploying the graft (PR: #1822) should fix it.

@bye43 @dmelotik
