### ISSUE TITLE
Compound Protocol Revenue Outlier

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#182]
Not sure if this is an issue in the data but there is a huge jump in protocol revenue around June 2020

<img width="1379" alt="Screen Shot 2022-05-15 at 7 54 34 PM" src="https://user-images.githubusercontent.com/2354636/168512224-dce1ab84-7fdb-46e7-ab64-82c859147e59.png">

https://subgraphs.messari.io/graphs?subgraph=https://api.thegraph.com/subgraphs/name/messari/compound-ethereum&tab=protocol&view=financialsDailySnapshots-dailyProtocolSideRevenueUSD

**Comment by this-username-is-taken** [comment]
This has been fixed in the latest deployment: https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fid%2FQmdJrbZNS4awTCnwQbaBqT5Ab4DRCYGnwBNuAUXMd9kTmY&tab=protocol&view=financialsDailySnapshots-totalValueLockedUSD

![image](https://user-images.githubusercontent.com/2354636/176330876-cc5016bd-93cc-40ff-8b24-f5c4cf5c8ae8.png)

**Comment by this-username-is-taken** [comment]
This is actually still occurring in the latest deployment:
https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fid%2FQmdJrbZNS4awTCnwQbaBqT5Ab4DRCYGnwBNuAUXMd9kTmY&tab=protocol&view=financialsDailySnapshots-dailyProtocolSideRevenueUSD

![image](https://user-images.githubusercontent.com/2354636/176332020-28895a96-dede-436d-8951-fcff1c18aa29.png)

**Comment by dmelotik** [comment]
Findings:

- The influx is in the BAT market
- The reserve factor is 50% during this time https://etherscan.io/tx/0x788fce747addcd2e7f6893e2193627a0f6f96140a002527d28a01f4d8eabe9b0#eventlog which is on the high side of reserve factors https://www.comp.xyz/t/reserve-factor-standardization/608
- Looking at BAT balances there is a big influx at this time: https://defillama.com/protocol/compound
- Input token prices are accurate cross referencing coingecko

Here is the query to see the data in the subgraph: https://api.thegraph.com/subgraphs/name/messari/compound-ethereum/graphql?query=query+MyQuery+%7B%0A++marketDailySnapshots%28%0A++++where%3A+%7Btimestamp_gt%3A+%221591768354%22%2C+timestamp_lt%3A+%221596261154%22%2C+dailyProtocolSideRevenueUSD_gte%3A+%22100000%22%7D%0A++%29+%7B%0A++++id%0A++++timestamp%0A++++dailyTotalRevenueUSD%0A++++dailyProtocolSideRevenueUSD%0A++++dailySupplySideRevenueUSD%0A++++market+%7B%0A++++++id%0A++++++name%0A++++%7D%0A++++dailyDepositUSD%0A++++dailyRepayUSD%0A++++dailyWithdrawUSD%0A++++dailyBorrowUSD%0A++++dailyLiquidateUSD%0A++++%0A++++totalDepositBalanceUSD%0A++++inputTokenBalance%0A++++inputTokenPriceUSD%0A++++totalBorrowBalanceUSD%0A++++exchangeRate%0A++++rates+%7B%0A++++++side%0A++++++rate%0A++++%7D%0A++%7D%0A%7D

**Comment by this-username-is-taken** [comment]
Fair enough. I will close this one then
