### ISSUE TITLE
#bug; VolumeByTokenUSD and VolumeUSD unexpected results

### ISSUE THREAD

**Issue by liambeckman199** [messari/subgraphs#1830]
Describe the bug
There are cases when the **dailyVolumeByTokenAmount/hourlyVolumeByTokenAmount** is defined but the subsequent time resolution **VolumeByTokenUSD and VolumeUSD** is 0 on some Dex **production ready** subgraphs.

Reproduction

uniswap-v3-optimism
uniswap-v3-polygon
sushiswap-arbitrum
sushiswap-moonbeam
sushiswap-celo
(potentially more)

Expected behavior
For example, on the sushiswap-arbitrum subgraph, for the pool with the greatest TVL on the latest daily snapshot,  dailyVolumeByTokenAmount=['1000','1000'] and dailyVolumeByTokenUSD= '0' and dailyVolumeUSD= '0'.

I would expect to see a non-zero value for the USD volume fields if dailyVolumeByTokenAmount is non-zero for this snapshot.

**Comment by bye43** [comment]
@liambeckman199 Can you send a sample query? Are these mostly long-tail assets, I imagine this is another pricing issue and we are actively working on pricing for assets on DEXs

**Comment by liambeckman199** [comment]
Yah I imagine it's the same pricing issue I noted with rewardsEmissionUSD, but I figured I should flag it regardless.

Query:
```
{
                liquidityPools(first: 1 orderBy: totalValueLockedUSD, orderDirection: desc) {
                  id
                  $dailySnapshots(first: 1, orderBy: timestamp, orderDirection: desc) {
                   timestamp
                   dailyVolumeByTokenAmount
                   dailyVolumeByTokenUSD
                   dailyVolumeUSD
                  }
                }
              }
```

**Comment by liambeckman199** [comment]
> Yah I imagine it's the same pricing issue I noted with rewardsEmissionUSD, but I figured I should flag it regardless.
> 
> Query:
> 
> ```
> {
>                 liquidityPools(first: 1 orderBy: totalValueLockedUSD, orderDirection: desc) {
>                   id
>                   dailySnapshots(first: 1, orderBy: timestamp, orderDirection: desc) {
>                    timestamp
>                    dailyVolumeByTokenAmount
>                    dailyVolumeByTokenUSD
>                    dailyVolumeUSD
>                   }
>                 }
>               }
> ```

**Comment by liambeckman199** [comment]
> @bye43 speaking of the rewardsEmissionUSD issue, I'm also finding this problem on the ethereum balancer-v2 subgraph:

balancer-v2-ethereum pool 50OHM-50DAI yields: rewardTokenEmissionsAmount= 5446719996047866 and rewardTokenEmissionsUSD= 0

**Comment by bye43** [comment]
@liambeckman199 Looks like it potential is a smaller decimal value. I am seeing ~0.03 on this [query](https://api.thegraph.com/subgraphs/name/messari/balancer-v2-ethereum/graphql?query=%7B%0A++liquidityPoolDailySnapshots+%28orderBy%3A+timestamp%2C+orderDirection%3Adesc%2C+where%3A+%7Bpool_%3A+%7B_poolId_contains%3A+%220x76fcf0e8c7ff37a47a799fa2cd4c13cde0d981c9%22%7D%7D%29+%7B%0A++++pool+%7B%0A++++++name%0A++++++id%0A++++++rewardTokens+%7B%0A++++++++token+%7B%0A++++++++++name%0A++++++++++id%0A++++++++++decimals%0A++++++++++lastPriceUSD%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++++rewardTokenEmissionsAmount%0A++++rewardTokenEmissionsUSD%0A++++timestamp%0A++%7D+%0A%7D). Looks like that matches the 0.22% BAL rewards on the balancer UI for that pool
![Screen Shot 2023-03-07 at 10 22 40 AM](https://user-images.githubusercontent.com/107651107/223466737-500638ca-f17e-4ea0-b2bf-85cc1c7f6ef6.png)
