### ISSUE TITLE
#feature; Add liquidation revenue to aave

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1831]
**What do you think is missing?**
Aave liquidations have a liquidation revenue. That should be considered protocol revenue.

**Describe the solution you'd like**
Start tracking liquidation revenue. Ideally we upgrade to schema 3.0.0 and then we can also see the source of all revenue.

**Comment by tnkrxyz** [comment]
@dmelotik , I am assigned both tasks - this one and aave-forks upgrade. do you prefer to do this one first before updrading?

**Comment by dmelotik** [comment]
The upgrade will not make it unnecessary. Regardless of the upgrade we don't currently have logic in the subgraph to calculate liquidation revenue. Something I missed when I first did the aave forks directory.

I think this can be done separately or concurrently with the upgrade to 3.0.0. Whatever makes more sense to do in your workflow, so it is up to you!

**Comment by tnkrxyz** [comment]
I see, that's helpful! I prefer to add liquidation revenue concurrently with the upgrade if that's OK.
