### ISSUE TITLE
Stargate Arbitrum, Avalanche, BSC, Optimism, Polygon QA

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1846]
@pietydespises Can you give these deployments a quick scan, mark them off if they look good and leave any comments for @dhruv-chauhan in this issue?
Deployment to QA:

- [x] #1847
- [x] Avalanche: https://okgraph.xyz/?q=QmYFygCMetwkxpib8E1RWcbPckSJ819rKRSYdMudgmLiHU
- [x] BSC: https://okgraph.xyz/?q=QmPoYMaS8XDL3y7iuc9SjJXwje5akWV62v218v3HW35yqr
- [x] Optimism: https://okgraph.xyz/?q=QmVkLyV8ga4ZSwtWLjS2HhEbhCLusJDDQSUST3Dx2wnLAP
- [x] Polygon: https://okgraph.xyz/?q=QmbADHmhjQrgZR8W3HrGceyzEEAvJYWsuWXPzuhYiBxWzT

**Comment by pietydespises** [comment]
These all look good to go
