### ISSUE TITLE
uniswap-v3 Ethereum: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1860]
ethereum: Block #16811417 - https://okgraph.xyz/?q=messari%2Funiswap-v3-ethereum - firehose error status: Internal, message: "protocol error: received message with invalid compression flag: 60 (valid flags are 0 and 1) while receiving response with status: 503 Service Unavailable", details: [], metadata: MetadataMap { headers: {"server": "nginx/1.22.1", "date": "Sun, 12 Mar 2023 10:41:50 GMT", "content-type": "text/html", "content-length": "197"} }

**Comment by bye43** [comment]
@steegecs

**Comment by bye43** [comment]
Ya weird ... it was popping of with the same error all day yesterday. Will close this and keep an eye out if it comes up again
