### ISSUE TITLE
reflexer-governance: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1865]
ethereum: Block #16817203 - https://okgraph.xyz/?q=messari%2Freflexer-governance-ethereum - Failed to transact block operations: subgraph `QmRvW1py3pFRFxCvYpjpszMRZbFW2g6bZgArEznnXbfxXm` has already processed block `16817200`; there are most likely two (or more) nodes indexing this subgraph

**Comment by bye43** [comment]
@danielkhoo - https://okgraph.xyz/?q=QmRvW1py3pFRFxCvYpjpszMRZbFW2g6bZgArEznnXbfxXm
