### ISSUE TITLE
aura-finance: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1866]
ethereum: Block #16818369 - https://okgraph.xyz/?q=messari%2Faura-finance-ethereum - Mapping aborted at ~lib/array.ts, line 114, column 42, with message: Index out of range	wasm backtrace:	    0: 0x2920 - <unknown>!~lib/array/Array<~lib/string/String>#__get	    1: 0x9162 - <unknown>!src/common/getters/getOrCreateBalancerPoolToken	    2: 0x8d5d - <unknown>!src/common/getters/getOrCreateBalancerPoolToken	    3: 0x8d5d - <unknown>!src/common/getters/getOrCreateBalancerPoolToken	    4: 0xd51d - <unknown>!src/mappings/helpers/createWithdraw	    5: 0xd861 - <unknown>!src/mappings/handlers/handleWithdrawn	 in handler `handleWithdrawn` at block #16818369 (1b7fb27c35feb4175d6d67d52ead1731c30be735b05b5968d4d79959560007db)

**Comment by dhruv-chauhan** [comment]
PR #1868 fixes this
@bye43
