### ISSUE TITLE
Aura-Finance Ethereum (Decentralized Network): Indexing error

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#1914]
https://thegraph.com/explorer/subgraphs/33aQTj7abtAR5zGcG9JBd1fd1sodgKDjoTsKuA8QrUW7?view=Overview&chain=mainnet
<img width="961" alt="Screen Shot 2023-03-21 at 7 40 54 AM" src="https://user-images.githubusercontent.com/56660047/226608811-b49cdbff-1b36-4941-8018-19c361181ad9.png">

**Comment by dmelotik** [comment]
@dhruv-chauhan that is not causing the issue, we will let it slide, just needs to be redeployed.


A note though, without bumping the version, it is hard for our system to know if it is out of sync

**Comment by dmelotik** [comment]
@steegecs I deployed, can you publish
