### ISSUE TITLE
Compound V2 Ethereum: Market `0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5`0 TVL for certain dates

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1938]
[Query](https://api.thegraph.com/subgraphs/name/messari/compound-v2-ethereum/graphql?query=query+MyQuery+%7B%0A++market%28id%3A+%220x4ddc2d193948926d02f9b1fe9e1daa0718270ed5%22%29+%7B%0A++++name%0A++++inputTokenPriceUSD%0A++++dailySnapshots%28%0A++++++orderBy%3A+timestamp%0A++++++orderDirection%3A+desc%0A++++++where%3A+%7Btimestamp_gte%3A+%221661670000%22%2C+timestamp_lte%3A+%221661929200%22%7D%0A++++%29+%7B%0A++++++id%0A++++++timestamp%0A++++++outputTokenPriceUSD%0A++++++inputTokenBalance%0A++++++totalValueLockedUSD%0A++++++%7D%0A++++%7D%0A++%7D)
![compound-v2-0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5-daily-totalValueLockedUSD-032323](https://user-images.githubusercontent.com/107651107/227276683-533b204a-c4b9-4006-9d13-6700b8cae5d4.jpeg)

**Comment by dmelotik** [comment]
This is actually related to a comp proposal where they upgraded the oracle and it broke ETH pricing. It took a few days to fix.

We decided to keep this in there to reflect what was happening on chain. During that time the market was paused.

Breaking proposal: https://compound.finance/governance/proposals/117
Fix: https://compound.finance/governance/proposals/119
Our compound v2 notes: https://github.com/messari/subgraphs/tree/master/subgraphs/compound-forks/protocols/compound-v2#notes
