### ISSUE TITLE
abracadabra fantom: Protocol Error cumulativeUniqueUserFactors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1952]
Field: cumulativeUniqueUserFactors
Value: 6533+5145+116+4731=175
Description: lendingProtocol entity has fewer cumulativeUniqueUsers than cumulativeUniqueDepositors/cumulativeUniqueBorrowers/cumulativeUniqueLiquidators/cumulativeUniqueLiquidatees.

**Comment by dmelotik** [comment]
This is fixed in the pending version
