### ISSUE TITLE
abracadabra arbitrum: Protocol Error cumulativeUniqueUserFactors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1953]
Field: cumulativeUniqueUserFactors
Value: 1846+1374+11+1139=14
Description: lendingProtocol entity has fewer cumulativeUniqueUsers than cumulativeUniqueDepositors/cumulativeUniqueBorrowers/cumulativeUniqueLiquidators/cumulativeUniqueLiquidatees.

**Comment by dmelotik** [comment]
This is fixed in the pending version
