### ISSUE TITLE
bug(#minor); monitor; Discord bot duplicating thread messages

### ISSUE THREAD

**Issue by MichaelC1999** [messari/subgraphs#1959]
1) The monitor is not reading the existing threads and creates messages for protocols that already have a thread. 
2) The call to convert these messages to threads is failing.

https://discord.com/channels/953684103012683796/1002746564336431204/1089678586782421032

**Comment by dhruv-chauhan** [comment]
@bye43 I'll take this up

**Comment by dhruv-chauhan** [comment]
PR #1988 fixes this!
@MichaelC1999

**Comment by bye43** [comment]
@dhruv-chauhan merged/deployed!
