### ISSUE TITLE
Extend Price Lib to support Optimism

### ISSUE THREAD

**Issue by rube-de** [messari/subgraphs#196]
The lib supports next to mainnet also fantom and arbitrum, extending it for optimism is probably not too different to arbitrum.

**Comment by this-username-is-taken** [comment]
Hey @rube-de, this is on our roadmap but not a priority for the next couple weeks. I'd appreciate it if you could add support and submit a PR. We will help review it.

**Comment by harsh9200** [comment]
Hello @rube-de, Optimism support to Price lib has been added.
