### ISSUE TITLE
#bug; subgraph dashboard options schema broken

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1963]
**Describe the bug**
There were some changes to the options schema recently that broke some of the visualization on our visualizer.

**Reproduction**
See dopex: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRMSkXhCxfqATXLuD3uyXBwtGoQTMXvY234SYHtu3ZJaT&tab=protocol

**Additional context**
I believe these are the 2 commits that changed the schema since the last update on the dashboard

- https://github.com/messari/subgraphs/commit/ebf3ee82cf8242d864ca541c63fd0287fd53e367
- https://github.com/messari/subgraphs/commit/4f59f75f2965f2873068e24aac57c9048461e235

**Comment by dhruv-chauhan** [comment]
@dmelotik I'll take this up

**Comment by dhruv-chauhan** [comment]
PR #1965 fixes broken Pool Overview tab, supports options schema version 1.3.0.

@dmelotik @MichaelC1999 @bye43
