### ISSUE TITLE
#feature; subgraph monitor version comparison change

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1964]
**What do you think is missing?**
When comparing subgraph versions on the version comparison page we should compare against all deployments (hosted, hosted pending, dec) and flag any version that is out of sync with the latest master branch.

Right now it only compares the hosted service version and then shows the other versions.

**Comment by dmelotik** [comment]
@dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
@dmelotik I'd take it up!

**Comment by dmelotik** [comment]
This is awesome! Thank you @dhruv-chauhan
