### ISSUE TITLE
sushiswap ethereum: Protocol Error totalValueLockedUSD

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1969]
Field: totalValueLockedUSD
Value: $122,114,604,903.64
Description: This field on dexAmmProtocol entity has a value below $0 or above $100,000,000,000.

**Comment by bye43** [comment]
@steegecs Looks like this pool `0xea9b00b169dda4cbc9fa0a64b0d1e4a6a23a3f34` is pricing wrong

**Comment by ishraq8** [comment]
thanks @steegecs, it hasn't synced yet.

**Comment by steegecs** [comment]
Synced up now!

**Comment by ishraq8** [comment]
@steegecs QA passed, looks like blacklisting Deri token worked. Thank you.
