### ISSUE TITLE
#bug; In subgraphs.xyz bridge net volume can be negative

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1980]
**Describe the bug**
Right now on bridge subgraphs in subgraphs.xyz net volume negative is labeled an error.

**Expected behavior**
Net volume and volumeUSD can be negative in bridges. So the only errors should be if the volume is > than our upper limit threshold for being crazy.

**Screenshots**

<img width="1262" alt="Screen Shot 2023-04-04 at 8 28 01 PM" src="https://user-images.githubusercontent.com/60583747/229973888-b7963823-af05-46cc-a95b-5395a7e29732.png">

**Comment by dmelotik** [comment]
@dhruv-chauhan

**Comment by dhruv-chauhan** [comment]
PR #1982 

@dmelotik @bye43

**Comment by bye43** [comment]
Merged and looks good @dhruv-chauhan
