### ISSUE TITLE
Opyn Gamma QA MAINNET

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1981]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmeVSwnvqMo2fNZe7Bc4GuLjAVBtgF9anuCiq98vivrxCn&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1tqWG8-Wqq77NpKoKhSQIJvxB9FaWUUq5/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview - TVL

- TVL data for only one out of the 17 pools, which is the 'Aave Token' vault, has shown a discrepancy of -59.03% when compared with the Defi Llama data.

March 31, 2023:

| Subgraph - Aave Token Pool | Defi Llama - Aave Token Pool | Difference % 
| :---- | :--- | :---  | 
| $555,537.52| $1,356,102.11 |  -59.03% | 

- While there are two pools with double-digit discrepancies, we believe that these discrepancies may be attributed to differences in time and token prices. These pools are 'Uniswap' and 'Perpertual'.

- Refer to the sheet "Pool_Overview" for details

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@spitko QA for Opyn

**Comment by spitko** [comment]
Hey, thanks for the QA.

> * TVL data for only one out of the 17 pools, which is the 'Aave Token' vault, has shown a discrepancy of -59.03% when compared with the Defi Llama data.

There was an option that expired on 31.03, which caused the drop in TVL. It seems the subgraph was first to show this, but by the next day, the DefiLlama TVL again matches with the subgraph data.


> * While there are two pools with double-digit discrepancies, we believe that these discrepancies may be attributed to differences in time and token prices. These pools are 'Uniswap' and 'Perpertual'.

Yes, this is due to the subgraph having outdated price data. The token price and TVL is only updated whenever some action is done in that pool. And those two pools have relatively low activity.

**Comment by bye43** [comment]
cc: @ishraq8

**Comment by ishraq8** [comment]
that resolves the issues. there is an update PR https://github.com/messari/subgraphs/pull/1967

but shouldn't affect data and the fields are optional

great work @spitko

**Comment by dmelotik** [comment]
published on arb network
