### ISSUE TITLE
Build Mummy Finance Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1984]
Docs: https://docs.mummy.finance/contracts
Derivs-Perp SDK: https://github.com/messari/subgraphs/tree/master/subgraphs/_reference_/src/sdk/protocols/perpfutures

```[tasklist]
### Deployment Status:
- [ ] https://github.com/messari/subgraphs/issues/2143
- [ ] Optimism
```

@shashwatS22

**Comment by shashwatS22** [comment]
I'll start working on this. Thanks!
