### ISSUE TITLE
Pancakeswap V3 QA

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1995]
```[tasklist]
### Deployment Status
- [ ] BSC: https://okgraph.xyz/?q=messari%2Fpancakeswap-v3-bsc
- [ ] Ethereum: https://okgraph.xyz/?q=QmYZj7NxhoX8aMTJ5wjYr1W4hHSY7pZ4NQW6aJtzzypknK
```

**Comment by pietydespises** [comment]
Took a look at the [eth](https://okgraph.xyz/?q=messari%2Fpancakeswap-v3-ethereum ) and [bsc](https://okgraph.xyz/?q=messari%2Fpancakeswap-v3-bsc) deployments and the data is matching with both dapp radar and defillama with no data anomalies detected
