### ISSUE TITLE
#bug; subgraph.xyz Dashboard is not showing data for certain time range on Curve Avalanche

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2000]
Description: [Looks](https://subgraphs.messari.io/subgraph?endpoint=messari/curve-finance-avalanche&tab=protocol) like there is data for Curve Avalanche starting 08/05/2021, but this is not reflected on the dashboard. See [query](https://api.thegraph.com/subgraphs/name/messari/curve-finance-avalanche/graphql?query=%7B%0A%09liquidityPoolDailySnapshots%28orderBy%3A+blockNumber%2C+orderDirection%3A+asc%29+%7B%0A++++id%0A++++totalValueLockedUSD%0A++++blockNumber%0A++++timestamp%0A++%7D%0A%7D) here that shows data present
![curve-avalanche-041123](https://user-images.githubusercontent.com/107651107/231267451-e1af88ec-e9c2-4e5e-b00f-db523f18253d.jpeg)

**Comment by dmelotik** [comment]
@bye43 I believe the subgraph is just missing pricing data prior to dec 2021. The query you sent shows 0s for TVL

**Comment by bye43** [comment]
Ahh, good catch @dmelotik. Sorry, @dhruv-chauhan you can ignore this I will close this out
