### ISSUE TITLE
Gains Trade Arbitrum QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2005]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/Qmf9rLtaDvZwYBnHuRSRkSjiNmycsQxW2trDk4ukeodoet&tab=protocol
| Schema Version  |  1.2.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/10dtaf7F0aAbI4NlbJpNGofK9xGJws1y3/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool - gDAI vault

- In the 'Pool' section for the gDAI vault, all of the daily data is equivalent to the cumulative data, which is inaccurate since it should be lower.

- Refer to the sheet "Pool_snapshot" for details

### Pool - Daily Active Users
- Data is not in line with the data from the 'Protocol' sheet, considering that there is only one vault in the Arbitrum chain.

### Pool - rewardTokenEmissionsAmount 
- Data is not mathematically in line with the data from "Pool_vault schema" sheet. It should be only 3,780.19.

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@dhruv-chauhan QA for Gains!

**Comment by dhruv-chauhan** [comment]
@bye43 good for re-review

polygon@ https://okgraph.xyz/?q=QmR6aUUaQaPXmkg8Uyqm4EFEnfBSHwwVNSdEZ5gKUankFw
arbitrum@ https://okgraph.xyz/?q=QmTpznweZxMD3pqUrqpk58vv89JBYGKUddsqJQR1qVcy5M

**Comment by bye43** [comment]
@ishraq8

**Comment by ishraq8** [comment]
most of the earlier issues were resolved. there are a couple of things that arose when I took a look
1. Funding rate looks very off. This is usually a very small number and I think the decimal point requires it to be divided. In GMX it was divided by a million based on the contract.
![Screen Shot 2023-04-24 at 4 38 09 PM](https://user-images.githubusercontent.com/47088402/234111430-1710f674-a638-42a7-933b-90ae9d137575.png)

2. Did you want to update the schema to current version?

**Comment by dhruv-chauhan** [comment]
Good catch @ishraq8 ! funding rate value needs to be divided by 1e10, updated now.
Schema version is also up to date.

deployments, (pending versions)
polygon@ https://okgraph.xyz/?q=dhruv-chauhan%2Fgains-trade-polygon
arbitrum@ https://okgraph.xyz/?q=dhruv-chauhan%2Fgains-trade-arbitrum

**Comment by bye43** [comment]
@ishraq8 Do you mind giving this a quick look when you get the chance?

**Comment by ishraq8** [comment]
looks like the funding rate issue was resolved. Great work @dhruv-chauhan
