### ISSUE TITLE
Axelar - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2007]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/axelar-ethereum&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/14m3StI-RskdRGi8uh6Qx9zbdnkScknd3/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Revenue
- Axelar does not generate revenue since it does not impose fees, and only the relayer gas fees are collected. You may refer to this link: https://axelar.network/blog/cross-chain-gas-costs-on-satellite-explained
- Refer to the sheet 'Protocol'   

### Total Pool Count and Total Supported Token Count
- Axelar's official website displays that there are solely 18 tokens native to Ethereum, which contrasts with the 24 tokens listed on the subgraph.

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@tnkrxyz QA for axelar.

**Comment by bye43** [comment]
@tnkrxyz Just wanted to follow up on this QA in case it got buried!

**Comment by tnkrxyz** [comment]
Response to QA comments ** WIP**

> ## Review Info

> ## Metric to Review

> ### Revenue
> * Axelar does not generate revenue since it does not impose fees, and only the relayer gas fees are collected. You may refer to this link: https://axelar.network/blog/cross-chain-gas-costs-on-satellite-explained

I am aware of this, but I remember seeing somewhere that it is possible to enable protocol fees (current set to 0). Let me see if I can find it.

> 
> ### Total Pool Count and Total Supported Token Count
> * Axelar's official website displays that there are solely 18 tokens native to Ethereum, which contrasts with the 24 tokens listed on the subgraph.
 
> Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
Dashboard linke for ETH:  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmYqtQzyWSc5LPevXUesaw4bP5VzmK6QXVH98s1H9PeNaK&tab=protocol

**Comment by pietydespises** [comment]
Looks good :)

**Comment by dmelotik** [comment]
Should this be prod now and in PM? @pietydespises @bye43

**Comment by bye43** [comment]
Yes, I was waiting to do all of axelar, but will do this now that its taking a little longer
