### ISSUE TITLE
Add Arbitrum deployment for theGraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2008]
theGraph is now deployed on Arbitrum

```[tasklist]
### Deployment QA
- [ ] Arbitrum: https://thegraph.com/hosted-service/subgraph/messari/the-graph-arbitrum
```

**Comment by ishraq8** [comment]
the usage metrics are accurate.

 There is no price for GRT token on arbitrum and thus financial data is zero. @steegecs, once this is up then we can get that data.
