### ISSUE TITLE
#feature; track dex reserve amounts on a per swap basis

### ISSUE THREAD

**Issue by Evan-Kim2028** [messari/subgraphs#2026]
**What do you think is missing?**
Dex subgraph pool entities only contain historical reserve values on a per hourly/daily level. This lack of granularity makes it impossible to analyze reserve changes with respect to swap amounts to understand things such as slippage.

Everytime a swap occurs, it will change the reserve amounts of the pool based on how many tokens are swapped into and out of the pool. Thus the pool entity inputTokenBalances (reserve amounts) should also be updated on a per swap basis to reflect this change.

**Describe the solution you'd like**
- update the pool entity inputTokenBalances array to include the reserves everytime a swap occurs instead of just the most recent reserve amount.

**Comment by dmelotik** [comment]
Implementation:

- Upgrade both DEX (normal) and extended schemas with this and make it a minor change
- Upgrade uniswap-forks and uniswap v3 forks
- deploy to your hosted service
