### ISSUE TITLE
Tokemak  TVL  issue

### ISSUE THREAD

**Issue by sevenshi** [messari/subgraphs#203]
![image](https://user-images.githubusercontent.com/1418738/169458025-32aaa749-9155-48fa-acbe-979e0ec69e74.png)
![image](https://user-images.githubusercontent.com/1418738/169458090-de911b12-33a4-482a-8eb0-776f84dacac7.png)

**Comment by bye43** [comment]
Going to condense this on here: https://github.com/messari/subgraphs/issues/581
