### ISSUE TITLE
Build Mux Network Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2032]
- Docs: https://docs.mux.network/protocol/contracts

```[tasklist]
### Deployment QA Status
- [ ] https://github.com/messari/subgraphs/issues/2170
- [x] Avalanche: https://okgraph.xyz/?q=QmVZokEXfJ4VVQMEzweWGXdQcok1dEb4rNcze4XDpzb1wb
- [x] BSC: https://okgraph.xyz/?q=QmYfiunoaB3rHogksbMHigLZo9NAKuz1XcawLdGoufgvSk
- [x] Fantom: https://okgraph.xyz/?q=QmVzjqtmcQBxU5S4Rm587DsNUG8mKZrBKGnLAT7EVbDtfN
- [x] Optimism: https://okgraph.xyz/?q=QmZeBzc15ySS4DudqSWn9gaU6g1SQyuwQ2f1oe7o3cBr42
```

**Comment by bye43** [comment]
@corerouter

**Comment by corerouter** [comment]
Codes are submitted at https://github.com/messari/subgraphs/pull/2070

Deployments: (All deployments will finish syncing at May 22 (next Monday))

arbitrum: https://okgraph.xyz/?q=QmY8zEbstD3gzDyzYSHRMDFR1TLcqiJqnGNXA64dqdg4my
avalanche: https://okgraph.xyz/?q=QmVZokEXfJ4VVQMEzweWGXdQcok1dEb4rNcze4XDpzb1wb
bsc: https://okgraph.xyz/?q=QmYfiunoaB3rHogksbMHigLZo9NAKuz1XcawLdGoufgvSk
fantom: https://okgraph.xyz/?q=QmVzjqtmcQBxU5S4Rm587DsNUG8mKZrBKGnLAT7EVbDtfN
optimism: https://okgraph.xyz/?q=QmZeBzc15ySS4DudqSWn9gaU6g1SQyuwQ2f1oe7o3cBr42

**Comment by bye43** [comment]
@ishraq8 these other deployments prob need a quick scan too, but no rush since like 80% of all it's TVL is on that arbitrum deployment

**Comment by ishraq8** [comment]
data looks good here. should go to code review. thanks @corerouter
