### ISSUE TITLE
sonne-finance optimism: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#2042]
optimism: Block #92709234
Link: https://okgraph.xyz/?q=messari%2Fsonne-finance-optimism
Error: failed to process trigger: block #92709234 (0x9875…fe45), transaction 387a5ddac8fe1de1a1f2540fd6ef2959a1435e7a82a8063a4f63488ec06b75cd: Failed to call 'asc_type_id' with 'ArrayBuffer'	wasm backtrace:	    0: 0x266f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    1: 0xd627 - <unknown>!protocols/sonne-finance/src/mapping/handleAccrueInterest	: wasm trap: interrupt	wasm backtrace:	    0: 0xffffffff - <unknown>!../../node_modules/@graphprotocol/graph-ts/global/global/id_of_type	    1: 0x266f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    2: 0xd627 - <unknown>!protocols/sonne-finance/src/mapping/handleAccrueInterest

**Comment by bye43** [comment]
Graph node error
