### ISSUE TITLE
curve-finance gnosis: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#2043]
gnosis: Block #27552052
Link: https://okgraph.xyz/?q=messari%2Fcurve-finance-gnosis
Error: failed to process trigger: block #27552052 (0x0630…5df2), transaction e105b6903538a9175dfc18ac87d747d8a014065bae287048a934538cdfae8f7d: Failed to call 'asc_type_id' with 'ArrayBuffer'	wasm backtrace:	    0: 0x43e6 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    1: 0x59eb - <unknown>!src/prices/oracles/InchOracle/getTokenPriceUSDC	    2: 0x7d28 - <unknown>!src/prices/index/getUsdPricePerToken	    3: 0x8b50 - <unknown>!src/common/initializers/getOrCreateToken	    4: 0xf4d7 - <unknown>!src/common/utils/updateProtocolTotalValueLockedUSD	    5: 0xf7fd - <unknown>!src/modules/Deposit/Deposit	    6: 0xfa82 - <unknown>!src/mappings/poolMappings/handleAddLiquidityWithFees	: wasm trap: interrupt	wasm backtrace:	    0: 0xffffffff - <unknown>!node_modules/@graphprotocol/graph-ts/global/global/id_of_type	    1: 0x43e6 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    2: 0x59eb - <unknown>!src/prices/oracles/InchOracle/getTokenPriceUSDC	    3: 0x7d28 - <unknown>!src/prices/index/getUsdPricePerToken	    4: 0x8b50 - <unknown>!src/common/initializers/getOrCreateToken	    5: 0xf4d7 - <unknown>!src/common/utils/updateProtocolTotalValueLockedUSD	    6: 0xf7fd - <unknown>!src/modules/Deposit/Deposit	    7: 0xfa82 - <unknown>!src/mappings/poolMappings/handleAddLiquidityWithFees

**Comment by bye43** [comment]
Graph-node error
