### ISSUE TITLE
arrakis-finance ethereum: Indexing Errors

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#2047]
ethereum: Block #17107413
Link: https://okgraph.xyz/?q=messari%2Farrakis-finance-ethereum
Error: failed to process trigger: block #17107413 (0x0d11…2b8d), transaction 34db1cb183a276cb752c1f48e72178431671f7ad7e23a77d9e621e70917a9da2: Failed to call 'asc_type_id' with 'ArrayBuffer'	wasm backtrace:	    0: 0x53b0 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    1: 0xbf9c - <unknown>!src/mappings/helpers/financials/updateVaultTokenValue	    2: 0xc69b - <unknown>!src/mappings/helpers/financials/updateTvl	    3: 0xd26f - <unknown>!src/mappings/handlers/vault/handleFeesEarned	: wasm trap: interrupt	wasm backtrace:	    0: 0xffffffff - <unknown>!node_modules/@graphprotocol/graph-ts/global/global/id_of_type	    1: 0x53b0 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall	    2: 0xbf9c - <unknown>!src/mappings/helpers/financials/updateVaultTokenValue	    3: 0xc69b - <unknown>!src/mappings/helpers/financials/updateTvl	    4: 0xd26f - <unknown>!src/mappings/handlers/vault/handleFeesEarned

**Comment by bye43** [comment]
Graph node error
