### ISSUE TITLE
#bug; GMX PnL different from GMX leaderboard

### ISSUE THREAD

**Issue by noamsch** [messari/subgraphs#2052]
**Describe the bug**
`account.position.realisedPnlUSD` is higher PnL values compared to GMX leaderboard (gmx.house), potentially due to including paid fees. 

**Reproduction**
Compare a position in GMX leaderboard https://www.gmx.house/arbitrum/account/0x0c571c3785ab78b59cfb36a6f5dbae7329410c37

1. Link to subgraph on [[`okgraph.xyz`](https://okgraph.xyz/)](https://okgraph.xyz/?q=messari%2Fgmx-arbitrum)

**Expected behavior**
Subgraph PnL should match the GMX House PnL

**Screenshots**
<img width="282" alt="Screen Shot 2023-04-24 at 20 56 19" src="https://user-images.githubusercontent.com/31586628/234033548-128b7f66-50ef-4a13-9008-a4ac1be37ddb.png">

<img width="565" alt="Screen Shot 2023-04-24 at 20 55 59" src="https://user-images.githubusercontent.com/31586628/234033599-f666f322-59f2-4e59-95d7-7261e3cc3fa7.png">

**Additional context**
It is possible the the difference originates from paid fees, as diff is around 0.2% of position value (0.1% open fee, 0.1% close fee).

**Comment by bye43** [comment]
@corerouter

**Comment by corerouter** [comment]
Looking into it. Thanks!
