### ISSUE TITLE
#bug; stakedao-ethereum non-nullable depositLimit

### ISSUE THREAD

**Issue by fishTsai20** [messari/subgraphs#2072]
"message": "failed to process trigger: block #11692672 (0x5157…0264), transaction c1fbd73c32505ed9051a31c2372a85c96bf228a7778fe632c32ee7601a1ade3d: Entity Vault[0xb17640796e4c27a39af51887aff3f8dc0daf9567]: missing value for non-nullable field `depositLimit`\twasm backtrace:\t    0: 0x3637 - <unknown>!generated/schema/Vault#save\t    1: 0x49d2 - <unknown>!src/mappings/controllerMappings/handleSetVault\t",
          "block": {
            "hash": "0x5157d2971b5af185f3dc1a4bb7451eba297b866f886509c87b1b67b4b6410264",
            "number": "11692672"

**Comment by bye43** [comment]
This is being redeployed with a couple other changes
