### ISSUE TITLE
#feature; Add support for new DEX Schema 3.0.4/1.3.2 fields on validation dashboard

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2074]

**Comment by steegecs** [comment]
Schemas are being updated for the Uniswap Forks -> 1.3.1 - 1.3.2 and Uniswap V3 -> 3.0.3 - 3.0.4. 

The PR making these changes can be found here. Yet to be merged: 
https://github.com/messari/subgraphs/pull/2064

**Comment by steegecs** [comment]
Changes to each schema are simply adding a `reserveAmounts` field to each event (swap, deposit, withdraw)
