### ISSUE TITLE
#bug; Arbitrum Bridge (Ethereum) pool off

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2090]
**Describe the bug**
The `Spell Token` pool has an uncharacteristic price in the TVL. It does not get aggregated to the protocol level TVL, but this still looks like an issue. Likely the price on that block range is inflated for some 

Query:

```graphql
{
  pool(id:"0xa3a7b6f88361f48403514059f1f16c8e78d60eec090185f2135308bad17527004364ebcc2d37e5f6"){
    id
    symbol
    name
    dailySnapshots (
      where:{
        timestamp_gt: 1640845781
        timestamp_lt: 1641191381
      }
      orderBy:timestamp
      orderDirection: desc
    ){
      id
      timestamp
      totalValueLockedUSD
      pool {
        name
      }
    }
  }
}
```

cc @fortysevenlabs

**Comment by bye43** [comment]
@fortysevenlabs

**Comment by fortysevenlabs** [comment]
👀 ack

**Comment by bye43** [comment]
@dmelotik this needs to be deployed to the hosted when the PR is merged
