### ISSUE TITLE
#bug; Compound-v3 All - supply/repay event isn't handled correctly

### ISSUE THREAD

**Issue by ronlv10** [messari/subgraphs#2095]
**Describe the bug**
In compound v3, the `Supply` event is used for both repay and supply in a market. In the subgraph implementation, it tries to distinguish between the two cases by comparing the amount of mint of cToken and the transfer [here](https://github.com/messari/subgraphs/blob/4444ac9f903656d9658864c628b47c7fa4a3a7ff/subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts#L484)

But IIUC, instead of using `le` I think it should use `equals` or `ge` - when the mint amount is less than the transfer amount, it should be full repay and partial deposit. 

**Reproduction**
Where can we see this bug in action?
For example, take a look on `0x326ac9f9150be38ae6a8424effbbe9299dc0d20c` wallet.
In the subgraph [response](https://pastebin.com/bbZWsRtK) its balance is:
1. COLLATERAL of WBTC of "1"
2. Borrow of "70000000000" USDC
3. collateral (supply) of "922612" USDC 

The state of the user on compound : 

Here is the repay + mint tx of this user![image](https://github.com/messari/subgraphs/assets/17575462/2c871a84-37ce-4273-a0d2-bb14c6a30363)

In general, this state of both collateral and borrow of the market asset in compound v3 is impossible. 
https://etherscan.io/tx/0xbb955b1771c1edbd88c7d83e725ab091d352728e4f269ba40265ded809b1f71c#eventlog

Link to subgraph on [`okgraph.xyz`](https://okgraph.xyz/): https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-polygon

As mentioned above, I think we should change the logic to check if amount == mint amount -> deposit, otherwise it full repay and partial deposit .

Also I see in the code that we do `const repayAmount = amount.minus(mintAmount);` for `mintAmount > amount`, which make me think that maybe it the condition was meant to be `amount.le(mintAmount)` instead of `mintAmount.le(amount)`

Hope that I didn't miss something.

**Comment by ronlv10** [comment]
First of all, just for clarification, for the picture that I attached, I used https://www.impersonator.xyz/ which helps to impersonate to an account and use the UI.

Regarding the "1" BTC collateral. So yes, "1" BTC is basically `1/10^8` , so IIUC the UI doesn't show this amount because it's too small. Note that in the screenshot, there is an option in the UI of "-" for reducing the collateral (only for BTC), which means that the UI does see a balance for the BTC collateral. 

Regarding the root cause:
IIUC, this is the transaction that didn't handle correctly- https://etherscan.io/tx/0xbb955b1771c1edbd88c7d83e725ab091d352728e4f269ba40265ded809b1f71c#eventlog 

In this transaction, the user repaid all the debt, and had some change that has minted as supply. The condition that I attached above, the code handled it just as supply of the diff between the debt and the total amount the user provided (change), and not as repay and supply and that's the reason the use still have the balance of the borrow.

**Comment by ronlv10** [comment]
My proposed solution can be found here: https://github.com/ChaosLabsInc/messari-subgraphs/pull/1

Deployed to https://thegraph.com/hosted-service/subgraph/ronlv10/compound-v3-ethereum

Before with production graph:
https://api.thegraph.com/subgraphs/name/messari/compound-v3-ethereum/graphql?query=%7B%0A++accounts%28where%3A+%7Bid%3A+%220x326ac9f9150be38ae6a8424effbbe9299dc0d20c%22%7D%29+%7B%0A%0A++%0A++++positions+%28where%3A%7Basset_%3A%7Bsymbol%3A%22USDC%22%7D%2C+balance_not%3A%220%22%7D%29+%7B%0A++++++id%0A++++++side%0A++++++asset++%7B%0A++++++++id%0A++++++++symbol%0A++++++++lastPriceUSD%0A++++++++lastPriceBlockNumber%0A++++++%7D%0A++++++timestampClosed%0A++++++balance%0A++++++_principalValue%0A++++++market+%7B%0A++++++++id%0A++++++++_baseBorrowIndex%0A++++++++_baseSupplyIndex%0A++++++++_baseTrackingBorrowSpeed%0A++++++++_baseTrackingSupplySpeed%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D

After (with the deployed version of this branch):
https://api.thegraph.com/subgraphs/name/ronlv10/compound-v3-ethereum/graphql?query=%7B%0A++accounts%28where%3A+%7Bid%3A+%220x326ac9f9150be38ae6a8424effbbe9299dc0d20c%22%7D%29+%7B%0A%0A++%0A++++positions+%28where%3A%7Basset_%3A%7Bsymbol%3A%22USDC%22%7D%2C+balance_not%3A%220%22%7D%29+%7B%0A++++++id%0A++++++side%0A++++++asset++%7B%0A++++++++id%0A++++++++symbol%0A++++++++lastPriceUSD%0A++++++++lastPriceBlockNumber%0A++++++%7D%0A++++++timestampClosed%0A++++++balance%0A++++++_principalValue%0A++++++market+%7B%0A++++++++id%0A++++++++_baseBorrowIndex%0A++++++++_baseSupplyIndex%0A++++++++_baseTrackingBorrowSpeed%0A++++++++_baseTrackingSupplySpeed%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D


As you can see, the balance of the user is correct now. 

Happy to hear WDYT ?

**Comment by ronlv10** [comment]
Hey @dmelotik , 
Any ETA for this ? 
AFAIU, the subgraph currently shows a lot for wrong balances for bunch of positions

**Comment by dmelotik** [comment]
@ronlv10 do you want to make a PR on our repo for this? You can follow this: https://github.com/messari/subgraphs/blob/master/docs/CONTRIBUTING.md

And the only extra thing you need to do is bump the version https://github.com/messari/subgraphs/blob/master/deployment/deployment.json#L2049 to 2.1.0

And then tag me as a reviewer

**Comment by dmelotik** [comment]
@ronlv10 thank you for raising this and helping with the fix. This is now deployed for all comp v3 on hosted service.
