### ISSUE TITLE
#bug; Yearn prices in price library very inconsistent

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2107]
**Describe the bug**
Prices we get from Yearn tend to be inconsistent in the price library.

**Reproduction**
Where can we see this bug in action?
- Arbitrum Bridge (SPELL)
- We disabled Yearn from lido

**Additional context**

- We should use this issue to investigate these issues further. (ie, test the price of tokens at different points to see how the yearn portion of the calculator fares)
- Options: Remove yearn pricing from the price lib OR make Yearn lower down on the list of price locations OR add a flag to skip a certain price location.

**Comment by bye43** [comment]
@dhruv-chauhan When you get to the other pricing library fixes in https://github.com/messari/subgraphs/issues/2097 could you also address this too? Thanks!
