### ISSUE TITLE
Morpho Compound - MAINNET

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2114]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmPCkYZLMRsBVFqvTwLVQDYxG1GTi97sLFvhNtKLPxWkof&tab=protocol
| Schema Version  |  3.0.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1WPYcIciRFqU7w_7Fvlsb2Dcy_AbHT8oV/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Revenue

- We calculated the implied supply-side revenue using data from the official website and found a notable discrepancy of 226.61%. This discrepancy could indicate potential inaccuracies in the subgraph data. 
-Secondly, our calculations using data from the official website indicate that the implied protocol side revenue is not zero, and instead should be around $345.53 based on the latest data. 
- Lastly, according to our computations using data from the official website, there is a substantial discrepancy of 160.48% between the daily total revenue and the implied revenue. 
- Refer to the 'Protocol' sheet
 
As of May 10, 2023

| Subgraph - Supply Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 4,445.35| 1,361.04 | 3,084.31| 226.61%| 

| Subgraph - Protocol Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 0.00| 345.53 | -345.53| -100.00%| 

| Subgraph - Daily Total Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 4,445.35| 1,706.57 | 2,738.78| 160.48%| 

- To see the details, please refer to the "Support-Revenue" sheet.

### Total Pool Count

- There should only be seven pools at the FEI pool/market is not active and displayed on the official website.
- - Refer to the 'Protocol' and 'Pool_Overview' sheets

### TVL balance of DAI market (largest pool by TVL)

- Our computations reveal that the TVL data for the DAI market on May 2nd and 7th (latest dates) differ significantly from the figures reported on the official website, with discrepancies of -61.57% and -60.69%, respectively.

As of May 2, 2023

| Subgraph - TVL | Official Website - TVL | Difference % 
| :---- | :--- | :---  | 
| 3,371,887.10| 8,774,417.03| -61.57%| 

As of May 7, 2023

| Subgraph - TVL | Official Website - TVL | Difference % 
| :---- | :--- | :---  | 
| 3,961,364.73| 10,078,381.67| -60.69%| 

###  Borrow balance of DAI market (largest pool by TVL)

- Based on our computations using data from the official website, there are significant discrepancies in the total borrow balance USD data for the DAI market on May 2 and May 7 (latest dates). Specifically, the data shows a discrepancy of -57.07% on May 2 and -59.29% on May 7.

As of May 2, 2023

| Subgraph - Borrow balance | Official Website - Borrow balance | Difference % 
| :---- | :--- | :---  |
| 2,730,178.36| 6,359,604.77| -57.07%| 

As of May 7, 2023

| Subgraph - Borrow balance | Official Website - Borrow balance | Difference % 
| :---- | :--- | :---  | 
| 2,928,709.29| 7,194,412.13| -59.29%| 

Please refer to the attached worksheet for more details.

**Comment by dmelotik** [comment]
TVL looks hit or miss.. When I look at the current TVL of the DAI market it is correct, but the snapshots are not.

This could be an issue with creating snapshots.

The other thing I am noticing is that cumulative values are not strictly increasing and that is also likely an issue with the cumulative logic.

**Comment by bye43** [comment]
@harsh9200 This also looks good. Just one comment on the `DAI` market:
- Looks like on 5/24 the subgraph data spikes down and the morhpo UI does not. Small thing, but seems like it might be a slight error 
![Image](https://github.com/messari/subgraphs/assets/107651107/a9a0dc97-940c-4499-a34c-b3c9d1fc9ef8)
![Image](https://github.com/messari/subgraphs/assets/107651107/0066d044-4a5e-4fd3-bb66-0425f2b47dd0)
