### ISSUE TITLE
#bug; Radiant subgraph is down (hosted service)

### ISSUE THREAD

**Issue by Zeazy** [messari/subgraphs#2118]
**Describe the bug**
When we try to query the radiant subgraph via the api.graph.com link below, we are getting timeouts. It appears that the subgraph is down. We do not see this issue on other messari subgraphs.

Links: 
https://thegraph.com/hosted-service/subgraph/messari/radiant-arbitrum
https://api.thegraph.com/subgraphs/name/messari/radiant-arbitrum

Are you aware of this issue?

Thank you,
Hamza

**Comment by bye43** [comment]
This looks ok to me now - whttps://okgraph.xyz/?q=Qme7ieWfPfvoFeoxEcNuMQU3vzsrMm8PD9jKwsBkWP7EpR. We have been having some indexing errors from graphnode that fix themselves after a few mins. Going to close this for now, but will keep an eye on if it goes down now. Thanks for raising

**Comment by Zeazy** [comment]
Thank you for the quick response and resolution @bye43 - will keep an eye on it my side too
