### ISSUE TITLE
#upgrade(minor); Upgrade GMX Perps Schema 1.3.1

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#2120]
To do: Upgrade perps schema 1.3.1
Notes: PR for upgrade https://github.com/messari/subgraphs/pull/2099

Reasoning: There were some requirements for BE to have `stakeSideRevenue` in pool level data. Data is already in `dailyfinancialsnapshot` 

@bye43 @corerouter built the subgraph and would be ideal for this small upgrade. I can QA.

**Comment by corerouter** [comment]
PR is created at https://github.com/messari/subgraphs/pull/2129

Deployments:

arbitrum: https://okgraph.xyz/?q=QmRanHDRPDJkYSZjAX4GXRrz4JqXVPpp5ZUGWixDNbAZjL
avalanche: https://okgraph.xyz/?q=QmZngPUiSEEUH2TtKW3MSHmNPPsdvhZgqcSkfg1Q4zBNuE

**Comment by ishraq8** [comment]
Data to upgrade looks good. Thank you for doing this.

Just had a question about weights, USDC seems low weighted on subgraph, see if you can fix for this update:
![image](https://github.com/messari/subgraphs/assets/47088402/b6dbee32-4101-4cbd-b0cc-ba690b04e031)
![Screen Shot 2023-05-19 at 1 01 55 PM](https://github.com/messari/subgraphs/assets/47088402/c8a844d6-748c-446a-8b2d-8e82f3c3f607)

**Comment by dmelotik** [comment]
@corerouter @ishraq8 we have a concurrent upgrade going on that has already moved gmx to 1.3.1 https://github.com/messari/subgraphs/pull/2075 

If you could check the data there (once synced, and if it is good then we can close the other PR). Also, we should consider making a separate issue for the weights. It can be confusing to have so many issues in one

**Comment by corerouter** [comment]
Sure. I will make any further changes on GMX based on the new code base from #2075 . Thanks!

**Comment by ishraq8** [comment]
submitted a new issue for the weights: https://github.com/messari/subgraphs/issues/2188

#2075 will be the primary upgrade to 1.3.1, thanks @dmelotik  for coordinating.

**Comment by dmelotik** [comment]
Finished in #2075 and QA'd
