### ISSUE TITLE
Add Compound V3 ARB

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2131]

**Comment by ishraq8** [comment]
@dmelotik QAed the data and it is accurate since launch. great work. Once code review passes it can be deployed ( I can announce it as well).

**Comment by ishraq8** [comment]
Re opened issue @dmelotik 

Seems like there is a $50B spike in the USDC pool yesterday. This was post QA. @bye43 let me know if I should make a separate issue for this.   

![Image](https://github.com/messari/subgraphs/assets/47088402/90c51ce4-d0f7-4a4d-aaa7-ef1d9db4d873)

**Comment by ishraq8** [comment]
Makes sense thanks for following up
