### ISSUE TITLE
Lido Ethereum: Negative `totalRevenue`

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2132]
![lido-dailyTotalRevenueUSD-051723](https://github.com/messari/subgraphs/assets/107651107/77057a0c-2bb5-45cf-9c01-35119dc28ffc)

**Comment by bye43** [comment]
@dhruv-chauhan This looks good except looks like after 5/16 the Lido fee switches from 10% to 5%. This lines up with the release of Lido V2, but IIRC fee split did not change here. Please correct me if I am wrong

**Comment by dhruv-chauhan** [comment]
The decrease in fee is reflecting as expected, notice change in protocol's revenue after 5/16, while the total revenue remains of a similar order

![Screenshot from 2023-05-24 21-24-39](https://github.com/messari/subgraphs/assets/32761670/4edab56e-d6f7-404b-b54a-fb2a6b81a479)

![Screenshot from 2023-05-24 21-25-18](https://github.com/messari/subgraphs/assets/32761670/82d794ad-28a3-4950-85b5-7b3510384687)

with latest values,
total rev: 1,842,293
protocol rev: 92,114 (= 5% of total rev)

**Comment by dhruv-chauhan** [comment]
fixed for protocol fee, same deployment.

![Screenshot from 2023-05-29 16-38-45](https://github.com/messari/subgraphs/assets/32761670/b013becb-5307-4644-8375-fc69d4f54a4d)

![Screenshot from 2023-05-29 16-38-31](https://github.com/messari/subgraphs/assets/32761670/c34a5976-97b9-4a54-939d-ad9c352278a1)

@bye43

**Comment by bye43** [comment]
This looks good! Thanks @dhruv-chauhan. @dmelotik this is good for hosted once code review is gtg
