### ISSUE TITLE
#feature; Add GQL directives to all schemas

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2134]
**Description**
We want to add [directives](https://www.apollographql.com/docs/apollo-server/schema/directives/) to our subgraph schemas to make ingestion easier and more dynamic as we scale. The link about directives has more than we are interested in. In our subgraphs we want 4 directives added:

- `@hourlySnapshot` 
- `@dailySnapshot`
- `@transaction`
- `@regularPolling`

I think all of these are self explanatory except for `@regularPolling`. This should be added to any entity that is NOT the above 3, and is NOT a helper entity added outside of the standard schema or used to calculate other things.

How to add a directive:

```graphql
type FinancialsDailySnapshot @entity @dailySnapshot { }
type RevenueDetail @entity @regularPolling { }
type InterestRate @entity @regularPolling { }
```

**Acceptance Criteria**
To complete this task we need to:
- Update all schemas (at the root of the repo, and each individual schema)
- Follow the guidelines on what directive to add to what enitity

**Comment by dmelotik** [comment]
@dhruv-chauhan I will do comp v3 as an example, but could you make a PR for the rest of them?

**Comment by dhruv-chauhan** [comment]
Sure!

@dmelotik could you :+1:  all the schemas here #2148 so I'll go ahead and upgrade the subgraphs too

**Comment by dmelotik** [comment]
@dhruv-chauhan looks good, few comments

**Comment by dhruv-chauhan** [comment]
@dmelotik rest of the updated subgraph-schemas here: #2177

**Comment by dmelotik** [comment]
Reopening this. @dhruv-chauhan can we change all `PositionSnapshot` entities to `@hourlySnapshot` and not `@regularPolling`? We had a miscommunication on our end of what that meant
