### ISSUE TITLE
#bug; dashboard crashing

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2140]
**Describe the bug**
The dashboard home page will crash if there is an error response from the github issues API query.

<img width="1516" alt="Screen Shot 2023-05-18 at 2 52 23 PM" src="https://github.com/messari/subgraphs/assets/60583747/ec3a6c20-9ec2-431e-a0c5-1959b75b9726">

We probably want to handle the errors and log a message in the console, but not crash the entire dashboard when this happens.

**Comment by dhruv-chauhan** [comment]
caused due to deprecating network subgraphs (#2136).

github api 401 is a separate issue, fixed in #2144
