### ISSUE TITLE
Mummy Finance - FANTOM

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2143]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/Qma8rCUYJiAhJmMt3PG5Dsxqs5KNbpbr2ijaAQ83BpQ6BF&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1pMqi3pWSYhfFHkA8v6aSks6LXohuO36B/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Daily Protocol Side Revenue

- During the observed period from May 12 to 16, the daily protocol side revenue consistently exhibits a significant discrepancy of 75% with Token Terminal data.
 
5-day average (from May 12 to 16 of 2023)

| Subgraph - Protocol Side Revenue | Token Terminal - Protocol Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 939.53| 3,750.99 | -2,811.46| -74.95%| 

- Refer to the 'Protocol' sheet

###  Daily Volume USD
- The 5-day average daily volume data is significantly different from the data reported by Defi Llama and Dune Analytics, with discrepancies of -97.45% and -98.46% respectively.

5-day average (from May 12 to 16 of 2023)

| Subgraph - Daily Volume USD | Defi Llama - Daily Volume USD | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 70,550.24| 2,766,000.00 | -2,695,449.76| -97.45%| 

| Subgraph - Daily Volume USD | Dune Analytics - Daily Volume USD | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 70,550.24| 4,588,766.22 | -4,518,215.98| -98.46%| 

- Refer to the 'Protocol' sheet

###  Daily Short and Total Open Interest

- Since the daily short open interest data takes into account past information, it should be presented cumulatively. Currently, the day-to-day percentage change in short open interest is inconsistent with the daily short open interest data reported on the official website, resulting in an average discrepancy of -71.63% over the last four days.

4-day average (from May 13 to 16 of 2023)

| Subgraph - Daily Short Open Interest (day to day change) | Official Website - Daily Short Open Interest | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 812,214.86| 2,862,717.96 | -2,050,503.09| -71.63%| 

- The daily total open interest data should also be cumulative since it incorporates previous data. In addition, the day-to-day change % of the total open interest does not align with the official website's daily total open interest data, indicating an average discrepancy of -61.10% over a span of four days.

4-day average (from May 13 to 16 of 2023)

| Subgraph - Daily Total Open Interest (day to day change) | Official Website - Daily Total Open Interest | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 1,317,586.17| 3,387,160.83 | -2,069,574.66| -61.10%| 

- Refer to the 'Protocol' sheet

### Daily Transaction Count

- The daily transaction count data is not equal to the sum of deposit, withdraw, borrow, swap, daily long & short positions count data.
- Refer to the 'Protocol' sheet

### Reward Token Emissions data - MMY Vault

- Our calculations of the implied MMY price based on the rewardTokenEmissions data indicate a significant deviation of 50.54% compared to its market price on CoinGecko. This suggests a potential inaccuracy in the rewardTokenEmissions data.

As of May 16, 2023

| Subgraph - Implied MMY token price | CoinGecko - MMY token price | Difference % 
| :---- | :--- | :---  | 
| 1.77| 3.57| -50.54%| 

- Refer to the 'Pool_vault schema' sheet

Please refer to the attached worksheet for more details.

**Comment by ishraq8** [comment]
Took a look at the fixes from: https://github.com/messari/subgraphs/pull/2075

1. token terminal combines revenue to stake holders and revenue to treasury as protocol side revenue. we seperate these to stake side and protocol side revenue. Numbers are accurate when you add them together.
2. Volume looks accurate for fantom (some differences in day overlap)
However it does look off compared to DefiLlama on optimism:
![Screen Shot 2023-05-25 at 11 25 22 AM](https://github.com/messari/subgraphs/assets/47088402/b1416dc5-ed74-46cb-b26f-6478c12fa11b).
3. open interest looks good in both
4. transaction count is slightly off can you double check?
5. pricing issue looks resolved

@shashwatS22 great work, just fix #2 and #4

**Comment by ishraq8** [comment]
volume matches dune, defillama was including internal protocol swaps. 
transaction count is accurate too. 

this is ready to deploy.

**Comment by ishraq8** [comment]
I checked the avalanche deployment to stat.gmx.io they are within 1% similar for volume (which they call margin trading volume), open interest, total revenue and TVL to defillama

there is a discrepancy on how they label date (their labeling is one day behind ours). We can wait for arbitrum as that is behind the data on the official gmx site.
