### ISSUE TITLE
#bug; Withdrawal and Deposit mean opposite?

### ISSUE THREAD

**Issue by hoangvictor** [messari/subgraphs#2150]
**Describe the bug**
There is a problem in the meaning of the actions: the withdraw and the deposit actions.

**Reproduction**
When I search for some withdrawal actions, I take some hash and look it up in Scan Polygon, all of them are withdrawal actions.

Link to subgraph on [`uniswap-v3-polygon`](https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-polygon)

**Screenshots**
![Screenshot from 2023-05-23 10-40-25](https://github.com/messari/subgraphs/assets/41613226/6d5dc11b-a6ba-4589-846c-a180e3fbd139)

**Comment by steegecs** [comment]
Addressing this bug in this PR. Will begin indexing. Should take ~2 weeks to index for most Uniswap V3 subgraphs.
