### ISSUE TITLE
Across - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2165]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmPvn1Gv2ew6xydfTumdxW7gWkDST5kfDSSz3EFAM6VW1D&tab=protocol
| Schema Version  |  1.1.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/15vtSbIY6nYhY8J7en4-Uee9cY3ieUly4/edit?usp=share_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  Total Value Locked (TVL)

- The latest subgraph TVL data (May 24, 2023) exhibits significant discrepancies of -38.80% and -39.40% when compared to the official website and Defi Llama data, respectively. 
 
 | Subgraph - TVL | Official Website - TVL| Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 27,377,569.42| 44,731,608.37 | -17,354,038.95| -38.80%| 

 | Subgraph - TVL | Defi Llama - TVL| Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 27,377,569.42| 45,241,678.94 | -17,864,109.52| -39.49%| 

- Additionally, the 5-day average TVL data shows a substantial deviation of 37.11% from Defi Llama data. These findings strongly suggest inaccuracies in the subgraph TVL data.
- Refer to the 'Protocol' sheet

###  Revenue

- Since there is no protocol side revenue, the daily total revenue should be equivalent to the supply side revenue. However, both the supply side revenue and the daily total revenue should not be zero since LP fees are incurred within the Across protocol. 
- Furthermore, according to the data from Token Terminal, the 4-day average daily total revenue for the Across protocol is recorded as 4,564 (from May 20 to 23, 2023). This evidence reinforces the notion that the daily total revenue should not be zero.
 
4-day daily total revenue average (from May 20 to 23 of 2023)

| Subgraph - Daily Total Revenue | Token Terminal - Daily Total Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 0| 4,564.75 | -4,564.75| -100.00%| 

- Refer to the 'Protocol' sheet

###  Total Pool Count and Total Supported Token Count

- The official website of Across shows only 11 pools/tokens within the Ethereum network, which is inconsistent with the 21 tokens listed in the subgraph data.

###  Pool Overview - TVL & Reward
- Contrary to what is shown on the official website, there are currently two pools for each token, including USD, WETH, ACX, WBTC, USDT, DAI, BAL, UMA, and BOBA in the subgraph data. There should be only one pool for each token.
- Despite including the data from the second pool of each token, the USDC and WETH pools still exhibit significant discrepancies in their Total Value Locked (TVL) data compared to the figures provided by the official website. These discrepancies amount to over 30%.
- According to the official website, there should be a total of 11 pools.
- There is a significant disparity between the data in the 'REWARDS TOKENS' column and the token reward APY data provided by Defi Llama.
- Refer to the 'Pool_Overview' sheet

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@fortysevenlabs

**Comment by fortysevenlabs** [comment]
**Pool Overview - TVL & Reward**
> Contrary to what is shown on the official website, there are currently two pools for each token, including USD, WETH, ACX, WBTC, USDT, DAI, BAL, UMA, and BOBA in the subgraph data. There should be only one pool for each token.

* There are two types of pools in across liquidity (hubpool, only on mainnet) and transfer (spokepool, on each chain). There have been transfer attempts for unsupported tokens (Badger, Synthetix Network Token) that result in more pools. 
* Summary: There are 9 tokens supported resulting in 9 liquidity and transfer pools. The 2 additional token pools bring the total pool count to 20.

> Despite including the data from the second pool of each token, the USDC and WETH pools still exhibit significant discrepancies in their Total Value Locked (TVL) data compared to the figures provided by the official website. These discrepancies amount to over 30%.

Will address as part of TVL section.

> According to the official website, there should be a total of 11 pools.

See first point in this comment.

> There is a significant disparity between the data in the 'REWARDS TOKENS' column and the token reward APY data provided by Defi Llama.

- [ ] Ack. Was working as expected in my spot checks. Will address.

**Comment by fortysevenlabs** [comment]
**Total Pool Count and Total Supported Token Count**

> The official website of Across shows only 11 pools/tokens within the Ethereum network, which is inconsistent with the 21 tokens listed in the subgraph data.

Addressed in https://github.com/messari/subgraphs/issues/2165#issuecomment-1565195689

**Comment by fortysevenlabs** [comment]
**Revenue**

> Since there is no protocol side revenue, the daily total revenue should be equivalent to the supply side revenue. However, both the supply side revenue and the daily total revenue should not be zero since LP fees are incurred within the Across protocol.

> Furthermore, according to the data from Token Terminal, the 4-day average daily total revenue for the Across protocol is recorded as 4,564 (from May 20 to 23, 2023). This evidence reinforces the notion that the daily total revenue should not be zero.

The methodology in the subgraph vs defillama is different. Here's what defillama does. they:
a) [include both](https://discord.com/channels/@me/1041647201908170762/1112060240024838144) funds deposited (source) and filled relays (destination) events/tx for supply side revenue
b) [include relayer fees](https://discord.com/channels/@me/1041647201908170762/1112060366785093713) also as part of supply side revenue

Regarding (a) -> I'm going to double check if lp fee is applied twice (deposit and filled relay). I would assume this isn't the case as this wouldn't be ideal from a user (who is bridging) perspective. Any additional thoughts on this? 
Regarding (b) -> I didn't treat relayer fees as supply side revenue, only LP fees. We can make a case against and for it. How do we want to approach this?

**Comment by fortysevenlabs** [comment]
**TVL**

There is a difference in methodology for TVL as well. Here's the differences -
* Approach 1: I'm tracking TVL based on the overall token amount held by across's contracts (eg. WETH held by hubpool, spokepools, acceleratingDistributor would be the across's TVL for WETH)
* Approach 2: Whereas, defillama uses the total supply of the LP tokens to track the TVL associated with a token `totalSupply(Av2-WETH-LP) * input token price`

The actual assets held by the bridging protocol may decrease over time as they are used to fulfill bridging requests. I believe Approach 1 is a more accurate representation of TVL because the total supply of LP tokens does not directly reflect the assets held by the protocol.

How do we want to approach TVL?

**Comment by pietydespises** [comment]
@fortysevenlabs I agree with you, Approach 1 is more accurate.

**Comment by pietydespises** [comment]
@fortysevenlabs oops sorry missed the revenue comment. Indeed two fees applied, a LP fee and a Relayer fee that the user has to pay. https://docs.across.to/how-across-works/fees . I don't think the LP fee is applied twice.

Let's include relayer fees in protocol side revenue.

**Comment by fortysevenlabs** [comment]
> @fortysevenlabs oops sorry missed the revenue comment. Indeed two fees applied, a LP fee and a Relayer fee that the user has to pay. https://docs.across.to/how-across-works/fees . I don't think the LP fee is applied twice.
> 
> 
> 
> Let's include relayer fees in protocol side revenue.

Sounds good. Will add relayer fees. There seems to be bug in defillama where LP fees are added for filled relays as well. I have messaged in across's discord. Will raise a bug fix on defillama accordingly.

**Comment by fortysevenlabs** [comment]
Complete the changes necessary. Summary:

- TVL - no changes
- Revenue - [add relayer fee to supply side revenue](https://github.com/messari/subgraphs/pull/1777/commits/ab4005bba210db3ddefecafd2dbffe1833584a05)
- Rewards - [reward APY](https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/name/fortysevenlabs/across-v2-ethereum&tab=pool&version=current&name=fortysevenlabs/across-v2-ethereum&poolId=0xc186fa914353c44b2e33ebe05f21846f1048beda2260fac5e5542a773aa44fbcfedf7c193bc2c5996c6971756964697479) (see reward APR image for WBTC pool below)
<img width="1335" alt="image" src="https://github.com/messari/subgraphs/assets/4187512/ba9415a0-dc2d-4b17-ae32-56956bfbada0">

**Comment by fortysevenlabs** [comment]
@this-username-is-taken Regarding item `Revenue - daily total revenue (may 20 -24)` in the https://github.com/messari/subgraphs/issues/2165#issuecomment-1571734069, I would recommend the following approach (to get things out faster and avoid delays):
* Complete this QA and get data until 25-04-2023 out to production
* Iteratively, as a separate task, add support for new contracts

**Scope change details**
* Based on a quick review, there are minor changes in event ABIs (FundsDeposited, FilledRelay) but this will involve a bunch of additions (ABIs, sources, handlers, tracking as part of same spokepool vs new spokepool, etc). 
* Would also want to do deeper review of all changes to ensure nothing else requires further change.
* Estimate: ~1-2 days to review changes, add support, QA from my side

@dmelotik @bye43 fyi, share your thoughts

**Comment by pietydespises** [comment]
Looks great!

**Comment by fortysevenlabs** [comment]
Great, will resolve the lint issues and we should be good to go for production!
