### ISSUE TITLE
#docs: Update Bytes, immutables performance report

### ISSUE THREAD

**Issue by sebastiantf** [messari/subgraphs#2171]
**Describe the bug**
Docs in https://github.com/messari/subgraphs/blob/master/docs/PERFORMANCE.md#results-3 reports that Bytes as ids and immutables did not help improve performance. But following the thread on https://github.com/graphprotocol/graph-node/issues/3534, it seems this is not the case, anymore? Docs could be updated appropriately to avoid misleading future readers, if this was indeed resolved

Apologies for marking this as a bug. Couldn't find an appropriate type to report this

**Reproduction**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
Nil

**Comment by steegecs** [comment]
Docs have been updated. Thanks for bringing this to our attention! https://github.com/messari/subgraphs/pull/2173
