### ISSUE TITLE
#qa; Aave V3 Metis

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2182]
https://subgraphs.messari.io/subgraph?endpoint=https://andromeda.thegraph.metis.io/subgraphs/name/messari/aave-v3-metis&tab=protocol

**Comment by bye43** [comment]
@ishraq8 whenever you get the chance can you take a look at this?

**Comment by dmelotik** [comment]
@ishraq8 those 2 photos are comparing `dailySupplySideRev` with `cumulativeProtocolSideRevenue`

Looking at this [query](https://andromeda.thegraph.metis.io/subgraphs/name/messari/aave-v3-metis/graphql?query=query+MyQuery+%7B%0A++markets+%7B%0A++++name%0A++++totalValueLockedUSD%0A++++_reserveFactor%0A++++cumulativeTotalRevenueUSD%0A++++cumulativeSupplySideRevenueUSD%0A++++cumulativeProtocolSideRevenueUSD%0A++%7D%0A%7D) it seems reasonable to me (supply > protocol) in each market

**Comment by ishraq8** [comment]
makes sense. sorry my mistake, got confused as the revenue is so small. thanks for double checking. This passes QA and is ready for deployment
