### ISSUE TITLE
#bug; GMX `inputTokenWeights` is off

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#2188]
**Describe the bug**
Input token weight is off from GMX. 

**Reproduction**
![image](https://github.com/messari/subgraphs/assets/47088402/634263e9-78dc-4b1f-92be-a1b77b832ea2)
![image](https://github.com/messari/subgraphs/assets/47088402/28dc6892-2a2a-46f0-aa52-130f77917cf7)

**Expected behavior**
should match

fix after: https://github.com/messari/subgraphs/pull/2075

**Comment by bye43** [comment]
@corerouter

**Comment by ishraq8** [comment]
looks like #2075 fixed it
