### ISSUE TITLE
#feature; `deployment.json` does not support goerli

### ISSUE THREAD

**Issue by gosuto-inzasheru** [messari/subgraphs#2193]
### What do you think is missing?
using goerli as a network in the deployment json gives an error when trying to `messari b`:
```
Invalid network in deployment.json for protocol: xyz deployment: xyz-ethereum network: goerli
```
however, i can still define `network: goerli` in the `xyz.template.yaml` and deploy it to a decentralised node on the goerli network without any problems. 

an added artefact of goerli not being supported by the deployment json is that it still ends up being labelled as `xyz-ethereum` by the cli:
```
RESULTS:
Build Succesful: xyz-ethereum
END
```

### Describe the solution you'd like
would be nice to have native goerli support :)

**Comment by dmelotik** [comment]
Hey @gosuto-inzasheru `goerli` support was added to the cli tool here: https://github.com/messari/subgraph-cli/pull/10

The latest version should fix your issues
