### ISSUE TITLE
Bug with closed Uniswap V3 polygon positions, incorrect NULL result for hashClosed, blockNumberClosed, timestampClosed

### ISSUE THREAD

**Issue by Gwendiie** [messari/subgraphs#2200]
**Bug:**
When I ran this in the Playground (https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-polygon), **it gave me null for all hashClosed, blockNumberClosed, timestampClosed, even though the following 3 positions have already closed.** 
To add on further, because i filtered for **liquidity_gt: 0** , which allows me to fetch positions that have actual liquidity provided or borrowed, excluding positions with zero liquidity. By right, these 3 positions below in my response should not appear since these positions have been closed already. 

**What I ran in the playground:** 
{
  positions(where: {
    account: "0x027afe0a7caa646c2c035e9108079e1a9ad50208",
    liquidity_gt: 0
  }) {
    pool {
      name
      symbol
      liquidityTokenType
      inputTokens{
      name
      symbol 
      id}
      tick
      inputTokenBalances
      inputTokenBalancesUSD
      inputTokenWeights
    }
    id
    hashOpened
    hashClosed
    blockNumberClosed
    timestampClosed
    }
    }
    
    
    Response that I got:
    
     {
        "pool": {
          "name": "Uniswap V3 (PoS) Wrapped BTC/XSGD 0.3%",
          "symbol": "(PoS) Wrapped BTC/XSGD",
          "liquidityTokenType": "MULTIPLE",
          "inputTokens": [
            {
              "name": "(PoS) Wrapped BTC",
              "symbol": "WBTC",
              "id": "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6"
            },
            {
              "name": "XSGD",
              "symbol": "XSGD",
              "id": "0xdc3326e71d45186f113a2f448984ca0e8d201995"
            }
          ],
          "tick": "58490",
          "inputTokenBalances": [
            "172113123",
            "724820164878"
          ],
          "inputTokenBalancesUSD": [
            "44243.3819161305976196537198756513",
            "538641.3957853791411718642607258928"
          ],
          "inputTokenWeights": [
            "50",
            "50"
          ]
        },
        "id": "0x0000000000970b0900",
        "hashOpened": "0x7514384655d9ff909354d5d6c13a6126087b118e6681216b2d8ac9268019105d",
        **"hashClosed": null,
        "blockNumberClosed": null,
        "timestampClosed": null**
      },
      {
        "pool": {
          "name": "Uniswap V3 XIDR/Wrapped Ether 0.3%",
          "symbol": "XIDR/Wrapped Ether",
          "liquidityTokenType": "MULTIPLE",
          "inputTokens": [
            {
              "name": "XIDR",
              "symbol": "XIDR",
              "id": "0x2c826035c1c36986117a0e949bd6ad4bab54afe2"
            },
            {
              "name": "Wrapped Ether",
              "symbol": "WETH",
              "id": "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
            }
          ],
          "tick": "105536",
          "inputTokenBalances": [
            "3629908775846362",
            "42175404853159552460"
          ],
          "inputTokenBalancesUSD": [
            "0",
            "74169.28549191856910024540406370034"
          ],
          "inputTokenWeights": [
            "50",
            "50"
          ]
        },
        "id": "0x0000000000a80b0900",
        "hashOpened": "0x1b89444a8f6c0cf0be87c0b1dcb0d8292e773fbacccfa4873e6d4137a0ba1610",
        **"hashClosed": null,
        "blockNumberClosed": null,
        "timestampClosed": null**
      },
      {
        "pool": {
          "name": "Uniswap V3 Wrapped Ether/XSGD 0.3%",
          "symbol": "Wrapped Ether/XSGD",
          "liquidityTokenType": "MULTIPLE",
          "inputTokens": [
            {
              "name": "Wrapped Ether",
              "symbol": "WETH",
              "id": "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
            },
            {
              "name": "XSGD",
              "symbol": "XSGD",
              "id": "0xdc3326e71d45186f113a2f448984ca0e8d201995"
            }
          ],
          "tick": "-198658",
          "inputTokenBalances": [
            "222371350132097941033",
            "937854261300"
          ],
          "inputTokenBalancesUSD": [
            "390791.7020836492100518745047917243",
            "696955.124634158340489236375103664"
          ],
          "inputTokenWeights": [
            "50",
            "50"
          ]
        },
        "id": "0x0000000000b8270500",
        "hashOpened": "0x9b1696bf399956ae567b68ece3608967d997f23aa61480c7347b04776d139286",
        **"hashClosed": null,
        "blockNumberClosed": null,
        "timestampClosed": null**
      },
      {
    
  
    
**Expected behavior**
The above positions should show some results for hashClosed, blockNumberClosed, timestampClosed, since the position has already been closed. 
position ID:
0x0000000000970b0900, https://app.uniswap.org/#/pools/337954
0x0000000000a80b0900, https://app.uniswap.org/#/pools/337961
0x0000000000b8270500, https://app.uniswap.org/#/pools/337872

**Comment by bye43** [comment]
@steegecs

**Comment by bye43** [comment]
Believe this change needs to be deployed to the hosted service, but the code change is merged, which is why the issue is closed

**Comment by Gwendiie** [comment]
Ah I see, thanks for the explanation @bye43 ! 
Will try again tomorrow instead (will wait about 1 day for the deployment to hosted service)

**Comment by bye43** [comment]
Sounds good you can refer to this issue again the status will change from `deploy to hosted` to `done`. Was mis-drag earlier on the status

**Comment by Gwendiie** [comment]
hi @bye43 @steegecs good day to you! Thanks for information, can I check roughly what is the timeline for status to be changed from `deploy to hosted` to `done `? This is so that I will know as to check back on that time range, thank you so much! :)

**Comment by bye43** [comment]
@Gwendiie this is syncing on @steegecs hosted service believe its about 2ish weeks out

**Comment by Gwendiie** [comment]
gotcha, thanks and noted! @bye43 @steegecs 
Will check back next week instead
