### ISSUE TITLE
Velodrome-Finance Optimism: Indexing Error 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2209]
Indexing errors on velodrome-finance
optimism: 105555272 
Link: https://okgraph.xyz/?q=messari%2Fvelodrome-optimism
``` A determinstic fatal error occured at block 105555272: transaction 39fddc3916ad527e958950c6a1fe87c7ce9ebcdddbed7040157ed04cc6a9cd3d: Mapping aborted at src/common/getters.ts, line 72, column 10, with message: unexpected null wasm backtrace: 0: 0x316e - <unknown>!src/common/getters/getLiquidityPool 1: 0x3df4 - <unknown>!src/mappings/helpers/rewards/createGauge 2: 0x4dc3 - <unknown>!src/mappings/rewards/handleGaugeCreated in handler `handleGaugeCreated` at block #105555272 (971c7a606bc3a05d3c323d489d447bc565999fda49570b01589409238c32cb04))```

**Comment by bye43** [comment]
@dhruv-chauhan Can I bump this to the top of your to-do list?

**Comment by bye43** [comment]
@dhruv-chauhan looks like this is syncing really slow, anything we can do to speed it up or just a lot of entities?

**Comment by dhruv-chauhan** [comment]
It does look like it has a lot of entities, makes sense for the biggest dex on OP. Even the graft is taking a lot of time to copy, more than a day and only 40% done. :eyes: 

@bye43

**Comment by bye43** [comment]
Sounds good, will sit tight then thanks!

**Comment by bye43** [comment]
@dhruv-chauhan Took a look at this since it synced to head, but looks like there are negative TVL values - https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/id/QmcSgSEVenSadUj2hhzXKuZFFe6wUktkxA5FnosiNa4BrR&tab=protocol&protocolId=0x25CbdDb98b35ab1FF77413456B31EC81A6B6B746

**Comment by dhruv-chauhan** [comment]
@bye43 yes, I looked into it. Velodrome has launched V2, and hence the liquidity has moved to the V2 pools. I had started adding V2 contracts, will get back to this after perps-sdk changes.

**Comment by bye43** [comment]
Awesome, ty!

**Comment by bye43** [comment]
@dmelotik @dhruv-chauhan V1 and V2 look good now. Closing this issue out
