### ISSUE TITLE
Kwenta - OPTIMISM

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2213]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmYY7tJU3wsSmVDApGw9UroJYHzDHMtF9YaFAYnHcVYS4g&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1f3URZUDONW1QJDQ0g8Iqnd3qRWoQZoJf/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Total Value Locked (TVL)

- The TVL data for the Kwenta protocol should be considered as zero since all TVL is derived from the Synthetix protocol. It's important to note that the official website, analytics, and other sources do not provide TVL data specifically for the Kwenta protocol. 
- Additionally, there has been a misconception where Messari mistakenly took the open interest data as the TVL data for the Kwenta protocol.

###  Daily Volume

- The provided daily volume data may be inaccurate, as there is a substantial discrepancy of -90.20% in the five-day average when compared to the data from the official website/analytics.

5-day average (May 28 - June 1, 2023)

| Subgraph - Daily Volume | Official Website - Daily Volume | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 13,235,547.75| 159,042,808.00 | -145,807,260.25| -90.20%| 

- Additionally, the four-day average of the daily volume data shows a -89.54% deviation when compared to the figures from Token Terminal, providing further evidence of potential inaccuracies in the data.

4-day average (May 28 - 31, 2023)

| Subgraph - Daily Volume | Token Terminal - Daily Volume | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 15,402,051.108| 179,178,644.55 | -163,776,593.44| -89.54%| 

-  Please refer to the 'Protocol' sheet

###  Daily Open Interest 

- The daily total open interest data should not be zero, as indicated by the official website/analytics.
- It appears that Messari has mistakenly considered the open interest data as the TVL (Total Value Locked) data, whereas these are distinct metrics that should be treated separately.

###  Total Pool Count

The official website/analytics data displays only 41 pools, which is significantly fewer than the 59 pools shown in the subgraph data.

-  Please refer to the 'Protocol' sheet

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@amritkumarj Sorry for the delay here is the QA for Kwenta

**Comment by amritkumarj** [comment]
Thanks for the review above mentioned are fixed, you can check it using the same deployment link - https://thegraph.com/hosted-service/subgraph/amritkumarj/kwenta-optimism



## TVL 

TVL is zero now 
<img width="994" alt="image" src="https://github.com/messari/subgraphs/assets/72156537/35108542-40eb-45a0-81d6-eca805df0e82">


## Daily Volume

<img width="974" alt="image" src="https://github.com/messari/subgraphs/assets/72156537/8b69f69b-a26b-4a4d-92a4-3e7ceef8a158">
<img width="1238" alt="image" src="https://github.com/messari/subgraphs/assets/72156537/d2035985-60f7-4d51-b437-8c03687812a0">


5-day average (June 1 - June 5, 2023)

Subgraph - Daily Volume | Official Website - Daily Volume | Absolute difference | Difference %
-- | -- | -- | --
40390418.843 | 37682361.8 | +2708056.6 | ~7%


## Total Open Interest (14 Jul 2023)
Subgraph - Total Open Int. | Official Website - Total Open Int. | Absolute difference | Difference %
-- | -- | -- | --
102,636,324 | 104,725,845 | -20,89,521 | ~-2%

## Pool Count

Subgraph - Pool Count | Official Website - Pool Count | Difference
-- | -- | -- 
42 | 42 | 0

**Comment by bye43** [comment]
@ishraq8 Can you take a look at this when you get the chance?

**Comment by ishraq8** [comment]
@amritkumarj I think TVL should reflect liquidity sourced from synthetix, similar to yield aggregators. checking the rest of protocol and will get back.

**Comment by ishraq8** [comment]
one more questions:
1) open interest on mainsite and subgraph are different:
![Screen Shot 2023-07-17 at 8 23 53 AM](https://github.com/messari/subgraphs/assets/47088402/7fa4d16c-8220-4102-9fb1-1a5866ce7b3a)
![Screen Shot 2023-07-17 at 8 24 00 AM](https://github.com/messari/subgraphs/assets/47088402/2117ca48-43e1-4ce3-b1d3-cd11e76af6ca)

Other than open interest and TVL, subgraph looks very good. thank you @amritkumarj

**Comment by amritkumarj** [comment]
Hey @ishraq8 thanks for the review

TVL - Previously we calculated it using the margin deposits but according to the review it should be zero, so should I change it back like it was before

Open Interest - If you are talking about the above images graph difference, the official website graph is comparing open interest of different markets and our graph is the daily total open interest of the whole protocol, so they are different graphs.

If you are talking about that our Total Open Interest is - ~$130M and their ~$148M, the difference is because the 130M is of the previous day and the snapshot for today is not yet taken, if you want to see the current total open interest you can view the total open interest usd variable in the protocol data

<img width="1217" alt="image" src="https://github.com/messari/subgraphs/assets/72156537/82e20d4e-2bcc-43f1-aa4d-ad79a17082f2">

![image](https://github.com/messari/subgraphs/assets/72156537/a8ac97a1-235a-4ab1-a4ab-49b66c29b746)

(The little bit difference is because the market is constantly moving up and down every second)

**Comment by ishraq8** [comment]
@amritkumarj Talked to @bye43 and others on team. Lets do deposits from synthetix to kwenta as TVL. technically it should be zero but we currently dont support synthetix and also it looks odd on front end explorer.

we will take a note of it in the docs and come back to it when we deploy synthetix

**Comment by amritkumarj** [comment]
Gotcha! So, calculate the TVL by the SUSD margin deposits in Kwenta, right?

**Comment by ishraq8** [comment]
@amritkumarj yes sir, it should be different from `totalOpenInterest` that you calculated

**Comment by amritkumarj** [comment]
@ishraq8 Sorry I am confused, we previously also calculated TVL using margin deposits, should we change it this time?

**Comment by ishraq8** [comment]
@amritkumarj Quick question, how are you calculating Open interest? is it also margin deposits?

**Comment by bye43** [comment]
cc: @amritkumarj

**Comment by ishraq8** [comment]
Amrit fixed it, looked good. Should be able to merge now

**Comment by bye43** [comment]
Should we close this issue @ishraq8?
