### ISSUE TITLE
Dashboard Pool Tab: Ignore internal fieldNames

### ISSUE THREAD

**Issue by nemani** [messari/subgraphs#222]
We are not using the `outputToken` field, but we are using an internal field with the name `_outputTokens`.
fields starting with `_` should be ignored in the dashboard as they are internal and not for the dashboard to read.

https://github.com/messari/subgraphs/blob/19f99a33c3211fd96df2afba5266769181c9e50c/dashboard/src/interfaces/tabs/PoolTab.tsx#L550

We should use `startsWith` instead of `contains` or better yet: ignore all field names starting with `_`

**Comment by nemani** [comment]
cc: @MichaelC1999 @this-username-is-taken

**Comment by MichaelC1999** [comment]
@nemani  Is the _ being used just for internal fields on the table data or does this apply to time series data as well?

**Comment by nemani** [comment]
We use `_internalFieldName` in multiple places you can see our subgraph schema here: https://github.com/nemani/subgraphs/blob/platypus-swap-2/subgraphs/platypus-finance/schema.graphql

Also Similar issue: OutputToken is optional so many we should check if before trying to read it? Or use some optional modifier like `maybenull?` 
https://github.com/messari/subgraphs/blob/19f99a33c3211fd96df2afba5266769181c9e50c/dashboard/src/common/chartComponents/TableEvents.tsx#L37

**Comment by MichaelC1999** [comment]
The dashboard pulls data from the Graph using pre-generated queries based on the protocol type and schema version. The query being made only pulls entities/fields that are specified in the common schema (for DEXs this is the `schema-dex-amm.graphql` file). Any additional fields on the subgraph aren't specified in the query and therefore do not get returned in the data. In this case, there won't be any conflict with the _ internal fields.

**Comment by MichaelC1999** [comment]
As far as the outputToken being optional, I actually made some revisions taking that into account today. This will be included in my next pull request.

**Comment by nemani** [comment]
Great! Lets revisit this once that PR is merged!

**Comment by this-username-is-taken** [comment]
@nemani the PR has been merged, would you be able to verify? Feel free to close the issue if it's fixed in the update
