### ISSUE TITLE
#bug; velodrome optimism subgrpah - fatal error

### ISSUE THREAD

**Issue by MSilb7** [messari/subgraphs#2221]
**Describe the bug**

https://okgraph.xyz/?q=messari/velodrome-optimism

**Reproduction**
Where can we see this bug in action?

1. Link to subgraph on [`okgraph.xyz`](https://okgraph.xyz/?q=messari/velodrome-optimism)
2. Optional: link on graph protocol - [thegraph](https://thegraph.com/hosted-service/subgraph/messari/velodrome-optimism)

**Expected behavior**
Not an indexing error

**Screenshots**
<img width="855" alt="image" src="https://github.com/messari/subgraphs/assets/4006780/e4122576-e899-48c3-b39f-0a91d3e9ea75">

**Additional context**

**Comment by bye43** [comment]
Thanks for raising @MSilb7! There is a PR out for this and a corresponding issue, which you can track here - https://github.com/messari/subgraphs/issues/2209. Going to close this one out as a duplicate
