### ISSUE TITLE
#bug; GMX Avalanche - missing snapshots

### ISSUE THREAD

**Issue by GuyPie** [messari/subgraphs#2229]
**Describe the bug**
In the GMX Avalanche graphs, many positions have a single snapshot with a 0 balance, which doesn't make sense because a position must have a size when it is opened.

**Reproduction**

Run the following query on https://thegraph.com/hosted-service/subgraph/messari/gmx-avalanche -

`positions {
    snapshots(orderBy: timestamp, orderDirection: asc) {
      balance
      balanceUSD
      collateralBalance
      collateralBalanceUSD
      timestamp
    }
  }
`

**Expected behavior**
None of the positions should have a single snapshot with 0 balanche.

**Screenshots**
<img width="1454" alt="Screenshot 2023-06-22 at 14 05 30" src="https://github.com/messari/subgraphs/assets/3736200/900de146-8577-434f-bb79-87a9bfa6a4aa">

**Additional context**
The GMX Arbitrum graph has no instances of this happening.

**Comment by ishraq8** [comment]
It looks like on avalanche these are closed positions. On arbitrum subgraph closed positions show the value right before close and the 0 position at close. On avalnche we are not picking up the position right before close.

@corerouter can you take a look when you get a chance?

![Screen Shot 2023-06-22 at 10 43 40 AM](https://github.com/messari/subgraphs/assets/47088402/1ce453ad-bfd1-4dbf-a430-825e8a9cb86d)
![Screen Shot 2023-06-22 at 10 43 55 AM](https://github.com/messari/subgraphs/assets/47088402/85526787-dacb-4555-b90d-b1d3deee12a7)

**Comment by corerouter** [comment]
Actually, As of the current time when I reply, if you check the pending version of GMX subgraph, it did not pick up the position right before close either, as shown in the following screen shot.
<img width="1203" alt="image" src="https://github.com/messari/subgraphs/assets/28422812/a9859ff6-f559-42d3-ac98-d42456b4fc11">

Both the pending Arbitrum GMX subgraph and current version Avalanche subgraph were deployed 7 days ago based on #2075 which rewrote the previous GMX subgraph source codes. Now both GMX subgraph and Mummy Finance subgraph share the same codes based on Perp Lib. So, I think the current behavior for the snapshot is introduced by #2075 

Based on the above observations, the developer for #2075, @shashwatS22, may be the best person to check the issue and give a more accurate evaluation. Thanks!

**Comment by shashwatS22** [comment]
I'll have a look and get back to you. Thanks!

**Comment by ishraq8** [comment]
@dhruv-chauhan I think it is the SDK, i am creating an issue to upgrade the sdk and then we can fix GMX mummy and gains.

**Comment by GuyPie** [comment]
FYI there are other issues except for the missing snapshots, it's all probably related to the rewrite in https://github.com/messari/subgraphs/pull/2075. Many positions have `timestampClosed: null`, which would indicate they're still open but they are in fact closed. For example this position which was closed more than a year ago, on June 8th 2022. Is it possible to deploy a reverted version of the graph until the data issues in the current version are resolved? Or at least keep the GMX Arbitrum graph using the correct data from the previous version.

<img width="705" alt="Screenshot 2023-06-24 at 8 58 41" src="https://github.com/messari/subgraphs/assets/3736200/48cb8ddc-720b-482f-9e1f-8f82385364c6">

**Comment by ishraq8** [comment]
@GuyPie thanks for bringing it up, this is really helpful in making these better.

Temporarily can you use the old deployments for @corerouter 
https://thegraph.com/hosted-service/subgraph/corerouter/gmx-avalanche
https://thegraph.com/hosted-service/subgraph/corerouter/gmx-arbitrum

see if these work for you and if you have any issues. Sorry for the inconvenience.

**Comment by ishraq8** [comment]
this was resolved here: https://github.com/messari/subgraphs/pull/2241
