### ISSUE TITLE
Add TVI and TVE for bridges to dashboard

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2235]
@dhruv-chauhan Believe that TVI and TVE used to be part of the dashboard for bridges, but looks like they might have been accidentally removed in that last dashboard release

**Comment by dhruv-chauhan** [comment]
`totalValueExportedUSD` and `totalValueImportedUSD` were [introduced](https://github.com/messari/subgraphs/commit/18899c24331ada7ae2562e4f1c76145ab850bee1) in bridge schema v1.2.0. Subgraphs with schema>=1.2.0, do have graphs for these entities - example [in axelar](https://subgraphs.messari.io/subgraph?endpoint=messari%2Faxelar-ethereum&tab=protocol&view=financialsDailySnapshots-totalValueExportedUSD).

**Comment by bye43** [comment]
Ahh my mistake, thanks for the explanation!
