### ISSUE TITLE
#bug; SDK not getting position right before close

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#2236]
**Describe the bug**
Position data at close shows 0, which is technically accurate but we also want to show the value of the position right before close. Can we upgrade the sdk to reflect this? Older version of GMX was doing this which @corerouter had made.

**Reproduction**
Where can we see this bug in action?

This is what we get: 
![image](https://github.com/messari/subgraphs/assets/47088402/289bce29-60e5-40f6-acfd-918922027fb2)

This is what we might expect :
![image](https://github.com/messari/subgraphs/assets/47088402/a37f18eb-e10a-40e5-8b8c-e1f0dcaa70ca)

See discussion here for reference: https://github.com/messari/subgraphs/issues/2229

```[tasklist]
### Tasks
- [ ] Position balance right before close
- [ ] timestampclosed: null issue
```

**Comment by ishraq8** [comment]
![image](https://github.com/messari/subgraphs/assets/47088402/b5b9b207-3991-4246-9e53-07970784ff1f)

Also looks like`timestampclosed: null` in some of the snapshots: https://github.com/messari/subgraphs/issues/2229#issuecomment-1605281967

**Comment by dhruv-chauhan** [comment]
on it :vulcan_salute:

**Comment by dhruv-chauhan** [comment]
Hey @ishraq8 , PR #2241 should fix this.
Deployments and example query are in the PR description. Could you please verify?
