### ISSUE TITLE
Ellipsis Finance - non-fatal build and deployment errors

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#224]
<img width="599" alt="Screen Shot 2022-05-22 at 5 41 56 PM" src="https://user-images.githubusercontent.com/56660047/169717146-54946f72-3ebd-48e1-8f73-bc6e4c2121a7.png">

When I build and deploy this subgraph. I run into these errors. Its probably because this is a required field.

**Comment by this-username-is-taken** [comment]
@tannishmango
