### ISSUE TITLE
Update dashboard to support arbitrum network

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2248]
Now that all of the query IDs for the decentralized network on arbitrum we need to:

- update the links on the dashboard
- pull any metadata from the new URL: https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/[subgraph-id]

**Comment by dhruv-chauhan** [comment]
The decentralized network links were updated earlier, however there was a bug which should be fixed in PR #2253
