### ISSUE TITLE
#bug; YA `VaultSnapshot` initializer issues

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2256]
**Describe the bug**
It is possible that a `vaultSnapshot` can be initialized and the TVL (and other fields) are set to 0, but then they are never updated to their proper value.

This is causing false 0s in snapshots.

To fix this:
- When a snapshot is initialized, any cumulative values or "running total" values should be set to the `vault` values on initialization, and not after the fact.
- The affected subgraphs:
    - BadgerDao
    - Vesper
    - Convex Finance
    - Belt Finance
    - Stakedao
    - Ribbin Finance
    - Yearn V2
- This fix can be applied to all of the listed subgraphs in the same PR since the issue is exactly the same

**Comment by dhruv-chauhan** [comment]
@dmelotik I've done the change for the protocols you mentioned. Just confirming if we have to do this for other YA subgraphs too, or are these it for now?

**Comment by dmelotik** [comment]
yes, those are the only protocols I saw that had the issue @dhruv-chauhan
