### ISSUE TITLE
#bug; Morpho TVLs don't add up

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2267]
**Describe the bug**
This is an issue in Morpho where the TVL of the market's and market snapshots do not add up to the same thing in the overall protocol snapshots.

**Explanation**
What is good:
- As expected the sum of market TVLs = protocol TVL
- This is good, that means those pieces of data are good

What is bad:
- The sum of `marketDailySnapshots` on a given day does not add up to the `financialSnapshot.TVL`
- If there is a missing `marketDailySnapshot` you would expect that nothing in the market has changed, so in those cases the most recent snapshot should still sum up to the `financialSnapshot.TVL`, but this is not the case.

Seen in Morpho Aave V2 (might also be an issue in Morpho Compound):
Looking at 5/8/2023:
- The `financialSnapshot.TVL = 696,994,592.684`. However the sum of the `marketSnapshot.TVLs` is `~780M`

**Comment by bye43** [comment]
@harsh9200 Do you mind taking a look at this when you get the chance? Noticed cause on the messari FE we are propagating that stETH market spike, but it does not look like the subgraph `financialDailySnapshot` is
![Screenshot 2023-07-06 at 2 48 58 PM](https://github.com/messari/subgraphs/assets/107651107/9db12ec4-6b92-4c61-b0cb-9f4f9f5101f0)
![Screenshot 2023-07-06 at 2 49 50 PM](https://github.com/messari/subgraphs/assets/107651107/8978d425-ddc0-415f-971a-06c5b640fd70)
