### ISSUE TITLE
#feature; Support swap only DEXs

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2268]
**Goal**
We want skinny subgraphs for the following protocols:
- uniswap V2
- Pancakeswap
- quickswap

**What is a skinny subgraph?**
- We only want swap events. Every other (unnecessary) entity can be commented out.
- We do not need pricing data
- So, within the swap events we can set `swap.amountUSD` to 0

**Acceptance criteria**
- There is an open PR with all of the above for those 3 subgraphs
- From there we will deploy to `messari/[deployment-name]-skinny`

**Comment by dmelotik** [comment]
Deployments:
- https://thegraph.com/hosted-service/subgraph/messari/pancakeswap-v3-swap-bsc
- https://thegraph.com/hosted-service/subgraph/messari/pancakeswap-v3-swap-ethereum
- https://thegraph.com/hosted-service/subgraph/messari/uniswap-v2-swap-ethereum
- https://thegraph.com/hosted-service/subgraph/messari/quickswap-swap-polygon

**Comment by this-username-is-taken** [comment]
@dmelotik  I just noticed we should be getting pancake v2 not v3. v2 is the one that takes forever to index

**Comment by dmelotik** [comment]
https://api.thegraph.com/subgraphs/name/messari/pancakeswap-v2-swap-bsc
