### ISSUE TITLE
#feature; Mummy Finance on arbitrum

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#2272]
Mummy Finance was launched on arbitrum last week: https://twitter.com/mummyftm/status/1674822863474556929?s=20

We can fork the other deployments for this for full coverage.

Talked to @shashwatS22 about potentially doing this.

**Comment by dmelotik** [comment]
Can be QA'd: https://okgraph.xyz/?q=messari%2Fmummy-finance-arbitrum

**Comment by ishraq8** [comment]
QA pass
