### ISSUE TITLE
Lido Ethereum: Protocol Revenue spike on 06/30/2023

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2279]
![lido-dailyProtocolSideRevenueUSD-071223](https://github.com/messari/subgraphs/assets/107651107/7cd8c45e-f0a4-4e37-bf25-bd06df8c091a)
https://subgraphs.messari.io/subgraph?endpoint=messari%2Flido-ethereum&tab=protocol&view=financialsDailySnapshots-dailyProtocolSideRevenueUSD

**Comment by dmelotik** [comment]
Also, `cumulativeSupplySideRevenueUSD` decreased on 6/28/23. What is weird about this one is that there is no negative daily rev
