### ISSUE TITLE
Rocket-Pool Ethereum: No data after 04/17

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2280]
Looks like the subgraph [is healthy](https://okgraph.xyz/?q=QmdcfAF8q5V4acFddxmGMiG2UMPeUbyeSQoseSR14E9fqD), but there is no data being recorded after 04/17/2023
![Screenshot 2023-07-12 at 6 03 50 PM](https://github.com/messari/subgraphs/assets/107651107/4dec31b9-49bb-475c-bce9-473cf5fddcda)

**Comment by dmelotik** [comment]
Tried redeploying. There are a bunch of weird errors in the logs, like this. So maybe something got messed up?

```
An error occurred while streaming blocks: status: Unknown, message: \"error reading a body from connection: stream error received: unexpected internal error encountered\", details: [], metadata: MetadataMap { headers: {} }: error reading a body from connection: stream error received: unexpected internal error encountered: stream error received: unexpected internal error encountered, provider: mainnet-firehose-sf, deployment: QmdcfAF8q5V4acFddxmGMiG2UMPeUbyeSQoseSR14E9fqD, component: FirehoseBlockStream```

**Comment by dhruv-chauhan** [comment]
Rocket-pool contracts were updated on 5/20/2023; updated subgraph to use `rocketStorage` contract to get latest contract address as they are deployed.

@bye43

**Comment by bye43** [comment]
This lgtm
