### ISSUE TITLE
LEVEL - BSC

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2283]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=QmWfHyE83LzoGJcdk1ymFnkJTABJRe4vRHJcYVaHA8dcg8&tab=protocol
| Schema Version  |  1.3.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1EomrFe8LjyFkMxNwnRz5QLMTmyGDGpue/edit?usp=drive_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  Total Value Locked (TVL)

- The TVL data provided in our analysis shows a discrepancy of 24.30% compared to the data on the official website and a 21.99% discrepancy compared to Defi Llama's data, based on a 5-day average. 
- 
5-day average (July 8 - July 12, 2023)

| Subgraph - TVL| Official Website - TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 18,837,181.34| 15,154,857.20 | 3,682,324.14| 24.30%| 

| Subgraph - TVL | Defi Llama - TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 18,837,181.34| 15,442,000.00 | 3,395,181.34| 21.99%| 

-  Please refer to the 'Protocol' sheet

###  Total Pool Count

- As per the official website, there are three liquidity pools available: the Senior tranche, Mezzanine tranche, and Junior tranche. These pools offer different levels of risk and potential returns to cater to the diverse preferences of investors.

-  Please refer to the 'Protocol' sheet

###  Pool Overview

- The overall TVL data provided here exhibits a discrepancy of 25.66% when compared to the data on the official website.
- Instead of just having one pool, the platform shows three liquidity pools, namely the Senior tranche, Mezzanine tranche, and Junior tranche, as stated on the official website. These distinct pools provide different risk-reward profiles, allowing users to select the option that best suits their investment preferences and risk tolerance.

-  Please refer to the 'Pool_Overview' sheet

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@shashwatS22 QA for Level!

**Comment by ishraq8** [comment]
Looks like the TVL issue was resolved and it does have 3 tranches but a single pool which is shown in subgraph.

@shashwatS22 was there a deployment for arbitrum?

**Comment by ishraq8** [comment]
QA passed on arbitrum. can merge
