### ISSUE TITLE
#bug; Hop Protocol Error

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2304]
**Describe the bug**
https://okgraph.xyz/?q=messari%2Fhop-protocol-ethereum
https://okgraph.xyz/?q=messari%2Fhop-protocol-xdai

```
A determinstic fatal error occured at block 17787408: transaction 94b561b8c6ff4373934b03dcc05b762638672355dda8b7f7ff259402f1de29eb: Critical error logged in mapping wasm backtrace: 0: 0xee17 - <unknown>!protocols/hop-protocol/src/mainnet/bridge/handleTransferSentToL2 in handler `handleTransferSentToL2` at block #17787408 (1b711836832ebc5eafec7d3e99092948c3ab689e6bd9b86d18ffc5f0741cb9f6)
```

cc @itsjerryokolo

**Comment by itsjerryokolo** [comment]
I'll take a look.

**Comment by itsjerryokolo** [comment]
@dmelotik So I found the issue. They broke because ETH were being transferred to Base (chainId: 8453) and there's currently no config.  I think they are probably testing so they can add support.

**Comment by dmelotik** [comment]
Thanks @itsjerryokolo ! I am thinking it would be good to add the base config into the subgraph, what do you think?

**Comment by bye43** [comment]
Ahh thanks for raising this @cryptomarabout will make a separate issue
