### ISSUE TITLE
#bug; GMX Arbitrum showing 0 on June 26, 2023

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#2307]
**Describe the bug**
 The issue here is that the subgraph isn't returning any input token volume values for 2023-06-26: could not convert pool daily metric snapshot schema to model: count of input tokens (10) does not match count of daily volume by token USD (0).
 @jaksonkallio noticed on back ned

**Reproduction**
[https://api.thegraph.com/subgraphs/name/messari/gmx-arbitrum/graphql?query=%7B%0A++li[…]++++++id%0A++++%7D%0A++++dailyVolumeByTokenUSD%0A++%7D%0A%7D](https://api.thegraph.com/subgraphs/name/messari/gmx-arbitrum/graphql?query=%7B%0A++liquidityPoolDailySnapshots%28%0A++++first%3A5%2C%0A++++orderBy%3Adays%2C%0A++++orderDirection%3Adesc%2C%0A++++where%3A+%7B%0A++++++days%3A+19534%2C%0A++++%7D%0A++%29%7B%0A++++days%0A++++inputTokens+%7B%0A++++++id%0A++++%7D%0A++++dailyVolumeByTokenUSD%0A++%7D%0A%7D)

**Expected behavior**
Data for the date

**Screenshots**
![image](https://github.com/messari/subgraphs/assets/47088402/f98baa58-888e-4b40-a147-a2fff2c33c17)

**Comment by dhruv-chauhan** [comment]
This is happening when a new input token is added, which causes uneven lengths of inputTokens across snapshots. The snapshotter calls the `subtractArrays` helper method, which has been updated in the PR to handle uneven length arrays.

**Comment by ishraq8** [comment]
Looks good thanks for the fix
