### ISSUE TITLE
Polygon Bridge - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2319]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmSpk5gpsCxsaikuxYQHiPoPSZY3oGzvg7obVcvSc78F36&tab=protocol
| Schema Version  |  1.1.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1x1uQ6EBUPrKfA0UVRJadKlQGNXgJtEZA/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview - TVL

- The Pool Overview section displays only a total of 50 tokens, whereas the website of Polygon's native bridge showcases 2460 tokens.

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@nemani

**Comment by nemani** [comment]
I think there was some mistake in the qa. There are 49 pages of 50 pools
each in the subgraph page which should be equal to what is displayed on the
bridge website.

Thanks

**Comment by bye43** [comment]
@nemani Ya just double checked this! Looks good to me. @dmelotik This should be good to go then.
