### ISSUE TITLE
Uniswap-V3 Optimism: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2333]
Link: https://okgraph.xyz/?q=messari%2Funiswap-v3-optimism
optimism: 108380846
```A determinstic fatal error occured at block 108380846: transaction 3cc452c70c81c1300c65169d261f5c4ad037b48da2139bf0743429d6e100de96: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x53ad - <unknown>!~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x548f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 2: 0x8c73 - <unknown>!src/common/entities/token/getOrCreateToken 3: 0x9a4a - <unknown>!src/common/entities/pool/createLiquidityPool 4: 0xc070 - <unknown>!src/mappings/factory/handlePoolCreated in handler `handlePoolCreated` at block #108380846 (79d22a108667bd24a7e92bac67420fbc027d8eb2dd641c7275bbea4d07bffb73)```

**Comment by dmelotik** [comment]
https://okgraph.xyz/?q=dmelotik%2Funiswap-v3-optimism
