### ISSUE TITLE
Add filter on subgraphs.xyz for substream-based subgraphs

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2334]
@dhruv-chauhan Imagine we can add this to the top of the page next to `Version Comparison`, as another page and called it `Substreams-Based Subgraphs`.
![Screenshot 2023-08-18 at 10 26 52 AM](https://github.com/messari/subgraphs/assets/107651107/ff3f56cd-4b1a-493c-9ced-ce40bdb60b11)

**Comment by dmelotik** [comment]
Thinking about how to identify substream based subgraphs. Open to any thoughts @dhruv-chauhan. Maybe the easiest option is to just reserve `substream-` to substream based subgraphs and you can filter on that

**Comment by dhruv-chauhan** [comment]
I was thinking `"base": "substreams"` for the substream powered subgraphs

https://github.com/messari/subgraphs/blob/master/deployment/deployment.json#L5246C14-L5246C24
