### ISSUE TITLE
#qa; Comp V3 Base

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2335]
Looking to ensure the data looks right for Compound V3 Base.

> This is more of a sanity check, given we know the data is right on other comp v3 deployments.

Note: Reward token ($COMP) price is not available through any oracles or DEXs right now.

Visualizer link: https://subgraphs.messari.io/subgraph?endpoint=https://api.studio.thegraph.com/query/32057/compound-v3-base/version/latest&tab=protocol

**Comment by ishraq8** [comment]
Did QA, this looks very good. only issue is that reward tokens is showing up as $0. Might be pricing issue. 
<img width="1269" alt="Screen Shot 2023-08-18 at 2 20 19 PM" src="https://github.com/messari/subgraphs/assets/47088402/15a4997e-9f9c-4504-ba6a-0ee766e990b9">

**Comment by ishraq8** [comment]
never mind, passes QA. i missed the comment. great work @dmelotik

**Comment by dmelotik** [comment]
#2323
