### ISSUE TITLE
Uniswap-V2 Ethereum: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2339]
Link: https://okgraph.xyz/?q=messari/uniswap-v2-swap-ethereum
```A determinstic fatal error occured at block 17308596: transaction a8c3aeeab902eefb325592237b07050ba4ac9027baa2390699b01afc9b2d7c91: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x367f - <unknown>!src/common/getters/getOrCreateToken 1: 0x3ced - <unknown>!src/common/creators/createLiquidityPool 2: 0x45be - <unknown>!src/mappings/factory/handlePairCreated in handler `handlePairCreated` at block #17308596 (b88be2ee58ee136c5425c71f08136a0c1e69dfe02b6cdd00f757953f5b81dc98)```

**Comment by dmelotik** [comment]
https://okgraph.xyz/?q=dmelotik%2Funiswap-v2-ethereum
https://okgraph.xyz/?q=messari%2Funiswap-v2-swap-ethereum
