### ISSUE TITLE
#bug; Pancakeswap V2 Indexing Error

### ISSUE THREAD

**Issue by melotik** [messari/subgraphs#2389]
See: https://okgraph.xyz/?q=messari%2Fpancakeswap-v2-swap-bsc

<img width="760" alt="Screen Shot 2023-09-28 at 9 59 06 AM" src="https://github.com/messari/subgraphs/assets/60583747/534091c0-87d3-4ac2-ba90-a0d3663afcf0">

**Comment by melotik** [comment]
Same issue occuring, re-opening this issue to track it.

<img width="673" alt="Screen Shot 2023-10-13 at 3 11 14 PM" src="https://github.com/messari/subgraphs/assets/60583747/beba0960-f900-4db6-9ecb-5cbb08f80e51">

**Comment by bye43** [comment]
@melotik I made a new one (https://github.com/messari/subgraphs/issues/2400), so going to close this
