### ISSUE TITLE
Build EigenLayer Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2392]
`non-standard` subgraph

Website: https://www.eigenlayer.xyz/

**Comment by bye43** [comment]
@dhruv-chauhan

- [ ]  Looks like on the poolsnapshots there is a lot of dates missing snapshots (makes sense cause there is probably no events), but the TVL/inputTokenBalances on the three strategies look to p fluctuating p heavily which I do not think should be the case. Examples below

[Strategy-Liquid staked Ether 2.0](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmTJaP3Tg86SCNemCybMk5CACqXnoquKj7f99dhuKYMF7c&tab=pool&poolId=0x93c4b944d05dfe6df7645a86cd2206016c51564d)
![eigenlayer-0x93c4b944d05dfe6df7645a86cd2206016c51564d-daily-inputTokenBalances  0  -102423](https://github.com/messari/subgraphs/assets/107651107/3acc5ae6-039b-4764-9e0e-f603719efbf1)
![eigenlayer-0x93c4b944d05dfe6df7645a86cd2206016c51564d-daily-totalValueLockedUSD-102423](https://github.com/messari/subgraphs/assets/107651107/6b39ad6a-ecc6-441e-8b33-249f6188463d)

- [ ] It also looks like we are not recording the withdrawal and deposit volume for the strategies correctly compared to this [Dune dashboard](https://dune.com/21co/eigen-layer). For example, on stETH the [largest deposit on the subgraph is like 5ETH](https://api.thegraph.com/subgraphs/id/QmTJaP3Tg86SCNemCybMk5CACqXnoquKj7f99dhuKYMF7c/graphql?query=%7B%0A++pool+%28id%3A+%220x93c4b944d05dfe6df7645a86cd2206016c51564d%22%29+%7B%0A++++name%0A++++dailySnapshots%28orderBy%3A+dailyDepositVolumeAmount%2C+orderDirection%3A+desc%29+%7B%0A++++++timestamp%0A++++++dailyDepositVolumeAmount%0A++++%7D%0A++%7D%0A%7D%0A), while it is much larger on the dashboard and on a different date.
![Screenshot 2023-10-24 at 5 59 13 PM](https://github.com/messari/subgraphs/assets/107651107/02ba55d3-4d0a-43be-92a6-1d7f15c22b1e)

![Screenshot 2023-10-24 at 5 59 31 PM](https://github.com/messari/subgraphs/assets/107651107/f2d8dfc4-ef82-4927-8a1f-97ce204b8c69)

**Comment by dhruv-chauhan** [comment]
@bye43 there was a problem with pool snapshot IDs, fixed now - should resolve the above comments.

**Comment by bye43** [comment]
@dhruv-chauhan looks better now! One other things I found:

- [ ] It looks like some of the strategy snapshots are returning negative `dailyWithdrawalVolumeAmount`values, which should not be the case. If it was negative, then there should just be a deposit. [Query](https://api.thegraph.com/subgraphs/id/QmaKD1VfVL5Hxoe52EY2ss1GJjGuvmHUykZiMp2iD6aVAL/graphql?query=%7B%0A++stETHSnapshots%3A+pool%28id%3A+%220x93c4b944d05dfe6df7645a86cd2206016c51564d%22%29+%7B%0A++++name%0A++++dailySnapshots%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%29+%7B%0A++++++timestamp%0A++++++dailyDepositVolumeAmount%0A++++++dailyWithdrawalVolumeAmount%0A++++%7D%0A++%7D%0A%0A++cbETHSnapshots%3A+pool%28id%3A+%220x93c4b944d05dfe6df7645a86cd2206016c51564d%22%29+%7B%0A++++name%0A++++dailySnapshots%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%29+%7B%0A++++++timestamp%0A++++++dailyDepositVolumeAmount%0A++++++dailyWithdrawalVolumeAmount%0A++++%7D%0A++%7D%0A%0A++rETHSnapshots%3A+pool%28id%3A+%220x1bee69b7dfffa4e2d53c2a2df135c388ad25dcd2%22%29+%7B%0A++++name%0A++++dailySnapshots%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%29+%7B%0A++++++timestamp%0A++++++dailyDepositVolumeAmount%0A++++++dailyWithdrawalVolumeAmount%0A++++%7D%0A++%7D%0A%7D).

- [ ] It also looks like the cbETH deposit/withdrawal volume is still different than the dune dashboard linked above. For some days, it looks like it is missing
![Screenshot 2023-10-30 at 11 43 54 AM](https://github.com/messari/subgraphs/assets/107651107/00fc5149-f558-4d92-ac97-f3471448d3ee)
![Screenshot 2023-10-30 at 11 43 46 AM](https://github.com/messari/subgraphs/assets/107651107/5846db8e-1a3e-4aaa-89e2-396b16e4500c)

**Comment by dhruv-chauhan** [comment]
Hey @bye43, could you check now for the above points
deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Feigenlayer-ethereum-2

**Comment by bye43** [comment]
@dhruv-chauhan negative values are fixed, but still missing cbETH values compared to dune

**Comment by bye43** [comment]
LGTM!
![Screenshot 2023-10-31 at 10 05 59 AM](https://github.com/messari/subgraphs/assets/107651107/983c9f59-830d-44f1-bbfc-85b6b9ce33d5)
