### ISSUE TITLE
Compound: rates don't change in snapshots

### ISSUE THREAD

**Issue by menaitm** [messari/subgraphs#242]
The chart on the Messari dashboard shows the rates are fixed throughout historical snapshots. But they should be changing over time ([see rates on Compound](https://compound.finance/markets/ETH)).

[https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/compound-ethereum&tab=pool&poolId=0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/compound-ethereum&tab=pool&poolId=0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5)

![image](https://user-images.githubusercontent.com/106617039/171232085-d78c27ff-5b09-4817-b5f4-edce9415f829.png)

Problem occurs for both the `hourly` and `daily` snapshots.

Replicate with the query:
```
{  			
  markets(
      first:1
      orderBy:totalValueLockedUSD
      orderDirection:desc
  ) {
      name
      dailySnapshots (
          first: 5
          orderDirection: desc
          orderBy: timestamp
      ) {
          blockNumber
          timestamp

          # Below should change over time but do not
          rates(orderBy:id) {
            id
            rate
          }
      }    
  }
}
```

**Comment by this-username-is-taken** [comment]
We are in code freeze for Graph Hack (https://thegraph.com/graph-hack/2022). Will release the new versions early next week.

**Comment by menaitm** [comment]
@this-username-is-taken thank you.

The Compound reward rates are also affected (show 0% for everything). Is 1.5.5 expected to patch this too?
eg. https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Fmessari%2Fcompound-ethereum&tab=pool&poolId=0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5&view=marketHourlySnapshots-rewardAPR

**Comment by menaitm** [comment]
I'll track reward rates in your separate issue here: https://github.com/messari/subgraphs/issues/288

Closing this issue once `1.5.5` is released

**Comment by dmelotik** [comment]
@menaitm feel free to track the fix in our [visualizer](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmQHYLfZt4oYaKYof6BQfmZdckJKS6zvuss2RNfZpgJ7To&tab=protocol) and [hosted service](https://thegraph.com/hosted-service/subgraph/messari/compound-ethereum?version=pending)

**Comment by menaitm** [comment]
@this-username-is-taken @dmelotik I'm unable to test the fix on the [hosted service](https://thegraph.com/hosted-service/subgraph/messari/compound-ethereum?version=pending):

![image](https://user-images.githubusercontent.com/106617039/172808815-7c6e870a-fb17-424d-a22c-e6c822826203.png)

**Comment by menaitm** [comment]
@dmelotik thanks for the fix! @this-username-is-taken are we able to get this deployed to the hosted service today so I can test tomorrow?

**Comment by this-username-is-taken** [comment]
> @dmelotik thanks for the fix! @this-username-is-taken are we able to get this deployed to the hosted service today so I can test tomorrow?

We will redeploy after the schema upgrade is done: https://github.com/messari/subgraphs/pull/324

**Comment by dmelotik** [comment]
Hey @menaitm thanks for keeping us sharp ! I am working on this new schema upgrade atm. Also interested to hear what kind of product you are working on with the subgraph data? thanks

**Comment by menaitm** [comment]
@dmelotik thanks. Product is for educational/research users, so we benefit from a standardized schema across all the Messari subgraphs for ease of use.

Is there a way to specify the subgraph/schema version when querying the Hosted service?
Required for backwards compatibility between current MAINNET version (1.5.3) and the one that's pending now (https://api.thegraph.com/subgraphs/id/QmZgu3RNLyB1c7Joi2kaHmCMx6n3BwEyPkpXGT3uS36a7z)

**Comment by this-username-is-taken** [comment]
You can just use the deployment ID to query
