### ISSUE TITLE
Hop-Protocol All: Indexing Error 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2422]
Looks like all the hop subgraphs have indexing errors, which might be the result of support of Linea Network.
```A determinstic fatal error occured at block 147941414: transaction e9f740fa15d14a0fa1e55d223699ee6a5b0ca24cef95788a18787d5e7644e069: Critical error logged in mapping wasm backtrace: 0: 0xfcbc - <unknown>!protocols/hop-protocol/src/L2/bridge/handleTransferSent in handler `handleTransferSent` at block #147941414 (b3c41eb709601441ae837052da1b8f14306f8a8713bf0c699a46653727a34b10)```

- [x] https://okgraph.xyz/?q=messari/hop-protocol-arbitrum
- [x] https://okgraph.xyz/?q=messari%2Fhop-protocol-ethereum
- [x] https://okgraph.xyz/?q=messari%2Fhop-protocol-optimism
- [x] https://okgraph.xyz/?q=messari%2Fhop-protocol-polygon
- [x] https://okgraph.xyz/?q=messari%2Fhop-protocol-gnosis

**Comment by bye43** [comment]
@dhruv-chauhan I am going to re-open this so that subgraphs.xyz users can see the gh issue. I will close when new versions are deployed.

**Comment by eldimious** [comment]
Hello, do we have any news on above issue, cause seems hop protocol is broken

**Comment by dhruv-chauhan** [comment]
@eldimious hop deployments are fixed and up now!
