### ISSUE TITLE
#bug; UNI asset is missing in for Venus

### ISSUE THREAD

**Issue by ronlv10** [messari/subgraphs#2427]
**Describe the bug**
The market UNI is missing in the subgraph of venus although it's listed in Venus protocol: https://app.venus.io/#/core-pool

**Reproduction**
Where can we see this bug in action?
```
{
  markets(first: 500) {
    inputToken {
      symbol
    }
    outputToken {
      id
    }
  }
}
```
https://api.thegraph.com/subgraphs/name/messari/venus-protocol-bsc/graphql?query=%7B%0A++markets%28first%3A+500%29+%7B%0A++++inputToken+%7B%0A++++++symbol%0A++++%7D%0A++++outputToken+%7B%0A++++++id%0A++++%7D%0A++%7D%0A%7D

1. Link to subgraph on [`okgraph.xyz`](https://okgraph.xyz/?q=messari%2Fvenus-protocol-bsc)
2. Optional: link on graph protocol

**Expected behavior**
A clear and concise description of what you expected to see.
UNI should be listed

**Screenshots**
![image](https://github.com/messari/subgraphs/assets/17575462/23a3cf39-4ffc-414c-b4bb-03d52478a8e1)

**Additional context**

**Comment by ronlv10** [comment]
Hey,
any update here?
Thanks!

**Comment by bye43** [comment]
@ronlv10 U believe we are missing that vault, so it is on our to-do to add it and redeploy the subgraph
