### ISSUE TITLE
#bug; Hop protocol Ethereum does not index transfers from Base 

### ISSUE THREAD

**Issue by cryptomarabout** [messari/subgraphs#2434]
The Hop Protocol Ethereum subgraph indexes transfers from ETH to Base, but not those from Base.

Subgraph: 
https://thegraph.com/hosted-service/subgraph/messari/hop-protocol-ethereum

Proof:
![image](https://github.com/messari/subgraphs/assets/72732919/53a083a3-0470-4f4b-9ac7-b10825998efe)

![image](https://github.com/messari/subgraphs/assets/72732919/c5aa3420-5024-4241-b00b-c0a401703cb0)

Tx example: https://etherscan.io/tx/0x1cd163144f4fbeac9bfbf1f7103ac8a0c83489402f087441fc5dfa0ca55fa69c

**Comment by dhruv-chauhan** [comment]
Hey @cryptomarabout , as per this [note in the README](https://github.com/messari/subgraphs/tree/master/subgraphs/hop-protocol#notes), we do not capture incoming transfers, regardless of the fromChainID, due to lack of events in their contracts.
