### ISSUE TITLE
Maker DAO build and deployment errors

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#244]
<img width="860" alt="Screen Shot 2022-05-31 at 1 22 11 PM" src="https://user-images.githubusercontent.com/56660047/171235399-2ae93b92-bb88-4d3c-aa16-89d3b2116e19.png">

These errors show up when I built the subgraph. These are most likely due to these fields not being marked as required in the schema, and they are used in the program without either checking if null or asserting not null with '!'. I tried to fix these issue for deployment by adding the exclamation, however, the deployment still failed when I tried to deploy to Messari Hosted service.

**Comment by tnkrxyz** [comment]
@steegecs , do you currently have deployment issue with makerdao subgraph? As @harsh9200 and I are discussing in #415, the makerdao subgraph in the master branch works for him, but I am getting a failure when I deploy it on hosted service (https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ext?selected=logs). I am wondering whether you were getting an error similar to what I am getting and whether it works for you now.

**Comment by steegecs** [comment]
The reason this is occurring is because the inputToken fields is required in the schema. The you run the program, it is telling you that you do not need the exclamation at the end, because it is never null, because it is a required field. I am not sure why it occurs when you deploy but not @harsh9200. I can look into this more, but for now, to get rid of the errors, just remove the exclamation.

**Comment by steegecs** [comment]
Yeah it seems to work for me. There is some sort of issue with this where it does not always trigger an error. These errors should actually trigger probably since these fields are required and will not be null. In the meantime, I'd recommend removing the exclamations and I'll follow up about this discrepancy.
