### ISSUE TITLE
Uniswap-V3 Arbitrum, Optimism, Polygon: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2465]
- Abitrum
https://okgraph.xyz/?q=messari/uniswap-v3-arbitrum
```A determinstic fatal error occured at block 174340925: transaction a01ff0ba11cb7c0be82aed9ba4e671e2b575993cf0aeda10163cd7da5ed4a728: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x53ad - <unknown>!~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x548f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 2: 0x8c73 - <unknown>!src/common/entities/token/getOrCreateToken 3: 0x9a4a - <unknown>!src/common/entities/pool/createLiquidityPool 4: 0xc070 - <unknown>!src/mappings/factory/handlePoolCreated in handler `handlePoolCreated` at block #174340925 (e87655a0140cf338143fba92a8a81b6d3f77802a1000a846a4bcbfd87e3019ff)```

- Optimism
https://okgraph.xyz/?q=messari/uniswap-v3-optimism
```A determinstic fatal error occured at block 115331326: transaction 968556c498e510bbcc8dde057affcc66192943000b06a7e143a6879b9901b993: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x53ad - <unknown>!~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x548f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 2: 0x900a - <unknown>!src/common/entities/token/getOrCreateToken 3: 0x9ccc - <unknown>!src/common/entities/pool/createLiquidityPool 4: 0xc30e - <unknown>!src/mappings/factory/handlePoolCreated in handler `handlePoolCreated` at block #115331326 (5e22b6c6039cd48d1a8e2acc241e29fab088f6bdbcc097f99fe41c2fd14ba0fb)```

- Polygon
https://okgraph.xyz/?q=messari/uniswap-v3-polygon
```A determinstic fatal error occured at block 52770144: transaction 1ef8bd15e82350e7f061c99f6ace434e46105065fac52b10c5497045f6b2ac85: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x53ad - <unknown>!~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x548f - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 2: 0x8c73 - <unknown>!src/common/entities/token/getOrCreateToken 3: 0x9a4a - <unknown>!src/common/entities/pool/createLiquidityPool 4: 0xc070 - <unknown>!src/mappings/factory/handlePoolCreated in handler `handlePoolCreated` at block #52770144 (dfff9164ffa5ebe039c51c414aa2516a8982aab4e2087c227e50c5267a9e60c4)```

**Comment by DyT9qC** [comment]
I have resolved the issue and recommend implementing the code fix as outlined here.

https://github.com/messari/subgraphs/pull/2467
