### ISSUE TITLE
Uniswap-V3-Swap Optimism: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2466]
https://okgraph.xyz/?q=messari/uniswap-v3-swap-optimism
```A determinstic fatal error occured at block 115331326: transaction 968556c498e510bbcc8dde057affcc66192943000b06a7e143a6879b9901b993: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 wasm backtrace: 0: 0x2acc - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 1: 0x4a6e - <unknown>!src/common/entities/token/getOrCreateToken 2: 0x506d - <unknown>!src/common/entities/pool/createLiquidityPool 3: 0x5ab5 - <unknown>!src/mappings/factory/handlePoolCreated in handler `handlePoolCreated` at block #115331326 (5e22b6c6039cd48d1a8e2acc241e29fab088f6bdbcc097f99fe41c2fd14ba0fb)```

**Comment by DyT9qC** [comment]
I have resolved the issue and recommend implementing the code fix as outlined here.

https://github.com/messari/subgraphs/pull/2467
