### ISSUE TITLE
uniswap v3: why no feeTier in liquidityPool?

### ISSUE THREAD

**Issue by guotie** [messari/subgraphs#2468]
**Describe the bug**

why no feeTier in liquidityPool?

**Comment by bye43** [comment]
Are you referring to feeType? On the Uniswap V3 Eth subgraph, I can query for the fee type and percentage - https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-ethereum/graphql?query=%7B%0A++liquidityPool+%28id%3A+%220xcbcdf9626bc03e24f779434178a73a0b4bad62ed%22%29+%7B%0A++++name%0A++++id%0A++++fees+%7B%0A++++%09feeType%0A++++++feePercentage%0A++++%7D%0A++%7D%0A%7D

**Comment by guotie** [comment]
OK，I konw

thanks
