### ISSUE TITLE
Integration of Morpho Blue Subgraphs, external repo

### ISSUE THREAD

**Issue by tomrpl** [messari/subgraphs#2471]
Hello Team,
**What do you think is missing?**
Based on your frameworks, at MorphoLabs we decided to implement the subgraphs of Morpho Blue, the new Morpho lending protocol.
For reference, here are the main websites:

1. https://app.morpho.org/index.html
2. https://morpho.org/index.html

**Describe the solution you'd like**

However, as we would love to maintain it and keeping it into our own org, we would love to know if it is possible to:
- support Morpho Blue

Here is the subgraphs: https://github.com/morpho-org/morpho-blue-subgraph

Thanks a lot for your time

**Comment by melotik** [comment]
@tomrpl thank you for sharing your code for the new Morpho Blue subgraphs, this makes it easy to recreate in our repo :)

@dhruv-chauhan we marked this as a p1 to copy this subgraph over into a `morpho-blue` folder in our repo. When you are done, @bye43 will do a QA and we should be g2g to merge it in. Thanks!

**Comment by tomrpl** [comment]
Hello @dhruv-chauhan 
Little bump here, our subgraphs are ready on our end, now that Morpho Blue has almost reached $130M of deposited asset, would it be possible to have it integrated? 
Happy to provide additional support if needed!

**Comment by tomrpl** [comment]
If needed, it has been deployed here already:
https://thegraph.com/hosted-service/subgraph/morpho-association/morpho-blue, but you may prefer use your own deployment if I am understanding it right! Thanks for the heads up, available if you need anything

**Comment by dhruv-chauhan** [comment]
@bye43 It's deployed and synced, ready for QA! 
https://okgraph.xyz/?q=dhruv-chauhan%2Fmorpho-blue-ethereum

**Comment by bye43** [comment]
@dhruv-chauhan can we add these fields as `NULL` or something, so we can use the visualizer or will the subgraph need to resync then?
![Screenshot 2024-03-05 at 10 08 31 AM](https://github.com/messari/subgraphs/assets/107651107/8a228947-fa3a-4741-83cb-7a3bd02abffc)

**Comment by dhruv-chauhan** [comment]
@bye43 the visualizer works now, same deployment

**Comment by bye43** [comment]
@dhruv-chauhan QA here: https://github.com/messari/subgraphs/issues/2498
