### ISSUE TITLE
#bug; Uniswap Arbitrum One - Indexing Error

### ISSUE THREAD

**Issue by po3na4skld** [messari/subgraphs#2506]
### Describe the bug

```
Subgraph instance failed to run: transaction 256ed218b87890eaba64f623e6bdf6dc01349b155880c25e0a657c5929ae5966: error while executing at wasm backtrace: 0: 0x53f9 - !~lib/@graphprotocol/graph-ts/common/collections/ByteArray#toI32 1: 0x54db - !~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toI32 2: 0x92f1 - !src/common/entities/token/getOrCreateToken 3: 0x9d60 - !src/common/entities/pool/createLiquidityPool 4: 0xc3a2 - !src/mappings/factory/handlePoolCreated: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/collections.ts, line 150, column 9, with message: overflow converting 0x0000000000000000000000000000000000000000000000000000000067e53c31 to i32 in handler handlePoolCreated at block #192237170 (837b279fd09a78f0e1005e6c343d97d8efafe43598be32a185233c44976ec5e7), code: SubgraphSyncingFailure
```

Link to subgraph on [okgraph.xyz](https://okgraph.xyz/): https://okgraph.xyz/?q=messari%2Funiswap-v3-arbitrum
Optional: link on graph protocol
https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-arbitrum?selected=logs

**Comment by bye43** [comment]
@dhruv-chauhan Looks like BSC, ETH, OP, and POL are all facing indexing errors too. 
-[ ] ETH : https://okgraph.xyz/?q=messari/uniswap-v3-ethereum
-[ ] BSC: https://okgraph.xyz/?q=messari%2Funiswap-v3-bsc
-[ ] OP: https://okgraph.xyz/?q=messari%2Funiswap-v3-optimism
-[ ] POL: https://okgraph.xyz/?q=messari%2Funiswap-v3-polygon

**Comment by radiofreejohn** [comment]
This contract is returning a bad value for `decimals`:

```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x0000000000958Ec6667EB97e2f64F6909073e6B7","data":"0x313ce567"},"0xb754e71"],"id":1}'  https://your-rpc-node
{"jsonrpc":"2.0","id":1,"result":"0x313ce56700000000000000000000000000000000000000000000000000000000"}
```

I suspect the [fix limiting the size of decimals on the official subgraph](https://github.com/Uniswap/v3-subgraph/pull/198) would apply here, but it also may be enough to blacklist the token [like in previous PRs](https://github.com/messari/subgraphs/pull/2470):
