### ISSUE TITLE
Stargate Arbitrum: Indexing Error

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2522]
https://okgraph.xyz/?q=messari%2Fstargate-arbitrum
```A non-deterministic fatal error occured at block 199539272: Failed to transact block operations: internal constraint violated: Batches must go forward. Can't append a batch with block pointer #199539272 (317cb83dc5e04f71a5f936a85030091f4646f2d178eb7d1d17b635d9eee0d465) to one with block pointer #199539291 (890955ff96830cfb114e5d62856ffdb8c61db1b12cdaaf1f7be439049480628d)```

**Comment by dhruv-chauhan** [comment]
Most probably an intermittent issue of the graph node, which fixed itself.
