### ISSUE TITLE
Dopex Arbitrum: Indexing Errors

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2524]
https://okgraph.xyz/?q=messari%2Fdopex-arbitrum
```A non-deterministic fatal error occured at block 199577827: Failed to transact block operations: internal constraint violated: Batches must go forward. Can't append a batch with block pointer #199577827 (9b90ed286057a8af2caf2a007284d034c92768eade65eaa3dc81d85a62f9914c) to one with block pointer #199577907 (bc4a1de3c7dbb8d70a077df901ab7ce4438066b15be6352eb567647c25becf66)```

**Comment by bye43** [comment]
@dhruv-chauhan A lot of the abritrum subgraphs had a similar indexing error to this, but the next day they seemed to fix themselves. So this may resolve itself, but I figured I would raise it incase it does not.

**Comment by dhruv-chauhan** [comment]
Most probably an intermittent issue of the graph node, which fixed itself.
