### ISSUE TITLE
Ive been hacked by my stolen laptop i need to emmed my files run a 16 year back up then put in my wallet please help me block the remote access 

### ISSUE THREAD

**Issue by zKazhz** [messari/subgraphs#2647]
**What do you think is missing?**
A clear and concise description of what the problem (or solution) is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

- new subgraph?
- new schema support?
- update schema?
- support new protocol?
- more docs?

**Describe alternatives you've considered**

**Additional context**
Add any other links, context, or screenshots to describe the feature requested.

**Comment by zKazhz** [comment]
I want to ude my data and crypto for wallet google psy

**Comment by ishraq8** [comment]
Please contact GitHub regarding compromised accounts
