### ISSUE TITLE
Compound reward emission issue

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#288]
Token emission are all zero. I believe they had a bug in their emission contract at the time and upgrade it to a different one. Probably worth looking into. @dmelotik 

https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Fmessari%2Fcompound-ethereum&tab=pool&poolId=0x39aa39c021dfbae8fac545936693ac917d5e7563&view=marketDailySnapshots-rewardAPR

<img width="908" alt="image" src="https://user-images.githubusercontent.com/2354636/172148302-0489b013-4625-455f-8582-8397fba0042a.png">

**Comment by dmelotik** [comment]
@this-username-is-taken @menaitm this issue was addressed here: https://github.com/messari/subgraphs/issues/240 is now merged into master so the `1.5.5` should address it.

**Comment by this-username-is-taken** [comment]
great!
