### ISSUE TITLE
Balancer V2 QA (Ethereum) Schema Version 1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#333]
| Description  | Value |
| ------------- | ------------- |
| Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/sevenshi/balancer-v2-ethereum&tab=protocol |
| Date Reviewed  |  June 16 2022  |
| Schema Version | 1.3.0 |
| Subgraph Version  | 1.1.0  |
| Methodology Version | 1.0.0  |
| Evidence Spreadsheet  | https://docs.google.com/spreadsheets/d/1rsxig-eZHN7Nrq-VXWz2CtWrEcoXwSgMt3VUuJCd8fk/edit?usp=sharing  |

### Metrics To Review
**Protocol Metrics**
| Section | Metric  | Issue | 
| ------------- | ------------- | ------------- | 
financialsDailySnapshots | dailyVolumeUSD | Big spikes in volume on 5/22
financialsDailySnapshots | cumulativeVolumeUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailySupplySideRevenueUSD | Big spike on 5/22 and values looking off across the board
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will also be. Supply and Protocol are also equivalent, which should not be the case.
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Big spike on 5/22 and values looking off across the board
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailyTotalRevenueUSD | Big Spike in revenue that looks off on 5/22
financialsDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will also be

**Pool Overview Metrics**
| Pool | Metric  | Issue | 
| ------------- | ------------- | ------------- | 
Balancer 80 BAL 20 WETH | Base Yield % | 775% when its like 13% on Balancer UI
AKITA Copper Launch | TVL (USD) | Huge TVL number that doesn't look right
AKITA Copper Launch | Base Yield % | 17.75% when it is like 1% on Balancer UI
Balancer 80 AURA 20 WETH | Base Yield % | 23% when Balancer UI is 161%

**Pool Metrics**
| Pool | Section | Metric  | Issue |
| ------------- | ------------- | ------------- | ------------- | 
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | Looks too low
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD | Looks too low
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | Numbers look to be in the right ball park, but does not seem like the correct daily is being added everyday
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - BAL | Does not look the price is being applied here. Values are too small
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - WETH | Same as above
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenSupply  B-80BAL-20WETH | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenPriceUSD  B-80BAL-20WETH | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | baseYield | 0.9% on Subgraph and Balancer UI reporting 9%
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | hourlySupplySideRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | cumulativeSupplySideRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | hourlyProtocolSideRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | cumulativeProtocolSideRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | hourlyTotalRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | cumulativeTotalRevenueUSD | Same problems as daily
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - BAL | Returning token amount and not USD value
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - WETH | Returning token amount and not USD value
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | outputTokenSupply  B-80BAL-20WETH | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | outputTokenPriceUSD  B-80BAL-20WETH | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolHourlySnapshots | baseYield | This doesn't look right because Balancer UI is saying 9% for this pool, so the hourly values should average around 9%

**Comment by KremerMichael** [comment]
these 4 pools have cumulative revenue greater than 10^39
```
0x088f073c4fc2f5d7af474cbb37fbe16b17fc2239
0xb28670b3e7ad27bd41fb5938136bf9e9cba90d65
0xcf3ae4b9235b1c203457e472a011c12c3a2fde93
0x17a35e3d578797e34131d10e66c11170848c6da1
```

Here is the code I used to catch this

```
import requests
import pandas as pd

murl = 'https://api.thegraph.com/subgraphs/name/messari/balancer-v2-arbitrum'

def get_liquidity_pools() -> pd.DataFrame:
    q = """
    {
      liquidityPools (first: 1000, orderBy: id, orderDirection: asc) {
        id
        name
        symbol
        inputTokens {
          id
          name
          symbol
          decimals
        }
        inputTokenBalances
        inputTokenWeights
        outputToken {
          id
          name
          symbol
          decimals
        }
        outputTokenSupply
        outputTokenPriceUSD
        stakedOutputTokenAmount
        allocPoint
        fees {
          feePercentage
          feeType
        }
        isSingleSided
        createdTimestamp
        createdBlockNumber
        totalValueLockedUSD
        cumulativeSupplySideRevenueUSD
        cumulativeProtocolSideRevenueUSD
        cumulativeTotalRevenueUSD
      }
    }
    """
    query = {'query':q}
    response = requests.post(murl, json=query).json()
    df = pd.DataFrame(response['data']['liquidityPools'])
    if len(df) == 1000:
        print('mike page this')
        return pd.DataFrame()
    
    df['totalValueLockedUSD'] = df['totalValueLockedUSD'].astype(float)
    df['cumulativeSupplySideRevenueUSD'] = df['cumulativeSupplySideRevenueUSD'].astype(float)
    df['cumulativeProtocolSideRevenueUSD'] = df['cumulativeProtocolSideRevenueUSD'].astype(float)
    df['cumulativeTotalRevenueUSD'] = df['cumulativeTotalRevenueUSD'].astype(float)
    
    return df
liquidity_pools = get_liquidity_pools()
liquidity_pools.sort_values('cumulativeTotalRevenueUSD', ascending=False)
```

**Comment by this-username-is-taken** [comment]
This is ready for review. The Ethereum deployment only has 300k blocks (0.25%) left to index.

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/balancer-v2-ethereum&tab=protocol
Date Reviewed | August 1 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1-mhYY2wHs-UfQwNfa_PCBChgrtFwv58hUbU0m0yyrfk/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | Huge spike on 07/27/2022 and 07/28/2022 that is throwing scaling off. I am guessing this is from a weirdly priced pool. Besides these dates, TVL looks good.
financialsDailySnapshots | dailySupplySideRevenueUSD | This looks off to me. There is >30% difference for most of the dates that I checked.
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailyProtocolSideRevenueUSD | This is looking very off. Balancer did not have protocol revenue till after 01/01/2022, so those values should be 0 on the subgraph. Also looks like the fee split between supply side and revenue side are incorrect. Currently 02/01/2022 is outputting data that displays fees as split 50/50, but this should be split 10/90, as the balancer proposal for changing fees to 50/50 did not happen till after Feb. Link to proposal - https://vote.balancer.fi/#/proposal/0x03e64d35e21467841bab4847437d4064a8e4f42192ce6598d2d66770e5c51ace
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailyTotalRevenueUSD | These values also look off here (>30% difference for most dates checked).
financialsDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will also be

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
AKITA Copper Launch | TVL (USD) | Pool TVL is off compared to Balancer UI . Balancer UI outputting 7.4m and subgraph outputting 400k. This is most likely a problem with supported token pricing I am guessing though. Link to Balancer UI - https://app.balancer.fi/#/pool/0xc065798f227b49c150bcdc6cdc43149a12c4d75700020000000000000000010b
ALL POOLS | Base Yield % | I know this is not part of the actual subgraph development, but the equation is stating that the Daily Supply Side revenue for all the pools is 0.
SOME POOLS | Reward Tokens | Seems like the majority of larger TVL pools should have reward tokens in BAL, as Balancer has liquidity mining incentives. Link to Balancer UI with pools showing staking APY - https://app.balancer.fi/#/

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | There are values here, which do not look that far off, but will recheck once daily is fixed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD | There are values here, which do not look that far off, but will recheck once daily is fixed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Outputting 0
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | There are values here, which do not look that far off, but will recheck once daily is fixed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - BAL | Does not look the price of the token is being correctly applied here. Values are too small and I would expect to see that the volume of both tokens in USD is = to 2x daily volume, which is not the case
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - WETH | Same as above
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenSupply  B-80BAL-20WETH | Outputting 0, which is incorrect. Link to etherscan of output token - https://etherscan.io/token/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenPriceUSD  B-80BAL-20WETH | Same as above
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | stakedOutputTokenAmount -  B-80BAL-20WETH | The BPTs from balancer can be locked into a contract in exchange for veBAL, so I believe there should be an output here. But if this does not count, I also checked the stETH/WETH pool and there is no output for this field, when these BPTs can be staked for liquidity mining rewards
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | rewardTokenEmissionAmount | Same as above. This pool looks like it receiving emissions via BAL, but is also could be a weird edge case since it is a veToken, but I also checked the stETH/WETH pool and there was no output here when there should be emissions of BAL here. See link to pool and hover over APY - https://app.balancer.fi/#/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | rewardTokenEmissions - USD | Same as above

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRhKJaZesH6WiZ29Jh6joeEXcJk1K9XbCW1Etj6DE3Moy&tab=protocol&version=pending
Date Reviewed | August 15 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1G05mD9iukWLeR87nEwcCSSJpH7lb9IdmVDmDcfjNt_o/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | There is another large spike on 05/22/2022 to 87b, which looks incorrect (guessing this is a weird pool ). There are a few dates (7/27/2022, 7/01/2022, 06/01/2022, 08/01/2022) that are >20% difference than dune, but it could be we are blacklisting certain pools?
financialsDailySnapshots | dailyVolumeUSD | This looks more accurate than the last version, but 05/22/2022 is a 2670% difference and 08/01/2022 is a 79% difference when compared to the dune dashboard. Link to dune dashboard (V2 Volume USD Column) - https://dune.com/queries/515765/998459
financialsDailySnapshots | cumulativeVolumeUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailySupplySideRevenueUSD | This looks off to me. There is >40% difference for most of the dates that I checked and on 08/01/2022 there is a 1841% difference. Link to dune query I am comparing against (V2 Supply-Side Revenue Column) - https://dune.com/queries/515765/998459
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Does not look like fees are being split correctly here (fees should split be 0/100, 10/90, 50/50, but I am seeing inconsistent splits like 8/92,27/73, etc) and the values still seem very off compared to dune dashboard. Dates, such as 05/01/2022, 04/01/2022, 02/01/2022, are >80% difference. Link to dune dashboard (V2 Protocol-Side Revenue USD Column) - https://dune.com/queries/515765/998459
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will also be
financialsDailySnapshots | dailyTotalRevenueUSD | This also look very off. Many dates that are >40% difference with dune dashboard. It also looks like on 08/01/2022 dailyTotalRevenue is 2.24% of dailyVolumeUSD, which seems too high since most of the balancer pool swap fees are => 1%. Link to dune dashboard (V2 Fees Column) - https://dune.com/queries/515765/998459
financialsDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will also be

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | This looks very off compared to the dune dashboard with some values being up to 100% off. Furthermore, does not look like the fee split is being applied correctly like in the protocol metrics sections. Link to dune dashboard (LP Revenue Column) - https://dune.com/queries/547472/1036171?1.+Pool_address_t6c1ea=0x5c6ee304399dbdb9c8ef030ab642b10820db8f56
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | Off because daily is
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Similar comments to dailySupplySideRevenueUSD. Values are not as far off, but does not look like the correct fee split is being applied to protocol revenue. Link to dune dashboard (Protocol Revenue Column) - https://dune.com/queries/547472/1036171?1.+Pool_address_t6c1ea=0x5c6ee304399dbdb9c8ef030ab642b10820db8f56
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD | Off because daily is
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Overall, the values are roughly 40%-80% difference from dune. Link to dune dashboard (Fees Column) - https://dune.com/queries/547472/1036171?1.+Pool_address_t6c1ea=0x5c6ee304399dbdb9c8ef030ab642b10820db8f56
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | Off because daily is
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenPriceUSD  B-80BAL-20WETH | This is 0 when I believe there should be a price. Balancer dashboard has a price - https://app.apy.vision/pools/balancerv2_eth-BAL-WETH-0x5c6ee304399dbdb9c8ef030ab642b10820db8f56
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | stakedOutputTokenAmount -  B-80BAL-20WETH | The BPTs from balancer can be locked into a contract in exchange for veBAL, so I believe there should be an output here. But if this does not count, I also checked the stETH/WETH and WETH/WBTC pool and there is no output for this field, when BPTs can be stacked for liquidity mining rewards
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | rewardTokenEmissionAmount | It looks like on the balancer UI that there are BAL rewards for this pool, but subgraph is not ouputting anything. Might be the case that there is not, but going to make a note. Link to Balancer UI - https://app.balancer.fi/#/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | rewardTokenEmissions - USD | Same as above
Balancer stETH Stable Pool | liquidityPoolDailySnapshots | ALL Daily Snapshots | No output for all daily snapshot metrics. Error - "cannot read properties of undefined (reading 'value')"
Balancer stETH Stable Pool | liquidityPoolHourlySnapshots | rewardTokenEmissionAmount | While the Balancer 80 BAL 20 WETH might not have BAL rewards, this pool does for sure. Subgraph is outputting null value, which is incorrect. Looks like rewards are good though for other pools like WETH/WBTC. Might be because of the additional LDO rewards.
Balancer stETH Stable Pool | liquidityPoolHourlySnapshots | rewardTokenEmissions - USD | Same as above

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmXwtdnSMuibCVfeqH7MTkZxe3Ha6fooYBXr2qZdKRRnV9&tab=protocol&version=pending
Date Reviewed | August 23 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1pPGreHlEMHKz2s4SsZz9bnGiKzodhR4ZQC-MJ89eypg/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | dailyVolumeUSD | 06/01/2022 and 03/01/2022 are showing about a 25% and 39% difference respectively. In the previous version these were a less than 2% difference looks like this is due to these three pools (0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb2, 0x9210f1204b5a24742eba12f710636d76240df3d0, 0x2bbf681cc4eb09218bee85ea2a5d3d13fa40fc0c).Current version query - https://api.thegraph.com/subgraphs/name/messari/balancer-v2-ethereum/graphql?query=%7B%0A++liquidityPoolDailySnapshots+%28orderBy%3A+dailyVolumeUSD%2C+orderDirection%3A+desc%2C+where%3A+%7Btimestamp_gte%3A+1654041600%2C+timestamp_lte%3A+1654127999%7D%29+%7B%0A++++pool+%7B%0A++++++name%0A++++++id%0A++++%7D%0A++++dailyVolumeUSD%0A++++timestamp%0A++%7D%0A%7D. Pending version query - https://api.thegraph.com/subgraphs/id/QmXwtdnSMuibCVfeqH7MTkZxe3Ha6fooYBXr2qZdKRRnV9/graphql?query=%7B%0A++liquidityPoolDailySnapshots+%28orderBy%3A+dailyVolumeUSD%2C+orderDirection%3A+desc%2C+where%3A+%7Btimestamp_gte%3A+1654041600%2C+timestamp_lte%3A+1654127999%7D%29+%7B%0A++++pool+%7B%0A++++++name%0A++++++id%0A++++%7D%0A++++dailyVolumeUSD%0A++++timestamp%0A++%7D%0A%7D
financialsDailySnapshots | dailySupplySideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
financialsDailySnapshots | dailyTotalRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
financialsDailySnapshots | cumulativeTotalRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | Current implementation is using the incorrect revenue methodology. This is being addressed
Balancer 80 BAL 20 WETH | liquidityPoolDailySnapshots | outputTokenPriceUSD  B-80BAL-20WETH | I think this should be TVL/outputTokenPriceUSD. I am calculating around $14.6, but the subgraph is outputting around $5.7.
Balancer stETH Stable Pool | liquidityPoolDAilySnapshots | stakedOutputTokenAmount | The schema output looks like there is a value for this, but subgraph.xyz is not outputting anything and when I query the subgraph looks like null value - https://api.thegraph.com/subgraphs/name/messari/balancer-v2-ethereum/graphql?query=%7B%0A++liquidityPool+%28id%3A+%220x32296969ef14eb0c6d29669c550d4a0449130230%22%29+%7B%0A++++name%0A++++dailySnapshots+%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%29+%7B%0A++++++stakedOutputTokenAmount%0A++++++timestamp%0A++++%7D%0A++%7D%0A%7D
Balancer Aave Boosted StablePool (USD) | liquidityPoolDailySnapshots | stakedOutputTokenAmount | Like Balancer stETH Stable Pool, there is a value for this in the schema, but subgraph.xyz is outputting 0

**Comment by bye43** [comment]
@this-username-is-taken @harsh9200 I am going to close this issue, as the current deployment is going to be used for Mainnet. This version has a few errors that will have minimal effect on Protocol Metrics and they are going to be follow up on this issue here: https://github.com/messari/subgraphs/issues/983
