### ISSUE TITLE
Compound V2 QA (Ethereum) Schema Version 1.2.1 Subgraph Version 1.5.3 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#335]
Protocol Metrics in need of review: totalValueLockedUSD

Pool-level Metrics in need of review: totalValueLockedUSD, totalDepositBalanceUSD, rewardTokenEmissionsAmount

Full QA: https://docs.google.com/spreadsheets/d/1M2fqfxVm1ZozNESOdkQbfyM60grl9YMCPO1u3eylo54/edit?usp=sharing

**Comment by dmelotik** [comment]
@pietydespises So here is my take on why TVLs might be higher in our subgraph. Disclaimer, I have not done research into how DefiLama or our Dune dashboard calculate this.

TVL in our subgraph is a function of `outputTokenBalance` not necessarily how much liquidity a market has. At least on this [page](https://docs.google.com/spreadsheets/d/1M2fqfxVm1ZozNESOdkQbfyM60grl9YMCPO1u3eylo54/edit#gid=1829245697) it seems like you are looking at compound's liquidity.

And I believe `totalSupply` should be the same as `TVL` in this case, that is what we decided early on. cc @this-username-is-taken for confirmation

However, I think this should be revisited once the latest version fully syncs. This version made changes to the TVL calculations. https://github.com/messari/subgraphs/pull/255

**Comment by pietydespises** [comment]
TVL matches with DeFiLlama when "Borrowed" is toggled on, this fixes the remaining issues
