### ISSUE TITLE
YEARN V2 QA (Ethereum) Schema Version 1.2.1 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#336]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/yearn-v2-ethereum&tab=protocol
Date Reviewed | June 11 2022
Schema Version | 1.2.1
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1giCRxC27TDC9xscw0YEKJDHPb3ZgS6WtuS4VipaOHN0/edit?usp=sharing

### Metrics To Review
**Protocol Metrics** 
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | 5/22 and 5/23 are showing TVL in the trillions
financialsDailySnapshots | dailySupplySideRevenueUSD | I am not a 100% on this. The numbers are off compared to Token Terminal, but we could be using a different calculation. Regardless there is one day that is like 2,000% off
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will be
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Recording 0 revenue for the last couple of months
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will be
financialsDailySnapshots | dailyTotalRevenueUSD | Values closer to present seem way off, but the past data actually is aligning pretty well. There are instances where Total revene ≠ Protocol + Supply Side
financialsDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will be

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/yearn-v2-ethereum
Date Reviewed | July 8 2022
Schema Version | 1.3.0
Subgraph Version | 1.2.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/15Yl2DpzhezWwOXUd9BRXPf8bV1ZC6OA7v94BgcejzlU/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | The trend for TVL looks correct, but the values are about 100% larger than both Token Terminal and DefiLlama. 
financialsDailySnapshots | dailySupplySideRevenueUSD | Some of the values are like 40% to 50% off from Token Terminal, which is does not seem too bad, but 6/01/2022 is about 2000% too large. 
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will be
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Most of the values are between -50% to -100% off from Token Terminal.
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off so cumulative will be
financialsDailySnapshots | dailyTotalRevenueUSD | A lot of these numbers do not seem far off except for select dates, such as 06/01/2022. Also 05/2021 has two big spikes that seem too large, as Token Terminal has 23m recorded for that whole month.

The total revenue looks mostly right to me. I am not sure how token terminal calculates supply side and protocol side revenue, but I would assume they are not accounting for the management fee; thus, I would assume that the subgraph supply side revenue should be smaller and the protocol side revenue should be higher than the token terminal values, but this is not the case.

**Comment by bye43** [comment]
@harsh9200 and I have discussed revenue changes for Yearn. 
Google sheet being used to currently track Yearn: https://docs.google.com/spreadsheets/d/1_36EfDUHKIw-KxyKYQNE86hcNI1IKWCilNFv2vJxc7A/edit#gid=617964580

**Comment by bye43** [comment]
New comments on revenues: https://docs.google.com/spreadsheets/d/17NX9jATW0YiNj6_G-vWCQrS1csYBHCYt_xKaAEeNN1E/edit?usp=sharing

**Comment by bye43** [comment]
@this-username-is-taken @harsh9200 and I think that this is actually probably good to go. We would like to check total revenues with the Yearn team, but if this doesn't happen in a time period that allows Yearn to be fixed and released for Mainnet ,then we can probably freeze this for Mainnnet and deal with any changes after.

**Comment by this-username-is-taken** [comment]
> @this-username-is-taken @harsh9200 and I think that this is actually probably good to go. We would like to check total revenues with the Yearn team, but if this doesn't happen in a time period that allows Yearn to be fixed (if necessary) and released for Mainnet, then we can probably freeze this for Mainnnet and deal with any potential changes after.

sounds good. We can freeze the current version for Mainnet and deploy future versions in staging and graft later

**Comment by bye43** [comment]
@this-username-is-taken the cumulativeTotalRevenue bug has been fixed. This is good to freeze for Mainnet. I am going to close the issue, but will reopen if Yearn team every gets back to us and says something.
