### ISSUE TITLE
Uniswap V2 QA (Ethereum) Schema Version 1.2.1 Subgraph Version 1.0.2 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#342]
The TVL graph looks like a step function to a huge abnormally large value. Perhaps caused by wonky price data. The first issue that should be fixed is this, as this might resolve other issues.

More detail: https://docs.google.com/spreadsheets/d/1R3GvDHbv8hNfqgmZ0NbkQNS0raBsLtbuJ20Kk_bOwtM/edit#gid=617964580

**Comment by this-username-is-taken** [comment]
This has been fixed
