### ISSUE TITLE
Gamma Strategies Polygon issue on deployment

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#365]
<img width="914" alt="Screen Shot 2022-06-20 at 1 10 48 PM" src="https://user-images.githubusercontent.com/56660047/174650863-5d588389-be24-4529-a034-c9123782b667.png">

I deployed gamma strategies to polygon, but I have run into this error upon deployment.

**Comment by l0c4t0r** [comment]
I'll look into it.

**Comment by l0c4t0r** [comment]
This seems to be failing as the subgraph utilises the price lib which does not have support for polygon at the moment.  In fact it also doesn't support optimism so we should expect that to fail as well.
I have spoken to @this-username-is-taken and i think the decision for now is to wait for enhancements to the price lib.  Should we remove this from the deployment config meanwhile?  This would mean only deploying mainnet and arbitrum for now.

**Comment by this-username-is-taken** [comment]
fixed with polygon price lib support
