### ISSUE TITLE
Cream BSC subgraph wrong values

### ISSUE THREAD

**Issue by lowjiansheng** [messari/subgraphs#377]
There's a data issue with CREAM BSC subgraph.
The various values returned by the market / marketsnapshots are negative which should not happen.
Market id: "0xbf9b95b78bc42f6cf53ff2a0ce19d607cfe1ff82" 
![image](https://user-images.githubusercontent.com/15527690/174846913-2d6654a7-1342-425e-9e66-9ff37d26db61.png)

**Comment by dmelotik** [comment]
@lowjiansheng for some reason bsc is the only network that didn't get the latest subgraph version. The negative TVL issue should be fixed once it is deployed, and that _should_ happen on merge: https://github.com/messari/subgraphs/pull/403

![image](https://user-images.githubusercontent.com/60583747/175166191-6660e4d6-64fb-4988-9be0-092d8059a17c.png)

**Comment by dmelotik** [comment]
@lowjiansheng No more negative TVLs, the only one that isn't synced up yet is BSC.

Please re-open this if you still have this issue, but I looked at all the pools and TVL is only positive
