### ISSUE TITLE
Aave v2 doesn't load in subgraphs.xyz

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#385]
https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum&tab=protocol doesn't seem to work

**Comment by jihok** [comment]
@this-username-is-taken This is a general issue for all subgraphs using schema v1.1.0. Looks like Aave v2 is the only subgraph using that schema, and I assume new subgraphs won't be using v1.1.0. Is there a schema update for Aave v2 in the works? If so, should we deprioritize this?

**Comment by this-username-is-taken** [comment]
Ah I see. Yes, we will be upgrading Aave shortly. Don't worry about this then
