### ISSUE TITLE
SushiSwap QA (Ethereum )Schema Version 1.3.0 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#431]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdZkyen1vhAQSELcY9qGvzSeFkoJYx5sCCGuzgNKyY4xZ
Date Reviewed | June 24 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1oB3i9FDRm2LOLeZnP9lFGesxdaijNilu4GjRSCVxh_o/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | Big Spike in TVL on 3/23
financialsDailySnapshots | dailySupplySideRevenueUSD | Numbers are too big
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will be too
financialsDailySnapshots | dailyProtocolSideRevenueUSD | Numbers are too big
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will be too
financialsDailySnapshots | dailyTotalRevenueUSD | Numbers are too big
financialsDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will be too

**Pool Overview Metrics**
Pool | Metric | Issue
-- | -- | --
**ONSEN POOLS** | **Reward Token** | **Missing Onsen pools that have SUSHI as a reward token**
SushiSwap Illuvium/Wrapped Ether | Base Yield % | 2397.82% yield and 0.25% on Sushi UI
SushiSwap USD Coin/Wrapped Ether | Base Yield % | 891446.15% yield ... I wish this was the real yield. I could retire
SushiSwap Wrapped BTC/Wrapped Ether | Base Yield % | 45974.44% yield and 2.28% yield on Sushi UI

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | Daily is off, so cumulative will also be. Also seems like numbers are not being added correctly (Current cumulative =/= past cumulative + past dailySupplySide)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | Numbers are off by a decimal (See Total Revenue)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD | Daily is off, so cumulative will also be. Also seems like numbers are not being added correctly (Current cumulative =/= past cumulative + past dailyProtocolSide)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Numbers are off by a decimal (See Total Revenue)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | Daily is off, so cumulative will also be. Also seems like numbers are not being added correctly (Current cumulative =/= past cumulative + past dailyTotalRevenue)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Off by a decimal (Seems like fee being applied is 3% opposed to a 0.3%)
SushiSwap USD Coin/Wrapped Ether | liquidityPoolDailySnapshots | stakedOutputTokenAmount | Not sure if this is wrong, but I am wondering if there should be a value here since LPs can be staked in the Onsen pool. But might just be a value outputted for the actual Onsen pool. 
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | cumulativeSupplySideRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | hourlySupplySideRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | cumulativeProtocolSideRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | hourlyProtocolSideRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | cumulativeTotalRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | hourlyTotalRevenueUSD | Same Problems As Daily
SushiSwap USD Coin/Wrapped Ether | liquidityPoolHourlySnapshots | baseYield | Sushi UI is 14% and average over the 24 hours looks like its closer to 1%

**Comment by steegecs** [comment]
What is meant by ONSEN pools?

**Comment by bye43** [comment]
> What is meant by ONSEN pools?

They are the staked farms that Sushi offers for LPs to earn SUSHI - https://app.sushi.com/farm?chainId=1285. Not sure if these are considered separate pools with SUSHI as a reward token.

**Comment by steegecs** [comment]
Oh I see. So the issue you are pointing out is that some of the liquidity pools have specified a reward token, but there is not a staking pool for these tokens.

**Comment by bye43** [comment]
> Oh I see. So the issue you are pointing out is that some of the liquidity pools have specified a reward token, but there is not a staking pool for these tokens.

Ya two parts: 1) There should be stakedLPs being output for some of the pools (i.e. ETH/USDT) 2) There should be reward tokens for some of these pools, but I am not sure if we are supposed to be returning them as separate staked pools or if the whole pool should have the reward token (i.e. Non-staked USDC/USDT w/out reward token and a separate USDC/USDT Onsen Pool w/ SUSHI as a reward OR just non-staked USDC/USDT pool w/ SUSHI as a reward)

**Comment by bye43** [comment]
> Yeah the stake pools are associated with a certain LP token. Initially I had just input a reward token for all pools. I will be implementing a change so that the reward token field will only be populated in the LiquidityPool entity when its LP token can be staked. Does that sound good?

Yes. Thanks!

**Comment by this-username-is-taken** [comment]
Closing out this issue and using https://github.com/messari/subgraphs/issues/612 as the master reference
