### ISSUE TITLE
MakerDAO TVL significantly higher than Defi Llama value

### ISSUE THREAD

**Issue by lowjiansheng** [messari/subgraphs#436]
MakerDAO subgraph is showering that the total TVL is $9,110,531,585. 
![image](https://user-images.githubusercontent.com/15527690/175783563-14bfd544-5efa-4391-8453-53be3a1713db.png)

However, the TVL on Defi Llama is $7,897,615,105.
![image](https://user-images.githubusercontent.com/15527690/175783571-b591996f-9f64-47c6-9cee-4c9d98fa266c.png)

**Comment by this-username-is-taken** [comment]
This has been fixed here: https://github.com/messari/subgraphs/pull/555

See https://subgraphs.messari.io/subgraph?endpoint=https://api.studio.thegraph.com/query/29379/makerdao-ethereum-v2/v0.0.2&tab=protocol
