### ISSUE TITLE
Can we include the base schema for each of these?

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#453]
Also useful into to include if this is a lending, DEX, or Yield agg schema

**Comment by this-username-is-taken** [comment]
can you elaborate on this? What's the "base schema"? And include it for each of what?

**Comment by KremerMichael** [comment]
The use case here is pulling down this json & programmatically building out python data structs for each subgraph. it would be useful if the protocols were labeled by schema as well. like this

```
    "beefy-finance": {
      "beefy-finance": {
        "aurora": {
          "template": "beefy.finance.template.yaml",
          "deploy-on-merge": false,
          "schema": "Yield",
        }
      }
    },
```

added schema to the above

**Comment by this-username-is-taken** [comment]
you can find them here: https://subgraphs.xyz/deployments.json
