### ISSUE TITLE
QiDao QA (Polygon) Schema Version 1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#455]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/qidao-polygon&tab=protocol
Date Reviewed | June 29 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1gYkv2i3tu7ac4uKm-ApUffvTayHkAXaU9SYul--x7RM/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | dailySupplySideRevenueUSD | Error reported about negative values
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | error reported about two negative values

**Comment by this-username-is-taken** [comment]
@bye43 just wanted to confirm, this one can be closed right?

**Comment by bye43** [comment]
> @bye43 just wanted to confirm, this one can be closed right?

Yes. Just wanted to make sure those two things were tracked.

**Comment by this-username-is-taken** [comment]
@bye43 would you be able to go over the other deployments as well and see if there are any issues?

**Comment by this-username-is-taken** [comment]
https://thegraph.com/hosted-service/subgraph/messari/qidao-moonriver
https://thegraph.com/hosted-service/subgraph/messari/qidao-bsc
https://thegraph.com/hosted-service/subgraph/messari/qidao-fantom
https://thegraph.com/hosted-service/subgraph/messari/qidao-optimism
https://thegraph.com/hosted-service/subgraph/messari/qidao-avalanche
https://thegraph.com/hosted-service/subgraph/messari/qidao-arbitrum
https://thegraph.com/hosted-service/subgraph/messari/qidao-gnosis

**Comment by bye43** [comment]
Just realized that vault metrics are missing outputTokenSupply and outputTokenPriceUSD. Should be MAI supply and price USD for these two metrics

**Comment by this-username-is-taken** [comment]
@bye43 these are not output tokens, output tokens are ownership tracking tokens like cToken/aToken

**Comment by bye43** [comment]
> @bye43 these are not output tokens, output tokens are ownership tracking tokens like cToken/aToken. I'm not sure if QiDAO has an output token in that similar vein

Gotcha that makes sense. MakerDAO subgraph is outputting DAI for those fields, but it is also an old schema (not sure if this matters). Should I make a note in the MakerDAO issue to get rid of those two metrics?

**Comment by this-username-is-taken** [comment]
> > @bye43 these are not output tokens, output tokens are ownership tracking tokens like cToken/aToken. I'm not sure if QiDAO has an output token in that similar vein
> 
> Gotcha that makes sense. MakerDAO subgraph is outputting DAI for those fields, but it is also an old schema (not sure if this matters). Should I make a note in the MakerDAO issue to get rid of those two metrics?

Yes, please open a ticket for that. I think Abracadabra might have the same issue if you could check

**Comment by this-username-is-taken** [comment]
ah yes, snapshots are skipped when there are no events during that period. This is just the behavior of subgraphs.
