### ISSUE TITLE
Vesper QA (Polygon) Schema Version 1.2.1 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#458]
Description | Value |   |  
-- | -- | -- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/jaideepdas/vesper-finance&tab=protocol |   |  
Date Reviewed | June 11th 2022 |   |  
Schema Version | 1.2.1 |   |  
Subgraph Version | 1.1.0 |   |  
Methodology Version | 1.0.0 |   |  
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/10J-oYj3qoQ-9D9a53Uqleqd-ndnMjWmLkvhL3aBmDkk/edit?usp=sharing|   |  
  |   |   |  
### Metrics To Review 
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
totalValueLockedUSD | NOT OK | 20-60% off
dailySupplySideRevenueUSD | UNSURE | I dont know if this is actually wrong but might just be a difference in calculation between us and token terminal
cumulativeSupplySideRevenueUSD | UNSURE | Daily is off so cumulative will be
dailyProtocolSideRevenueUSD | NOT OK | Recording 0 revenue for the last couple of months
cumulativeProtocolSideRevenueUSD | NOT OK | Daily is off so cumulative will be
dailyTotalRevenueUSD | NOT OK | Values closer to present seem way off, but the past data actually is aligning pretty well. There are instances where Total revene ≠ Protocol + Supply Side
cumulativeTotalRevenueUSD | NOT OK | Daily is off so cumulative will be
cumulativeUniqueUsers | UNSURE | Dune has a high number; needs cross checking
dailyTransactionCount | UNSURE | Hard to find data to compare with; need more time to dig or create dune dashboard
dailyDepositCount | UNSURE | same as above
dailyWithdrawCount | UNSURE | same as above
hourlyActiveUsers | UNSURE | These numbers seem fine against the daily numbers, so if daily numbers are ok these should be too
hourlyTransactionCount | UNSURE | These numbers seem fine against the daily numbers, so if daily numbers are ok these should be too
hourlyDepositCount | UNSURE | These numbers seem fine against the daily numbers, so if daily numbers are ok these should be too
hourlyWithdrawCount | UNSURE | These numbers seem fine against the daily numbers, so if daily numbers are ok these should be too

**Vault Overview** 

Pool | Section | Metric | Issue
-- | -- | -- | --
vaUSDC Pool | Reward Tokens | UNSURE | Not sure on the data points for this

**Pool Metrics**

Pool | Section | Metric | Issue
-- | -- | -- | --
vaultDailySnapshots | totalValueLockedUSD | UNSURE | missing data points for some of the days and not much data to compare with ; need more time to compare with similar size protocol (maybe Cryptex)
vaultDailySnapshots | inputTokenBalance - USDC | UNSURE | see above
vaultDailySnapshots | outputTokenSupply - vaUSDC | UNSURE | see above
vaultDailySnapshots | outputTokenPriceUSD - vaUSDC | UNSURE | see above
vaultDailySnapshots | stakedOutputTokenAmount - vaUSDC | UNSURE | see above
vaultDailySnapshots | pricePerShare | UNSURE | see above
vaultDailySnapshots | rewardTokenEmissionsAmount - USDC | UNSURE | see above
vaultDailySnapshots | rewardTokenEmissionsUSD - USDC | UNSURE | see above
vaultDailySnapshots | rewardAPR | UNSURE | see above
vaultHourlySnapshots | totalValueLockedUSD | UNSURE | see above
vaultHourlySnapshots | inputTokenBalance - USDC | UNSURE | see above
vaultHourlySnapshots | outputTokenSupply - vaUSDC | UNSURE | see above
vaultHourlySnapshots | outputTokenPriceUSD - vaUSDC | UNSURE | see above
vaultHourlySnapshots | stakedOutputTokenAmount - vaUSDC | UNSURE | see above
vaultHourlySnapshots | pricePerShare | UNSURE | see above
vaultHourlySnapshots | rewardTokenEmissionsAmount - USDC | UNSURE | see above
vaultHourlySnapshots | rewardTokenEmissionsUSD - USDC | UNSURE | see above
vaultHourlySnapshots | rewardAPR | UNSURE | see above

**Comment by this-username-is-taken** [comment]
Fixed here: https://github.com/messari/subgraphs/pull/506. Ready for another round of review

**Comment by pietydespises** [comment]
@this-username-is-taken @harsh9200 Everything looks good but what is up with the two negative values for dailySupplySideRevenueUSD and one negative value for TotalRevenueUSD? Given the formulas in the methodology it doesn't make sense for there to ever be negative values.

Once this is fixed or explained the subgraph is ready to be frozen.

**Comment by this-username-is-taken** [comment]
Closing per conversation on Discord
