### ISSUE TITLE
Convex v2 (Ethereum) Schema Version 1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#459]
Description | Value |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/convex-finance-ethereum&tab=protocol |   |   |   |   |  
Date Reviewed | June 27th 2022 |   |   |   |   |  
Schema Version | 1.3.0 |   |   |   |   |  
Subgraph Version | 1.1.0 |   |   |   |   |  
Methodology Version | 1.0.0 |   |   |   |   |  
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1nmUATfiGqOP1HNPOBKbVvXcBh9GL_iY6/edit?usp=sharing&ouid=117022469384251277944&rtpof=true&sd=true |   |   |   |   |  
  |   |   |   |   |   |  
### Metrics To Review   
**Protocol Metrics** 

Section | Metric | Issue |  
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | NOT SURE | Difference might be due to CVX staked/locked. Historical data before 26 July 2021 have large discrepancy.
financialsDailySnapshots | dailyVolumeUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | cumulativeVolumeUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | dailySupplySideRevenueUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | dailyProtocolSideRevenueUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | OK | Discrepancy less than 25%.
financialsDailySnapshots | dailyTotalRevenueUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | cumulativeTotalRevenueUSD | NOT OK | Over 50% discrepancy.
financialsDailySnapshots | protocolControlledValueUSD | NA | No protocol controlld value for Convex
usageMetricsDailySnapshots | dailyActiveUsers | NOT OK | Over 100% discrepancy; descrepany in user data might arise from Convex having users interacting contracts to claim rewards.
usageMetricsDailySnapshots | cumulativeUniqueUsers | NOT OK | Over 25% discrepancy.
usageMetricsDailySnapshots | dailyTransactionCount | NOT OK | Over 25% discrepancy.
usageMetricsDailySnapshots | dailyDepositCount | NOT OK | Over 25% discrepancy.
usageMetricsDailySnapshots | dailyWithdrawCount | NOT OK | Over 25% discrepancy.
usageMetricsDailySnapshots | dailySwapCount | NOT OK | Over 25% discrepancy.
usageMetricsHourlySnapshots | hourlyActiveUsers | NOT OK | Over 25% discrepancy.
usageMetricsHourlySnapshots | hourlyTransactionCount | NOT OK | Over 25% discrepancy.
usageMetricsHourlySnapshots | hourlyDepositCount | NOT OK | Over 25% discrepancy.
usageMetricsHourlySnapshots | hourlyWithdrawCount | NOT OK | Over 25% discrepancy.
usageMetricsHourlySnapshots | hourlySwapCount | NOT OK | Over 25% discrepancy.

**Pool Overview**

Pool | Section | Metric | Issue
-- | -- | -- | --
Rewards |   | NOT OK | Rewards data are not in line. The reward tokens do not include CVX. Values for CRV and other incentives tokens are not matching official website data.

**Pool Metrics** 

Pool | Section | Metric | Issue
-- | -- | -- | --
liquidityPoolDailySnapshots | depositLimit | NA |  
liquidityPoolDailySnapshots | cumulativeSupplySideRevenueUSD | NOT OK | Over 50% discrepancy. The discrepancy might be due to attributing revenue to CRV stakers as protocol side revenue in subgraph.
liquidityPoolDailySnapshots | cumulativeProtocolSideRevenueUSD: BigDecimal! | NOT OK | Over 50% discrepancy.
liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD: BigDecimal! | NOT OK | Over 50% discrepancy.
liquidityPoolDailySnapshots | rewardTokenEmissionsAmount: [BigInt!] [Frax Share,Curve DAO Token] | NOT OK | Rewards data are not in line. The reward tokens do not include CVX. Values for CRV and other incentives tokens are not matching official website data.
liquidityPoolDailySnapshots | rewardTokenEmissionsUSD: [BigDecimal!] [Frax Share,Curve DAO Token] | NOT OK | Rewards data are not in line. The reward tokens do not include CVX. Values for CRV and other incentives tokens are not matching official website data.
liquidityPoolDailySnapshots | vaultHourlySnapshots-cumulativeSupplySideRevenueUSD | NOT SURE | Generally the hourly numbers match the daily numbers and there's no third party reference to counter check.

**Comment by this-username-is-taken** [comment]
@pietydespises this has been fixed here https://github.com/messari/subgraphs/pull/553 and is ready for another round

**Comment by pietydespises** [comment]
@harsh9200 Hey, this update looks really good. Our user metrics are still a bit elevated than external sources but not outrageously so, so gonna close this.
