### ISSUE TITLE
Daily snapshots in Yearn Ethereum subgraph incorrect values

### ISSUE THREAD

**Issue by lowjiansheng** [messari/subgraphs#462]
https://thegraph.com/hosted-service/subgraph/messari/yearn-v2-ethereum

Fetching data for poolID: 0xf2db9a7c0acd427a680d640f02d90f6186e71725
For snapshots on timestamp: **1648757395**, the TVL is 0 and cumulativeTotalRevenueUSD/cumulativeSupplySideRevenue is non 0. 
This is odd as the TVL for other daily snapshots is non-0.
However, for snapshot entries after this timestamp, the cumulative revenue values are back to 0 which shouldn't be the case since cumulative values should be strictly increasing. The TVL also became non-0.

```{
  vaults (where:{id:"0xf2db9a7c0acd427a680d640f02d90f6186e71725"}) {
    id
    name
    inputToken {
      name
      symbol
    }    
    dailySnapshots (orderBy: timestamp, orderDirection:desc, where:{timestamp_gte: 1648757395}){
    	timestamp
      totalValueLockedUSD 
      cumulativeTotalRevenueUSD
      dailyTotalRevenueUSD
      cumulativeProtocolSideRevenueUSD
      dailyProtocolSideRevenueUSD
      cumulativeSupplySideRevenueUSD
      dailySupplySideRevenueUSD
      inputTokenBalance
      outputTokenSupply
      outputTokenPriceUSD
      stakedOutputTokenAmount
      pricePerShare
    }
  }
}
```

**Comment by this-username-is-taken** [comment]
For better visualization: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/yearn-v2-ethereum&tab=pool&poolId=0xf2db9a7c0acd427a680d640f02d90f6186e71725

**Comment by lowjiansheng** [comment]
Awesome 👍  from the charts, there's clearly an issue with the data

**Comment by harsh9200** [comment]
@lowjiansheng I have fixed this issue in #465

**Comment by this-username-is-taken** [comment]
@lowjiansheng the reason for these zeros is because there are days where there is no harvest event, so we don't have any data for these days. One way to deal with this issue is to apply some sort of smoothing on the backend. Convex is a more extreme example of this where they harvest even more sparingly (IIRC).

**Comment by this-username-is-taken** [comment]
@bye43 we can close this right?

**Comment by bye43** [comment]
Yes. Will close it out.
