### ISSUE TITLE
subgraphs.xyz Reward APR incorrect

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#469]
This is an issue on compound forks I noticed. The Reward APR is the same for both the supply and borrow side. 

With these protocols the amount of reward token distributed to suppliers / borrowers is generally the same, but suppliers will get less for their share bc there is more of that asset being supplied.

The calculation should look something like this:

Supply Reward APR = (`Supply Rewards Per Day USD` / `totalSupplyBalanceUSD`) * 365 * 100
Borrow Reward APR = (`Borrow Rewards Per Day USD` / `totalBorrowBalanceUSD`) * 365 * 100

**Comment by this-username-is-taken** [comment]
Fixed in https://github.com/messari/subgraphs/pull/592
