### ISSUE TITLE
Compound: ETH pool not being returned

### ISSUE THREAD

**Issue by menaitm** [messari/subgraphs#478]
1. ETH is no longer being returned since the new subgraph (v1.6.6) got released.

2. Also I can no longer query the previous Subgraph v1.5.3 using the deployment ID `QmWj2EuaaY4KPVzvFZMYTzefAuj9ajzoedFipSbQeKaMFd`. Is there a way to safely release and keep the prior version?

https://api.thegraph.com/subgraphs/name/messari/compound-ethereum
```
    {

        # Get market-level data
        markets(
            first:50
            orderBy:totalValueLockedUSD
            orderDirection:desc
            where:{
                isActive:true
                canBorrowFrom:true
                canUseAsCollateral:true
            }
        ) {
            id
            name
            inputToken { symbol }
            outputToken { symbol }
            totalValueLockedUSD
            exchangeRate
        }
    }
```

verifying with the available pools on the dashboard:
https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/compound-ethereum&tab=poolOverview
![image](https://user-images.githubusercontent.com/106617039/176930947-e1def1ae-8621-424a-96bb-228504eac4bb.png)

**Comment by this-username-is-taken** [comment]
If you could share more about what you are working on and what your use case is, maybe we can help you

**Comment by menaitm** [comment]
> If you could share more about what you are working on and what your use case is, maybe we can help you

simple use case: need the rates for all markets on Compound (educational users)

The ETH market missing (and unknown tokens) are bugs addressed in @dmelotik's draft PR.

But the redeploy and index time can take weeks, so the production subgraph is buggy and I can't run queries against the previous v1.5.3 subgraph using its deployment ID.

**Comment by menaitm** [comment]
@dmelotik thanks for the fix!

Do you know how I can still query current version (v1.6.6) even after the pending version has finished indexing?
https://api.thegraph.com/subgraphs/id/QmWL2UDXPUUiTLNAKGXHDShiWFkiLjSbgfwE1g2DBP9Cdf

This is what happened to the previous deploy:
[https://api.thegraph.com/subgraphs/id/QmWj2EuaaY4KPVzvFZMYTzefAuj9ajzoedFipSbQeKaMFd](https://api.thegraph.com/subgraphs/id/QmWj2EuaaY4KPVzvFZMYTzefAuj9ajzoedFipSbQeKaMFd/graphql?query=%7B%0A++++++++_meta%28%0A++++++++++block%3A%7Bnumber%3A14013195%7D%0A++++++++%29+%7B%0A++++++++++++block+%7B+number+%7D%0A++++++++++++deployment%0A++++++++%7D%0A++++%7D)
```
{
  "errors": [
    "{\n  \"errors\": [\n    {\n      \"message\": \"deployment `QmWj2EuaaY4KPVzvFZMYTzefAuj9ajzoedFipSbQeKaMFd` does not exist\"\n    }\n  ]\n}"
  ]
}
```

**Comment by dmelotik** [comment]
@menaitm you would have to deploy the code yourself if you wanted to look at old versions
