### ISSUE TITLE
Bastion Protocol (Aurora) QA Schema Version 1.3.0 Subgraph Version	1.0.9 Methodology Version 1.0.0 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#492]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/bastion-protocol-aurora&tab=protocol
Date Reviewed | July 1 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.9
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1cVOEhT9liSYMIAk3aZZhlA1HQ72thOhugM-Jyhpou9Q/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | Completely different trend from DefiLlama and seems too high. The very of the beginning of the protocol should have a TVL of 0, which is not the case for the subgraph. In addition, there is a 400m difference between the peak TVL on the Subgraph and DefiLlama, but I believe this will be addressed by a change in methodology for calculating lending protocol TVL.

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
**ALL POOLS** | **Reward Token** | Should have BSTN as reward token

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Bastion Ether | marketDailySnapshots | totalValueLockedUSD | This value looks correct on the daily, but do not have time series to check. I am guessing that trend is probably off since pool TVL starts way above zero.
Bastion Ether | marketDailySnapshots | dailyLiquidateUSD | This looks right, but on 6/17 there was a USDT pricing error so USDC positions got liquidated. Bastion claims it was 81k in liquidations, but subgraph is saying 104k so might be worth a double check. Link - https://bastionprotocol.medium.com/usdt-liquidation-incident-report-a33af2ab1de2
Bastion Ether | marketDailySnapshots | rewardTokenEmissionsAmount - ETH | Should have outputs since BSTN is being emitted
Bastion Ether | marketDailySnapshots | rewardTokenEmissionsUSD - ETH | Should have outputs since BSTN is being emitted
Bastion Ether | marketDailySnapshots | rewardAPR | Should have outputs since BSTN is being emitted
Bastion Ether | marketHourlySnapshots | rewardTokenEmissionsAmount - ETH | Same as daily
Bastion Ether | marketHourlySnapshots | rewardTokenEmissionsUSD - ETH | Same as daily
Bastion Ether | marketHourlySnapshots | rewardAPR | Same as daily

**Comment by bye43** [comment]
> @bye43 is the TVL different because of different methodology?

@this-username-is-taken I think its partially off cause of different methodology, but the trend also seems wrong to me too compared to defiLlama.

**Comment by dmelotik** [comment]
@bye43 I am working on getting some more in depth info from the Bastion team in their disc. @0xbe1 and I have noticed that Defi Llama is off for the current metrics when comparing (https://defillama.com/protocol/bastion / https://dashboard.bastionprotocol.com/realms/0x6De54724e128274520606f038591A00C5E94a1F6).

Following the same methodology as compound it is more accurate after mid-May, but will follow up here if I learn more from the Bastion team.

**Comment by bye43** [comment]
> @bye43 I am working on getting some more in depth info from the Bastion team in their disc. @0xbe1 and I have noticed that Defi Llama is off for the current metrics when comparing (https://defillama.com/protocol/bastion / https://dashboard.bastionprotocol.com/realms/0x6De54724e128274520606f038591A00C5E94a1F6).
> 
> Following the same methodology as compound it is more accurate after mid-May, but will follow up here if I learn more from the Bastion team.

Awesome, sounds good! I made that note when we were still debating about subtracting borrows from deposits to account for loop borrowing, but we are staying with total deposits, so I think the methodology point can be disregarded now. Seems like we should generally follow trend as DefiLlama, unless it is is deemed wrong.

**Comment by dmelotik** [comment]
So the bastion people didn't really seem to know of anything that could've been wrong, so I did some more investigating with our aurora archival node.

The values returned from `totalSupply()` for `0xe5308dc623101508952948b141fd9eabd3337d99` using the archival node seem accurate. For example, at block `60937008` the aurora rpc endpoint returns `25499893792`, which equates to around $50. The subgraph returns `439515974299817635` which equates to around $880,349,678.

![image](https://user-images.githubusercontent.com/60583747/182253034-d8472f90-3177-45e6-b83f-96fdd53bf76b.png)

**Comment by bye43** [comment]
Hmm ... that is not good. @this-username-is-taken any thoughts on how we should proceed with this? Most of my substantial comments were about TVL, so more than likely after the next round of QA I would assume this would have been good to be frozen.

**Comment by dmelotik** [comment]
@bye43 as far as the liquidations that occurred on 6/17. I believe the higher value we see is because there happened to be other liquidations that occurred on that day. There were 17 other liquidations that occured not reported as part of the USDT price.

You can see all of them using this query: https://api.thegraph.com/subgraphs/id/QmdP4JGKYi4RQmBSh2gGxyT2u4EdVpcQbKzvZmVxSY6tMH/graphql?query=query+MyQuery+%7B%0A++liquidates%28where%3A+%7Btimestamp_gt%3A+%221655416800%22%2C+timestamp_lt%3A+%221655503199%22%7D%29+%7B%0A++++id%0A++++amount%0A++++amountUSD%0A++++asset+%7B%0A++++++name%0A++++%7D%0A++++market+%7B%0A++++++name%0A++++%7D%0A++%7D%0A%7D

**Comment by bye43** [comment]
IIRC I think that I was only referring to the vault dailyliquidateUSD value for that - https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/name/messari/bastion-protocol-aurora&tab=pool&poolId=0xe5308dc623101508952948b141fd9eabd3337d99

![Image](https://user-images.githubusercontent.com/107651107/182265019-ee995aee-761a-43fe-bf60-15c54061f425.png)

Maybe the FE is making is display weird then?

**Comment by dmelotik** [comment]
I am pretty sure the discrepancy comes from the fact that they are saying the amount they will reimburse is the actual value of USDC. Where our subgraph takes exactly what is on chain, so ours is inflated due to the price oracle error.

@this-username-is-taken do you have a take on if we should use the price oracle returning an incorrect amount or override the price during these blocks?

**Comment by this-username-is-taken** [comment]
Either way is fine as long as you make it clear in the README

**Comment by dmelotik** [comment]
@this-username-is-taken I will stick with price oracle then bc I don't have to make changes to the current version

**Comment by bye43** [comment]
> @this-username-is-taken I will stick with price oracle then bc I don't have to make changes to the current version. I will make a note in the readme either way.
> 
> Unless there is a compelling reason otherwise 👀

Ahh makes sense in regards to your first point. I am also good with going with the price oracle ... as the difference is not that much and as long as the data reflects the the oracle error I think that is fine.

**Comment by this-username-is-taken** [comment]
https://github.com/graphprotocol/graph-node/issues/3802

**Comment by dmelotik** [comment]
brushing off the dust @bye43 this one is ready to review again ✅ 

https://okgraph.xyz/?q=dmelotik%2Fbastion-protocol

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRCZdC1cu4mQKHZjMpeYA8n5SfDFejRbzdcSskJRS4YFp&tab=protocol
Date Reviewed | September 28 2022
Schema Version | 2.0.1
Subgraph Version | 1.1.3
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1gY8oEfHALxKIVELVGmNEFuoQOg6m2eiO32WsyS5rtDg/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialDailySnapshots | dailyLiquidateUSD | In the previous version of the subgraph, there was a liquidations on 6/17 because of a USDT oracle misprice leading to about 100K in liquidations. Does not looks like this is the case in this newer version and there liquidations on days there was not before (5/01/2022). See dailyLiquidate under Protocol_MetricsComparison (its in green). Link to 06/17/2022 - https://bastionprotocol.medium.com/usdt-liquidation-incident-report-a33af2ab1de2

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
All Pools | Reward Token | This is outputting EMPTY as the token name when it should be BSTN, but the address looks correct.

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Bastion Ether | marketDailySnapshots | rewardTokenEmissionsAmount | This is 0 on subgraph.xyz. I think this is because the decimals are being reported as 0.
Bastion Ether | marketDailySnapshots | rewardTokenEmissionsUSD | The pricing also looks off here for BSTN or the decimals, not sure which, as it is scaling into the E22. (This looks off for all pools) Query for rewards - https://api.thegraph.com/subgraphs/id/QmRCZdC1cu4mQKHZjMpeYA8n5SfDFejRbzdcSskJRS4YFp/graphql?query=%7B%0A++market+%28id%3A+%220xe5308dc623101508952948b141fd9eabd3337d99%22%29+%7B%0A++++name%0A++++rewardTokens+%7B%0A++++++id%0A++++%7D%0A++++dailySnapshots+%28orderBy%3A+timestamp%2C+orderDirection%3Adesc%29%7B+%0A++++++totalValueLockedUSD%0A++++++rewardTokenEmissionsUSD%0A++++++rewardTokenEmissionsAmount%0A++++%7D%0A++%7D%0A%7D
Bastion Ether | marketDailySnapshots | rewardAPR | Off cause
Bastion USDC | marketDailySnapshots | dailyLiquidateUSD | In relation to the liquidation incident on 06/17/2022 there should be a larger liquidation here. Please see USDC_Pool_Metric_Comparison tab. Also looks like the liquidations from the two versions have a couple differences

**Comment by dmelotik** [comment]
I believe the Aurora RPC is returning incorrect data still. Here are my findings:

| Description                                                                        | Subgraph                                     | AuroraScan                                                                                                                              |
|------------------------------------------------------------------------------------|----------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| Transaction missing (could be due to something else in the subgraph, not reliable) | Not there                                    | https://aurorascan.dev/tx/0xf70c147e4114dca1026ca9294f6e2b4359dc332fe18ecc0200b6d3ef8e7ee500                                            |
| siezeToken value is different from Aurorascam                                      | Returns 426469707240                         | shows 753038633943 https://aurorascan.dev/tx/0x62f23feaea5050947bc40ea9091bb5c4b23822004c9db0b1248dd49b499eeb9f                         |
| Another missing transaction                                                        | Not there                                    | https://aurorascan.dev/tx/0x646d2ebf2cee6adf25649cb92628f00b3e384f461104fea8edec336fce872d16                                            |
| Block number different / sieze tokens different                                    | siezeTokens: 3568453 / blockNumber: 67915529 | siezeTokens: 6300994 blockNumber: 67915528 https://aurorascan.dev/tx/0x8dcd0bd418dbc90668e1bdca54c05faeda549fe270c6c59b4453f90b07d09e20 |

There were many more missing transactions too. We are also expecting around $100k liquidations 6/17 and only see $8500, in a previous deployment we saw $140k which was much more probably. 

To test this further I am going to redeploy using the latest version of compound fork code (some changes to the position handling). We can compare the deployments to see if this changes anything, and assess from there. You can find the new deployment here: https://okgraph.xyz/?q=dmelotik%2Fbastion-aurora

**Comment by dmelotik** [comment]
hmmm, same exact output as what I just outlined from dmelotik/bastion-aurora

Going to try again and put a log for liquidations that occur between block 67915511 - 67915618

grafting here: https://okgraph.xyz/?q=dmelotik%2Fbastion-aurora

**Comment by this-username-is-taken** [comment]
@dmelotik I think a couple things we can do to help repro are:
1. See if you can find the tx directly by querying Alchemy's JSON-RPC node.
2. Put together a simple subgraph with only one entity that just indexes that specific missing tx and see if we can repro that way

**Comment by dmelotik** [comment]
Made a skeleton subgraph here (https://okgraph.xyz/?q=dmelotik%2Fbastion-skeleton):
- it picked up 21/64 liquidations in the affected block range
- Many of them have incorrect `siezeToken`, `repayToken`, and `blockNumber` amounts, they are close most of the time but wrong.
- The graph, the aurora blockscanner, and the aurora public rpc all return different data lol:

Aurora block scanner: https://aurorascan.dev/tx/0x072d18bd32824a593b9fc22ec2fa8bbb9243131da0cc41a7bd1cf4ae05baa9e3
```
blockNumber: **67915576**
siezeAmount: **215555538792**
repayAmount: **393124486**
```

the graph:
```
{
        "hash": "0x072d18bd32824a593b9fc22ec2fa8bbb9243131da0cc41a7bd1cf4ae05baa9e3",
        "siezeAmount": "**215789411356**",
        "repayAmount": "**393124486**",
        "timestamp": "1655468421",
        "blockNumber": "**67915578**",
        "market": "0x845e15a441cfc1871b7ac610b0e922019bad9826"
}
```

Aurora public RPC:
```
{
    blockNumber: **67915578**,
    blockHash: '0x6e97b707001340791293f53106a2da37d129a9a0e037e7fae57c857ff84e517b',
    transactionIndex: 0,
    transactionHash: '0x072d18bd32824a593b9fc22ec2fa8bbb9243131da0cc41a7bd1cf4ae05baa9e3',
    logIndex: 12,
    address: '0x845E15A441CFC1871B7AC610b0E922019BaD9826',
    removed: false,
    id: 'log_87119e79',
    returnValues: Result {
      '0': '0xbe1599C0430FE50ef3C111C93Be5bCC584786a5C',
      '1': '0x02E7b714fae84e4BA80f3CDa5508553e7CF5042A',
      '2': '393124486',
      '3': '0xe5308dc623101508952948b141fD9eaBd3337D99',
      '4': '215555538792',
      liquidator: '0xbe1599C0430FE50ef3C111C93Be5bCC584786a5C',
      borrower: '0x02E7b714fae84e4BA80f3CDa5508553e7CF5042A',
      repayAmount: '**393124486**',
      cTokenCollateral: '0xe5308dc623101508952948b141fD9eaBd3337D99',
      seizeTokens: '**215555538792**'
    },
    event: 'LiquidateBorrow',
    signature: '0x298637f684da70674f26509b10f07ec2fbc77a335ab1e7d6215a4b2484d8bb52',
    raw: {
      data: '0x000000000000000000000000be1599c0430fe50ef3c111c93be5bcc584786a5c00000000000000000000000002e7b714fae84e4ba80f3cda5508553e7cf5042a00000000000000000000000000000000000000000000000000000000176e9a86000000000000000000000000e5308dc623101508952948b141fd9eabd3337d9900000000000000000000000000000000000000000000000000000032301c7f68',
      topics: [Array]
    }
```

**Comment by azf20** [comment]
hey @dmelotik can you share the RPC call you are making to get the bottom result?

And to clarify the comparison:
blockNumber: 67915576 / 67915578 / 67915578 <- subgraph matches public RPC
repayAmount: 393124486 / 393124486 / 393124486 <- subgraph matches public RPC
seizeAmount: 215555538792 / 215789411356 / 215555538792 <- block explorer matches public RPC

Is that pattern consistent across events?

**Comment by dmelotik** [comment]
Hi @azf20 thatnks for taking a look at this. One note, the repayAmount matches across all sources.

Here is the code I used to get the event from the RPC:

```
const contractAddress = '0x845e15a441cfc1871b7ac610b0e922019bad9826';
const contract = new web3.eth.Contract(ABI, contractAddress);
    contract.getPastEvents("LiquidateBorrow", {
        fromBlock: 67915570, 
        toBlock: 67915580
    }, function(error, events){ console.log(events); })
    .then(function(events){
        console.log(events) // same results as the optional callback above
    });
```

Diving into this other event: https://aurorascan.dev/tx/0x4f70aef720fa5c45a0d761dc08cd25a58a46fad71aaa29f193d2631ab0c772ee

<img width="1012" alt="Screen Shot 2022-10-04 at 11 30 17 AM" src="https://user-images.githubusercontent.com/60583747/193874509-113f4562-340a-45cf-bd41-13fd468ff888.png">
```
blockNumber: 67915585
seizeTokens: 73322557343
repayAmount: 452221841
```

Subgraph:
```
{
        "id": "0x4f70aef720fa5c45a0d761dc08cd25a58a46fad71aaa29f193d2631ab0c772ee",
        "siezeAmount": "73402110551",
        "repayAmount": "452221841",
        "blockNumber": "67915586"
}
```

Public RPC:

```
{
    blockNumber: 67915586,
    blockHash: '0xa601222ec4fda14f8e32dccd31a5e3730150e35184c1e5685a100b3789e09a8a',
    transactionIndex: 5,
    transactionHash: '0x4f70aef720fa5c45a0d761dc08cd25a58a46fad71aaa29f193d2631ab0c772ee',
    logIndex: 11,
    address: '0x845E15A441CFC1871B7AC610b0E922019BaD9826',
    removed: false,
    id: 'log_d556dafb',
    returnValues: Result {
      '0': '0xbe1599C0430FE50ef3C111C93Be5bCC584786a5C',
      '1': '0x5651412bc177c82a5227AF23884bE6aAaFcF9d45',
      '2': '452221841',
      '3': '0x8C14ea853321028a7bb5E4FB0d0147F183d3B677',
      '4': '73322557343',
      liquidator: '0xbe1599C0430FE50ef3C111C93Be5bCC584786a5C',
      borrower: '0x5651412bc177c82a5227AF23884bE6aAaFcF9d45',
      repayAmount: '452221841',
      cTokenCollateral: '0x8C14ea853321028a7bb5E4FB0d0147F183d3B677',
      seizeTokens: '73322557343'
    }
```

The comparison:
blockNumber: 67915585 / 67915586 / 67915586 <- Subgraph matches the public RPC
seizeTokens: 73322557343 / 73402110551 / 73322557343 <- Block Scanner matches the public RPC
repayAmount: 452221841 / 452221841 / 452221841 <- All match

Looks to be consistent in what matches what.

Also, here is an event that never got picked up by the subgraph: https://aurorascan.dev/tx/0x1b3a185677fb37e3edf355143f5263af09653f631abb568f6e17e9cb6d3fc079

**Comment by dmelotik** [comment]
The issues outlined here have been occuring and are out of our control. The concessions we made are visible in the bastion-protocol README.
