### ISSUE TITLE
VVS Finance issues

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#494]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/2354636/177086296-52e3ae0e-70ae-41db-95e8-34d85219c43f.png">

https://cronoscan.com/address/0xbc149c62EFe8AFC61728fC58b1b66a0661712e76#code

**Comment by steegecs** [comment]
Fixed reward tokens on all of the uniswap-forks subgraphs.

**Comment by steegecs** [comment]
Still have to work on craftsmanV2

**Comment by this-username-is-taken** [comment]
Haven't heard back from protocol team

**Comment by dmelotik** [comment]
ACTION: Seems to be done. @steegecs following up before we move this to "done"

**Comment by steegecs** [comment]
We never integrated Craftsman V2, as there were questions I had about it, but they never got back after we reached out a couple times.
