### ISSUE TITLE
Rename DEX-schema variable

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#499]
https://github.com/messari/subgraphs/blob/c26c73157d46faccaf77f7545a4310871d7c6a4f/schema-dex-amm.graphql#L772

This variable is `amountInUSD`, can we rename it to `amountUSD` so it matches the same variable for the Deposit & Withdraw events?

**Comment by KremerMichael** [comment]
Actually I see this has to do with slippage &or fees on the swap. maybe amountInUSD or amountOutUSD becomes amountUSD & we have some other variable we can use to calculate the delta?

With the current naming there are 3 'amounts'
deposit & withdraw: amountUSD
swap: amountInUSD, amountOutUSD

I think the goal would be to compress this to 2 amounts:

deposit & withdraw: amountUSD
swap: amountUSD, amountOutUSD

or 

deposit & withdraw: amountUSD
swap: amountUSD, slippage

etc...

It's also fine to ignore this, my solution may create more confusion by being less explicit than the current schema.

**Comment by this-username-is-taken** [comment]
Why is `amountUSD` and `slippage` better than `amountIn/amountOut`? Doesn't it require extra calculation on the client side?

**Comment by KremerMichael** [comment]
> Why is `amountUSD` and `slippage` better than `amountIn/amountOut`? Doesn't it require extra calculation on the client side?

Reading this again after having messed with the other schemas more, you can ignore this. I was trying to optimize for the reuse of taxonomy as much as possible but I no longer think that's most important.
