### ISSUE TITLE
Subgraphs.xyz Transaction count checker issue

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#512]
There is a warning being thrown on the validation end saying the sum of transactions doesn't equal `dailyTransactionCount`.

![image](https://user-images.githubusercontent.com/60583747/177524640-b0807d26-b651-4725-99b3-456de53a4899.png)

I believe this is an error on the validation end as the transactions check out in the graphql playground: https://api.thegraph.com/subgraphs/name/messari/compound-ethereum/graphql?query=query+MyQuery+%7B%0A++usageMetricsDailySnapshot%28id%3A+%2218176%22%29+%7B%0A++++dailyTransactionCount%0A++++dailyWithdrawCount%0A++++dailyRepayCount%0A++++dailyLiquidateCount%0A++++dailyDepositCount%0A++++dailyBorrowCount%0A++%7D%0A%7D

**Comment by jihok** [comment]
@dmelotik this should be resolved on dashboard v1.1.10 (verified against Compound and Solarbeam-Moonriver)
