### ISSUE TITLE
Mainnet or Ethereum

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#522]
https://github.com/messari/subgraphs/blob/3373e14204d3bcd3159d4681c1a7ec3c3904fae2/deployment/deploymentConfigurations.json#L29

Using this line as a specific example but it also applies to https://subgraphs.messari.io/deployments.json

when auto generating links, these deployments are tagged under 'mainnet' so auto completing aave-v2 would look like

`aave-v2-mainnet`

However, the real deployment is at `aave-v2-ethereum`

**Comment by this-username-is-taken** [comment]
changed `mainnet` to `ethereum`
