### ISSUE TITLE
Total Borrow is always 0

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#523]
https://github.com/messari/subgraphs/blob/3373e14204d3bcd3159d4681c1a7ec3c3904fae2/subgraphs/aave-v2-forks-ext/schema.graphql#L487

for aave-v2 mainnet, this query gives all 0
```
{
financialsDailySnapshots(first: 1000) {
    id
    timestamp
    totalBorrowUSD
  }
}
```

**Comment by dmelotik** [comment]
@KremerMichael This is on the old aave-v2 subgraph, the one with updated schema I am working through a bug for the ethereum version.

You can track that issue here: #487
