### ISSUE TITLE
Sushiswap (Polygon) Subgraph QA- not indexing 

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#537]
<google-sheets-html-origin><style type="text/css"></style>

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-polygon&tab=protocol |  
-- | -- | --
Date Reviewed | July 5th 2022 |  
Schema Version | 1.3.0 |  
Subgraph Version | 1.0.0 |  
Methodology Version | 1.0.0 |  

<google-sheets-html-origin><style type="text/css"></style>

Protocol |   |  
-- | -- | --
Section | Value | Status
All | All | NOT OK

<google-sheets-html-origin><style type="text/css"></style>

OVERALL COMMENTS
--
-Indexing has stopped, no values are being shown
-Subgraph needs to resume indexing before passing QA
-Chain should be called Polygon and not Matic.

**Comment by this-username-is-taken** [comment]
next time when this happens, can you specify the block number where it failed, and copy the error message here?
