### ISSUE TITLE
Naming convention daily vs hourly

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#544]
sampling from Network Schema but this extends everywhere. With the schema as currently defined, queries between the two different snapshot timeframes are not reusable.
```
{
  dailySnapshots (first: 10) {
    dailyBlocks
    dailyRewards
    dailyDifficulty
  }
}

{
  hourlySnapshots (first: 10) {
    hourlyBlocks
    hourlyRewards
    hourlyDifficulty
  }
}
```
If we moved to this then queries could be reused.
```
{
  dailySnapshots (first: 10) {
    Blocks
    Rewards
    Difficulty
  }
}
{
  hourlySnapshots (first: 10) {
    Blocks
    Rewards
    Difficulty
  }
}
```
This makes the schema less explicit however both `hourly` and `daily` are defined in Entity so I think this is a fair leap to make.

**Comment by dmelotik** [comment]
@this-username-is-taken I think this can be closed with the new schema

**Comment by this-username-is-taken** [comment]
hmm, there is a specific reason for it to be named this way, which is to disambiguate: https://github.com/messari/subgraphs/blob/master/docs/Schema.md#naming-conventions

For example, if I see `totalVolumeUSD` in a daily snapshot, I can interpret it as two ways:
- total volume of that day
- total volume up to that day

Explicitly naming these two scenarios as `dailyVolumeUSD` and `cumulativeVolumeUSD` addresses this issue.

**Comment by KremerMichael** [comment]
That's a good point. I can live with things as they are.
