### ISSUE TITLE
Solarbeam QA (Moonriver) Schema Version 1.3.0 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#547]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/solarbeam-moonriver&tab=protocol
Date Reviewed | July 11 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1NOS8FPgnyJa-a3rKe_KcVbx5SZY-TZRa7JhU1z8QwPg/edit?usp=sharing

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | dailyVolumeUSD | Trend looks good, but there are certain days where the volume reported on the subgraph is over 100% difference than Solarbeam UI. This could be a Solarbeam UI problem, but difference is worth looking into
financialsDailySnapshots | dailySupplySideRevenueUSD | 2% fee applied supposed to be 0.2% fee
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | Looks good, but daily is off
financialsDailySnapshots | dailyProtocolSideRevenueUSD | 0.5% fee applied supposed to be 0.05% fee
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | Looks good, but daily is off
financialsDailySnapshots | dailyTotalRevenueUSD | 2.5% fee applied supposed to be 0.25% fee
financialsDailySnapshots | cumulativeTotalRevenueUSD | Looks good, but daily is off

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
ALL POOLS | Reward Token | Missing SOLAR as a reward token
Solarbeam MOVR/xcKSM | Base Yield % | 930.00% being outputted, Solarbeam UI is 11.58%
SolarBeam MOVR/USDC | Base Yield % | 100010.56% being outputted, Solarbeam UI is 154.95%
Solarbeam ETH/WMOVR | Base Yield % | 19424.32% being outputted, Solarbeam UI is 43.40%
Solarbeam FRAX/ROME | ALL | This pool is the number one pool in TVL on the Solarbeam UI, but is not present in the subgraph's Pool Overview

**Pool Metrics**
Pool Metrics were not loading for Solarbeam, so was not able to check pool metrics.

**Comment by this-username-is-taken** [comment]
@bye43 this is ready to be reviewed again

**Comment by this-username-is-taken** [comment]
This is ready for another round

**Comment by bye43** [comment]
New comments raised here - https://docs.google.com/spreadsheets/d/1loo3Rm4mCaXLEsudCKj6k1Ct_pB6pc_nPLwKpbEh2Jc/edit?usp=sharing

**Comment by steegecs** [comment]
This has been deployed and you can review again!

**Comment by this-username-is-taken** [comment]
Fixed and indexed. Will graft soon

**Comment by bye43** [comment]
There is one more issue with Solarbeam:

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Solarbeam Wrapped liquid staked KSM/xcKSM | liquidityPoolDailySnapshots | rewardTokenEmissionAmount | The reward array is off (i.e. SOLAR is being represented as wstKSM)

**Comment by steegecs** [comment]
Okay - Going to graft the change for fixing the liquidity pool TVLs, and then work on the reward emissions fix as a lower priority.

**Comment by steegecs** [comment]
Grafted and PR merged.

**Comment by bye43** [comment]
@steegecs going to move reward emissions to its on issue here: https://github.com/messari/subgraphs/issues/1104

**Comment by this-username-is-taken** [comment]
@bye43 should we get this ingested given the only issue is rewards?

**Comment by bye43** [comment]
Ya that sounds good! I will let JS know.
