### ISSUE TITLE
Arrakis Finance QA (Ethereum) Schema Version 1.3.0 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#587]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=l0c4t0r/laboratory4&tab=protocol
Date Reviewed | July 14 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1zlH-rlysSs5g7rb8ODd1cEhKL_IzuOm6/edit?usp=sharing&ouid=113156017090580515789&rtpof=true&sd=true

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
All Pools | Naming | The subgraph name does not include the pool commission rate of 0.01%, 0.05% etc. making it hard to differentiate. Would be nice if this was included.
Some Pools | TVL | Pools such as Gelato Un...DAI/FEI LP, Gelato Un...EI/USDC LP, Gelato Un...AR/USDC LP, Gelato Uniswap USDC/WETH LP, Gelato Uniswap GEL/WETH LP have differing TVLs compared to the Arrakis UI. See evidence sheet "Pool Overview" for more detail. Link to Arrakis - https://beta.arrakis.finance/vaults. I also checked the FEI/DAI contract and I am getting token balances that align with Arrakis UI and not the subgraph (4.6m vs 2.9m). Link to FEI/DAI etherscan under getUnderlyingTokenBalances - https://etherscan.io/address/0x3d1556e84783672f2a3bd187a592520291442539#readProxyContract

**Comment by l0c4t0r** [comment]
Checking this now. It does seem like there is some issue with stale TVL

**Comment by l0c4t0r** [comment]
Additional, the price of FEI from price lib seems to be under-reported ($0.35 vs ~$1)

**Comment by l0c4t0r** [comment]
I have opened the above PR to address some of the issues mentioned above.  However, not all vault TVL are "fixed".  I elaborate on the reasons for the discrepancies here:

1. Price lib in it's current form doesn't always return the most accurate data. In this specific case, Yearn lens was returning $0.35 for FEI, while it should have been ~$1 (reported correctly by chainlink)
2. Freshness of data: currently, TVL values are updated whenever there are any major interactions with the vault (deposits, withraws and rebalancing),  however, for smaller vaults that have less interactions, the data can become stale.
3. Impermanent loss: the above is made worse if price changes by a lot but there are no vault interactions to "refresh" the TVL calculations.  Other than the pricing of the assets being inaccurate, the ratio between token0 and token1 can also shift dramatically with Uniswap V3 pools.  This means positions incur "impermanent loss" which is not accounted for if there are no triggers to update the TVL in the subgraph.

To address the issues I listed we need:
1.  Enhancements to price lib
2. Discussions around data freshness as part of our methodology, and how to implement these.

I think these are larger issues that could affect multiple subgraphs.  

#632 addresses (imo) the issues that are specific to the Arrakis subgraph.

**Comment by this-username-is-taken** [comment]
@bye43 the fix has been deployed and fully indexed. Ready for another review 👍

**Comment by bye43** [comment]
There was not much on this so not going to write a formal review. But looked everything over and looks good. There are a couple low liquidity pools that have the freshness of TVL issue. The only pool TVL that may need a second look is USDC/POP. The Arrakis UI has TVL at $732,352.77 and subgraph has TVL at $419,458.83. I feel like this is a large enough TVL that it should be refreshing somewhat frequently and would not be this far off. If @l0c4t0r gives that pool an ok, then this should be good to freeze.

**Comment by l0c4t0r** [comment]
Unfortunately POP is one of the tokens that we are unable to get pricing for at the moment, I have documented this in the readme.
This is because this is only trading on uniswap v3 at the moment, which price lib supports.
I have done some reseearch around adding uniswap v3 support to price lib, it's not trivial but I do have some new ideas around how to do this, which I will create a new issue to track.
