### ISSUE TITLE
Belt Finance (Binance) Schema Version 1.2.1 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#588]
Description | Value |  
-- | -- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/belt-finance-bsc&tab=protocol |  
Date Reviewed | June 27th 2022 |  
Schema Version | 1.2.1 |  
Subgraph Version | 1.0.0 |  
Methodology Version | 1.0.0 |  
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1DL68163f5TtEPWPHfxi8j21D22MTq-uxdrcTVl0P8nE/edit?usp=sharing |  
  |   |  
### Metrics To Review 
**Protocol Metrics** 

Section | Metric | Issue |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
financialsDailySnapshots | dailyProtocolSideRevenueUSD | NOT OK | Type `Vault` has no field `dailyProtocolSideRevenueUSD` are 0 | yieldAggregator-cumulativeProtocolSideRevenueUSD is 0. Verify that this data is correct |   |   |   |  
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | NOT OK | Type `Vault` has no field `cumulativeProtocolSideRevenueUSD` are 0 | yieldAggregator-cumulativeTotalRevenueUSD is 0. Verify that this data is correct |   |   |   |  
financialsDailySnapshots | dailyTotalRevenueUSD | NOT OK | All values in financialsDailySnapshots-dailyTotalRevenueUSD are 0 | All values in financialsDailySnapshots-protocolControlledValueUSD are 0. Verify that this data is being mapped correctly. |   |   |   |  
financialsDailySnapshots | cumulativeTotalRevenueUSD | NOT OK | All values in financialsDailySnapshots-cumulativeTotalRevenueUSD are 0 |   |   |   |   |  
financialsDailySnapshots | protocolControlledValueUSD | NOT OK | All values in financialsDailySnapshots-protocolControlledValueUSD are 0 |   |   |   |   |  

**Pool Overview** 

Not Displaying in validation dashboard

**Pool Metrics**

Pool | Section | Metric | Issue |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
beltBNB |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
vaultDailySnapshots | stakedOutputTokenAmount - beltBNB | NOT OK | stakedOutputTokenAmount timeseries has invalid data.
vaultDailySnapshots | stakedOutputTokenAmount - beltBNB | NOT OK | stakedOutputTokenAmount timeseries has invalid data.

**Comment by this-username-is-taken** [comment]
Will use this one to track: https://github.com/messari/subgraphs/issues/1107
