### ISSUE TITLE
Uniswap V3 Ethereum subgraph with high TVL

### ISSUE THREAD

**Issue by lowjiansheng** [messari/subgraphs#609]
Querying the Uniswap V3 Ethereum subgraph: https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-ethereum for deployment ID: QmQ6w5oXZiMeTpVSkLy4UqBVtVKmtiEMcL9ygiPZgGddg5

This particular pool has an invalid TotalValueLockedUSD returned for pool address: 0xfd9715a9f03678975b2e224c938fae8d481b09b2.  
<img width="914" alt="image" src="https://user-images.githubusercontent.com/15527690/179446022-3eb89d27-dae1-4774-b7ae-8907e1f1ee02.png">

**Comment by this-username-is-taken** [comment]
This should've been fixed. Please reopen if you see it again.
