### ISSUE TITLE
MakerDAO input token balance too high

### ISSUE THREAD

**Issue by lowjiansheng** [messari/subgraphs#610]
For pool ID:
0x0a59649758aa4d66e25f08dd01271e891fe52199

The input token (USDC) has a balance of 3732352195247595000000000000 and decimal of 6.
This translates to a balance of 3732352195247595000000 normalised. Multiplied with the price of USDC ($1), it gives us an input balance of US$3732352195247595000000 which is incorrect for Makerdao.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/15527690/179506806-fa3ae6fa-74b3-4ad4-8efc-19cc87953e80.png">

**Comment by tnkrxyz** [comment]
This will be fixed as part of fixing #500 via PR #555

**Comment by tnkrxyz** [comment]
This was due to incorrect decimals for tokens not having 18 decimals in the previous implementation. It is now fixed in #555. Feel free to close this issue.
