### ISSUE TITLE
Sushiswap (All: Arbitrum, Fuse, Polygon, Avalanche, BSC, Celo, Fantom, Gnosis, Mainnet, Moonriver, moonbeam) Schema Version 1.3.0 Subgraph Version  1.1.2 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#612]
Overall Comments: 1) All subgraphs have issues for `Base Yield` on pool overview page based on sanity check. 2) Avalanche, Celo and Gnosis have issues of `totalvaluelockedUSD` and `dailyvolumeUSD` when compared to Defilama and Sushi analytics dashboard. 3) Fantom, Celo, Avalanche and Fuse have issues with `dailyvolumebytokenUSD` charts showing zero inside the pool section. 4. Ethereum, BSC and Polygon are still indexing (blocks and percentage indicated in their section). 

Excel file for all issues combined: https://docs.google.com/spreadsheets/d/1-z6Eyl0cKodxq7fmnhS7Pt_F56ci6qW-zBi-KkPvugw/edit#gid=0

**Arbitrum**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-arbitrum&tab=protocol
-- | --
Date Reviewed | July 15 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1CJzTV7LA2BsH1iMpY5x7Y3diTCbP9HbxvW-WJrdE7a0/edit#gid=617964580

Pool Overview
All Pools |   |   |  
-- | -- | -- | --
All | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

**Fuse**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-fuse&tab=protocol
-- | --
Date Reviewed | July 15 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1lch_ID4FZMOQLGEtQf0fwju2RgB-yVXWCHr6WJwxAJQ/edit?usp=drive_web&ouid=111561086681119932380

Pool Overview
All Pools |   |   |  
-- | -- | -- | --
All | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Pool
wFuse/USDC
liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - WFUSE | not ok | All zeroes, sanity check, should have some volume on the tokens
-- | -- | -- | --

**Avalanche**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-avalanche&tab=protocol
-- | --
Date Reviewed | July 15 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1eHePJk_OuHpxbnsiQIInvRDe7b29An0VGtxtJhFQrR8/edit?usp=drive_web&ouid=111561086681119932380

Protocol
Section | Value | Status | Comments
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | Not ok | Appears 60% less, should be 15-20mil based on sushi dashboard at peak and defillama but showing 5-6 mil
financialsDailySnapshots | dailyVolumeUSD | not ok | Appears to be 60% less, should be 600K from sushi dashboard, but showing 200k

Pool Overview
All Pairs|   |   |  
-- | -- | -- | --
all coins | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Pool 
SushiSwap USD Coin/wavax |   |   |  
-- | -- | -- | --
liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - WAVAX | Not ok | All zeroes, sanity check, should have some volume on the tokens
liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - USDC | not ok | All zeroes, sanity check, should have some volume on the tokens

**Celo**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-celo&tab=protocol
-- | --
Date Reviewed | July 18 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1cL-_hAfSztiEaxKCtWdEDF5qiVF87NcEutwuI9f3QWE/edit#gid=617964580

Protocol
Section | Value | Status | Comments
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | Not ok | Appears 60% less, should be 1.4mil at peak based on sushi dashboard and defillama but showing 500k.
financialsDailySnapshots | dailyVolumeUSD | not ok | Appears 60% less, should be 100K from sushi dashboard, but showing 10000-30000

Pool Overview
All Pools|   |   |  
-- | -- | -- | --
ALL | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Pool
SushiSwap USD Coin/cUSD |   |   |  
-- | -- | -- | --
liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - cUSD | Not ok | All zeroes, sanity check, should have some volume on the tokens
liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - cUSD | not ok | All zeroes, sanity check, should have some volume on the tokens

**Fantom**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-fantom&tab=protocol
-- | --
Date Reviewed | July 18 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1pvPgw9TJLL6R6Du3lvEDuiUETmJC392KNepNAOh0_Zs/edit#gid=617964580

Pool Overview
All Pools |   |   |  
-- | -- | -- | --
All pools | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Pool 
SushiSwap USD Coin/wftm |   |   |  
-- | -- | -- | --
liquidityPoolDailySnapshots | dailyVolumeByTokenUSD - wftm | not ok | All zeroes, sanity check, should have some volume on the tokens
liquidityPoolHourlySnapshots | hourlyVolumeByTokenUSD - wFTM | not ok | All zeroes, sanity check, should have some volume on the tokens

**Gnosis**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmP2voZc7m5tKok56etPYcfefH2ubF4E7qx36Xa3uBcLYu&tab=protocol&version=pending&name=messari/sushiswap-gnosis
-- | --
Date Reviewed | July 18 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1j2aDCimCBhrfsETxXQqD7TZaCJmuhk7dekwPaQ_Z0U4/edit#gid=617964580

Protocol
Section | Value | Status | Comments
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | not ok | Appears 30% less, should be 21 mil but at 14 mil when comparing sushi dashboard to subgraph.

Pool Overview
All pools |   |   |  
-- | -- | -- | --
all | Base Yield % | not ok | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Comment: There are two versions of Gnosis on the front end.

**Moonriver**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-moonriver&tab=poolOverview
-- | --
Date Reviewed | July 18 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1vSliBYy_l8jB_5w7Zkar7wEg2CcIdiqvACFEmgFHFTo/edit#gid=617964580

Pool Overview
All pools |   |   |  
-- | -- | -- | --
All pools | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

**Moonbeam**
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/sushiswap-moonbeam&tab=poolOverview
-- | --
Date Reviewed | July 18 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.2
Methodology Version | 1.0.0
Evidence | https://docs.google.com/spreadsheets/d/1dpG4w7QUQYJ7t98xbItXT3lux7ssClvsJcKVKtePRbA/edit#gid=617964580

Pool Overview
All Pools |   |   |  
-- | -- | -- | --
All | Base Yield % | NOT OK | Yield is showing APY in the 4 digits. This is excluding liquidity mining. Sanity check suggests something is wrong. Could it be pulling farm data?

Comment: Liquidity is very low on this network, probably very new

**Awaiting indexing**
--
**Mainnet (Ethereum)**

Cannot QA, needs to finish indexing before QA (currently 0%)
Latest block: 0
Current chain block: 15167045
there is an old subgraph version with errors previously reported, this is the new subgraph. both appear on front end.

**Polygon**

Cannot QA, needs to finish indexing before QA (currently 54%)
Latest block: 16592869
Current chain block: 30828152
Change front end title from "Matic" to "Polygon"

**BSC**

Cannot QA, needs to finish indexing before QA (currently 43%)
Latest block: 8491536
Current chain block: 19633609

**Comment by steegecs** [comment]
Hey @ishraq8  ! Thanks for the review. I requested access to the excel file you posted at the top since I do not yet have permission.

**Comment by ishraq8** [comment]
@steegecs already approved. let me know if you have any issues accessing it or if you have any questions or concerns. The issues seem largely consistent between deployments. Thank you for going through the subgraphs. :)

**Comment by steegecs** [comment]
Thanks!

**Comment by steegecs** [comment]
Is the `hourlyVolumeByTokenAmount` for fuse supposed to be `hourlyVolumeByTokenUSD`?

**Comment by ishraq8** [comment]
You are correct @steegecs, my mistake, the metric is accurate on the other chains. Some of these hourly issues I brought up are more sanity checks, as unusual outputs (ie: high variability and zeros would be more common).

**Comment by this-username-is-taken** [comment]
Hey @ishraq8, the APR issue in the validation dashboard should've been fixed and the numbers should be accurate now. Do you mind giving this another pass?

**Comment by ishraq8** [comment]
All sushi subgraphs look good except the two following issues:

1) https://analytics-bsc.sushi.com/

TVL and daily volume is higher on the subgraph for BSC than on the sushi dashboard. unsure why that is. if you would like i can raise another issue on github,.

2) https://analytics-polygon.sushi.com/
Polygon tvl and volume looks higher on subgraph as well. schema is listed as 1.1.2 which is old. may just need to be updated. 

once complete we can icebox all sushi subgraphs.

**Comment by ishraq8** [comment]
@this-username-is-taken Sushi is good on all chains. Polygon is a bit slow to complete indexing but the data is good. Please freeze
