### ISSUE TITLE
Sushiswap Ethereum invalid swaps

### ISSUE THREAD

**Issue by jihok** [messari/subgraphs#614]
there are a few swap transactions that may need some attention

![image](https://user-images.githubusercontent.com/1700785/179551510-741c1779-fb31-40d6-bd2c-8c2e09d79a17.png)

**Comment by steegecs** [comment]
I believe this is from the current deployment if I am not mistaken. These tokens should be blacklisted in the pending version which you can see when it is done grafting, so these outliers should not occur.

**Comment by jihok** [comment]
Not mistaken. Lgtm thanks!
