### ISSUE TITLE
Benqi Finance (Avalanche) Schema Version 1.3.0 Subgraph Version 1.0.6 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#627]
Benqi Finance (Avalanche)
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/benqi-avalanche&tab=protocol
-- | --
Date Reviewed | June 29th 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.6
Methodology Version | 1.0.0

Protocol
Section | Value | Status | Comments
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | NOT OK | Currently the Subgraph TVL is calculated as Deposit + Borrow, it should be Deposit only (avoiding double counting). 
financialDailySnapshots | dailyBorrowUSD | NOT OK | Sanity check. showing $40B in daily borrow while total borrow balance is 1-2B
financialDailySnapshots | cumulativeBorrowUSD | not ok | Same as top, cumulative in the trillions of dollars.
financialDailySnapshots | dailyDepositUSD | NOT OK | Sanity check. showing $40B in daily deposit while total deposit balance is 1-2B
financialDailySnapshots | cumulativeDepositUSD | not ok | Same as top, cumulative in the trillions of dollars.

Pool Overview 
All pools | Metric |   |  
-- | -- | -- | --
All pools | Reward Token | NOT OK | APY very high, much higher than benqi front end. Critical error :Benqi QI does not have a valid 'totalBorrowBalanceUSD' value. Neither Reward APR (BORROWER) nor Base Yield could be properly calculated.

Pools
USDCn |   |   |  
-- | -- | -- | --
marketDailySnapshots | totalValueLockedUSD | NOT OK | TVL is accounting for deposits+borrowed. Should be deposits only. Double check if this is accurate, similar to the tvl of the protocol
marketDailySnapshots | totalDepositBalanceUSD | not ok | $79M, while front end shows $43M. could be adding deposits and borrow.
marketDailySnapshots | inputTokenBalance - USDCn | Not ok | Looks like it is taking into account both borrow and deposits
marketDailySnapshots | outputTokenSupply - USDCn | not ok | Seems to be off by order of magnitude. borrow is 35M and not 3.5B as being reported.
marketDailySnapshots | rewardAPR | not ok | Sanity check, shows 300% APR.
marketHourlySnapshots | totalValueLockedUSD | Not OK | TVL is accounting for deposits+borrowed, should be deposits only. Double check if this is accurate, similar to the tvl of the protocol
marketHourlySnapshots | totalDepositBalanceUSD | Not ok | $79M, while front end shows $43M. could be adding deposits and borrow.
marketHourlySnapshots | inputTokenBalance - USDCn | Not ok | Looks like it is taking into account both borrow and deposits
marketHourlySnapshots | outputTokenSupply - USDCn | Not ok | Seems to be off by order of magnitude. borrow is 35M and not 3.5B as being reported.
marketHourlySnapshots | rewardAPR | NOT OK | Sanity check, shows 300% APR.

OVERALL COMMENTS
TVL and deposit rate showing both borrow and deposits, is this accurate?
APR rate showing >300% on USDCn, sanity check

**Comment by dmelotik** [comment]
@ishraq8 Thanks for the review!

We do calculate `totalValueLockedUSD` as total deposits (ie total supply). So the `totalValueLockedUSD` / `totalDepositBalanceUSD` data issues are non issues. And it seems to follow DefiLlama as it is right now. Let me know if you think otherwise.

The other issues I am investigating though

**Comment by ishraq8** [comment]
@dmelotik Thank you for the clarification and you are correct. I was discussing the `totalValueLockedUSD` and total deposits being the same earlier and this approach is standard for lending subgraphs currently.

Thank you again for all your help and clarifying the issues brought up. I appreciate all your efforts.

**Comment by dmelotik** [comment]
@ishraq8 with the current understanding of the definition would you agree those fields are okay now? Just want to double check

**Comment by dmelotik** [comment]
@ishraq8 outputTokenSupply` in Benqi is going to be orders of magnitude larger than other values. the exchange rate between output token and input token is around .02, so that means USDCn is worth about 50 output tokens.

So I believe this is a non-issue as well, but if you could confirm that I would appreciate the help! thanks

**Comment by dmelotik** [comment]
As far as the crazy high Deposits and Borrows  and Repays are actual transactions in the market. They are just all done in the same transaction so it is not affecting the TVL really. 

Here is an example transaction: https://snowtrace.io/tx/0x183468c6342cd0025a66dff69c5d1b5e511ece772ff762be92084f71bf0ddb82

Seems to be another Benqi contract as well.

cc @this-username-is-taken for some guidance on whether we should try to handle these crazy transactions or leave as is?

**Comment by ishraq8** [comment]
> @ishraq8 with the current understanding of the definition would you agree those fields are okay now? Just want to double check

Yes we are I agree, @dmelotik

**Comment by this-username-is-taken** [comment]
> As far as the crazy high Deposits and Borrows and Repays are actual transactions in the market. They are just all done in the same transaction so it is not affecting the TVL really.
> 
> Here is an example transaction: https://snowtrace.io/tx/0x183468c6342cd0025a66dff69c5d1b5e511ece772ff762be92084f71bf0ddb82
> 
> Seems to be another Benqi contract as well.
> 
> cc @this-username-is-taken for some guidance on whether we should try to handle these crazy transactions or leave as is?

well if they are real transactions we definitely want to record them as is. These would be interesting properties of the market.

**Comment by this-username-is-taken** [comment]
Just went through the thread and it seems like this is good to go now? @ishraq8 can we get the final green light from you?

**Comment by ishraq8** [comment]
@dmelotik Just did another full QA, all issues are resolved. Thank you so much, this is stellar work!

@this-username-is-taken This Subgraph is done and should be Iceboxed.

**Comment by this-username-is-taken** [comment]
Thanks so much @ishraq8!
