### ISSUE TITLE
Compound Ethereum Extended

### ISSUE THREAD

**Issue by BroderickBonelli** [messari/subgraphs#631]
For the Compound extended schema, under the Position field, the isCollateral values are all false. None are true.
<img width="1268" alt="isCollateral_true" src="https://user-images.githubusercontent.com/79765357/179896074-60b22258-356d-481e-9f5d-6fa0fbfcf8cf.png">
<img width="1262" alt="isCollateral_false" src="https://user-images.githubusercontent.com/79765357/179896078-1e1d14ab-e659-4f1b-9880-a836c014edf6.png">

**Comment by this-username-is-taken** [comment]
@BroderickBonelli this should be fixed. Can you confirm?

**Comment by BroderickBonelli** [comment]
Hey @this-username-is-taken , it looks like the 'isCollateral' values are all showing as 'false' still for this subgraph (https://api.thegraph.com/subgraphs/name/messari/compound-ethereum-extended). Are the changes generally immediate?

**Comment by dmelotik** [comment]
Hey @BroderickBonelli for this change we needed to resync the subgraph, so if you look at the pending subgraph here you can see the collateral positions are true/false. https://okgraph.xyz/?q=messari%2Fcompound-ethereum-extended

Example query: https://api.thegraph.com/subgraphs/id/QmRfsjMrwCgvuFfKsgUMgB5zZXCd1EaQbYExRZYs9uSvaQ/graphql?query=query+MyQuery+%7B%0A++positions+%7B%0A++++id%0A++++isCollateral%0A++++market+%7B%0A++++++name%0A++++%7D%0A++%7D%0A%7D

**Comment by BroderickBonelli** [comment]
Hey @dmelotik, excellent, thanks so much!
