### ISSUE TITLE
Spiritswap rewardTokenEmissions fields have 2 elements on pools with only 1 reward token

### ISSUE THREAD

**Issue by MichaelC1999** [messari/subgraphs#657]
This pool is an example. Either the pool is missing a second reward token, or the reward token emissions fields have an extra element. [The "Pool Overview" on the Validation Dashboard indicates this is the case for all pools on Spiritswap](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmZ8WgBQ9Nmkux4EJ1Ghqs2LfZzyom7YhEuvtSkmCrfh1X&tab=poolOverview&version=pending)

![spirit issue](https://user-images.githubusercontent.com/69168498/180484829-45b74eb4-e934-438c-8320-d4c4ff202aee.png)

**Comment by steegecs** [comment]
Added a PR here: 
https://github.com/messari/subgraphs/pull/727

**Comment by steegecs** [comment]
This PR fixes the issue specified here. I am just waiting for the right time to re-deploy with everything going on with QA

**Comment by steegecs** [comment]
Redeployed.
