### ISSUE TITLE
Abracadabra Money Avalanche Ext 

### ISSUE THREAD

**Issue by BroderickBonelli** [messari/subgraphs#658]
There appear to be errors with borrow balances. Under the Position field, many balances are negative where side = 'Borrower'.
<img width="1223" alt="Abracadabra Extended Schema Borrows" src="https://user-images.githubusercontent.com/79765357/180494267-64600a60-88fa-457e-9d87-034ba40677d5.png">

**Comment by this-username-is-taken** [comment]
I believe this has been fixed in https://thegraph.com/hosted-service/subgraph/messari/abracadabra-money-avalanche?version=pending:

![image](https://user-images.githubusercontent.com/2354636/185533457-a2e2e16d-26c0-4bef-8858-4e8b3735d6fa.png)

Would you be able to confirm: @BroderickBonelli

**Comment by BroderickBonelli** [comment]
Hey @this-username-is-taken, confirming this looks correct now. Thanks!

**Comment by this-username-is-taken** [comment]
Great! Thanks
