### ISSUE TITLE
Venus Protocol QA (BSC) Schema Version 1.3.0 Subgraph Version 1.0.6 Methodology Version	1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#707]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/venus-protocol-bsc&tab=protocol
Date Reviewed | August 1 2022
Schema Version | 1.3.0
Subgraph Version | 1.0.6
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1uRTeDj5l9ItwThie-6rbI1-g5uYouIivueY3urS6LGI/edit#gid=617964580

### Metrics To Review
**Comments** - Revenue values look correct based on the borrow and liquidation metrics, but those metrics (daily borrow and liquidate) look off for certain dates. So did not make any comments on the revenue and will recheck it once borrows and liquidate is addressed (I am guessing the current implementation for revenue is correct though).

**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | dailyBorrowUSD | All time high at 80 billion daily borrow on 04/21/2021 seems too high and most likely needs a double check, as Compound's highest dailyBorrowUSD value is roughly 3b.
financialsDailySnapshots | cumulativeBorrowUSD | If daily off, cumulative also off. Cumulative sum correct from a mathematical perspective
financialsDailySnapshots | dailyDepositUSD | Spike on 04/21/2021 of 200b in deposits. This seems too high and needs second look. Compound's highest deposit daily value was around 4.5b for comparison.
financialsDailySnapshots | cumulativeDepositUSD | Daily is off, also cumulative is off
financialsDailySnapshots | dailyLiquidateUSD | Spike on 05/19/2021 of $287,917,021.674 in liquidations. This seems too high and needs second look. Comparatively, Compound's daily liquidation on this date was under 150b.
financialsDailySnapshots | cumulativeLiquidateUSD | If daily is off, this is off

**Pool Overview**
Pool | Metric | Issue
-- | -- | --
Venus CAKE | Naming | Nuance thing, but Cake should be CAKE

**Comment by this-username-is-taken** [comment]
Really high deposit/borrow is reasonable on a low fee chain (similar to BENQI) since people can "wash"-deposit/borrow. Also bots might do this for arbs/mev. In any case, we should check to confirm.

With regard to liquidation on 5/19, did you mean Compound's value is 150M?

**Comment by bye43** [comment]
That makes sense and sorry, yes 150M not 150B

**Comment by dmelotik** [comment]
@bye43 the symbol recorded on the blockchain is `Cake`, do you think it should still be `CAKE`? I can just override it 

https://bscscan.com/address/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82#readContract

**Comment by dmelotik** [comment]
Should we exclude `Venus CAN` altogether? It looks like it was only active on 3 different days... But it was still part of the protocol. My instinct is to keep it even though it is a deprecated pool.

**Comment by dmelotik** [comment]
After some investigation, here is my take on the crazy high deposits / borrows. This address (https://bscscan.com/address/0x8123cafca48b37e0f4936b2388d6b8a29f8f0da5) is a Venus bridge contract and it is responsible for a crazy amount of deposits and borrows. Looking at a select group of borrows alone it sums up to $10b. 

It is interesting that they have a bridge that interacts so heavily with their markets, but that is what seems to be making crazy numbers.

Here is an example transaction where the bridge borrows around $100m in one transaction

**Comment by bye43** [comment]
@dmelotik 

Cake - O ya seems like Cake isn't capitalized on chain. I think most FE make it CAKE since that is the ticker (the pancake swap homepage has it as CAKE - https://pancakeswap.finance/).  If it is not too much of a hassle, I think overriding it into capitals would be better. 

`Venus Can` - I agree with you on this. The original QAer made a note about us having too many pools (b/c of CAN), but I think its better to have more coverage and keep the deprecated pools 

High borrows - Ahh. That is pretty interesting and make sense then. I am comfortable with the high values then.

**Comment by this-username-is-taken** [comment]
I don't think we should override stuff in the subgraph level. We should expose things as they are in the smart contract. Should let FE or consumer of the subgraph handle casing.

**Comment by this-username-is-taken** [comment]
For Venus bridge data, could you ask in the Venus Discord to see if they know more about it? The data seems to be correct but would be nice if we can get more context around the data.

**Comment by dmelotik** [comment]
I will follow up in their discord

**Comment by dmelotik** [comment]
In regards to the liquidation, it seems like they had an event, but the details are gone. I asked their disc

https://twitter.com/VenusProtocol/status/1394892979190513664?s=20&t=yvrRsx4T8RpH7zgKOvGUaQ

**Comment by this-username-is-taken** [comment]
> In regards to the liquidation, it seems like they had an event, but the details are gone. I asked their disc. Would be good for more context, but if this is similar to Bastion's liquidation issue, I think our precedent is to include, but make a note in the readme.
> 
> https://twitter.com/VenusProtocol/status/1394892979190513664?s=20&t=yvrRsx4T8RpH7zgKOvGUaQ

Ah I remember that incident. It was quite a big deal at the time. You can find more details here:
https://blog.venus.io/venus-protocol-incident-post-mortem-4468c87d245e

Yes, we should include and make a note in the README 👍

**Comment by this-username-is-taken** [comment]
@bye43 just to confirm we are all cleared on Venus?

**Comment by bye43** [comment]
> @bye43 just to confirm we are all cleared on Venus?

Yes. Looks like it does not need any changes, so it is good to go

**Comment by bye43** [comment]
Reopening this, as @dmelotik and I have discussed that there are three bugs in the market metrics:

1) Reward Tokens (XVS) not being output for all pools 
2) marketDailySnapshots-rates outputting incorrect rates (appearing to be too low for most markets)
3) On 5/14/2022 and 11/23/2020, only for stablecoins (USDC, USDT, BUSD) marketDailySnapshots-inputTokenPriceUSD and marketDailySnapshots-outputTokenPriceUSD are spiking down to 0

**Comment by dmelotik** [comment]
@bye43 
1- working on adding rewards
2- I see the error here
3- The event on 11/23/2020 was from venus launch to the first 15 minutes, then the next day started (ie a new snapshot). All of the inputTokenBalances are 0 so I don't think we need to do anything here. I will make a note though. 

For the later date, that was something venus did during the LUNA depeg. They set certain price feeds to 0. Do you think we should override the price feeds in our subgraph? cc @this-username-is-taken 

The affected markets include DAI, UST, BUSD, LUNA, USDC, ETH, USDT. My take is Luna we let die, the other stables I think it would be fair to override to $1. But then ETH is the other one, we could use other price oracles for this period of time.

**Comment by bye43** [comment]
I agree on letting Luna die ... I mean I hope no one is looking at that market. And O, I think if Venus actively set prices to 0 it is good to reflect that in our data for transparency. @this-username-is-taken this could be one of those events that we start marking down internally to reflect in our dApps.

**Comment by dmelotik** [comment]
lmao add UST into the LUNA category as well

Here is their "postmortem" statement https://blog.venus.io/venus-luna-incident-update-3-resuming-the-protocol-ff059a914405

**Comment by this-username-is-taken** [comment]
> I agree on letting Luna die ... I mean I hope no one is looking at that market. And O, I think if Venus actively set prices to 0 it is good to reflect that in our data for transparency. @this-username-is-taken this could be one of those events that we start marking down internally to reflect in our dApps.

Agreed!
