### ISSUE TITLE
Uniswap V3 - Re-indexing for pool snapshot volume issues. 

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#718]
Some of the volumes on the daily snapshots are coming in negative. I have started a re-deployment on Ethereum and Arbitrum. 
When Polygon and Optimism are fully synced, then re-deploy. 

Deployments: 
Ethereum - DEPLOYED
Arbitrum - DEPLOYED
Polygon -  DEPLOYED
Optimism -  DEPLOYED

![2022-08-03 20 06 27](https://user-images.githubusercontent.com/56660047/182735682-f71126aa-1fde-42e9-9588-3ede497dd1ab.jpg)

**Comment by this-username-is-taken** [comment]
@lowjiansheng FYI, there are a couple minor issues in uniswap v3 that will be fixed relatively soon on Ethereum and Arbitrum (deployed and waiting to sync). The data in the "current" subgraph is fully synced and mostly usable except the issue called out here. They will be fixed after the "pending" subgraph fully syncs.

On Polygon and Optimism, we are waiting for the "current" subgraph to fully index, so we at least have a reasonably good subgraph fully indexed. After it fully indexes, we will deploy the version with fixes in it.

**Comment by this-username-is-taken** [comment]
@steegecs we can redeploy polygon now

**Comment by steegecs** [comment]
Deployed Polygon
