### ISSUE TITLE
Lido QA (Ethereum) Schema Version 1.3.0 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#726]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/lido-ethereum&tab=protocol
Date Reviewed | 8/4/2022
Schema Version | 1.3.0
Subgraph Version | 1.0.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1n8b_DX9ayNrHXw6xICm-wze7kX0SVOGx/edit?usp=sharing&ouid=113156017090580515789&rtpof=true&sd=true

### Metrics To Review
**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Liquid Staked Ether 2.0 | poolDailySnapshots | poolDailySnapshots-outputTokenPriceUSD - stETH: Liquid staked Ether 2.0 | From 01/18/2022 to 6/10/2022 looks like the price of stETH is off. For example, on 04/27/2022, the subgraph is outputting 1.618 versus $2,888 on CoinGecko

**Comment by fortysevenlabs** [comment]
Good catch @bye43.

FYI @this-username-is-taken

I had observed issues with `Yearn Lens Oracle` previously. I disabled this oracle, this results in prices being pulled from `Chainlink Feed Registry` and that fixes the `stETH` price discrepancies.

If this change looks good and other price dependent fields are not impacted, give me a thumbs up  and I’ll push this change to master.

(Action item for Messari team later is to review if any other prices outside of this subgraph are impacted  and whether they want to continue to use Yearn Lens Oracle).

— 

Here’s the change:
```
diff --git a/subgraphs/lido/src/prices/index.ts b/subgraphs/lido/src/prices/index.ts
index dd176e68..aea6ed3e 100644
--- a/subgraphs/lido/src/prices/index.ts
+++ b/subgraphs/lido/src/prices/index.ts
@@ -18,14 +18,14 @@ export function getUsdPricePerToken(tokenAddr: Address): CustomPriceType {
   let network = dataSource.network();
 
   // 1. Yearn Lens Oracle
-  let yearnLensPrice = getTokenPriceFromYearnLens(tokenAddr, network);
-  if (!yearnLensPrice.reverted) {
-    log.warning("[YearnLensOracle] tokenAddress: {}, Price: {}", [
-      tokenAddr.toHexString(),
-      yearnLensPrice.usdPrice.div(yearnLensPrice.decimalsBaseTen).toString(),
-    ]);
-    return yearnLensPrice;
```

Here’s the deployments you can use to verify:
* (start_block: 13996681, synced) https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmeR3DnmteWFzosbkNAasbr7myELSWeo5sdwpzdYjzTb9n&tab=pool&poolId=0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84
* (start_block: 11473216, still syncing) https://subgraphs.messari.io/subgraph?endpoint=+https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fid%2FQmWD3yaxk8gEts5Jr8C7viBUCL6sMPZKRPtjS9fGBGuvSG&tab=pool&poolId=0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84&view=poolHourlySnapshots-outputTokenPriceUSD

**Comment by this-username-is-taken** [comment]
that sounds fine to me!

**Comment by this-username-is-taken** [comment]
@bye43 this should have been fixed. Can you give another look?

**Comment by bye43** [comment]
> @bye43 this should have been fixed. Can you give another look?

Yes, this looks good now. I think that was the only issue with Lido, so its good to go.
