### ISSUE TITLE
Tectonic QA (Cronos) Schema Version 1.3.0 Subgraph Version 1.0.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by pietydespises** [messari/subgraphs#739]
Looks good, only a couple small things to check: 

-dailyTransactionCount off by more than 100% compared to Dapp Radar. Not necessarily wrong, but needs double checking.

-Rewards in **Pool Overview** page for both lending and borrowing higher than on official Tectonic site. Needs double checking.

-VaultSchema Interest rate and rewardTokenEmissionUSD (Tectonic Governance Token) in **Pools** not in line with website data, needs double checking. If only 5% discrepancy, can leave it.

-rates & rewardAPR both hourly and daily in **Pools** 5% off with website, worth double checking but not a big issue.

-dailyCumulativeSupplySideRevenue in **Pools** not in line with daily data.

Evidence: https://docs.google.com/spreadsheets/d/1ZhJUoQx8GSqXMEfdUjlazq87ykijiT72/edit#gid=1467419641

**Comment by dmelotik** [comment]
Adding a link to Evidence that I can view: https://docs.google.com/spreadsheets/d/1DldCXFrBY2PdjsRLdp7Slyyb70oe9bW_/edit#gid=1896722059

**Comment by dmelotik** [comment]
Recording some findings so far:
- reward rates and interest rates are based off assumed values, making them off
- or the `dailyCumulativeSupplySideRevenue` are you referring to this here: https://docs.google.com/spreadsheets/d/1DldCXFrBY2PdjsRLdp7Slyyb70oe9bW_/edit#gid=1267795481&range=D20
     - I believe it is good, the value to look at is the one for the day of 7/19 if I am reading that correctly
- For the transaction count, I think their data is not a whole picture. If you look at the "data we are tracking" on dapp radar, they are looking at tCRO and the Comptroller. Not every single market. The other metrics they report too are more in line with tCRO than the whole protocol as well.
