### ISSUE TITLE
Compound forks' unique depositor count higher than unique user count

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#745]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/2354636/183272004-0ad4b03b-3d35-4fee-aa13-916c27d1e502.png">

**Comment by this-username-is-taken** [comment]
@MichaelC1999 maybe we can add a check here as well?

**Comment by MichaelC1999** [comment]
> @MichaelC1999 maybe we can add a check here as well?

Yeah I could add that for the different types of users. Ill see what other fields I could validate as being equal to the sum of other fields

**Comment by this-username-is-taken** [comment]
> > @MichaelC1999 maybe we can add a check here as well?
> 
> Yeah I could add that for the different types of users. Ill see what other fields I could validate as being equal to the sum of other fields

these won't be the sum as they can be overlapping, but unique user has to be greater or equal to all the rest

**Comment by MichaelC1999** [comment]
> > > @MichaelC1999 maybe we can add a check here as well?
> > 
> > 
> > Yeah I could add that for the different types of users. Ill see what other fields I could validate as being equal to the sum of other fields
> 
> these won't be the sum as they can be overlapping, but unique user has to be greater or equal to all the rest

Ah thats true, ill adjust the logic accordingly
