### ISSUE TITLE
Compound / Aave v2 Forks `Position` fails to load

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#751]
The position entity fails to load in these subgraphs pretty often, resulting in missing many valid `Transactions`. Here we see it occur 4x in 30s

![image](https://user-images.githubusercontent.com/60583747/183393473-ef109d15-dcb5-4216-8de3-1124f6a66ca4.png)

**Comment by 0xbe1** [comment]
@dmelotik would be helpful to investigate: when it says position not found, is it that these positions will never be created, or they are created but just slightly later than the log?

**Comment by dmelotik** [comment]
@0xbe1 It seems like this issue is only happening on transactions where `subtractPosition()` is called, and this does not create a new position, but tries to load an existing one.

So maybe the logic to find the existing position is not 100% accurate. Another thing I was thinking about is that there may be a chance that a third party account is executing these transactions on the borrower/suppliers behalf, and the logic does not account for it.

**Comment by 0xbe1** [comment]
> @0xbe1 It seems like this issue is only happening on transactions where `subtractPosition()` is called, and this does not create a new position, but tries to load an existing one.
> 
> So maybe the logic to find the existing position is not 100% accurate. Another thing I was thinking about is that there may be a chance that a third party account is executing these transactions on the borrower/suppliers behalf, and the logic does not account for it.

Agreed

**Comment by dmelotik** [comment]
fixed in compound forks with #1008 closing and opening a separate issue to track persisting issues in aave v2
