### ISSUE TITLE
Output token is null for Abracadabra [CDP]

### ISSUE THREAD

**Issue by KremerMichael** [messari/subgraphs#758]
https://github.com/messari/subgraphs/blob/ea414e7476b80522aa44901956dc644bfb2b7df7/subgraphs/abracadabra/schema.graphql#L552

Here's abracadabra
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/37517750/183484144-ddb33259-4b29-4e68-a6de-e353ff9d4fa0.png">
vs what I would expect (maker)
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/37517750/183484185-8798d20c-f463-4dd9-a4aa-dd1427268607.png">

**Comment by this-username-is-taken** [comment]
I believe abracadabra doesn't have an output token (e.g. cToken/aToken) that tracks ownership like Compound/Aave does. Maker also shouldn't have one and that should have been removed in the latest update.

What's the specific use case you have here? You can probably look into Account/Position data, or `mintedToken` fields.

**Comment by KremerMichael** [comment]
> I believe abracadabra doesn't have an output token (e.g. cToken/aToken) that tracks ownership like Compound/Aave does. Maker also shouldn't have one and that should have been removed in the latest update.
> 
> What's the specific use case you have here? You can probably look into Account/Position data, or `mintedToken` fields.

My confusion then is that for Maker DAI is the output token of each market, I was expecting MIM to be the output token of abracadbra markets. This way the queries for both could be identical

**Comment by not-reed** [comment]
as of today, `outputToken` for maker is also null
![image](https://user-images.githubusercontent.com/86171134/184919476-284a7359-a19e-4772-a2dd-c7cf81232aab.png)

**Comment by this-username-is-taken** [comment]
> > I believe abracadabra doesn't have an output token (e.g. cToken/aToken) that tracks ownership like Compound/Aave does. Maker also shouldn't have one and that should have been removed in the latest update.
> > What's the specific use case you have here? You can probably look into Account/Position data, or `mintedToken` fields.
> 
> My confusion then is that for Maker DAI is the output token of each market, I was expecting MIM to be the output token of abracadbra markets. This way the queries for both could be identical

This is an issue on Maker where we are going to address (i.e. will remove outputToken). You should use the mintedToken fields instead.

**Comment by this-username-is-taken** [comment]
> as of today, `outputToken` for maker is also null ![image](https://user-images.githubusercontent.com/86171134/184919476-284a7359-a19e-4772-a2dd-c7cf81232aab.png)

See above ☝️

**Comment by KremerMichael** [comment]
> 

Gotcha! I'm all good on this, closing!
