### ISSUE TITLE
Uniswap V3 QA (Polygon) Schema Version 1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#761]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-polygon&tab=protocol
Date Reviewed | 8/8/2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1ZsDkbB196IBZKgQBHIIZ5QOXbgf-Vj0a/edit?usp=sharing&ouid=113156017090580515789&rtpof=true&sd=true

### Metrics To Review
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | totalValueLockedUSD | I think that the Uniswap UI is most likely off, but there are a couple dates that are way different. 07/26/2022 is about 1716% off and 07/01/2022 is 71% off. Uniswap UI also has a billion dollar spike in 07/26/2022, which is not reflected in the subgraph, this might be an error on Uniswap's side though.
usageMetricsDailySnapshots | cumulativeUniqueUsers | Usually this metric is correct, so could be a case where Dune Dashboard is wrong and subgraph is right, but the difference is pretty big and could use a double check. Dune is recording ~200k users and subgraph is reporting ~800K users. Link to Dune Query - https://dune.com/queries/431968/822918

**Pool Overview**
Comments - For most of these pools, I am guessing that they are blacklisted tokens (I checked the github, but want to make sure I read the right file - https://github.com/messari/subgraphs/blob/master/subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/polygon/polygon.ts), which makes sense why the subgraph TVLs are roughly half of the Uniswap UI, but figured a double check would not hurt. The only two TVLs that would be of concern to me are WETH/UNI 0.3% and FRAX/MinMATIC 0.05% pools since they are more legitimate project tokens (note - the FRAX/MinMatic pool has no volume output though on Uniswap UI, so subgraph might actually be correct) and should not be blacklisted. Uniswap UI also only lists the top 50 pools, so there could differences in other exotic pools that I could not check. 
Pool | Subgraph TVL | Uniswap UI TVL | % Difference
-- | -- | -- | --
FRAX/MinMATIC 0.05% | 1,640,170.76 | 2,000,000.00 | 17.99%
USDC/KOLO 0.3% | 139,728.83 | 487,260.00 | 71.32%
WETH/UNI 0.3% | 218,214.12 | 471,900.00 | 53.76%
RETH/WETH 1% | 41,636.73 | 285,420.00 | 85.41%
USDC/THX 0.3% | 152,913.71 | 272,820.00 | 43.95%
DOM/USDC 0.3% | 129,665.85 | 257,720.00 | 49.69%
NXTT/WMATIC 0.3% | 129,665.85 | 255,250.00 | 49.20%
MATIC/FTXXX 0.3% | 14,966.07 | 233,140.00 | 93.58%
WETH/NFTI 0.3% | 75,642.26 | 217,050.00 | 65.15%

**Comment by steegecs** [comment]
Some of the pricing issues in this issue should be addressed by PR #777. Waiting for it to finish indexing to head, and then I will re-deploy.

**Comment by bye43** [comment]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-polygon&tab=protocol
Date Reviewed | 8/17/2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1DHjyypiAHzPRr8QxSVsgZX4KcRWgbdq1/edit?usp=sharing&ouid=113156017090580515789&rtpof=true&sd=true

Pool | Subgraph TVL | Uniswap UI TVL | % Difference | Comments
-- | -- | -- | -- | --
USDC/XMT 1% | N/A | 2,880,000.00 | #VALUE! | This pool has no volume, so prob correctly blacklisted
FRAX/miMATIC 0.05% | 1,650,450.40 | 2,000,000.00 | -17.48% | No volume here, so this is good
FREC/MATIC 0.3% | 45373.85155 | 650,430.00 | -93.02% | Low volume here too, so prob correctly blacklisted
USDC/CGG 1% | 240,235.34 | 492,250.00 | -51.20% | Low volume here too, so prob correctly blacklisted
USDC/KOLO 0.3% | 136,237.91 | 480,460.00 | -71.64% | This has decent volume in the last 7 days (~300K), so maybe needs a second look
MVX/USDC 1% | 211,771.53 | 428,930.00 | -50.63% | Low volume here too, so prob correctly blacklisted
WETH/UNI 0.3% | 153,683.37 | 383,410.00 | -59.92% | I think UNI pricing is off here, looks like 0 when I checked on the pricing oracle debugger
KASTA/USDC 0.3% | 147,335.87 | 341,260.00 | -56.83% | Low volume here too, so prob correctly blacklisted
MATIC/CRV 0.3% | 109,876.63 | 320,760.00 | -65.74% | I think CRV pricing is off here, looks like 0 when I checked on the pricing oracle debugger
USDC/FRAX 0.05% | 76013.52782 | 309,380.00 | -75.43% | I think FRAX pricing is off here, looks like 0 when I checked on the pricing oracle debugger
WRAC/EFD 0.3% | N/A | 298,240.00 | #VALUE! | This pool has no volume, so prob correctly blacklisted
USDC/THX 0.3% | 156,585.62 | 275,490.00 | -43.16% | Low volume here too, so prob correctly blacklisted
WETH/MLN 1% | 98,002.91 | 270,850.00 | -63.82% | Low volume here too, so prob correctly blacklisted
NXTT/MATIC 0.3% | 138,478.45 | 270,330.00 | -48.77% | This has decent volume in that last 24H (~144K), might need another look
DOM/USDC 0.3% | 127,265.91 | 252,870.00 | -49.67% | Low volume here too, so prob correctly blacklisted
MATIC/XFUN 0.3% | 56,971.57 | 246,520.00 | -76.89% | Low volume here too, so prob correctly blacklisted
MATIC/FTXXX 0.3% | N/A | 233,140.00 | #VALUE! | This pool has no volume, so prob correctly blacklisted

**Comment by steegecs** [comment]
All Uniswap V3 subgraphs have just been re-deployed according to this PR #777. This should fix any issues with pool pricing. Additionally, I added a fix for the cumulativeUniqueUsers value as well. This is also described in the above PR.

**Comment by steegecs** [comment]
Indexing from PR #849 as of yesterday.

**Comment by bye43** [comment]
@this-username-is-taken @steegecs  Closing this for Mainnet and moving the existing issues here: https://github.com/messari/subgraphs/issues/984
