### ISSUE TITLE
AAVE V2 (mainnet, arc, rwa and AMM) Schema Version 2.0.1, Subgraph Version  1.2.6, Methodology Version  1.0.0

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#773]
Summary: `cumulativeLiquidateUSD` not adding up in all subgraphs and double check if `isCollateral` should be false in Positions tab. Some subgraphs have very low usage so no liquidations, double check ARC and RWA if subgraph is accurately reading this zero. 

**Aave v2 Mainnet**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v2-ethereum-extended
-- | --
Date Reviewed | 26-Jul-22
Schema Version | 2.0.1
Subgraph Version | 1.2.6
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | cumulativeLiquidateUSD | not ok |   | Not adding up liquidate data. Output is zero

Postions |   | not ok | Etherscan |  The data from etherscan shows that stETH tokens were enabled as collateral. However, the  'isCollateral' column in the subgraph data shows says FALSE. Should it be false? Double check The ranking in balance column is not sorted by value (seemingly sorted according to the alphanumerical order of the value data). 
-- | -- | -- | -- | --

**Aave v2 ARC**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-arc-ethereum&tab=protocol
-- | --
Date Reviewed | 9-Aug-22
Schema Version | 2.0.1
Subgraph Version | 1.2.6
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | dailyLiquidateUSD | NOT OK |   | Usage is very low so shows at zero, double check if subgraph will report if there is an event.
financialsDailySnapshots | cumulativeLiquidateUSD | not ok |   | Double check if adding up liquidate numbers

Positions |   | not ok | Etherscan |  The data from etherscan shows that stETH tokens were enabled as collateral. However, the  'isCollateral' column in the subgraph data shows says FALSE. Should it be false? Double check The ranking in balance column is not sorted by value (seemingly sorted according to the alphanumerical order of the value data). 
-- | -- | -- | -- | --

**Aave v2 RWA**

Subgraph Reviewed |https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-rwa-ethereum&tab=protocol
-- | --
Date Reviewed | 9-Aug-22
Schema Version | 2.0.1
Subgraph Version | 1.2.6
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | dailyLiquidateUSD | NOT OK |   | Usage is very low so shows at zero, double check if subgraph will report if there is an event.
financialsDailySnapshots | cumulativeLiquidateUSD | not ok |   | Double check if adding up liquidate numbers

Positions |   | not ok | Etherscan |  The data from etherscan shows that stETH tokens were enabled as collateral. However, the  'isCollateral' column in the subgraph data shows says FALSE. Should it be false? Double check The ranking in balance column is not sorted by value (seemingly sorted according to the alphanumerical order of the value data). 
-- | -- | -- | -- | --

**Aave v2 AMM**

Subgraph Reviewed |https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-amm-ethereum&tab=protocol
-- | --
Date Reviewed | 9-Aug-22
Schema Version | 2.0.1
Subgraph Version | 1.2.6
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | cumulativeLiquidateUSD | not ok |   | Numbers are not adding up

Pool 
vault schema | cumulativeProtocolSideRevenueUSD: BigDecimal! | not ok | Can you double check subgraph is collecting protocol side revenue. Docs are unclear. It is zero and looks correct compared to total revenue.
-- | -- | -- | --

Positions |   | not ok | Etherscan |  The data from etherscan shows that stETH tokens were enabled as collateral. However, the  'isCollateral' column in the subgraph data shows says FALSE. Should it be false? Double check The ranking in balance column is not sorted by value (seemingly sorted according to the alphanumerical order of the value data). 
-- | -- | -- | -- | --

**Comment by dmelotik** [comment]
@ishraq8

- `cumulativeLiquidateUSD` not showing issues should be fixed in #834 
- The `isCollateral` issues should be fixed by #832 
- For no `dailyLiquidateUSD` in ARC it is because there are no liquidations as of 8/19/22, but the mapping should be working (as it is in other aave forks)
- for the revenue issues in the amm markets it seems like some of the reserveFactors are not updating properly. I am working on a potential change
- Could you elaborate on what you mean by `double check The ranking in balance column is not sorted by value (seemingly sorted according to the alphanumerical order of the value data)`?

**Comment by ishraq8** [comment]
Thanks @dmelotik, great work. The ranking issue on the balance column is a front end issue, subgraph data is accurate compared to etherscan. 

Once the `reserveFactors` issue is resolved for revenue I think we should be good with all AAVE V2 except polygon (which will take a while to index).

**Comment by dmelotik** [comment]
#838 fixes the reserveFactor issue, and should be fully synced for `ethereum-amm` on merge

**Comment by dmelotik** [comment]
@ishraq8 I just merged this, but the subgraph (eth-amm) should be fully synced when you read this in the morning. cheers

**Comment by ishraq8** [comment]
Thanks @dmelotik will review today

**Comment by ishraq8** [comment]
issues resolved good for frozen. Except polygon as it will take time. Regarding AAVE V2 with smaller user base, there may be issues in front end visualization and "spikes".

**Comment by ishraq8** [comment]
issues resolved good for frozen. Except polygon as it will take time. Regarding AAVE V2 with smaller user base, there may be issues in front end visualization and "spikes".

**Comment by ishraq8** [comment]
issues resolved good for frozen. Except polygon as it will take time. Regarding AAVE V2 with smaller user base, there may be issues in front end visualization and "spikes".
