### ISSUE TITLE
Uniswap V3 QA (Optimism) Schema Version	1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#789]
Description | Value
-- | --
Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmZTknJxe41Kza1cExh8GKoKP77ELovfB3Ep35gTHPoBaV&tab=pool&poolId=0x68f5c0a2de713a54991e01858fd27a3832401849&version=pending
Date Reviewed | 8/12/2022
Schema Version | 1.3.0
Subgraph Version | 1.1.0
Methodology Version | 1.0.0
Evidence Spreadsheet | https://docs.google.com/spreadsheets/d/1kA6jhIWsiQXNSm4zRtiJolWuFuA90nvX/edit?usp=sharing&ouid=113156017090580515789&rtpof=true&sd=true

### Metrics To Review
**Pool Overview**
Pool | Metric | Issue
-- | -- | --
All Pools | Fee Labels | Missing labels for pools with different fees since there can be pools of the same assets, but with different fees.

Comments - I checked all the pool TVLs > 100k on the Uniswap UI and compared them the subgraph. Here are the ones with major differences below. The majority of the difference is probably cause the pair token is blacklisted, but I think some of the pairs have legit tokens and should be closer. Also some of the tokens, like KROM and sUSD, have real volume over the last 7 days, so maybe we don't blacklist them? This table is also on the evidence spreadsheet. Link to Uni UI - https://info.uniswap.org/#/optimism/pools

Pool | Subgraph TVL | Uniswap UI | % Difference | Comments
-- | -- | -- | -- | --
WETH/WBTC 0.3% | 903,253.10 | 3,480,000.00 | -74.04% | I feel like this pool should be correct. It has real volume and WBTC should be whitelisted
WETH/FIRN 1% | 465,116.98 | 1,560,000.00 | -70.18% | Probably should be blacklisted
sUSD/DAI 0.05% | 412,538.97 | 1,220,000.00 | -66.19% | Probably should be blacklisted
EST/DAI 0.3% | 28,878.59 | 800,260.00 | -96.39% | Ya this is some garbage and should be blacklisted
WETH/UNI 0.3% | 183,764.58 | 471,850.00 | -61.05% | UNI is a real token and the pool has volume, so I would expect the TVLs to be closer
WETH/KROM 0.3% | 77,911.37 | 284,920.00 | -72.66% | Probably should be blacklisted
LINK/WETH 0.3% | 94,019.83 | 219,740.00 | -57.21% | Same comments here as WETH/UNI pool
WETH/AAVE 1% | 65,613.15 | 160,220.00 | -59.05% | Same comments here as WETH/UNI pool
WBTC/USDC 0.3% | 46,560.67 | 142,140.00 | -67.24% | Same comments here as WETH/UNI pool
WETH/rETH 0.05% | 31,674.30 | 125,640.00 | -74.79% | Probably should be blacklisted
WETH/sUSD 0.3% | 84,365.35 | 134,500.00 | -37.27% | Probably should be blacklisted

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
Uniswap V3 Wrapped Ether/Optimism | liquidityPoolDailySnapshots | liquidityPoolDailySnapshots-dailyVolumeByTokenUSD [1] | This is outputting 0 when there should be a value. I would expect this to be the same value as dailyVolumeUSD.
Uniswap V3 Wrapped Ether/Optimism | liquidityPoolDailySnapshots | outputTokenSupply - Wrapped Ether/Optimism: Wrapped Ether/Optimism LP | Discussed this, but making a note. Has slight variations around 0, but should be displayed as null or straight 0

**Comment by steegecs** [comment]
Just re-deployed Optimism with the fix for this issue. See PR #777.

**Comment by steegecs** [comment]
Indexing from PR #849 as of yesterday.

**Comment by bye43** [comment]
@this-username-is-taken @steegecs Same comments as Uniswap V3 ethereum. New issues being moved here: https://github.com/messari/subgraphs/issues/984
