### ISSUE TITLE
AAVE V2 Avalanche and Polygon (Schema Version 2.0.1, Subgraph Version	 1.2.6, Methodology Version 1.0.0)

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#821]
**Avalanche**

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/aave-v2-avalanche&tab=protocol
-- | --
Date Reviewed | 17-Aug-22
Schema Version | 2.0.1
Subgraph Version | 1.2.6
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | totalValueLockedUSD | not ok | Public data | Prior to april 20, 2022 the graph shows double TVL to defillama
financialsDailySnapshots | totalBorrowBalanceUSD | not ok | Public data | before april 20, 2022, borrowed balance seems to be amount from expected TVL. need to double check if this is related to `totalvaluelockedUSD` issue
financialsDailySnapshots | totalDepositBalanceUSD | not ok | Sanity check | Prior to april 20, 2022 the graph shows double TVL to defillama
financialsDailySnapshots | cumulativeLiquidateUSD | not ok |   | Not adding up liquidate data. Output is zero
usageMetricsDailySnapshots | cumulativeUniqueLiquidatees | not ok |   | shows zero when there are liquidations.
-- | -- | -- | -- | --

**Polygon**

Still indexing, will take time. Skipping for Mainnet launch and will QA once done.

**Comment by dmelotik** [comment]
@ishraq8 I actually believe defiLlama is wrong prior to 4/20 (lol). I am cross-referencing with Aave's historical API calls (see api schema [here](https://aave-api-v2.aave.com/#/data/get_data_liquidity_v2))

Here is the [API call ](https://aave-api-v2.aave.com/#/data/get_data_liquidity_v2)I am using and the values compared to our [subgraph](https://api.thegraph.com/subgraphs/name/messari/aave-v2-avalanche/graphql?query=query+MyQuery+%7B%0A++marketHourlySnapshots%28%0A++++where%3A+%7Btimestamp_gt%3A+%221647354026%22%2C+timestamp_lt%3A+%221647359026%22%7D%0A++%29+%7B%0A++++id%0A++++market%7B%0A++++++name%0A++++%7D%0A++++timestamp%0A++++totalValueLockedUSD%0A++++inputTokenBalance%0A++++inputTokenPriceUSD%0A++++totalBorrowBalanceUSD%0A++%7D%0A%7D):
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| Token  | Subgraph TVL                  | subgraph timestamp | api tvl                       | api timestamp |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| USDC.e | 1681838761.559024             | 1647356026         | 1680092870.364223             | 1647357943    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| WETH   | 290773.644965167967864905     | 1647354636         | 290743.388444345064408666     | 1647357756    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| WBTC   | 13127.03113147                | 1647356379         | 13127.37394737                | 1647357697    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| AAVE.e |                               |                    | 127856.295513720274896194     | 1647347616    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| WAVAX  | 7861681.915048988310197367    | 1647356266         | 7852134.905049264078777443    | 1647357713    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| USDT.e | 367149121.192170              | 1647356081         | 366824917.828676              | 1647357822    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+
| DAI.e  | 1556164246.294619134471088494 | 1647355815         | 1554229725.943270481562596308 | 1647356505    |
+--------+-------------------------------+--------------------+-------------------------------+---------------+

* the balances are in the native token unit. and looking at the prices on our subgraph they seem to be correct

**Comment by ishraq8** [comment]
@dmelotik Just tested API data, you are accurate! Also great work on consolidating the git commands

**Comment by dmelotik** [comment]
@ishraq8 the fix is merged and syncing: https://okgraph.xyz/?q=messari%2Faave-v2-avalanche

**Comment by this-username-is-taken** [comment]
@dmelotik feel free to update the status here as you make progress:
![image](https://user-images.githubusercontent.com/2354636/185971599-e673c489-fc2f-45b5-abec-78f81ba7f734.png)

**Comment by ishraq8** [comment]
this is done. Polygon won't be at launch.

**Comment by ishraq8** [comment]
@polygon is accurate
