### ISSUE TITLE
Balancer Forks - Not ready to deploy Beethoven X Optimism

### ISSUE THREAD

**Issue by steegecs** [messari/subgraphs#843]
Beethoven X Optimism is not yet ready to deploy for 2 reasons.
- The price oracle is not configured to be able to calculate prices on Optimism. One solution is to modularize the price oracles, and use a uniswap-v2-like oracle. The other is to wait for Optimism support for Phoenix's oracle.
- The Gauge contract on Beethoven X Optimism does not have the Deposit or Withdraw events that Balancer Gauge contracts do. Because of this, the reward emissions rates will not be updated. We might want to find a different event to trigger the updates for reward emissions for deployments that use the Gauge contracts for rewards.

**Comment by nemani** [comment]
Same apply to Balancer V2 Ext https://github.com/messari/subgraphs/pull/890

**Comment by steegecs** [comment]
Hi @nemani 

Whats the status of this issue in relation to PR #890 ? Can I close this?

**Comment by steegecs** [comment]
Closing this, because I don't believe there are any issues here from feedback I received from @harsh9200
