### ISSUE TITLE
dForce BSC QA

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#868]
https://docs.google.com/spreadsheets/d/1iom5pm2nouStheavD9zgvbqK5JZt1RFb/edit#gid=507208116

**Comment by tnkrxyz** [comment]
## Protocol

Section | Value | Status | Comments
-- | -- | -- | --
financialsDailySnapshots | totalValueLockedUSD | NOT OK | Different values in further dates as shown in DefiLlama and Footprint Network
financialDailySnapshots | mintedTokenSupplies | NOT OK | Cant be zero => seen on BSC addresses that mint occured, so as in dApp analytics | 

## Pool Overview 
| Pool | Field | Status | Comment |
| ---- | ----- | ------- | ---------- |
| All pool | Reward Token | not OK | Reward Token output error on subgraph (Code Error) | 
| BNB | inputToken | not OK | address 0x0000000000000000000000000000000000000000 conflicts with ETH |

**Comment by tnkrxyz** [comment]
Fixed with merged #1062
