### ISSUE TITLE
Scream V1 Fantom (Schema Version 2.0.1, Subgraph Version 1.1.2, Methodology Version 1.0.0)

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#875]
Summary: The scream doc states "a 10% rate of interest paid on the borrowed asset allocated to SCREAM". Protocol side revenue is taking 20% (supply is getting 80%) on the subgraph, if the docs are true should be 10/90%.
https://docs.google.com/spreadsheets/d/1UIV5ia5hNy6Tr9ogxVkpiIsrEtwegzD_/edit#gid=1587289016

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/scream-fantom&tab=protocol
-- | --
Date Reviewed | 23-Aug-22
Schema Version | 2.0.1
Subgraph Version | 1.1.2
Methodology Version | 1.0.0

Protocol |   |   |   |  
-- | -- | -- | -- | --
Section | Value | Status |   | Comments
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | not ok | Docs| Supply side is collecting 80% when according to docs should be 90%
financialsDailySnapshots | dailyProtocolSideRevenueUSD | not ok | Docs| Doc says 10% of deposit interest goes to SCREAM (they call it reserve factor), protocol side revnue indicates 20%.

**Comment by 0xbe1** [comment]
@ishraq8 can you point me to the docs where "a 10% rate of interest paid on the borrowed asset allocated to SCREAM"?

I think scream's docs may be off - if you look into this query https://api.thegraph.com/subgraphs/id/Qmc8ewdYMQKbq1SZwLWUXfGQj8M36c9dFCgnyTYpjiRWgk/graphql?query=%7B%0A++markets%7B%0A++++id%0A++++name%0A++++_reserveFactor%0A++%7D%0A%7D you can find different reserve factor for markets: some 20%, some 10%, and some others.

**Comment by ishraq8** [comment]
Thanks, their docs are inconsistent. Will make note for future reference.
