### ISSUE TITLE
VVS Finance Chronos (Schema Version	1.3.0, Subgraph Version	1.1.5, Methodology Verstion 	1.0.0) 

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#916]
Summary: TVL is off. seems like WCRO pools not reporting what we see on front end leading to a 100M discrepency.

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://graph.cronoslabs.com/subgraphs/name/messari/vvs-finance&tab=protocol
-- | --
Date Reviewed | 18th Aug 2022
Schema Version | 1.3.0
Subgraph Version | 1.1.5
Methodology Verstion | 1.0.0

Protocol |   |   |  
-- | -- | -- | --
Section | Value | Status | Comments
financialsDailySnapshots | totalValueLockedUSD | NOT OK | General shape of graph seems good, but the numbers do not match up. Appears WCRO pools are either not reporting or showing uop as half
financialsDailySnapshots | dailyVolumeUSD | NOT OK | General shape of graph seems good, but the numbers do not match up/
financialsDailySnapshots | cumulativeVolumeUSD | NOT OK |  

Pool overview |   |   |  
-- | -- | -- | --
Rewardtokens | Rewardtokens | Not ok | Front end

Pool |   |   |   |  
-- | -- | -- | -- | --
Wcro/WETH |   |   |   |  
liquiditypoolDailySnapshots | totalValueLockedUSD | not ok | front end | should be 16 mil showing 8 mil
Wcro/USDC |   |   |   |  
liquiditypoolDailySnapshots | totalValueLockedUSD | not ok | front end | should be 14 mil showing 7 mil
Wcro/WBTC |   |   |   |  
liquiditypoolDailySnapshots | totalValueLockedUSD | not ok | front end | Non existant on subgraph
Wcro/ATOM |   |   |   |  
liquiditypoolDailySnapshots | totalValueLockedUSD | not ok | front end | should be 3 mil showing 1.7M
Wcro/Tonic |   |   |   |  
liquiditypoolDailySnapshots | totalValueLockedUSD | not ok | front end | should be 3 mil showing 1.5M
  |   |   |   |

**Comment by this-username-is-taken** [comment]
Quick note here we are pending for a response from VVS's team on rewards. I think we should skip rewards for now

**Comment by this-username-is-taken** [comment]
see https://github.com/messari/subgraphs/issues/935

**Comment by this-username-is-taken** [comment]
@ishraq8 would you give this another check? We can ignore rewards for now

**Comment by ishraq8** [comment]
Aside from rewards this looks great, @steegecs! Ready to ship @this-username-is-taken
