### ISSUE TITLE
Sushiswap Polygon seems to have invalid pool (KLIMA-BCT)

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#917]
![image](https://user-images.githubusercontent.com/2354636/187951815-7bb7b306-4b0c-4ff2-bc0a-095ef6398695.png)

![image](https://user-images.githubusercontent.com/2354636/187951956-e17d4e5d-dc99-4060-a715-4d7bb18acb01.png)

**Comment by steegecs** [comment]
Being addressed in this PR -> https://github.com/messari/subgraphs/pull/1393

**Comment by steegecs** [comment]
Grafted and backfilled.
