### ISSUE TITLE
VVS Finance Cronos QA 

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#935]
"## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://graph.cronoslabs.com/subgraphs/name/messari/vvs-finance&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.1.5  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1Zmzd3lW1TXi2RMaE4bp8bK65vu1sYU6s/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Protocol TVL
TVL data shows a large discrepancy of around 20% against Defi Llama data and official website data. This might be due to the reason that multiple pools in the official website are not being tracked by the subgraph (E.g., WBTC/WCRO pool, which has a TVL of $17 million, is not included in the subgraph data). 

| Subgraph | Defi Llama | Absolute Difference | % Difference | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | :---  | :---  | :---  | 
| 404,273,061| 498,635,394 | -94,362,333| -18.92%| 504,370,000 | -100,096,939| -19.85%|

### Revenue
- We have computed the supply side, protocol side, and total revenue using data from official website and the results show a massive discrepancy as compared against subgraph data. This is may have been driven by the fact that several pools in the official website are not being tracked by the subgraph. 
- Refer to the sheet 'Support-Revenue' 

|Subgraph Supply Side Revenue |Official Website|Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|4,649.22 | 16,532 |-11,882 |-71.88%|

|Subgraph Protocol Side Revenue |Official Website| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|2,325| 8,516 | -6,192|-72.70%

|Subgraph Total Daily Revenue |Official Website| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
| 6,974 | 25,048 |-18,074 |-72.16% |

### Pool Overview TVL
 - 12 out of top 30 pools’ TVL in the subgraph data are not included in the top 30 pools at the official website.
 - Out of 18 pools, seven pools’ TVL data in the subgraph show a large discrepancy around 50% to 80% as compared to official website data. 
- Nine pools in the top 30 pools of official website dashboard are not included in the subgraph data.
- Please refer to the sheet ""Pool_Overview"" for details

### Pool Overview Rewards and Base Yields
- In line with the understanding that there's no reward token for liquiduity providers in VVS Finance. Liquidity providers would have to stake their LP tokens in the ""Crystal Farm"" to earn VVS token rewards.
- As for the yields, four out of the top 10 pools in the subgraph data show a significant discrepancy with official website. The other six pools' base yields are close to official website data.
- Refer to the sheet ""Pool_Overview"" for details

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| VVS/WCRO Pair Base Yield| 0% | 0.84%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| WCRO/TONIC Pair Base Yield| 0% | 2.26%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| MTD/VVS Pair Base Yield| 0% | 18.96%|

| Pair | Subgraph | Official Website|
| :---- | :---- | :--- |
| VVS/FER Pair Base Yield| 0% | 2.28%|

Please refer to the attached worksheet for details."

**Comment by this-username-is-taken** [comment]
@ishraq8 I'm assuming this can be closed?

**Comment by ishraq8** [comment]
Yes sir, wcro & vvs pricing  resolved by @steegecs

**Comment by steegecs** [comment]
Closing :)
