### ISSUE TITLE
Tornado Cash Mainnet QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#936]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/dhruv-chauhan/tornado-cash-mainnet |
| Schema Version  |  1.3.0  | 
| Subgraph Version |  0.0.4  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1osCOrMSzV2ZyL0Lk5CH4Ah7kCFZfg3It/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true| 

### Add Fee Rate
As the Tornado Cash's documentation is not always available, it's helpful to add the fee rate charged by the protocol for each pool.

### Rewards
According to the official information available, the incentive program has stopped on Dec 2021. In addition, the price of TORN derived from the subgraph rewards data seems to be inaccurate.

### Total Revenue
On the protocol level, the cumulative total revenue is about 6% different from a dashboard from Dune Analytics (https://dune.com/poma/tornado-cash_1).

|Subgraph Total Cumulative Revenue |Dune| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
| 20,035,922 |  18,934,969  |1,100,953 |5.81% |

The revenue for August from the same Dune dashboard was also 10% to 20% different from that of the subgraph. Please see worksheet "Support-Revenue" for details.

### Pool Revenue
We have further checked the revenue of two largest pools, each for a recent date with high revenue per subgraph.
- 100 ETH pool, on 29 August
- 100k DAI pool, on 9 August

Our method is to download the full day's transactions from Etherscan and then extract the amount paid to the relayer and compute the total revenue, supply-side and protocol-side based on the methodology assumptions.  

For the 100 ETH pool, we note some 4% to 20% discrepancy in the revenue, but probably due to either the ETH prices used (Etherscane has a fixed price for the whole day). 

For the 100k DAI pool, the total revenue is in line with the subgraph, but the protocol-side revenue is different, seemingly to suggest the fee rate is 0.25% rather than 0.3%.

For more details on the above, please refer to the additional worksheet "Support-Pool Revenue 100 ETH" and "Support-Pool Revenue 100k DAI".

**Comment by SerenityFund** [comment]
In addition, we note that for DAI withdrawals, there are sometimes some extra ETH withdraw together as well. It probably relates to the deposit initially - but it's hard to find original info now. This part now is counted as revenue I suppose, but this should be clarified. Please refer to details in the worksheet "Support-Pool Revenue 100k DAI", the note on the right side as well.

**Comment by ishraq8** [comment]
The revenue is fairly close to dune dashboard and matches perfectly with token terminal. 
The extra eth withdrawal, like said, is due to initial deposit, and the amount is quite small.

Over all the subgraph matches token terminal and some of the variation can be attributed to oracle or timing. 

Great QA and this is good to deploy @this-username-is-taken

**Comment by this-username-is-taken** [comment]
LFG!!!
