### ISSUE TITLE
Venus DAI minor price issue on 2022/05/14

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#940]
<img width="1424" alt="Screen Shot 2022-09-04 at 5 39 16 PM" src="https://user-images.githubusercontent.com/2354636/188340064-9d815774-d43c-418c-9586-54d8fdaf3952.png">

**Comment by dmelotik** [comment]
Override DAI price from block 17803407 - 17836448 to `1000000000000000000`
