### ISSUE TITLE
Ubeswap Celo QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#952]
## Review Info

| Description | Info | 
| :-------- | :--- | 
|Sugraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/ubeswap-celo&tab=protocol |
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.1.5  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1QNiYnJ00Q6Sow1qok81XeZvymN2jvZsC/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview TVL
 - Only two out of 30 pools have shown large discrepancy of around 50% in its TVL data. These pools are the 13th pool (MOO/mCELO) and 26th pool (cETH/mCUSD). 
 - cGLD ticker must be changed to CELO ticker. They are the same but it's confusing.
 - Refer to the sheet "Pool_Overview" for details

##  Pool Section Error
- Six out of the first 10 pools are displaying issues in the 'Pool' Section. It says failed to fetch.
-  The pools are 2nd pool (cGLD/mCUSD), 3rd pool (WETH/mCUSD), 5th pool (cGLD/mCUSD), 7th pool  (sCELO/cGLD), 9th pool (mCUSD/WBTC), and 10th pool (cGLD/mCEUR).
- Refer to the sheet "Pool_vault schema" for details

## Pool_snapshots
- The reward APRs of the first (mCUSD, Mceur) & fourth  (UBE, cGLD) pools are outdated and they both have the same percentage data which is 7.73%. 
- Please refer to the sheet 'Reward-APR-Support' for more details

### Editorials  There are some differences we have noticed and are not necessarily data errors.

- Protocol TVL
TVL data is in line with data from Defi Llama in the past five days. However, as compared against official website, there has been 3% discrepancy in the past four days before the latest day. Additionally there have been two period wherein the discrepancy was ranging from 8% to 11%. This could be due to some individual pools having big discrepancies.

Please refer to the attached worksheet for details.

**Comment by steegecs** [comment]
Are we sure that we want to change the cGLD ticker to CELO? This appears to be the proper token symbol and is the same one used by Coinbase. And if we do want to change it, I propose we update but re-deploy when there is a new change that required re-deployment.

**Comment by steegecs** [comment]
I think the pools not fetching is not an issue with the subgraph, but an issue with the query speeds.

**Comment by steegecs** [comment]
I am not sure I understand what the issue is with the reward APR. Can you please clarify? Are you saying it is wrong that they have the same APR?

**Comment by steegecs** [comment]
Also, for future reference, it would be very helpful if the pool addresses were supplied along with the name. It helps me to query the pools from the subgraph API.

**Comment by SerenityFund** [comment]
> I am not sure I understand what the issue is with the reward APR. Can you please clarify? Are you saying it is wrong that they have the same APR?

These two pools are not updated (only having data in a much early date), whilst other pools have recent rewards data. And these two pools have rewards ongoing in Ubeswap. Now the two pools are in the "critical to fetch" status.

**Comment by steegecs** [comment]
This is ready for QA!

https://thegraph.com/hosted-service/subgraph/steegecs/ubeswap-celo

**Comment by bye43** [comment]
@steegecs and I discussed, but looks like 0x9272388fdf2d6bfba8b1cdd99732a3d552a71346 needs to be whitelisted and then this should be good to be frozen

**Comment by steegecs** [comment]
Issues have been fixed and validated and are now grafting from staging to prod
