### ISSUE TITLE
Abracadabra negative `openPositionCount`

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#957]
![image](https://user-images.githubusercontent.com/60583747/189042300-17f4a236-e78d-4b9a-a3a1-99bbd3bc700c.png)

Abracadabra has a negative open position early on in fantom's sync

**Comment by bye43** [comment]
@dmelotik Is this fixed? Looks like its on [1.2.11](https://subgraphs.messari.io/subgraph?endpoint=messari/abracadabra-money-fantom&tab=pool&poolId=) now.

**Comment by dmelotik** [comment]
No, I don't think it was ever fixed

**Comment by bye43** [comment]
@ishraq8 Can you give this a quick look should be merged in.

**Comment by ishraq8** [comment]
looks good, resolved.
