### ISSUE TITLE
Rari Fuse Rewards not working

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#961]
I don't think rari-fuse rewards are working properly. Sometimes rewards are detected, but it doesn't seem to actually populate an amount / USD value. Need to do more research to see if this is a real issue or not..

This is only on ethereum as well.

**Comment by dmelotik** [comment]
Rewards still not working :/
<img width="891" alt="Screen Shot 2022-10-06 at 11 05 52 PM" src="https://user-images.githubusercontent.com/60583747/194465797-7d50c069-0b72-42cc-a414-6afcc25c0b63.png">

**Comment by dmelotik** [comment]
Since rari is all messed up now, I don't think it is worth the effort. And we should make a warning on the FE about rari fuse having no liquidity

**Comment by bye43** [comment]
@dmelotik Agreed here.
