### ISSUE TITLE
TrueFi Mainnet QA 

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#970]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/corerouter/truefi&tab=protocol |
| Schema Version  |  2.0.1  | 
| Subgraph Version |  1.1.4  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1Ylm7xUGUjYV69mm3OggwHgEXYZ8hMIlR/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview TVL
TVL numbers have discrepancy of a few million compared to official website data, due mainly to the tracking of the pools. Please refer to worksheet "Pool_Overview" for details. In particular:
- there's no TrueFi LP pool in the official website
- the price of WOO pool price might be wrong
- the TAM pool III is not tracked correctly in the subgraph

### Revenue
Due to the nature of the transactions recorded (not only an daily evenly distributed way), it's hard to check the accuracy of daily data. We have manually calculated the monthly data  instead, of the three largest pools for verification.  We note:

- The supply-side and total revenue might have decimal errors, as the interest revenue in less than a year's time should not be more than the loan initiated. 
- The protocol-side data might be accurate, as the protocol cumulative protocol-side revenue matches that of the official website. 

Please refer to  worksheet "Supply-side" and "Pool_value" for more details. 

### Rewards
There are rewards token given in TrueFi now. This is not tracked by the subgraph.

### Input Token
The input token supply and the exchange rate of the USDT pool do not look correct.

**Comment by ishraq8** [comment]
Comments: TVL discrepancy is within reasonable range. Likely variability due to when data was taken.
cumulative supply and protocol revenue add up to $34M. Front end says the same.
Woo pool is slightly off. likely cause of where and when price feed is coming from. It is not end of the world. 

Otherwise TrueFi looks good should be frozen. @this-username-is-taken
