### ISSUE TITLE
CREAM Finance BSC - missing price first month

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#973]
During the first month of the CREAM finance BSC, we do not have any way of grabbing price.

1- CREAM BSC oracle returns prices in BNB
2- Chainlink has an oracle available 1.5 months into the start of CREAM BSC
3- I could not find a way to get on chain prices during that time. I checked Pancake swap and they do not have any BSC liquidity pools before that as well.

![image](https://user-images.githubusercontent.com/60583747/189536954-c811973e-cf37-4d99-9090-f5b8faf4ae17.png)

**Comment by this-username-is-taken** [comment]
hmm, i wouldn't call this a bug as I don't think we will fix it. I'd call it out in the methodology doc and label it as a data note

**Comment by dmelotik** [comment]
closing and addressing in #1051
