### ISSUE TITLE
Balancer V2 (Ethereum) - Element Finance Pool Revenue, cumulativeTotalRevenueUSD, Fee Fields, Balancer Aave Boosted StablePool (USD), and  bb-a-USD outputTokenUSD Issues 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#983]
### Post Mainnet Issues

**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
financialsDailySnapshots | dailySupplySideRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet
financialsDailySnapshots | dailyProtocolSideRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet
financialsDailySnapshots | cumulativeProtocolSideRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet
financialsDailySnapshots | dailyTotalRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet
financialsDailySnapshots | cumulativeTotalRevenueUSD | These revenues are off because of the way that Element Finance handles their pool fees. This will be addressed post Mainnet

**Pool Metrics**
Pool | Section | Metric | Issue
-- | -- | -- | --
All Pools | liquidityPoolDailySnapshots | cumulativeTotalRevenueUSD | Outputting cumulative supply side
Balancer Aave Boosted StablePool (USD) | liquidityPoolDailySnapshots | outputTokenPriceUSD - bb-a-USD: Balancer Aave Boosted StablePool (USD) | This is outputting as 0.
SYNR Copper Launch | liquidityPoolDailySnapshots | totalValueLockedUSD | Pricing is causing this to be off for these days. Pool address - 0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101. Token address - 0xbc6e06778708177a18210181b073da747c88490a
SYNR Copper Launch | liquidityPoolDailySnapshots | dailyVolumeUSD | Pricing is causing this to be off for these days. Pool address - 0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101. Token address - 0xbc6e06778708177a18210181b073da747c88490a
SYNR Copper Launch | liquidityPoolDailySnapshots | dailyTotalRevenueUSD | Pricing is causing this to be off for these days. Pool address - 0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101. Token address - 0xbc6e06778708177a18210181b073da747c88490a
SYNR Copper Launch | liquidityPoolDailySnapshots | dailySupplySideRevenueUSD | Pricing is causing this to be off for these days. Pool address - 0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101. Token address - 0xbc6e06778708177a18210181b073da747c88490a
SYNR Copper Launch | liquidityPoolDailySnapshots | dailyProtocolSideRevenueUSD | Pricing is causing this to be off for these days. Pool address - 0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101. Token address - 0xbc6e06778708177a18210181b073da747c88490a

**Balancer Boosted Pools**
Comments - We are currently double counting volume and TVL for the pools listed above. The pools listed below make up the Balancer Aave Boosted Pool (0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb2). The boosted pool operates differently, as it creates linear pools that are used between swaps and holds the base token along with the aToken. To address this, we are going to remove these metrics from the overarching protocol metrics, but record metrics for the pool so that volumes and rebalances can be tracked. Link - https://docs.balancer.fi/products/balancer-pools/boosted-pools
Pool | Address
-- | --
Balancer Aave Boosted Pool (USDT) | 0x2bbf681cc4eb09218bee85ea2a5d3d13fa40fc0c
Balancer Aave Boosted Pool (USDC) | 0x9210f1204b5a24742eba12f710636d76240df3d0
Balancer Aave Boosted Pool (DAI) | 0x804cdb9116a10bb78768d3252355a1b18067bf8f

**Comment by bye43** [comment]
@harsh9200 Tracking the two issues here:

- [ ] Address pricing issue for SYNR Cooper Launch Pool `0xdda942bacbe6bd0c12e3ed2db45f0349e8c43101 `, causing TVL Spike on 01/23/2022 and problems with the pool

- [ ] Boosted Pools (`0xa13a9247ea42d743238089903570127dda72fe44`, `0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb2`) has no deposit and withdraw transaction and as the TVL, Volume, Revenue field is updated only on these transaction they are zero. Furthermore, this results in outputTokenPriceUSD - bb-a-USD: Balancer Aave Boosted StablePool having a value of 0 and the output supply is stuck at 0

**Comment by bye43** [comment]
@harsh9200 Tracking other issues:

- [ ] - [ ] Balancer Boosted Pool (`0xa13a9247ea42d743238089903570127dda72fe44`) volume is not matching [Balancer UI](https://app.balancer.fi/#/ethereum/pool/0xa13a9247ea42d743238089903570127dda72fe4400000000000000000000035d) volume

- [ ] Add `inputTokenWeight` methodology. Right now, `inputTokenWeight` is static and blank for pools. Need to make it based on `inputTokenBalanceUSD`

**Comment by bye43** [comment]
@steegecs Going to leave this open to remind me to backfill latest version when its on messari hosted

**Comment by harsh9200** [comment]
@bye43 yes, this subgraph is fully synced and ready
