### ISSUE TITLE
Uniswap V3 (All Chains) - CumulativeUniqueUsers

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#984]
# Uniswap V3 (All Chains) Post Mainnet QA

### All Chains 
**Protocol Metrics**
Section | Metric | Issue
-- | -- | --
usageMetricsDailySnapshots | cumulativeUniqueUsers | We are not currently calculating this right, as the router contract is being tracked when swaps happen

**Pool Metrics**
Pool | Metric | Issue
-- | -- | --
All Pools | totalValueLockedUSD | See - https://github.com/Uniswap/v3-subgraph/issues/74

### Ethereum - Schema Version 1.3.0 Subgraph Version 1.1.0 Methodology Version 1.0.0
**Mispriced Pools**
Pool | Address
-- | --
BIT/ETH 0.3% | 0x5C128d25A21f681e678cB050E551A895c9309945
APE/ETH 0.3% | 0xAc4b3DacB91461209Ae9d41EC517c2B9Cb1B7DAF

### Optimism - Schema Version 1.3.0 Subgraph Version 1.1.2 Methodology Version 1.0.0
**Mispriced Pools**
Pool | Address
-- | --
WETH/UNI 0.3% | 0xAD4c666fC170B468B19988959eb931a3676f0e9F
LINK/WETH 0.3% | 0x19EA026886cbB7A900EcB2458636d72b5CaE223B
WETH/rETH 0.05% | 0xAEfC1edaeDE6ADaDcdF3bB344577D45A80B19582
LINK/WETH 1% | 0x3202c46666E774b44Ba463EAfAa6da9a968a058F
WETH/rETH 0.3% | 0x8f477a5D632B5691A10A571575D55DC9C3D86d7C

### Polygon - Schema Version 1.3.0 Subgraph Version 1.1.2 Methodology Version 1.0.0
**Mispriced Pools**
Pool | Address
-- | --
MATIC/CRV 0.3% | 0x4D05f2A005e6F36633778416764E82d1D12E7fbb
CPLE/USDT 1%  | 0x613e24ec04fa61a5967cccc90cdc1d9513f73d5a (THIS NEEDS TO BE BLACKLISTED)

### Arbitrum - Schema Version 1.3.0 Subgraph Version 1.1.2 Methodology Version 1.0.0
**Mispriced Pools**
Pool | Address
-- | --
ETH/UNI 0.3% | 0xC24f7d8E51A64dc1238880BD00bb961D54cbeb29
ETH/LINK 0.3% | 0x468b88941e7Cc0B88c1869d68ab6b570bCEF62Ff
MAGIC/ETH 1% | 0x7e7FB3CCEcA5F2ac952eDF221fd2a9f62E411980
DPX/ETH 1% | 0xb52781C275431bD48d290a4318e338FE0dF89eb9

### Celo - Schema Version 1.3.0 Subgraph Version 1.1.2 Methodology Version 1.0.0
**Mispriced Pools** - Real low TVL on Celo, but these are the current 7-10 pools, so I think it would be good to have at least the top 10 pools
Pool | Address
-- | --
CELO/KNOX 0.3% | 0xBd0f6F34bAA3c1329448A69bab90111a20756F01
SOURCE/cUSD 0.3% | 0x9B42940E8184D866aAC6595A91F8D8952a59D3B9
cUSD/cREAL 0.05% | 0x723292eEA7e1576AE482A5C317934054c0199e24

**Comment by this-username-is-taken** [comment]
CumulativeUniqueUser has been fixed and indexing in staging

**Comment by steegecs** [comment]
Final TVL issue being tracked here: https://github.com/messari/subgraphs/issues/1071

**Comment by bye43** [comment]
@steegecs Going to reopen this per our slack conversation the other day. Updates:
- `cumulativeUniqueUsers` needs to be addressed

**Comment by bye43** [comment]
@steegecs Updating this issue with our discussion here on the difference between Dune and Subgraph:

> Probably the difference that is most impactful is that they use the sender field on the swap event in order to calculate unique users. This, I believe, should be whatever account or contract interacted with the liquidity pool or router. Whereas, I use the transaction.from field, which always refers to the EOA that initiated the swap.
> So for example, if a user interacted with Uniswap V3 through 1Inch, the sender would be the 1Inch router, or whatever part of one inch calls uniswap. Whereas transaction.from will refer to the EOA that interacted with 1Inch and by proxy made a swap on Uniswap V3.
> 
> I think our values will be off by like 0.05% since I was using the owner field on deposit as an exception which I now think should be transaction.from as well.

Second point is being fixed, but subgraph will not be re-indexed till there is a bigger change
