### ISSUE TITLE
Balancer V2 Ext. Schema v2.0.0 - DexAmmProtocol schemaVersion field still v1.3.0

### ISSUE THREAD

**Issue by MichaelC1999** [messari/subgraphs#991]
![Screenshot from 2022-09-13 18-17-47](https://user-images.githubusercontent.com/69168498/190011090-8f5a873c-7a7b-441c-92f3-49996848be61.png)

subgraphs.xyz generates a query for a subgraph based on the protocol type and schema version. As seen in the screenshot, the schema version on the dexAmmProtocol Entity does not have a matching schema version to the fields being queried for with schema v1.3.0 - Please update to v2.0.0

**Comment by this-username-is-taken** [comment]
@nemani

**Comment by dmelotik** [comment]
@bye43 this seems to not be an issue anymore. The balancer subgraphs work properly in subgraphs.xyz

**Comment by bye43** [comment]
Yes, will close
